import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Costa Rica 360° in 13 giorni" (src/content/viaggi/12-costa-rica-360.md).

export const destinazioniCostaRica: Destinazione[] = [
  {
    slug: 'san-jose',
    paeseSlug: 'costa-rica',
    ordine: 1,
    nome: 'San José',
    tipologia: ['città'],
    giorniConsigliati: '1 giorno all\'arrivo, 1 al rientro',
    visitataPersonalmente: true,
    introduzione: 'Il punto di arrivo e di rientro del viaggio: poco da vedere dal punto di vista turistico, ma un buon primo assaggio di cucina e vita sociale costaricana.',
    percheAndarci: 'Come base logistica per il meeting di benvenuto e per il primo/ultimo casado del viaggio.',
    cosaVedere: ['Il Mercado Central', 'Il quartiere coloniale di Barrio Amón', 'Il Museo Nazionale'],
    cosaFare: [
      'Cena al Jardín de Lolita, tra food truck e socialità di gruppo',
      'Dopocena da Booze and Scoops e serata di ballo a La Concha',
      'Cena d\'arrivederci al Costa Rica Beer Factory',
    ],
    doveDormire:
      'Casa Boutique Las Orquídeas, dove ho dormito sia all\'arrivo che all\'ultima notte: più una casa che un hotel, atmosfera familiare, staff disponibile a ogni ora, colazione preparata al momento. Qualche recensione segnala pareti sottili e camere un po\' spartane. Fascia media.\n\nAlternative: economiche: Selina San José, Costa Rica Backpackers Hostel · fascia media: Hotel Presidente, Hotel Kekoldi (Barrio Amón) · lusso: Hotel Grano de Oro, Xandari Resort & Spa (Alajuela, vicino all\'aeroporto).',
    doveMangiare: 'Jardín de Lolita e Colonia Arepas y Bar all\'arrivo; Costa Rica Beer Factory per la cena d\'arrivederci.',
    usciteSerali: 'La Concha, nel quartiere di La California, sicuro e animato anche di sera a differenza del centro.',
    comeArrivare: 'Volo internazionale su San José; Uber dall\'aeroporto al centro (30 min-1h, circa 14$).',
    comeSpostarsi: 'Uber, nettamente preferibile ai taxi: costa circa un terzo in meno ed è più sicuro.',
    periodoMigliore: 'metà-fine novembre',
    costi: 'Uber aeroporto-centro circa 14$.',
    erroriDaEvitare: ['Evitare il centro città dopo il tramonto: meglio muoversi sempre in gruppo o in Uber', 'Cambiare valuta solo in banche o uffici autorizzati, mai per strada'],
    miaEsperienza:
      'San José in sé ha poco da offrire dal punto di vista turistico, ma la cena al Jardín de Lolita, tra diversi food truck e tutto il gruppo seduto insieme, è stato un ottimo modo per socializzare fin dalla prima sera.',
    esperienzeSlugs: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Il centro di San José, capitale della Costa Rica',
    immagine: '/images/costa-rica/san-jose-stock.jpg',
  },
  {
    slug: 'puerto-viejo',
    paeseSlug: 'costa-rica',
    ordine: 2,
    nome: 'Puerto Viejo',
    tipologia: ['mare', 'natura', 'giungla'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'La costa caraibica della Costa Rica, girata in bicicletta tra Punta Uva, Playa Chiquita e Cocles, con il Parco Nazionale di Cahuita a un passo.',
    percheAndarci: 'Per Punta Uva, la spiaggia più bella per nuotare nei Caraibi, e per il tour di Cahuita, tra bradipi, comunità Bribrì e cioccolato tradizionale.',
    cosaVedere: ['Punta Uva', 'Playa Chiquita e Cocles', 'Il Parco Nazionale di Cahuita'],
    cosaFare: [
      'Noleggio bici da Rasta Lion per esplorare la costa',
      'Tour completo di Cahuita con la guida José — vedi la scheda esperienza dedicata',
      'Happy hour al tramonto a Cocles',
      'Pacuaré rafting (opzionale, da organizzare con una settimana d\'anticipo)',
    ],
    doveDormire:
      'Escape Caribeño, bungalow fronte spiaggia con piscina e giardino tropicale molto fotografato, colazione giudicata ottima dalla maggior parte degli ospiti. Qualche lamentela su dotazioni minime in camera e sul prezzo, già alto, che non include la colazione. Fascia medio-alta.\n\nAlternative: economiche: Cabinas Guaraná, Rocking J\'s · fascia media: Coco Loco Lodge · lusso: Le Cameleon Boutique Hotel, Cariblue Beach & Jungle Resort.',
    doveMangiare: 'Madre Tierra, Koki Beach Restaurant (spesso un bradipo attraversa il tetto la sera), Amimodo.',
    usciteSerali: 'Hot Rocks per musica dal vivo; Selina per il karaoke. Muoversi sempre in gruppo di notte.',
    comeArrivare: 'Circa 4-4h30 di van da San José.',
    comeSpostarsi: 'Bicicletta a noleggio, tuk tuk locali per gli spostamenti brevi (circa 4$ a persona).',
    periodoMigliore: 'tutto l\'anno tropicale',
    costi: 'Noleggio bici circa 6$; tour di Cahuita 50$ a persona; Pacuaré rafting 112$.',
    erroriDaEvitare: ['Prenotare il tour di Cahuita e il Pacuaré rafting con almeno una settimana d\'anticipo', 'Muoversi sempre in gruppo di notte, specialmente le ragazze da sole'],
    miaEsperienza:
      'Pedalare lungo la costa fino a Punta Uva, con le scimmie urlatrici che si sentono dagli alberi sopra la testa, è stato uno dei modi più genuini di scoprire il Caribe costaricano.',
    esperienzeSlugs: ['tour-cahuita'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'La spiaggia caraibica di Punta Uva vicino a Puerto Viejo, Costa Rica',
    immagine: '/images/costa-rica/puerto-viejo-stock.jpg',
  },
  {
    slug: 'tortuguero',
    paeseSlug: 'costa-rica',
    ordine: 3,
    nome: 'Tortuguero',
    tipologia: ['natura', 'giungla'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'Un piccolo villaggio senza strade per auto, raggiungibile solo in barca attraverso canali immersi nella giungla, con kayak all\'alba tra le mangrovie.',
    percheAndarci: 'Per il tragitto in barca stesso, uno dei trasferimenti più belli del viaggio, non solo una tappa di passaggio.',
    cosaVedere: ['I canali di Tortuguero, tra coccodrilli, caimani e uccelli', 'Cerro Tortuguero, collina panoramica con vista su tutta l\'area'],
    cosaFare: [
      'Navigazione in barca da Moín a Tortuguero — vedi la scheda esperienza dedicata',
      'Kayak all\'alba tra le mangrovie — vedi la scheda esperienza dedicata',
      'Cerro Tortuguero in autonomia',
      'Escursione notturna alla nidificazione delle tartarughe (stagionale, luglio-ottobre)',
    ],
    doveDormire:
      'Hotel Icaco Tortuguero, posizione comoda proprio davanti alla spiaggia del parco, check-in/check-out rapido. Alcune recensioni giudicano le camere piccole ed essenziali rispetto al prezzo. Fascia medio-bassa.\n\nAlternative: economiche: La Casona de Tortuguero, Cabinas Miss Junie · fascia media: Aracari Garden Hotel · lusso: Tortuga Lodge & Gardens, Manatus Hotel.',
    doveMangiare: 'Taylor\'s Place o Mi Niño in paese; cena inclusa in hotel.',
    comeArrivare: '1h30 di van fino al porto di Moín, poi 3 ore di navigazione in barca.',
    comeSpostarsi: 'A piedi: il villaggio non ha strade per auto. Kayak e barca per le escursioni.',
    periodoMigliore: 'luglio-ottobre per la nidificazione delle tartarughe',
    costi: 'Cerro Tortuguero 6$ barca + 3$ ingresso; escursione notturna tartarughe circa 40$ a persona.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Il tragitto in barca da Moín a Tortuguero, tra canali di giungla con coccodrilli e scimmie sulle rive, è stato uno dei trasferimenti più belli di tutto il viaggio: non una semplice tappa di passaggio, ma un\'esperienza a sé.',
    esperienzeSlugs: ['barca-tortuguero', 'kayak-tortuguero'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Un canale di giungla verso il villaggio di Tortuguero, Costa Rica',
    immagine: '/images/costa-rica/tortuguero-stock.jpg',
  },
  {
    slug: 'sarapiqui',
    paeseSlug: 'costa-rica',
    ordine: 4,
    nome: 'Sarapiquí',
    tipologia: ['natura', 'avventura'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'Un lodge immerso nella foresta, con rafting sul fiume Sarapiquí e una cooking class per imparare a preparare piatti tradizionali.',
    percheAndarci: 'Per il rafting sul Sarapiquí, più regolare e adatto anche ai principianti rispetto al più estremo Pacuaré.',
    cosaVedere: ['La foresta intorno all\'Epic Adventure Lodge', 'Le Cataratas Bajas del Toro (escursione facoltativa)'],
    cosaFare: [
      'Rafting sul fiume Sarapiquí — vedi la scheda esperienza dedicata',
      'Cooking class inclusa al lodge (tipicamente empanadas)',
      'Escursione facoltativa alle Cataratas Bajas del Toro',
    ],
    doveDormire:
      'Epic Adventure Lodge, molto apprezzato per la vicinanza al fiume, la colazione abbondante e il calore dei proprietari. Unica nota stonata: dettagli come zanzariere e ganci per gli asciugamani mancanti. Fascia media.\n\nAlternative: economiche: Hotel El Bambú, Perla Verde Hostel · fascia media: La Quinta de Sarapiquí Lodge · lusso: Sueño Azul Resort, Islas del Río.',
    doveMangiare: 'La cooking class al lodge, che diventa anche la cena; Restaurante Mirador Tinamú.',
    comeArrivare: '1h30 in barca da Tortuguero più 2h30 in van.',
    comeSpostarsi: 'Van privato; a piedi nel lodge.',
    periodoMigliore: 'tutto l\'anno, il Sarapiquí è più costante del Pacuaré',
    costi: 'Pranzo al sacco per Bajos del Toro circa 12$ a persona.',
    erroriDaEvitare: ['Fare scorta di bibite al supermercato lungo il tragitto prima di arrivare al lodge'],
    miaEsperienza:
      'La cooking class al lodge, con le empanadas preparate a mano diventate poi la cena della serata, è stato un momento conviviale diverso dal resto del viaggio, molto più lento e genuino.',
    esperienzeSlugs: ['rafting-sarapiqui'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'La foresta pluviale intorno a un lodge a Sarapiquí, Costa Rica',
    immagine: '/images/costa-rica/sarapiqui-stock.jpg',
  },
  {
    slug: 'arenal',
    paeseSlug: 'costa-rica',
    ordine: 5,
    nome: 'Arenal e La Fortuna',
    tipologia: ['natura', 'vulcani'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Il vulcano Arenal, la Cascada de La Fortuna e le sorgenti termali gratuite di El Choyin, molto più autentiche delle terme "da cartolina" a pagamento.',
    percheAndarci: 'Per le sorgenti termali gratuite di El Choyin, uno dei momenti più suggestivi e meno "da cartolina" di tutto il viaggio.',
    cosaVedere: ['Il vulcano Arenal', 'La Cascada de La Fortuna', 'Le sorgenti termali di El Choyin'],
    cosaFare: [
      'Bagno alla Cascada de La Fortuna — vedi la scheda esperienza dedicata',
      'Trekking al vulcano al Mirador El Silencio (opzionale)',
      'Ponti sospesi di Mistico Hanging Bridges (opzionale)',
      'Sorgenti termali gratuite di El Choyin',
      'Canyoning nel Lost Canyon (opzionale, molto adrenalinico)',
    ],
    doveDormire:
      'Hotel Campos Arenal, vista sul vulcano dalla piscina e colazione abbondante tra i punti di forza più citati, insieme alla posizione comoda. Il difetto ricorrente è il vialetto sterrato d\'accesso, scivoloso quando piove. Fascia media.\n\nAlternative: economiche: Arenal Backpackers Resort, Gringo Pete\'s · fascia media: Volcano Lodge & Springs · lusso: Nayara Springs, Tabacón Thermal Resort & Spa.',
    doveMangiare: 'Nanku Restaurant con musica dal vivo; Soda Víquez per la cucina tradizionale ed economica; Spectacular Cantina (messicano).',
    usciteSerali: 'Selina o Lava Lounge.',
    comeArrivare: 'Circa 1h20 di van da Sarapiquí.',
    comeSpostarsi: 'Minivan a disposizione per tutta la giornata.',
    periodoMigliore: 'tardo pomeriggio per le sorgenti termali',
    costi: 'Cascada de La Fortuna 18-20$; tour combo 90-120$ a persona; canyoning Lost Canyon 115-119$.',
    erroriDaEvitare: ['Alle sorgenti di El Choyin non ci sono spogliatoi: portare solo scarpe da fiume, costume e torcia frontale, senza asciugamani'],
    miaEsperienza:
      'Le sorgenti termali gratuite di El Choyin, nel tratto di fiume naturale, sono state molto più autentiche e suggestive delle terme a pagamento della zona: uno dei momenti più genuini di tutto il viaggio.',
    esperienzeSlugs: ['cascata-fortuna-termales'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Il vulcano Arenal visto da La Fortuna, Costa Rica',
    immagine: '/images/copertine/costa-rica-360.jpg',
  },
  {
    slug: 'monteverde',
    paeseSlug: 'costa-rica',
    ordine: 6,
    nome: 'Monteverde',
    tipologia: ['natura', 'avventura'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'La foresta nebulosa di Monteverde, con una piantagione di caffè, una camminata notturna per la fauna e alcune delle migliori zipline del paese.',
    percheAndarci: 'Per la foresta nebulosa in sé e per le zipline, considerate tra le migliori della Costa Rica, più lunghe di quelle di La Fortuna.',
    cosaVedere: ['La foresta nebulosa di Monteverde', 'Una piantagione di caffè'],
    cosaFare: [
      'Visita a una piantagione di caffè con degustazione',
      'Camminata notturna nella foresta nebulosa — vedi la scheda esperienza dedicata',
      'Zipline avventura — vedi la scheda esperienza dedicata',
      'Birdwatching all\'alba (opzionale, guida Jason)',
    ],
    doveDormire:
      'Hotel Jardines de Monteverde, giardini curati, tanta fauna da osservare dalla struttura stessa, staff sempre citato come gentile. Alcune recensioni più recenti segnalano camere e bagni un po\' datati. Fascia medio-bassa.\n\nAlternative: economiche: Pensión Santa Elena, Monteverde Backpackers · fascia media: Cloud Forest Lodge · lusso: Hotel Belmar, Monteverde Lodge & Gardens.',
    doveMangiare: 'Tree House (supermercato accanto); Tico y Rico, The Green Restaurant, Sabor Tico.',
    comeArrivare: 'Circa 3-3h30 di van da La Fortuna.',
    comeSpostarsi: 'Van privato per le escursioni.',
    periodoMigliore: 'mattina presto per birdwatching e zipline',
    costi: 'Camminata notturna (Kinkajou Night Walk) 28$ a persona; zipline circa 60$ a persona; birdwatching 50$ a persona.',
    erroriDaEvitare: ['Chiedere alla guida di accorciare la camminata notturna se dura troppo: non piace a tutti allo stesso modo per via della durata'],
    miaEsperienza:
      'La camminata notturna nella foresta nebulosa, con la fauna che si muove solo dopo il tramonto, è stata una delle esperienze più suggestive del viaggio, anche se la durata (1h30) può risultare lunga per alcuni.',
    esperienzeSlugs: ['camminata-notturna-monteverde', 'zipline-monteverde'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'La foresta nebulosa di Monteverde, Costa Rica',
    immagine: '/images/costa-rica/monteverde-stock.jpg',
  },
  {
    slug: 'uvita',
    paeseSlug: 'costa-rica',
    ordine: 7,
    nome: 'Uvita',
    tipologia: ['mare', 'natura', 'relax'],
    giorniConsigliati: '3 giorni',
    visitataPersonalmente: true,
    introduzione: 'La costa pacifica della Costa Rica, con il whale watching e il celebre banco di sabbia a forma di coda di balena, la Cola de la Ballena.',
    percheAndarci: 'Per il whale watching (nella stagione giusta) e per uno dei paesaggi più belli di tutto il viaggio, la Cola de la Ballena vista con la bassa marea.',
    cosaVedere: ['La Cola de la Ballena, il banco di sabbia a forma di coda di balena', 'Il ponte di Tárcoles con i grandi coccodrilli, lungo il tragitto'],
    cosaFare: [
      'Whale watching — vedi la scheda esperienza dedicata',
      'Equitazione al Rancho Merced (opzionale)',
      'Surf con noleggio tavole da Nomadic Surf',
      'Yoga al tramonto su un deck panoramico',
    ],
    doveDormire:
      'El Tecal, buona posizione e staff cordiale tra gli aspetti più citati; diverse recensioni segnalano camere e bagni non sempre curati come dovrebbero. Fascia economico-media.\n\nAlternative: economiche: Flutterby House, Cascada Verde Hostel · fascia media: Eden Tica Lodge, Hotel Por Qué No? · lusso: La Cusinga Lodge, Oxygen Jungle Villas.',
    doveMangiare: 'Gastro Park di Uvita (spesso sconto del 10% se avvisato in anticipo).',
    comeArrivare: 'Fino a 4 ore di van da Monteverde, con sosta fotografica al ponte di Tárcoles.',
    comeSpostarsi: 'A piedi in spiaggia; van per le escursioni.',
    periodoMigliore: 'gennaio-marzo o luglio-ottobre per il whale watching (novembre-dicembre è meno favorevole)',
    costi: 'Whale watching 70$ a persona; equitazione 52$ a persona; surf 70$ per 4 tavole al giorno; yoga 10$ a persona.',
    erroriDaEvitare: ['Organizzare il whale watching solo tramite il DMC, evitando fornitori locali senza assicurazione adeguata'],
    miaEsperienza:
      'La Cola de la Ballena, il banco di sabbia a forma di coda di balena visibile con la bassa marea, resta uno dei paesaggi più belli di tutto il viaggio, a prescindere da quante balene si riescano effettivamente ad avvistare in mare.',
    esperienzeSlugs: ['whale-watching-uvita'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Il banco di sabbia della Cola de la Ballena a Uvita, Costa Rica',
    immagine: '/images/costa-rica/uvita-stock.jpg',
  },
  {
    slug: 'manuel-antonio',
    paeseSlug: 'costa-rica',
    ordine: 8,
    nome: 'Parco Nazionale Manuel Antonio',
    tipologia: ['natura', 'mare'],
    giorniConsigliati: 'mezza giornata, lungo il tragitto di rientro',
    visitataPersonalmente: true,
    introduzione: 'Una delle tappe più belle di tutto il Costa Rica: sentieri guidati tra bradipi, scimmie e iguane, seguiti da una delle spiagge più belle del paese.',
    percheAndarci: 'Altissima probabilità di avvistare fauna selvatica con una guida esperta, in uno dei parchi nazionali più famosi del paese.',
    cosaVedere: ['Bradipi, scimmie, iguane e colibrì lungo i sentieri', 'Le spiagge all\'interno del parco'],
    cosaFare: ['Visita guidata inclusa nel parco — vedi la scheda esperienza dedicata', 'Tempo libero in spiaggia dentro il parco'],
    doveDormire: 'Non ho pernottato qui: tappa di mezza giornata lungo il tragitto di rientro verso San José.',
    doveMangiare: 'Nessuna indicazione specifica: tappa concentrata sulla visita al parco.',
    comeArrivare: 'Circa 1h30 di trasferimento da Uvita.',
    comeSpostarsi: 'A piedi lungo i sentieri del parco, con guida.',
    periodoMigliore: 'mattina presto, prima dell\'alba per la partenza',
    costi: 'da completare — il parco è chiuso il martedì.',
    erroriDaEvitare: ['Il parco è chiuso il martedì: verificare in anticipo ed eventualmente anticipare la visita'],
    miaEsperienza:
      'La guida ha reso Manuel Antonio una delle tappe più dense di avvistamenti di tutto il viaggio: bradipi, scimmie e iguane visti a distanza ravvicinata lungo sentieri che da soli sarebbero stati molto più difficili da decifrare.',
    esperienzeSlugs: ['parco-manuel-antonio'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Un bradipo tra gli alberi del Parco Nazionale Manuel Antonio, Costa Rica',
    immagine: '/images/costa-rica/manuel-antonio-stock.jpg',
  },
]
