import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Florida 360° in 10 giorni" (src/content/viaggi/09-florida-360.md).

export const destinazioniFlorida: Destinazione[] = [
  {
    slug: 'miami',
    paeseSlug: 'florida',
    ordine: 1,
    nome: 'Miami e Miami Beach',
    tipologia: ['città', 'mare', 'nightlife'],
    giorniConsigliati: '1 giorno all\'arrivo, 2-3 al rientro',
    visitataPersonalmente: true,
    introduzione: 'Il punto di arrivo e di rientro del viaggio: Little Havana, le spiagge di South Beach, e la Miami "di terra" tra Wynwood e Coconut Grove.',
    percheAndarci: 'Per l\'atmosfera cubana di Little Havana, la vita da spiaggia di Miami Beach e come base per il noleggio auto di tutto il tour.',
    cosaVedere: [
      'Little Havana: Calle 8, il Domino Park, la Walk of Stars',
      'I murales di Wynwood',
      'Il Vizcaya Museum and Gardens a Coconut Grove',
      'L\'Art Deco District di Miami Beach',
    ],
    cosaFare: [
      'Cena e serata a Little Havana o su Lincoln Rd/Ocean Dr',
      'Speed boat tour "Thriller Miami" — vedi la scheda esperienza dedicata',
      'Salsa Night con lezioni e mojito — vedi la scheda esperienza dedicata',
      'Tour a piedi Art Deco Welcome Center (1h30, $30)',
      'Spiaggia a South Beach o Muscle Beach',
    ],
    doveDormire:
      'Ho dormito al Generator Miami, il design hostel della catena Generator a South Beach: non un hotel tradizionale ma una struttura con dormitori e camere private, pensata per chi viaggia leggero senza rinunciare al design. Posizione comoda vicino al mare, piscina e area comune molto frequentate, atmosfera curata più che da "party hostel", reception 24h. Leggermente più caro della media degli ostelli della zona, ma ottimo rapporto qualità/prezzo per chi cerca socialità e posizione.\n\nEconomiche: Freehand Miami, Circa39 Hotel · fascia media: The Plymouth South Beach, Kimpton Surfcomber Miami · lusso: The Betsy South Beach, The Confidante Miami Beach.',
    doveMangiare: 'Doce Provisions, CVI.CHE 105 (miglior ceviche peruviano della città), Garcia\'s a Little Havana/Downtown; Fratelli la Bufala, Santorini by Georgios, Fat Ronnie\'s a Miami Beach.',
    usciteSerali: 'Cubaocho e il rooftop Sugar a Downtown; Kill Your Idol, Abbey Brewing Company, Mango\'s tra Lincoln Rd e Ocean Dr; E11EVEN, Club Space o The Hangar per la vita notturna più spinta (dress code spesso rigido).',
    comeArrivare: 'Volo internazionale su Miami; transfer in hotel di circa 15 minuti.',
    comeSpostarsi: 'Uber/Lyft (circa 30-40$ dall\'aeroporto, 15$ tra Mid Beach e South Beach), auto a noleggio per il resto del tour.',
    periodoMigliore: 'tutto l\'anno, caldo-umido',
    costi: 'Parcheggio in strada a Mid Beach 3$/ora 24 ore su 24; tour Art Deco $30.',
    erroriDaEvitare: ['Controllare sempre se la mancia (18-20%) è già inclusa nel conto prima di aggiungerla di nuovo', 'Verificare la resort fee degli hotel prima di pagare con la cassa comune'],
    miaEsperienza:
      'Little Havana, con gli anziani cubani che giocano a domino nel Domino Park ogni giorno, è stata la chicca meno turistica di tutta Miami: un pezzo di quotidianità lontano dai circuiti più battuti.',
    esperienzeSlugs: ['speedboat-thriller-miami', 'salsa-night-miami'],
    tripSlugs: ['florida-360'],
    imageAlt: 'Gli edifici Art Deco colorati di Ocean Drive, Miami Beach, Florida',
    immagine: '/images/florida/miami-stock.jpg',
  },
  {
    slug: 'key-west-marathon',
    paeseSlug: 'florida',
    ordine: 2,
    nome: 'Key West e Marathon',
    tipologia: ['mare', 'natura'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'La Seven Mile Bridge, il tramonto a Mallory Square e la casa di Hemingway, lungo la catena di isole più a sud degli Stati Uniti.',
    percheAndarci: 'Per il colpo d\'occhio sulla Seven Mile Bridge, sospesi tra due azzurri, e l\'atmosfera rilassata e un po\' eccentrica di Key West.',
    cosaVedere: [
      'La Seven Mile Bridge, con le soste fotografiche prima e dopo il ponte',
      'Hemingway Home and Museum, con i celebri gatti a sei dita',
      'Southernmost Point',
      'Mel Fisher Maritime Museum',
    ],
    cosaFare: [
      'Tramonto a Mallory Square, con cocktail e key lime pie al Sunset Pier',
      'Fort Zachary Taylor Beach per nuotare',
      'Snorkeling o kayak a Bahia Honda State Park — vedi la scheda esperienza dedicata',
      'Serata su Duval St, dal Green Parrot a Rick\'s',
    ],
    doveDormire:
      'Non ho il nome dell\'hotel dove ho effettivamente dormito in questa tappa: resta da confermare.\n\nAlternative Key West — economiche: Key Lime Inn, Seashell Motel & Key West Hostel · fascia media: La Concha Hotel & Spa, Old Town Manor · lusso: Casa Marina Key West (Curio Collection by Hilton), Southernmost Beach Resort.\n\nAlternative Marathon — economiche: Siesta Motel, Ocean Beach Club Marathon · fascia media: Banana Bay Resort & Marina, Coral Lagoon Resort & Marina · lusso: Isla Bella Beach Resort & Spa, Tranquility Bay Beachfront Resort.',
    doveMangiare: 'Blue Heaven, Robbie\'s, Burdine\'s Waterfront a Key West; La Nina e Sunset Grille & Raw Bar a Marathon.',
    comeArrivare: 'Circa 160 miglia da Miami, 3h30-4h di guida.',
    comeSpostarsi: 'Auto a noleggio, a piedi nel centro di Key West.',
    periodoMigliore: 'tramonto per Mallory Square',
    costi: 'Fort Zachary Taylor $6/auto o $2,5/pedone; Hemingway Home $17; Bahia Honda $10/auto; kayak 18$/ora doppio.',
    erroriDaEvitare: ['Prenotare in anticipo lo snorkeling a Bahia Honda ed essere presenti entro mezzogiorno per il tour del pomeriggio'],
    miaEsperienza:
      'La strada che diventa via via più spettacolare avvicinandosi alle isole, con l\'attraversamento della Seven Mile Bridge sospesi tra due sfumature di azzurro, è uno dei momenti di guida più belli di tutto il viaggio.',
    esperienzeSlugs: ['hemingway-home', 'snorkeling-bahia-honda'],
    tripSlugs: ['florida-360'],
    imageAlt: 'La Seven Mile Bridge che attraversa il turchese delle Florida Keys',
    immagine: '/images/florida/key-west-stock.jpg',
  },
  {
    slug: 'everglades-naples',
    paeseSlug: 'florida',
    ordine: 3,
    nome: 'Everglades e Naples',
    tipologia: ['natura', 'mare'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'L\'airboat tour nella palude primordiale delle Everglades, tra alligatori e uccelli, seguito dall\'eleganza balneare di Naples.',
    percheAndarci: 'Per vedere alligatori e fauna selvatica in uno degli ecosistemi più unici degli Stati Uniti, prima di rallentare il ritmo sulla costa del Golfo.',
    cosaVedere: ['Le paludi delle Everglades', 'Shark Valley', 'Il Naples Pier'],
    cosaFare: [
      'Everglades Airboat Tour — vedi la scheda esperienza dedicata',
      'Shark Valley in bici o tram',
      'Spiaggia al Naples Pier o al Lowdermill Park',
      'Passeggiata serale su 5th Ave a Naples',
    ],
    doveDormire:
      'Anche per questa tappa non ho il nome dell\'hotel reale: da confermare.\n\nAlternative: economiche: Naples Garden Inn, Extended Stay America Naples · fascia media: Hampton Inn & Suites Naples South, AC Hotel by Marriott Naples 5th Avenue · lusso: The Ritz-Carlton Naples, Naples Grande Beach Resort.',
    doveMangiare: 'Alberto\'s on 5th (ottima pasta), Taqueria San Julian, Michelbob\'s Ribs and Steaks a Naples.',
    comeArrivare: 'Everglades lungo la Route 40 tra Miami e Naples; circa 1h30, 80 miglia dalle Everglades a Naples.',
    comeSpostarsi: 'Auto a noleggio; airboat per il tour delle paludi.',
    periodoMigliore: 'mattina presto, prima che faccia troppo caldo; inverno per l\'avvistamento di lamantini',
    costi: 'Shark Valley $30/auto, bici $22 o tram $28.',
    erroriDaEvitare: ['Repellente per zanzare, crema solare, giacca antipioggia e pantaloni lunghi sono quasi obbligatori alle Everglades'],
    miaEsperienza:
      'Le Everglades sono un\'enorme palude primordiale, molto diversa da qualunque altro paesaggio del viaggio: il contrasto con l\'eleganza di Naples poche ore dopo è uno dei salti di atmosfera più netti di tutto il tour.',
    esperienzeSlugs: ['everglades-airboat'],
    tripSlugs: ['florida-360'],
    imageAlt: 'Un airboat tra le paludi delle Everglades, Florida',
    immagine: '/images/florida/everglades-stock.jpg',
  },
  {
    slug: 'orlando',
    paeseSlug: 'florida',
    ordine: 4,
    nome: 'Orlando',
    tipologia: ['divertimento', 'famiglia'],
    giorniConsigliati: '2-3 giorni',
    visitataPersonalmente: true,
    introduzione: 'Il grande cuore dei parchi a tema della Florida: Universal Studios e Disney World, da scegliere l\'uno o l\'altro per la giornata più intensa del viaggio.',
    percheAndarci: 'Per l\'esperienza dei parchi a tema più famosi al mondo, in una giornata che richiede organizzazione ma ripaga con attrazioni uniche.',
    cosaVedere: ['I quattro parchi di Disney World', 'I due parchi di Universal Studios', 'Lake Eola nel centro città'],
    cosaFare: [
      'Giornata intera al parco a tema (Universal o Disney) — vedi la scheda esperienza dedicata',
      'Cena dentro Universal Studios o al Mango\'s Tropical Café',
      'Passeggiata serale intorno a Lake Eola',
    ],
    doveDormire:
      'Ho alloggiato in una villa privata in affitto stile Airbnb/VRBO, la soluzione più diffusa nelle zone residenziali vicino a Disney/Universal (es. Championsgate, Kissimmee): casa indipendente con piscina privata, più spazio e cucina propria rispetto a una camera d\'hotel. Non ho l\'indirizzo o il nome esatto della struttura.\n\nAlternative: economiche: Destiny Palms Hotel Kissimmee, Regal Oaks Resort (ville in comunità) · fascia media: Storey Lake Resort (ville), Hampton Inn Kissimmee North · lusso: Reunion Resort (ville), Omni Orlando Resort at ChampionsGate.',
    doveMangiare: 'Gringos Locos in centro; Mango\'s Tropical Café, con spettacolo serale.',
    comeArrivare: 'Circa 5h, 280 miglia da Naples, con soste facoltative lungo la Route 41/Tampa Bay.',
    comeSpostarsi: 'Auto a noleggio; navetta gratuita dell\'hotel per i parchi, dove disponibile.',
    periodoMigliore: 'arrivare almeno 1h prima dell\'apertura del parco',
    costi: 'Universal 130-210$ a seconda dei parchi; Disney World da 250€ per minimo 2 giorni; parcheggio 26$/auto a Universal Studios.',
    erroriDaEvitare: ['Scaricare l\'app ufficiale del parco per i tempi di attesa in tempo reale', 'Portare uno zaino piccolo: quelli grandi non entrano nei lockers'],
    esperienzeSlugs: ['parco-tema-orlando'],
    tripSlugs: ['florida-360'],
    imageAlt: 'Le luci serali di un parco a tema a Orlando, Florida',
    immagine: '/images/florida/orlando-stock.jpg',
  },
  {
    slug: 'cape-canaveral',
    paeseSlug: 'florida',
    ordine: 5,
    nome: 'Cape Canaveral',
    tipologia: ['scienza', 'famiglia'],
    giorniConsigliati: 'mezza giornata, meglio una intera',
    visitataPersonalmente: true,
    introduzione: 'Il Kennedy Space Center, con il razzo Saturn V, uno space shuttle vero e la storia della corsa allo spazio americana.',
    percheAndarci: 'Un complesso davvero impressionante, con la possibilità (da verificare in anticipo) di assistere a un lancio dal vivo.',
    cosaVedere: [
      'Il Rocket Garden',
      'Il razzo Saturn V nell\'Apollo/Saturn V Center',
      'Uno space shuttle vero nell\'Atlantis Building',
      'La grande sfera della NASA per la foto ricordo',
    ],
    cosaFare: [
      'Visita al Kennedy Space Center — vedi la scheda esperienza dedicata',
      'Cinema IMAX',
      'Incontro con un astronauta (30 minuti, orari da controllare)',
    ],
    doveDormire: 'Non ho pernottato qui: tappa di mezza/una giornata tra Orlando e Miami.',
    doveMangiare: 'Colazione veloce da Keke\'s o Starbucks prima di partire; pranzo possibile a Cocoa Beach.',
    comeArrivare: 'Circa 1h, 60 miglia da Orlando.',
    comeSpostarsi: 'Bus navetta gratuito tra i due siti del complesso.',
    periodoMigliore: 'controllare in anticipo se è previsto un lancio nel giorno della visita',
    costi: 'Biglietto Kennedy Space Center $57.',
    erroriDaEvitare: ['Evitare le corsie "toll by plate" sulla Florida Turnpike verso Miami: sono riservate a chi ha il SunPass'],
    miaEsperienza:
      'La ricostruzione della control room che lancia il razzo Saturn V, seguita dal razzo vero in tutta la sua enormità, è uno dei momenti più impressionanti di tutto il viaggio in Florida.',
    esperienzeSlugs: ['kennedy-space-center'],
    tripSlugs: ['florida-360'],
    imageAlt: 'Il razzo Saturn V esposto al Kennedy Space Center, Cape Canaveral, Florida',
    immagine: '/images/florida/cape-canaveral-stock.jpg',
  },
]
