import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Giappone in 12 giorni" (src/content/viaggi/05-giappone-360.md).
// Il Monte Fuji/Chureito (Giorno 3) è una giornata aggiunta editorialmente,
// non vissuta realmente: per questo resta con visitataPersonalmente: false
// e senza miaEsperienza, come dichiarato esplicitamente dal markdown sorgente.

export const destinazioniGiappone: Destinazione[] = [
  {
    slug: 'tokyo',
    paeseSlug: 'giappone',
    ordine: 1,
    nome: 'Tokyo',
    tipologia: ['città', 'sakura', 'cibo'],
    giorniConsigliati: '3-4 giorni, spezzati tra inizio e fine viaggio',
    visitataPersonalmente: true,
    introduzione: 'La caccia ai sakura tra Chidorigafuchi e Shinjuku Gyoen, Shibuya Crossing, Harajuku, Asakusa e Akihabara: il Giappone contemporaneo vissuto a spizzichi tra arrivo e rientro.',
    percheAndarci: 'Il punto di partenza e arrivo del viaggio, con abbastanza varietà di quartieri da meritare, con più tempo, un capitolo a sé.',
    cosaVedere: [
      'Chidorigafuchi, il fossato del castello imperiale',
      'Shinjuku Gyoen, il giardino nazionale',
      'Shibuya Crossing e la statua di Hachiko',
      'Senso-ji ad Asakusa',
      'Il Meiji-Jingu a Harajuku',
    ],
    cosaFare: [
      'Sakura chasing tra Chidorigafuchi, Shinjuku Gyoen, Ueno Park e Meguro River',
      'Aperitivo in un izakaya di Hoppy Street',
      'Kimono Hunting Experience per foto',
      'Shibuya Crossing dall\'alto (gratis dall\'ottavo piano del Centro per il Turismo, o a pagamento dal rooftop Mag8)',
      'Mercato del pesce di Tsukiji',
      'Akihabara, il regno di manga e anime',
      'Golden Gai a Shinjuku, il reticolo di vicoletti pieni di minuscoli bar',
    ],
    doveDormire:
      'Agora Place Asakusa (arrivo) — hotel economico-funzionale a due passi dalla metro, lobby più curata della media e personale gentile. Camere molto piccole (bagno compreso), qualche segnalazione di wifi debole. Sunshine City Prince Hotel a Ikebukuro (rientro) — hotel-torre comodo, collegato al centro commerciale Sunshine City, personale cordiale, camere adeguate ma non generose.\n\nAlternative ad Asakusa — economiche: Khaosan Tokyo Kabuki, APA Hotel Asakusa Kaminarimon · fascia media: Mimaru Tokyo Asakusa Station, Hotel Wing International Asakusa · lux non eccessivo: The Gate Hotel Asakusa Kaminarimon by HULIC, Asakusa View Hotel.',
    doveMangiare: 'MoMo Paradise (shabu-shabu/sukiyaki); Gyozaro per gyoza; Kyomachi Koishigure Shinjuku; Gonpachi (il locale che ha ispirato la scena del ristorante in Kill Bill).',
    usciteSerali: 'Golden Gai a Shinjuku; rooftop Mag8 su Shibuya Crossing.',
    comeArrivare: 'Volo internazionale su Tokyo.',
    comeSpostarsi: 'Metro e JR Pass (attivato dal quarto giorno), carta PASMO/IC per i giorni precedenti.',
    periodoMigliore: 'inizio aprile per i sakura, sapendo che il picco reale è spesso fine marzo',
    costi: 'Kimono Hunting Experience da 1.100 a 5.000+ yen; Shibuya Scramble Square a pagamento 1.500 yen circa.',
    erroriDaEvitare: ['Portare uno zaino o borsone morbido, mai un trolley: con tutti gli spostamenti su mezzi pubblici si rimpiange una valigia rigida'],
    miaEsperienza:
      'Siamo arrivati per la fioritura dei sakura ma con qualche giorno di scarto rispetto al picco: a inizio aprile i ciliegi di Tokyo erano già verso la fine, tra petali che cadevano come neve rosa (lo hanafubuki) e i rami più spogli. Un modo diverso, ma altrettanto bello, di vivere la fioritura.',
    esperienzeSlugs: ['sakura-chasing-tokyo', 'shibuya-crossing'],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Shibuya Crossing illuminato di sera a Tokyo, Giappone',
    immagine: '/images/giappone/tokyo-stock.jpg',
  },
  {
    slug: 'kamakura',
    paeseSlug: 'giappone',
    ordine: 2,
    nome: 'Kamakura',
    tipologia: ['storia', 'religione', 'mare'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'L\'antica capitale sul mare, con templi zen, il Grande Buddha e, per chi ha tempo, una spiaggia a due passi dai templi.',
    percheAndarci: 'Una gita di un giorno perfetta da Tokyo, per uscire dalla metropoli senza allontanarsi troppo.',
    cosaVedere: [
      'Il tempio Engaku-ji',
      'Il tempio Kencho-ji, con la Butsuden e il santuario Hansobo',
      'Il Santuario Tsurugaoka Hachimangu',
      'Il Grande Buddha di Kamakura al tempio Kotoku-in',
      'La spiaggia di Shichirigahama',
    ],
    cosaFare: [
      'Visita ai templi di Kita-Kamakura',
      'Passeggiata lungo Komachi Dori per street food',
      'Visita al Grande Buddha',
      'Sosta alla spiaggia di Shichirigahama, se il tempo lo permette',
    ],
    doveDormire: 'Non ho pernottato qui: gita di un giorno da Tokyo.',
    doveMangiare: 'Street food lungo Komachi Dori.',
    comeArrivare: 'Metro fino a Shimbashi, poi linea Yokosuka fino a Kita-Kamakura (circa 820 yen).',
    comeSpostarsi: 'A piedi tra i templi.',
    periodoMigliore: 'giornata di sole, per vedere il Monte Fuji in lontananza dalla campana dell\'Engaku-ji',
    costi: 'Engaku-ji 400 yen; Kencho-ji 450 yen.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Pochi sanno che a Kamakura si è letteralmente a due passi dal mare: la sosta alla spiaggia di Shichirigahama dopo una mattinata di templi è stata una sorpresa piacevole, un lato meno noto di questa gita.',
    esperienzeSlugs: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Il Grande Buddha del tempio Kotoku-in a Kamakura, Giappone',
    immagine: '/images/giappone/kamakura-stock.jpg',
  },
  {
    slug: 'monte-fuji-chureito',
    paeseSlug: 'giappone',
    ordine: 3,
    nome: 'Monte Fuji e Pagoda Chureito',
    tipologia: ['natura', 'sakura'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: false,
    introduzione: 'Il punto panoramico più iconico del Giappone: la pagoda rossa a cinque piani in primo piano, il Monte Fuji sullo sfondo.',
    percheAndarci: 'Per l\'immagine simbolo del Giappone, e per recuperare i sakura mancati a Tokyo: la fioritura a Chureito arriva circa una settimana dopo quella della capitale.',
    cosaVedere: ['La Pagoda Chureito nel Parco Arakurayama Sengen, con il Monte Fuji sullo sfondo', 'Il Lago Kawaguchiko'],
    cosaFare: [
      'Salita dei 398 gradini fino alla Pagoda Chureito',
      'Giro sulle rive del Lago Kawaguchiko, eventualmente in barca',
      'Salita in funivia al monte Tenjo',
      'Onsen con vista Fuji, ad esempio all\'Hotel Mifujien',
    ],
    doveDormire: 'Non pernottato: gita di un giorno da Tokyo (Agora Place Asakusa).',
    doveMangiare: 'da completare',
    comeArrivare: 'Treno Fuji Excursion da Shinjuku a Kawaguchiko (circa 2h, ~4.130 yen; con JR Pass si copre la tratta fino a Otsuki e si paga solo il supplemento Fujikyu, circa 1.770 yen).',
    comeSpostarsi: 'A piedi per la salita alla pagoda, giro del lago in autonomia.',
    periodoMigliore: 'metà aprile, quando i ciliegi a Chureito sono spesso ancora in piena fioritura',
    costi: 'Onsen all\'Hotel Mifujien circa 1.200 yen.',
    erroriDaEvitare: ['Arrivare il prima possibile alla pagoda, appena si apre, per evitare la folla e avere la luce migliore'],
    esperienzeSlugs: ['chureito-monte-fuji'],
    tripSlugs: [],
    imageAlt: 'La Pagoda Chureito con il Monte Fuji sullo sfondo, Giappone',
    immagine: '/images/copertine/giappone-360.jpg',
  },
  {
    slug: 'kyoto',
    paeseSlug: 'giappone',
    ordine: 4,
    nome: 'Kyoto',
    tipologia: ['cultura', 'religione', 'sakura'],
    giorniConsigliati: '3 giorni',
    visitataPersonalmente: true,
    introduzione: 'I mille torii di Fushimi Inari, il Tempio d\'Oro, la foresta di bambù di Arashiyama e il quartiere delle geiko a Gion: il cuore culturale del Giappone.',
    percheAndarci: 'La concentrazione più alta di simboli del Giappone tradizionale in un\'unica città.',
    cosaVedere: [
      'Fushimi Inari, il santuario dei mille torii vermigli',
      'Kinkaku-ji, il Tempio d\'Oro',
      'Kiyomizudera',
      'Il Castello Nijo',
      'La Foresta di bambù di Arashiyama',
      'Il Sentiero del Filosofo',
    ],
    cosaFare: [
      'Nishiki Market',
      'Cerimonia del tè con Camellia a Gion',
      'Arashiyama Monkey Park Iwatayama',
      'Okochi Sanso Garden',
      'Walking tour di Gion',
      'Miyako Odori, la danza tradizionale delle geiko/maiko (stagionale)',
    ],
    doveDormire:
      'Agora Kyoto Shijo — buona scelta di fascia media: camere più spaziose della media giapponese, separazione tra zona bagno e doccia citata spesso come punto di forza, posizione comoda vicino a Shijo Street. Servizio clienti con valutazioni altalenanti.\n\nEconomiche: K\'s House Kyoto, Piece Hostel Sanjo · fascia media: Mitsui Garden Hotel Kyoto Shijo, Hotel Vista Premio Kyoto · lux non eccessivo: Gion Hatanaka (ryokan con onsen), The Celestine Kyoto Gion.',
    doveMangiare: 'Menbaka Fire Ramen (show col fuoco, da prenotare con anticipo); Hamburg Labo; Sushi No Musashi (sushi a nastro).',
    usciteSerali: 'Zona Pontocho, tra i club World Club e The Common One; Funaoka Onsen.',
    comeArrivare: 'Shinkansen Hikari da Tokyo, circa 2h40.',
    comeSpostarsi: 'A piedi, bus per Fushimi Inari e Kiyomizudera.',
    periodoMigliore: 'inizio-metà aprile per i sakura lungo il Sentiero del Filosofo',
    costi: 'Cerimonia del tè 2.700 yen + 3.000 yen per il kimono; Okochi Sanso Garden 1.000 yen; Miyako Odori 6.000 yen.',
    erroriDaEvitare: ['Prenotare il Menbaka Fire Ramen e la cerimonia del tè con largo anticipo: i posti si esauriscono in fretta', 'Rispettare i divieti di foto ai turisti a Gion, con multe salate in caso di infrazione'],
    miaEsperienza:
      'Il primo tratto di Fushimi Inari, quello fotografato da tutti, è spettacolare anche senza arrivare fino in vetta. La foresta di bambù di Arashiyama vista verso il tramonto, quando la folla diurna si dirada, resta una delle immagini più belle di tutto il viaggio.',
    esperienzeSlugs: ['fushimi-inari', 'kinkaku-ji'],
    tripSlugs: ['giappone-360'],
    imageAlt: 'I torii vermigli del santuario di Fushimi Inari, Kyoto, Giappone',
    immagine: '/images/giappone/kyoto-stock.jpg',
  },
  {
    slug: 'hiroshima-miyajima',
    paeseSlug: 'giappone',
    ordine: 5,
    nome: 'Hiroshima e Miyajima',
    tipologia: ['storia', 'religione'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Il Memoriale della Pace di Hiroshima e il torii galleggiante di Miyajima, in una giornata che alterna riflessione e meraviglia.',
    percheAndarci: 'Per un momento di riflessione necessario sulla storia del Giappone, bilanciato dalla bellezza di Miyajima nello stesso giorno.',
    cosaVedere: [
      'Il Memoriale della Pace e il Parco della Pace di Hiroshima',
      'Il Santuario Itsukushima, con il celebre torii "galleggiante" sull\'acqua',
      'Il Daisho-in a Miyajima',
    ],
    cosaFare: [
      'Visita al Museo del Memoriale della Pace con audioguida',
      'Traghetto verso Miyajima (incluso nel JR Pass)',
      'Street food a base di ostriche sull\'isola',
    ],
    doveDormire:
      'Toyoko Inn Hiroshima Station (o in alternativa una notte in minshuku/ryokan tradizionale) — catena economica ma affidabile: camere essenziali e pulite, colazione inclusa apprezzata, comoda vicino alla stazione. Pareti sottili il difetto più ricorrente.\n\nEconomiche: APA Hotel Hiroshima Ekimae Ohashi, Centurion Hotel Residential Hiroshima Ekimae · fascia media: Hotel Sunroute Hiroshima, Courtyard by Marriott Hiroshima · lux non eccessivo: Hotel Granvia Hiroshima, Sheraton Grand Hiroshima Hotel.',
    doveMangiare: 'Koba, per concentrare pre-cena e dopocena nello stesso locale.',
    comeArrivare: 'Shinkansen Hikari da Kyoto, circa 2h.',
    comeSpostarsi: 'Traghetto per Miyajima incluso nel JR Pass.',
    periodoMigliore: 'giornata di sole per il torii galleggiante con l\'alta marea',
    costi: 'da completare',
    erroriDaEvitare: ['Spedire i bagagli pesanti verso la tappa successiva la sera prima (servizio takkyubin), per viaggiare leggeri'],
    miaEsperienza:
      'Il Memoriale della Pace è una tappa intensa che vale la pena affrontare con calma. Vedere il torii "galleggiante" di Miyajima nel pomeriggio, dopo la visita al Museo, ha dato alla giornata un equilibrio raro tra riflessione e meraviglia.',
    esperienzeSlugs: ['torii-miyajima'],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Il torii galleggiante del Santuario Itsukushima a Miyajima, Giappone',
    immagine: '/images/giappone/miyajima-stock.jpg',
  },
  {
    slug: 'himeji',
    paeseSlug: 'giappone',
    ordine: 6,
    nome: 'Himeji',
    tipologia: ['storia'],
    giorniConsigliati: 'mezza giornata',
    visitataPersonalmente: true,
    introduzione: 'Il Castello di Himeji, il più bello e meglio conservato del Giappone, e una sosta ideale per assaggiare il vero manzo di Kobe.',
    percheAndarci: 'Uno dei pochi castelli feudali sopravvissuti intatti, tappa naturale tra Hiroshima e Osaka.',
    cosaVedere: ['Il Castello di Himeji', 'I Giardini Kokoen'],
    cosaFare: ['Visita guidata al castello', 'Pranzo a base di manzo di Kobe/Wagyu'],
    doveDormire: 'Non ho pernottato qui: tappa di passaggio verso Osaka.',
    doveMangiare: 'Fuku-tei (spiedini e burger da asporto, ottimo rapporto qualità-prezzo) o una steakhouse teppanyaki di Kobe per un\'esperienza più importante (70-80€ per 150g di carne).',
    comeArrivare: 'Shinkansen Kodama da Hiroshima; se disponibile, il treno a tema Hello Kitty su alcune tratte.',
    comeSpostarsi: 'A piedi dal castello ai giardini.',
    periodoMigliore: 'mattina, prima dell\'affollamento',
    costi: 'Biglietto combinato castello + Giardini Kokoen 1.060 yen.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Il Castello di Himeji è probabilmente il più fotogenico di tutto il viaggio, e la sosta per il manzo di Kobe nelle vicinanze è stata un bel modo per chiudere la mattinata prima di ripartire per Osaka.',
    esperienzeSlugs: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Il Castello di Himeji, il più bello e meglio conservato del Giappone',
    immagine: '/images/giappone/himeji-stock.jpg',
  },
  {
    slug: 'osaka',
    paeseSlug: 'giappone',
    ordine: 7,
    nome: 'Osaka',
    tipologia: ['città', 'cibo'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'Il Castello di Osaka, il quartiere di Dotonbori e Shinsekai: la capitale non ufficiale del cibo di strada giapponese.',
    percheAndarci: 'Per il cibo, probabilmente il vero filo conduttore del viaggio, e per l\'atmosfera più informale rispetto a Tokyo e Kyoto.',
    cosaVedere: ['Il Castello di Osaka, con vista dall\'ottavo piano', 'Dotonbori', 'La Torre di Tsutenkaku a Shinsekai'],
    cosaFare: [
      'Tombori River Cruise (20 minuti, 1.000 yen)',
      'Osaka Foodie Tour organizzato in zona',
      'Torikizoku, all-you-can-eat-and-drink per due ore (3.600 yen)',
      'Mercato di Kuromon, con tappa da Rikuro-Ojisan no Mise per il cheesecake giapponese',
      'Shinsekai by night',
    ],
    doveDormire:
      'Sarasa Hotel Namba — sorpresa positiva nelle recensioni, punteggio tra i più alti della zona: camere più ampie della media, personale disponibile, piccoli extra (pigiama, ciabattine, prestito smartphone) che alzano il livello percepito.\n\nEconomiche: Khaosan World Namba, First Cabin Namba · fascia media: Namba Oriental Hotel, Hotel Hokke Club Namba · lux non eccessivo: Swissotel Nankai Osaka, Hotel Nikko Osaka.',
    doveMangiare: 'Jumbo-tsuribune Tsurikichi per kushikatsu, okonomiyaki e takoyaki; Rikuro-Ojisan no Mise per il cheesecake.',
    usciteSerali: 'Shinsekai, con la Torre di Tsutenkaku.',
    comeArrivare: 'Da Himeji, nessuna prenotazione necessaria.',
    comeSpostarsi: 'A piedi, linea Kintetsu per Nara.',
    periodoMigliore: 'sera, per Dotonbori e Shinsekai illuminati',
    costi: 'Tombori River Cruise 1.000 yen; Torre di Tsutenkaku 900 yen; cheesecake 900-1.000 yen l\'intera torta.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Osaka è stata la sorpresa gastronomica del viaggio: tra kushikatsu, okonomiyaki e takoyaki nella zona di Shinsekai, il cibo di strada qui ha un\'energia diversa da quella più composta di Tokyo e Kyoto.',
    esperienzeSlugs: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Il quartiere di Dotonbori illuminato di sera a Osaka, Giappone',
    immagine: '/images/giappone/osaka-stock.jpg',
  },
  {
    slug: 'nara',
    paeseSlug: 'giappone',
    ordine: 8,
    nome: 'Nara',
    tipologia: ['natura', 'religione'],
    giorniConsigliati: 'mezza giornata',
    visitataPersonalmente: true,
    introduzione: 'I cervi sacri semi-liberi che passeggiano tra i templi, in una delle esperienze più surreali di tutto il Giappone.',
    percheAndarci: 'Per un\'atmosfera unica, tra il grande Buddha di Todaiji e i cervi che si avvicinano senza timore ai visitatori.',
    cosaVedere: [
      'Todaiji, con il grande Buddha',
      'Kasuga Taisha Shrine, il santuario delle mille lanterne',
      'Il Parco di Nara, con i cervi sacri (Sika deer)',
    ],
    cosaFare: [
      'Tappa golosa da Nakatanidou per i mochi, con lo spettacolo di preparazione',
      'Passeggiata nel Parco di Nara tra i cervi',
      'Old Nara Street, tra i due templi principali',
    ],
    doveDormire: 'Non ho pernottato qui: gita di mezza giornata da Osaka.',
    doveMangiare: 'Maguro Koya, per tonno e sashimi di qualità notevole.',
    comeArrivare: 'Linea Kintetsu da Namba (verificare copertura JR Pass).',
    comeSpostarsi: 'A piedi nel Parco di Nara.',
    periodoMigliore: 'metà mattina, per lo spettacolo di preparazione dei mochi da Nakatanidou',
    costi: 'da completare',
    erroriDaEvitare: ['Arrivare presto da Nakatanidou: c\'è sempre moltissima gente per lo spettacolo di preparazione dei mochi'],
    miaEsperienza:
      'Vedere i cervi sacri passeggiare liberi tra i templi, avvicinandosi senza timore ai visitatori, è stata una delle esperienze più surreali e piacevoli di tutto il viaggio.',
    esperienzeSlugs: ['cervi-nara'],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Cervi sacri semi-liberi tra i templi del Parco di Nara, Giappone',
    immagine: '/images/giappone/nara-stock.jpg',
  },
]
