import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Giordania 360°" (src/content/viaggi/03-giordania-360.md),
// arricchito con il feedback diretto dell'autore su Jerash, Monte Nebo, Mar Morto,
// Petra/Wadi Rum e il diving ad Aqaba.

export const destinazioniGiordania: Destinazione[] = [
  {
    slug: 'amman',
    paeseSlug: 'giordania',
    ordine: 1,
    nome: 'Amman',
    tipologia: ['città', 'storia'],
    giorniConsigliati: '1-2 giorni, come arrivo/rientro',
    visitataPersonalmente: true,
    introduzione: 'La capitale, punto di arrivo e di rientro del viaggio, con la Cittadella, il Teatro Romano e la vita serale di Rainbow Street.',
    percheAndarci: 'È l\'ingresso naturale al paese e, al rientro dal deserto e dal Mar Rosso, un\'ultima giornata di cultura e vita cittadina prima del volo.',
    cosaVedere: ['La Cittadella di Amman', 'Il Teatro Romano', 'Rainbow Street'],
    cosaFare: [
      'Cena di benvenuto da Zajal (Prince Mohammed Street, circa 15 JOD)',
      'Visita alla Cittadella e al Teatro Romano',
      'Pranzo al Bazaar',
      'Cooking class e corso di calligrafia araba',
      'Serata da Talet Al Jabal o C-Ling su Rainbow Street',
    ],
    doveDormire:
      'Ho dormito in un hotel generico (il nome non è annotato nei documenti di viaggio); una zona comoda in centro va benissimo per muoversi a piedi tra Cittadella, Teatro Romano e Rainbow Street.\n\nEconomici: Farah Hotel & Hostel, Cliff Hostel, entrambi a due passi dal Teatro Romano · fascia media: Toledo Hotel (vicino a Rainbow Street), Kaya Hotel Amman (quartiere Abdali, spa interna) · più lussuosi: Fairmont Amman, W Amman.',
    doveMangiare: 'Zajal per la cena di benvenuto; pranzo al Bazaar al rientro.',
    usciteSerali: 'Talet Al Jabal o C-Ling, su Rainbow Street.',
    comeArrivare: 'Volo internazionale su Amman.',
    comeSpostarsi: 'Transfer organizzati, a piedi nel centro.',
    periodoMigliore: 'dicembre-gennaio',
    costi: 'Cena da Zajal circa 15 JOD; buggy nel deserto vicino Amman 40 JOD (opzione alternativa del Giorno 7).',
    erroriDaEvitare: [],
    miaEsperienza:
      'La Cittadella, con vista su tutta la città vecchia, è stata una tappa carina per chiudere il viaggio prima del volo di rientro, senza essere il punto più memorabile della Giordania.',
    esperienzeSlugs: ['cittadella-amman'],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Le colonne del Tempio di Ercole sulla Cittadella di Amman, Giordania',
    immagine: '/images/giordania/amman-stock.jpg',
  },
  {
    slug: 'jerash',
    paeseSlug: 'giordania',
    ordine: 2,
    nome: 'Jerash',
    tipologia: ['storia', 'archeologia'],
    giorniConsigliati: 'mezza giornata',
    visitataPersonalmente: true,
    introduzione: 'Una delle città romane meglio conservate al mondo fuori dall\'Italia, con il suo foro ovale, il cardo colonnato e i due teatri.',
    percheAndarci: 'Una tappa lungo la strada tra Amman e il Mar Morto che vale la sosta di persé, molto più bella di quanto ci si aspetti da una tappa "di passaggio".',
    cosaVedere: ['Il Foro Ovale', 'Il Cardo colonnato', 'I due teatri romani'],
    cosaFare: ['Visita guidata al sito archeologico'],
    doveDormire: 'Non ho pernottato qui: tappa di passaggio tra Amman e il Mar Morto.',
    doveMangiare: 'Nessuna indicazione specifica: sosta prevalentemente per la visita.',
    comeArrivare: 'Circa 1h di transfer da Amman, con sosta per acquistare alcolici lungo il tragitto.',
    comeSpostarsi: 'A piedi all\'interno del sito archeologico.',
    periodoMigliore: 'mattina, prima del caldo e dei gruppi organizzati',
    costi: 'Ingresso incluso nel Jordan Pass.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Jerash è stata una sorpresa molto piacevole: una delle città romane meglio conservate che abbia visto, con il cardo colonnato che si estende a perdita d\'occhio. Molto bella, decisamente più di una semplice tappa di passaggio.',
    esperienzeSlugs: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Il cardo colonnato del sito archeologico romano di Jerash, Giordania',
    immagine: '/images/giordania/jerash-stock.jpg',
  },
  {
    slug: 'mar-morto',
    paeseSlug: 'giordania',
    ordine: 3,
    nome: 'Mar Morto',
    tipologia: ['natura', 'relax'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Il galleggiamento nelle acque iper-saline più basse della Terra, ancora più suggestivo al tramonto con le colline della Cisgiordania sullo sfondo.',
    percheAndarci: 'Un\'esperienza fisica unica, impossibile da replicare altrove, e un buon contrappunto rilassato tra Jerash e la parte più intensa del viaggio.',
    cosaVedere: ['Il tramonto sulle colline della Cisgiordania'],
    cosaFare: [
      'Bagno nelle acque iper-saline al tramonto',
      'Relax in resort',
      'Cena a Madaba (Haret Jdoudna o Hikayet Sitti)',
      'Dopocena al Saint John Sky Bar o al bar del Grand Hotel Madaba',
    ],
    doveDormire:
      'Ho dormito all\'Holiday Inn Resort Dead Sea by IHG. Dalle recensioni raccolte online (Tripadvisor, circa 5.600 recensioni, media 4/5) emerge un resort di fascia media-alta con staff attento, tre piscine, spiaggia privata e buffet abbondante; i punti dolenti più citati sono i prezzi alti di cibo e bevande interni, qualche problema di manutenzione nelle camere e il divieto di portare cibo dall\'esterno.\n\nEconomici: Ramada Resort by Wyndham Dead Sea, O Beach Hotel & Resort (accesso diretto al mare a una frazione del prezzo) · fascia media: Dead Sea Spa Hotel, Crowne Plaza Jordan Dead Sea Resort & Spa (qui si colloca l\'Holiday Inn) · più lussuosi: Hilton Dead Sea Resort & Spa, Kempinski Hotel Ishtar Dead Sea.',
    doveMangiare: 'Haret Jdoudna o Hikayet Sitti a Madaba; dopocena al bar del Grand Hotel Madaba o al Saint John Sky Bar.',
    comeArrivare: 'Circa 1h30 di transfer da Jerash.',
    comeSpostarsi: 'A piedi nel resort, transfer organizzato verso Madaba per cena.',
    periodoMigliore: 'tramonto',
    costi: 'da completare — prezzi del resort non specificati nel diario.',
    erroriDaEvitare: ['Acquistare alcolici a Madaba (Soho o Hangover) prima di spostarsi verso zone più conservatrici o il deserto'],
    miaEsperienza:
      'Galleggiare a pelo d\'acqua guardando il sole calare dietro le colline della Cisgiordania è stata un\'esperienza a sé, soprattutto vissuta al tramonto: probabilmente il momento in cui il Mar Morto rende più di quanto ci si aspetti.',
    esperienzeSlugs: ['bagno-mar-morto'],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Galleggiamento nelle acque del Mar Morto al tramonto, Giordania',
    immagine: '/images/giordania/mar-morto-stock.jpg',
  },
  {
    slug: 'karak-monte-nebo',
    paeseSlug: 'giordania',
    ordine: 4,
    nome: 'Karak e Monte Nebo',
    tipologia: ['storia', 'religione'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'La fortezza crociata di Karak e il Monte Nebo, il luogo da cui la tradizione vuole che Mosè abbia visto la Terra Promessa, lungo il tragitto verso Little Petra.',
    percheAndarci: 'Karak è una tappa storica solida sull\'altopiano a sud del Mar Morto; il Monte Nebo va messo in conto più per il suo valore simbolico che per l\'impatto scenico reale.',
    cosaVedere: ['La fortezza crociata di Karak Castle', 'Il panorama dal Monte Nebo'],
    cosaFare: ['Visita a Karak Castle', 'Sosta al Monte Nebo'],
    doveDormire: 'Non ho pernottato qui: tappa di passaggio verso Little Petra e Wadi Musa.',
    doveMangiare: 'Pranzo lungo la strada tra Monte Nebo e Little Petra.',
    comeArrivare: 'Circa 1h30 di transfer da Madaba per Karak; il Monte Nebo è una sosta successiva lungo il percorso verso Little Petra.',
    comeSpostarsi: 'A piedi all\'interno della fortezza di Karak.',
    periodoMigliore: 'mattina',
    costi: 'Ingresso a Karak incluso nel Jordan Pass.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Karak Castle è una fortezza imponente e vale la visita. Il Monte Nebo, sinceramente, mi ha lasciato indifferente: il valore è più simbolico (il luogo da cui la tradizione vuole che Mosè abbia visto la Terra Promessa) che scenico, e nella giornata è stata la tappa che ricordo meno.',
    esperienzeSlugs: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Le mura in pietra della fortezza crociata di Karak Castle, Giordania',
    immagine: '/images/giordania/karak-stock.jpg',
  },
  {
    slug: 'petra',
    paeseSlug: 'giordania',
    ordine: 5,
    nome: 'Petra e Little Petra',
    tipologia: ['storia', 'trekking', 'unesco'],
    giorniConsigliati: '1 giornata intera per Petra, mezza giornata per Little Petra',
    visitataPersonalmente: true,
    introduzione: 'Il vero cuore del viaggio: il Siq, il Tesoro (Al-Khazneh), la salita al Monastero (Ad-Deir) e, come anticipo, il piccolo canyon di Little Petra.',
    percheAndarci: 'Una delle Sette Meraviglie del Mondo Moderno, patrimonio UNESCO, vissuta quasi deserta per via del calo turistico regionale: un privilegio raro e irripetibile.',
    cosaVedere: [
      'Il Siq, la gola naturale lunga 1,2-1,5 km scavata nella roccia arenaria rosa',
      'Il Tesoro (Al-Khazneh), 39-40 metri di facciata scolpita nella roccia',
      'Le Tombe Reali',
      'Il Monastero (Ad-Deir), 45 metri di altezza per 50 di larghezza',
      'Little Petra (Siq al-Barid), l\'anticamera in miniatura di Petra',
    ],
    cosaFare: [
      'Cammino nel Siq fino al Tesoro (30-40 minuti)',
      'Salita al Monastero: oltre 800 gradini, 40-45 minuti di cammino ripido',
      'Tè alla menta al chiosco davanti al Monastero',
      'Little Petra Trek il giorno prima',
      'Hammam e bagno turco da Al Yhakor (Al Yakhor Turkish Bath, Wadi Musa) a fine giornata',
    ],
    doveDormire:
      'Ho dormito in un hotel generico a Wadi Musa (nome non annotato); comoda perché a pochi minuti a piedi o in navetta dall\'ingresso di Petra.\n\nEconomici: Petra Cabin Hostel, Rocky Mountain Hotel (conduzione familiare, terrazza panoramica) · fascia media: Petra Panorama Hotel, La Maison Hotel Petra · più lussuosi: Petra Moon Luxury Hotel (boutique, vicinissimo all\'ingresso), Petra Marriott Hotel.',
    doveMangiare: 'Cena tipica organizzata dal DMC il giorno di Little Petra.',
    comeArrivare: 'Little Petra e Wadi Musa raggiunti in transfer da Karak/Monte Nebo il giorno prima di Petra.',
    comeSpostarsi: 'A piedi lungo tutto il sito, incluso il Siq e la salita al Monastero.',
    periodoMigliore: 'mattina presto, per il Siq e il Tesoro con meno luce diretta e meno persone',
    costi: 'Ingresso incluso nel Jordan Pass.',
    erroriDaEvitare: ['Portare scarpe da trekking, indispensabili soprattutto per la salita al Monastero (oltre 800 gradini)'],
    miaEsperienza:
      'Vedere il Tesoro emergere dal Siq senza le folle abituali davanti è un momento che da solo vale il viaggio. La salita al Monastero ripaga ogni singolo gradino con una vista ancora più imponente del Tesoro stesso. Anche Little Petra, il giorno prima, è stata bellissima: meno affollata e già capace di dare la prima scarica di entusiasmo. Insieme a Wadi Rum, il vero must di tutto il viaggio.',
    esperienzeSlugs: ['salita-monastero-petra', 'hammam-wadi-musa'],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Il Tesoro (Al-Khazneh) scavato nella roccia arenaria rosa a Petra, Giordania',
    immagine: '/images/copertine/giordania-360.jpg',
  },
  {
    slug: 'wadi-rum',
    paeseSlug: 'giordania',
    ordine: 6,
    nome: 'Wadi Rum',
    tipologia: ['deserto', 'avventura'],
    giorniConsigliati: '1 giorno e una notte',
    visitataPersonalmente: true,
    introduzione: 'La "Valle della Luna": deserto di sabbia rossa e formazioni di arenaria che ha fatto da set a Lawrence d\'Arabia, vissuto con cammellata, jeep safari e una notte di Capodanno sotto le stelle.',
    percheAndarci: 'Il secondo grande protagonista del viaggio dopo Petra, e insieme a Petra il vero must di tutta la Giordania.',
    cosaVedere: [
      'La Sorgente di Lawrence',
      'Il canyon di Khazali con le incisioni rupestri nabatee',
      'Le dune rosse e i ponti di roccia naturali come Umm Fruth',
      'La Casa di Lawrence',
      'Il cielo stellato di Capodanno, lontano da ogni inquinamento luminoso',
    ],
    cosaFare: [
      'Cammellata di 45 minuti (20 JOD)',
      'Jeep safari di 4-6 ore sui classici pick-up beduini',
      'Sandboarding sulle dune',
      'Guidare la jeep nel deserto in prima persona (per chi se la sente)',
      'Partita di beach volley improvvisata sulla sabbia',
      'Cena beduina tipica (spesso zarb, cotto sotto la sabbia)',
      'Festa di Capodanno nel deserto',
      'Alba sulle dune il mattino dopo',
    ],
    doveDormire:
      'Ho dormito in un campo tendato nel deserto (nome non annotato): tenda beduina classica, cena e colazione incluse, cielo stellato impareggiabile.\n\nCampo base, bagno condiviso: Wadi Rum Bedouin Camp, Bedouin Lifestyle Camp · tenda privata con bagno: Wadi Rum Serenity Camp, Zeina Desert Lodge · luxury desert camp: Sun City Camp (celebre per i "martian domes"), Palmera Camp (tende/bubble panoramiche con bagno privato).',
    doveMangiare: 'Cena beduina tipica al campo tendato, sosta in panetteria/pasticceria locale per il pranzo al sacco (10 JOD).',
    comeArrivare: 'Circa 1h30 di transfer da Wadi Musa/Petra.',
    comeSpostarsi: 'Jeep 4x4 con guida beduina, cammello per il tratto iniziale nel deserto.',
    periodoMigliore: 'il periodo di Capodanno, per la festa nel deserto sotto le stelle; l\'alba per la luce migliore sulle dune',
    costi: 'Cammellata 20 JOD; pranzo al sacco 10 JOD.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Il jeep safari tra canyon e dune rosse, il sandboarding, il tramonto sulle dune all\'arrivo al campo e infine la festa di Capodanno sotto uno dei cieli stellati più belli visti in vita mia: difficile immaginare un modo più assurdo di salutare l\'anno vecchio. Insieme a Petra, il vero must di tutto il viaggio in Giordania.',
    esperienzeSlugs: ['jeep-safari-wadi-rum', 'capodanno-deserto'],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Jeep 4x4 tra le dune rosse e le formazioni di arenaria di Wadi Rum, Giordania',
    immagine: '/images/giordania/wadi-rum-stock.jpg',
  },
  {
    slug: 'aqaba',
    paeseSlug: 'giordania',
    ordine: 7,
    nome: 'Aqaba',
    tipologia: ['mare', 'relax'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Dal deserto al Mar Rosso in meno di un\'ora: beach club, sport acquatici, snorkeling e diving prima del rientro ad Amman.',
    percheAndarci: 'Uno dei contrasti più belli della Giordania, per chiudere la parte più intensa del viaggio con un giorno di mare.',
    cosaVedere: ['Le barriere coralline del Mar Rosso'],
    cosaFare: [
      'Beach club',
      'Sport acquatici (jet ski, banana boat)',
      'Snorkeling sulle barriere coralline',
      'Diving (organizzato in autonomia)',
      'Boat tour con Deep Blue (incluso nel pacchetto)',
    ],
    doveDormire:
      'Ho dormito in un hotel generico (nome non annotato); comodo per la vicinanza a spiaggia e lungomare.\n\nEconomici: Days Inn Hotel & Suites Aqaba, Extra Traveller (hostel) · fascia media: Golden Tulip Aqaba, Bratus Hotel Aqaba · più lussuosi: Kempinski Hotel Aqaba, Mövenpick Resort & Spa Aqaba.',
    doveMangiare: 'Sheikh El Harah (specialità di pesce), Suzana, Buffalo Wings & Ring (cucina americana), Khubza & Seneya (Al Nahda Street).',
    comeArrivare: 'Circa 1h di transfer da Wadi Rum.',
    comeSpostarsi: 'Transfer verso la spiaggia (15 minuti dall\'hotel).',
    periodoMigliore: 'giornata di sole, dopo l\'alba nel deserto',
    costi: 'Boat tour con Deep Blue incluso nel pacchetto.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Abbiamo fatto anche diving ad Aqaba: carino e piacevole, ma niente di memorabile rispetto ad altri punti del Mar Rosso più rinomati per le immersioni (l\'Egitto su tutti). Resta comunque una bella giornata di decompressione dopo il deserto, tra snorkeling e sport d\'acqua.',
    esperienzeSlugs: ['diving-aqaba'],
    tripSlugs: ['giordania-360'],
    imageAlt: 'La costa di Aqaba sul Mar Rosso, Giordania',
    immagine: '/images/giordania/aqaba-stock.jpg',
  },
]
