import type { Destinazione } from '@/lib/types'

// Contenuto riutilizzato dal viaggio "Islanda in tenda: 9 giorni sull'isola del
// ghiaccio e del fuoco" (src/content/viaggi/02-islanda-2024.md).
// Dove un dato non è nel diario originale, il campo resta vuoto o con una nota
// esplicita "da confermare/da completare" — nessun fatto inventato.
//
// Le immagini sono foto stock temporanee (Pixabay/Pexels, licenze free-use),
// scelte per rappresentare davvero il luogo in attesa delle foto reali del
// viaggio — vanno sostituite non appena disponibili gli scatti originali.

export const destinazioniIslanda: Destinazione[] = [
  {
    slug: 'keflavik',
    paeseSlug: 'islanda',
    ordine: 1,
    nome: 'Keflavík',
    tipologia: ['cultura'],
    giorniConsigliati: '1 notte, all\'arrivo',
    visitataPersonalmente: true,
    introduzione: 'Il primo hub del viaggio: qui si atterra, si dorme la prima notte in hotel (l\'unica insieme a Reykjavík) e si ritirano auto e tenda il giorno dopo.',
    percheAndarci: 'Punto di partenza obbligato, e a pochi minuti dalla penisola di Reykjanes, zona vulcanicamente attiva.',
    cosaVedere: ['Il centro di Keflavík', 'La penisola di Reykjanes'],
    cosaFare: [
      'Cena da Kaffi Duus e giro serale in centro',
      'Escursione al vulcano in eruzione sulla penisola di Reykjanes — vedi la scheda esperienza dedicata (giorno/logistica esatta da confermare)',
    ],
    doveDormire:
      'Ho dormito al Konvin Hotel, uno degli hotel più grandi della zona aeroporto: comodo grazie alla navetta e con colazione abbondante. Le recensioni online (circa 3/5 su quasi 940 recensioni Tripadvisor) restituiscono un quadro nella media per uno scalo di una notte — chi lo sceglie per la vicinanza all\'aeroporto lo trova pratico e il personale gentile, altri segnalano stanze fredde o bagni non impeccabili. Niente di eccezionale, ma funzionale per la prima notte.\n\nAlternative a Keflavík/Reykjanesbær — economiche: guesthouse e piccoli B&B della zona · fascia media (qui rientra il Konvin Hotel scelto): altri hotel vicino all\'aeroporto con navetta inclusa · più curate: hotel boutique in centro a Reykjavík (~45 min di auto), per chi preferisce sacrificare la comodità dell\'aeroporto alla prima o ultima notte.',
    doveMangiare: 'Kaffi Duus (bus 55 + pochi minuti a piedi): pesce misto, circa 30€ a persona.',
    comeArrivare: 'Volo su Keflavík; bus 55 (circa 20 minuti, fermata Kellir, 4€ a persona) fino in centro.',
    comeSpostarsi: 'Bus 55 il primo giorno; auto a noleggio dal giorno dopo (ritiro da Sixt Rent a Car in aeroporto).',
    periodoMigliore: 'da confermare',
    costi: 'Bus 55: 4€ a persona a tratta.',
    erroriDaEvitare: ['L\'ultima corsa del bus 55 parte poco dopo le 23: da non perdere per rientrare in hotel'],
    miaEsperienza:
      'Keflavík è stata una tappa breve ma con un ricordo fortissimo legato a lei: durante il viaggio ho visto da vicino un vulcano in eruzione sulla penisola di Reykjanes, a pochi minuti da qui — una delle esperienze più forti di tutta l\'Islanda (sto ancora ricostruendo il giorno esatto in cui è successo).',
    esperienzeSlugs: ['vulcano-reykjanes'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Colata di lava incandescente durante un\'eruzione notturna sulla penisola di Reykjanes, vicino Keflavík',
    immagine: '/images/islanda/keflavik-stock.jpg',
  },
  {
    slug: 'vik',
    paeseSlug: 'islanda',
    ordine: 2,
    nome: 'Vík',
    tipologia: ['natura', 'campeggio'],
    giorniConsigliati: '1 notte, dopo una giornata piena di cascate',
    visitataPersonalmente: true,
    introduzione: 'La prima notte in tenda del viaggio, dopo una giornata che attraversa tutto il Golden Circle e le cascate più fotografate del sud islandese.',
    percheAndarci: 'Base per una delle notti più memorabili di tutto il viaggio: il relitto dell\'aereo di Sólheimasandur, raggiunto a piedi a mezzanotte grazie al sole che a inizio luglio non tramonta mai del tutto.',
    cosaVedere: ['Geysir e Gullfoss (Golden Circle)', 'Seljalandsfoss e Gljúfrabúi', 'Skógafoss', 'Relitto dell\'aereo DC-3 a Sólheimasandur'],
    cosaFare: [
      'Golden Circle: Geysir (eruzioni ogni 6-7 minuti) e Gullfoss, la "cascata dorata" a due salti',
      'Seljalandsfoss, passando dietro la cascata, e la vicina Gljúfrabúi passando dentro il fiume',
      'Skógafoss e la salita dei circa 470 scalini del sentiero panoramico',
      'Escursione notturna al relitto dell\'aereo: circa 20 minuti d\'auto da Vík fino al parcheggio sulla Ring Road, poi 4 km (40-60 minuti) a piedi su sabbia nera piatta ed esposta al vento, andata e ritorno',
    ],
    doveDormire:
      'Ho dormito al campeggio di Vík (1.950 ISK + doccia 300 ISK): elettricità, docce, cucina comune — di fatto l\'unica grande struttura della zona, comoda e ben servita, anche se nelle recensioni più recenti emergono lamentele di sovraffollamento in alta stagione.\n\nAlternative a Vík — economiche: The Barn (uno dei migliori hostel d\'Islanda), Farmhouse Lodge Guesthouse · fascia media: Hotel Kría, design nordico sulla via principale · più curate: Hótel Vík í Mýrdal.',
    doveMangiare: 'Pranzo al sacco o nei dintorni delle cascate; cena al campeggio.',
    comeArrivare: 'Da Keflavík, con soste al Golden Circle e alle cascate del sud lungo il tragitto.',
    comeSpostarsi: 'Auto a noleggio (ritirata la mattina a Keflavík insieme alla tenda).',
    periodoMigliore: 'inizio luglio, per il sole di mezzanotte che rende possibile l\'escursione notturna al relitto',
    costi: 'Campeggio 1.950 ISK + doccia 300 ISK; parcheggio a Seljalandsfoss 700 ISK.',
    erroriDaEvitare: [
      'Il relitto dell\'aereo è una vera sfacchinata dopo una giornata già piena: valutare le energie prima di partire a mezzanotte',
      'Portare torcia o power bank per il telefono: quattro chilometri di sabbia nera piatta e senza punti di riferimento',
    ],
    miaEsperienza:
      'Grazie al sole di mezzanotte ancora presente a inizio luglio, dopo cena ho deciso all\'ultimo di non andare a dormire e raggiungere il relitto a piedi: una vera sfacchinata dopo una giornata già piena, ma probabilmente il momento più assurdo e memorabile di tutto il viaggio.',
    esperienzeSlugs: ['relitto-aereo-solheimasandur', 'golden-circle'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Relitto dell\'aereo DC-3 abbandonato sulla sabbia nera di Sólheimasandur, Islanda',
    immagine: '/images/islanda/vik-stock.jpg',
  },
  {
    slug: 'skaftafell-jokulsarlon',
    paeseSlug: 'islanda',
    ordine: 3,
    nome: 'Skaftafell e Jökulsárlón',
    tipologia: ['natura', 'avventura'],
    giorniConsigliati: 'una giornata piena, senza pernottamento',
    visitataPersonalmente: true,
    introduzione: 'Il cuore ghiacciato del Parco Nazionale del Vatnajökull, il più grande d\'Europa: trekking sul ghiacciaio, kayak tra gli iceberg e la Diamond Beach, tutto nella stessa giornata.',
    percheAndarci: 'Probabilmente la giornata con la più alta densità di esperienze forti di tutto il viaggio: dal ghiaccio del ghiacciaio al kayak tra gli iceberg, passando per due spiagge nere e un canyon.',
    cosaVedere: [
      'Dyrhólaey (faro e arco di lava nera) e Reynisfjara (spiaggia di colonne di basalto)',
      'Fjaðrárgljúfur, canyon di circa 100 metri di profondità',
      'Svartifoss, la cascata nera di Skaftafell',
      'Laguna di Jökulsárlón e Diamond Beach',
    ],
    cosaFare: [
      'Trekking guidato sul ghiacciaio Vatnajökull, con ramponi e piccozza — vedi la scheda esperienza dedicata',
      'Kayak tra gli iceberg della laguna di Jökulsárlón — vedi la scheda esperienza dedicata',
      'Passeggiata a Reynisfjara (attenzione alle onde, imprevedibili e pericolose) e Dyrhólaey',
      'Passeggiata fotografica a Fjaðrárgljúfur, molto meno affollato di altri siti della zona',
    ],
    doveDormire: 'Non ho pernottato qui: si dorme a Höfn, circa un\'ora più avanti sulla Ring Road.',
    doveMangiare: 'Pranzo veloce a Reynisfjara (baracchino hot dog/zuppa, 2-3.000 ISK).',
    comeArrivare: 'Da Vík, lungo la Ring Road, con soste a Dyrhólaey, Reynisfjara e Fjaðrárgljúfur.',
    comeSpostarsi: 'Auto a noleggio; l\'area di Skaftafell si esplora solo a piedi.',
    periodoMigliore: 'estate, per le migliori condizioni di accesso al ghiacciaio',
    costi: 'da completare (trekking ghiacciaio e kayak)',
    erroriDaEvitare: ['A Reynisfjara seguire sempre le indicazioni di sicurezza: le onde sono imprevedibili'],
    miaEsperienza:
      'Il trekking sul ghiacciaio e il kayak tra gli iceberg sono state due delle esperienze più intense di tutto il viaggio — sto ancora recuperando i dettagli esatti (operatore, durata, prezzi) da foto e ricevute.',
    esperienzeSlugs: ['trekking-ghiacciaio-vatnajokull', 'kayak-jokulsarlon'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Iceberg blu che galleggiano nella laguna glaciale di Jökulsárlón, Islanda',
    immagine: '/images/islanda/jokulsarlon-stock.jpg',
  },
  {
    slug: 'hofn',
    paeseSlug: 'islanda',
    ordine: 4,
    nome: 'Höfn',
    tipologia: ['natura', 'campeggio'],
    giorniConsigliati: '1 notte',
    visitataPersonalmente: true,
    introduzione: 'La "capitale dell\'aragosta islandese", con il set cinematografico vichingo di Vestrahorn proprio accanto al campeggio.',
    percheAndarci: 'Buona base dopo la giornata più densa del viaggio, con una tappa curiosa al Viking Village prima di ripartire.',
    cosaVedere: ['Viking Village (set costruito nel 2010)', 'Montagna Vestrahorn', 'Spiaggia nera di Stokksnes'],
    cosaFare: ['Giro al Viking Village: cavalli al pascolo, ricostruzione di villaggio vichingo'],
    doveDormire:
      'Ho dormito al campeggio Vestrahorn o al campeggio comunale di Höfn (sto ancora confermando quale dei due). Il Vestrahorn (~2.800 ISK a persona/notte) include l\'ingresso al Viking Village e la vista su Stokksnes, ma alcune recensioni segnalano solo due docce disponibili in orari limitati; il campeggio comunale su Hafnarbraut (~1.800 ISK) è più centrale, vicino alla piscina del paese.\n\nAlternative a Höfn — economiche: Höfn HI Hostel, Guesthouse Dyngja · fascia media: Hotel Höfn, The Old Airline Guesthouse · più curate: Fosshotel Vatnajökull, Brunnhóll Country Guesthouse.',
    doveMangiare: 'Zuppa di pesce in uno dei ristoranti di Höfn, la "capitale dell\'aragosta islandese" — o cena al campeggio.',
    comeArrivare: 'Da Skaftafell/Jökulsárlón, circa un\'ora di guida.',
    comeSpostarsi: 'Auto a noleggio.',
    periodoMigliore: 'da confermare',
    costi: 'Campeggio Vestrahorn ~2.800 ISK/notte, campeggio comunale ~1.800 ISK/notte.',
    erroriDaEvitare: [],
    miaEsperienza: 'Dopo la giornata più intensa del viaggio, Höfn è stata una tappa più tranquilla — comoda per riposare prima del lungo tratto verso i fiordi dell\'Est il giorno dopo.',
    esperienzeSlugs: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Montagna Vestrahorn e spiaggia di sabbia nera vicino Höfn, Islanda',
    immagine: '/images/islanda/hofn-stock.jpg',
  },
  {
    slug: 'egilsstadir',
    paeseSlug: 'islanda',
    ordine: 5,
    nome: 'Egilsstaðir',
    tipologia: ['natura', 'campeggio'],
    giorniConsigliati: '1 notte',
    visitataPersonalmente: true,
    introduzione: 'Il capoluogo dell\'est islandese, raggiunto attraverso i fiordi meno turistici e più selvaggi dell\'isola.',
    percheAndarci: 'La guida lungo i fiordi dell\'Est è tra le più scenografiche del viaggio, e i Vök Baths sono il primo vero bagno caldo dopo giorni di trekking e vento.',
    cosaVedere: ['Fiordi dell\'Est lungo la Route 1', 'Eventuale deviazione a Seyðisfjörður, cittadina artistica tra le montagne'],
    cosaFare: [
      'Guida panoramica lungo i fiordi dell\'Est (circa 250 km, 3-4 ore effettive che diventano facilmente 5-6 con soste — la strada segue ogni singolo fiordo)',
      'Vök Baths, piscina termale galleggiante sul lago Urriðavatn — vedi la scheda esperienza dedicata',
    ],
    doveDormire:
      'Ho dormito al Camp Egilsstaðir, ben recensito (4/5 su Tripadvisor): bagni puliti, lavatrici e asciugatrici, cucine al chiuso, elettricità — circa 2.000-2.400 ISK a notte.\n\nAlternative a Egilsstaðir — economiche: Hafaldan HI Hostel (edificio Harbour) · fascia media: Við Lónið Guesthouse · più curate: Gistihúsið Lake Hotel Egilsstaðir, Hotel Valaskjálf.',
    doveMangiare: 'Cena in campeggio o in uno dei locali di Egilsstaðir.',
    comeArrivare: 'Da Höfn, lungo i fiordi dell\'Est (Route 1).',
    comeSpostarsi: 'Auto a noleggio.',
    periodoMigliore: 'da confermare',
    costi: 'Campeggio circa 2.000-2.400 ISK/notte.',
    erroriDaEvitare: [],
    miaEsperienza: 'I Vök Baths sono arrivati al momento giusto: dopo due giorni tra trekking e vento, il primo bagno caldo vero del viaggio.',
    esperienzeSlugs: ['terme-naturali-islanda'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Villaggio di Seyðisfjörður tra le montagne innevate di un fiordo dell\'Est islandese',
    immagine: '/images/islanda/egilsstadir-stock.jpg',
  },
  {
    slug: 'asbyrgi',
    paeseSlug: 'islanda',
    ordine: 6,
    nome: 'Ásbyrgi',
    tipologia: ['natura', 'campeggio'],
    giorniConsigliati: '1 notte',
    visitataPersonalmente: true,
    introduzione: 'Il canyon a forma di ferro di cavallo nel cuore del parco nazionale, con lo Stuðlagil e la cascata più potente d\'Europa lungo il tragitto.',
    percheAndarci: 'Una delle giornate più intense del viaggio per paesaggi naturali: colonne di basalto, la cascata più potente d\'Europa e un canyon leggendario, tutto in poche ore.',
    cosaVedere: [
      'Stuðlagil Canyon: colonne di basalto alte 30 metri e fiume dalle acque turchesi, famoso solo dal 2017',
      'Dettifoss: la cascata più potente d\'Europa (44 m di salto, portata fino a 500 m³/s in estate)',
      'Canyon di Ásbyrgi, con passeggiata fino allo stagno Botnstjörn',
    ],
    cosaFare: [
      'Passeggiata allo Stuðlagil Canyon (circa 1h di guida, ultimo tratto su sterrato)',
      'Vista su Dettifoss dal lato ovest (Route 862, asfaltata, la vista migliore)',
      'Passeggiata tra le pareti verdi del canyon di Ásbyrgi',
    ],
    doveDormire:
      'Ho dormito al campeggio del parco nazionale di Ásbyrgi (fino a 350 piazzole, aperto da metà maggio a fine ottobre), con buoni servizi secondo le recensioni (bagni puliti, docce, lavanderia) — consigliata la prenotazione in alta stagione.\n\nZona molto remota, con poche vere alternative nelle vicinanze: a Kópasker (circa 35-40 minuti) si trovano Kópasker Guesthouse, MELAR Guesthouse e Kópasker HI Hostel (fascia economica/media). Non ci sono opzioni di lusso nei dintorni — la scelta resta tra il campeggio stesso (che offre anche piccoli studio) e le guesthouse di Kópasker.',
    doveMangiare: 'Cena in campeggio.',
    comeArrivare: 'Da Egilsstaðir, con soste allo Stuðlagil Canyon e a Dettifoss.',
    comeSpostarsi: 'Auto a noleggio; ultimo tratto per lo Stuðlagil su sterrato.',
    periodoMigliore: 'campeggio aperto da metà maggio a fine ottobre',
    costi: 'da completare',
    erroriDaEvitare: ['Prenotare il campeggio in alta stagione: zona molto remota con poche alternative'],
    miaEsperienza: 'Dettifoss si sente prima di vederla — il boato e la potenza dell\'acqua fangosa restano tra i ricordi più fisici del viaggio.',
    esperienzeSlugs: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Vista aerea del canyon di Ásbyrgi a forma di ferro di cavallo, Islanda',
    immagine: '/images/islanda/asbyrgi-stock.jpg',
  },
  {
    slug: 'akureyri',
    paeseSlug: 'islanda',
    ordine: 7,
    nome: 'Akureyri e il lago Mývatn',
    tipologia: ['natura', 'campeggio'],
    giorniConsigliati: '1 notte',
    visitataPersonalmente: true,
    introduzione: 'Base per il whale watching a Húsavík e per la zona geotermica del lago Mývatn, prima dell\'ultimo grande trasferimento verso Snæfellsnes.',
    percheAndarci: 'Un tour in barca alla ricerca di megattere e balenottere, seguito da uno dei concentrati di fenomeni geotermici più densi di tutta l\'Islanda.',
    cosaVedere: [
      'Baia di Skjálfandi, per il whale watching da Húsavík',
      'Grjótagjá (grotta lavica con sorgente termale, location di Game of Thrones — oggi non balneabile)',
      'Hverfjall (cratere vulcanico ad anello), Hverir (fumarole e pozze di fango), Dimmuborgir (labirinto di formazioni laviche)',
      'Goðafoss, la "cascata degli dei"',
    ],
    cosaFare: [
      'Whale watching da Húsavík — vedi la scheda esperienza dedicata',
      'Giro della zona geotermica di Mývatn — vedi la scheda esperienza dedicata',
    ],
    doveDormire:
      'Ho dormito al campeggio Hamrar, tra i meglio recensiti d\'Islanda (4/5 su Tripadvisor), ai margini della foresta di Kjarnaskógur, con docce quasi nuove e ottimi servizi — prezzo indicativo intorno a 1.500 ISK a persona più una quota per la tenda.\n\nAlternative ad Akureyri — economiche: Akureyri Backpackers, Guesthouse Bægisá · fascia media: Centrum Hotel · più curate: Hotel Kea, Bryggjan Boutique Hotel.',
    doveMangiare: 'Pranzo veloce a Húsavík; barbecue in campeggio la sera con la spesa fatta ad Akureyri.',
    comeArrivare: 'Da Ásbyrgi, con tappa a Húsavík e alla zona di Mývatn.',
    comeSpostarsi: 'Auto a noleggio.',
    periodoMigliore: 'estate, per le migliori condizioni del tour whale watching',
    costi: 'Campeggio Hamrar ~1.500 ISK/persona + quota tenda.',
    erroriDaEvitare: [],
    miaEsperienza: 'La combinazione di whale watching al mattino e zona geotermica al pomeriggio è stata una delle giornate più varie di tutto il viaggio — dal mare aperto allo zolfo in poche ore.',
    esperienzeSlugs: ['whale-watching-husavik', 'zona-geotermale-myvatn'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Pozza termale fumante nel terreno colorato di zolfo della zona geotermica vicino al lago Mývatn',
    immagine: '/images/islanda/akureyri-stock.jpg',
  },
  {
    slug: 'grundarfjordur',
    paeseSlug: 'islanda',
    ordine: 8,
    nome: 'Grundarfjörður',
    tipologia: ['natura', 'campeggio'],
    giorniConsigliati: '1 notte',
    visitataPersonalmente: true,
    introduzione: 'La penisola di Snæfellsnes e il Kirkjufell, la montagna più fotografata d\'Islanda, dopo la giornata di trasferimento più lunga del viaggio.',
    percheAndarci: 'Giornata quasi interamente di guida, ma la ricompensa è il tramonto al Kirkjufell — e l\'ultima vera cena in tenda del viaggio.',
    cosaVedere: ['Case di torba tradizionali lungo la Route 1', 'Kirkjufell (463 m) e la cascata Kirkjufellsfoss'],
    cosaFare: [
      'Sosta in una piscina termale naturale poco battuta del West Iceland, es. Guðrúnarlaug (spogliatoio essenziale, ingresso gratuito)',
      'Foto al Kirkjufell al tramonto — parcheggio proprio accanto alla cascata, nessuna camminata necessaria',
    ],
    doveDormire:
      'Ho dormito al campeggio ai piedi del Kirkjufell, semplice e panoramico, con vista diretta sul fiordo e sulla montagna.\n\nLe opzioni in paese sono poche: il Kirkjufell Guesthouse and Apartments (da circa 180$/notte) è di fatto la scelta principale di fascia media, con poche vere alternative economiche o di lusso nella stessa cittadina. Per più scelta conviene guardare verso Stykkishólmur, a circa 25 minuti d\'auto.',
    doveMangiare: 'Spesa nei negozi del paese (10 minuti a piedi dal campeggio) e cena al campeggio — l\'ultima vera cena in tenda del viaggio.',
    comeArrivare: 'Da Akureyri, circa 390 km e 5 ore di guida effettive via Route 1 e Borgarnes (6-7 ore con soste).',
    comeSpostarsi: 'Auto a noleggio.',
    periodoMigliore: 'estate, per la luce fino a tardi sul Kirkjufell al tramonto',
    costi: 'da completare',
    erroriDaEvitare: ['Mettere in conto 6-7 ore di guida con le soste: è il trasferimento più lungo di tutto il viaggio'],
    miaEsperienza: 'L\'ultima cena in tenda, con vista sul Kirkjufell e il fiordo, è stata un bel modo di chiudere la parte "on the road" del viaggio prima delle due notti finali in hotel.',
    esperienzeSlugs: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Montagna Kirkjufell e la cascata Kirkjufellsfoss, Islanda',
    immagine: '/images/islanda/grundarfjordur-stock.jpg',
  },
  {
    slug: 'reykjavik',
    paeseSlug: 'islanda',
    ordine: 9,
    nome: 'Reykjavík',
    tipologia: ['cultura'],
    giorniConsigliati: '1-2 notti, a chiusura del viaggio',
    visitataPersonalmente: true,
    introduzione: 'La capitale, ultima tappa dopo sei notti in tenda: un letto vero, il centro città, e l\'ultima cena del viaggio.',
    percheAndarci: 'Il modo giusto per chiudere il viaggio, tra le vie colorate del centro e una sosta termale lungo il tragitto di rientro.',
    cosaVedere: ['Chiesa di Hallgrímskirkja', 'Vie colorate del centro', 'Mercatino dell\'usato di Kolaportið (sabato/domenica)'],
    cosaFare: [
      'Eventuale sosta in una piscina termale naturale del West Iceland lungo il tragitto di rientro (es. zona di Deildartunguhver/Krauma, la sorgente calda più potente d\'Europa)',
      'Giro a piedi del centro città, con eventuale tappa al mercatino di Kolaportið',
    ],
    doveDormire: 'Hotel dell\'ultima notte, nome ancora da confermare.\n\nAlternative a Reykjavík — economiche: KEX Hostel, Loft HI Eco Hostel · fascia media: hotel di zona Þingholt, Hlemmur Square · più curate: The Reykjavik EDITION, Canopy by Hilton Reykjavík.',
    doveMangiare: 'Ultima cena in uno dei ristoranti del centro, locale ancora da ricordare/confermare.',
    comeArrivare: 'Da Grundarfjörður, circa 2h30 di guida (180 km via Borgarnes).',
    comeSpostarsi: 'A piedi in centro.',
    periodoMigliore: 'da confermare',
    costi: 'da completare',
    erroriDaEvitare: [],
    miaEsperienza: 'Dopo sei notti in tenda, l\'ultima notte in un letto vero a Reykjavík è stata quasi surreale — un buon modo per festeggiare la fine del viaggio prima del volo di rientro da Keflavík.',
    esperienzeSlugs: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Guglia in stile Art Déco della chiesa di Hallgrímskirkja a Reykjavík',
    immagine: '/images/islanda/reykjavik-stock.jpg',
  },
]
