import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Marocco 360°" (src/content/viaggi/07-marocco-360.md).

export const destinazioniMarocco: Destinazione[] = [
  {
    slug: 'marrakech',
    paeseSlug: 'marocco',
    ordine: 1,
    nome: 'Marrakech',
    tipologia: ['città', 'cultura'],
    giorniConsigliati: '3 giorni, tra inizio e fine viaggio',
    visitataPersonalmente: true,
    introduzione: 'La medina, i souk, Jemaa El-Fna di sera e il Jardin Majorelle: il punto di partenza e arrivo del viaggio, vissuto in tre notti diverse.',
    percheAndarci: 'Il punto di ingresso naturale al Marocco, con abbastanza monumenti e atmosfera da meritare più di una visita.',
    cosaVedere: [
      'Piazza Jemaa El-Fna, il cuore pulsante della medina',
      'Medersa Ali Ben Youssef',
      'Palazzo della Bahia',
      'Tombe Saadiane',
      'Moschea Koutoubia (solo esterno)',
      'Jardin Majorelle',
    ],
    cosaFare: [
      'Tour guidato di Marrakech — vedi la scheda esperienza dedicata',
      'Visita al Jardin Majorelle — vedi la scheda esperienza dedicata',
      'Shopping nei souk',
      'Cena con dinner show da Narwama',
    ],
    doveDormire:
      'Villa Zahra — una villa spaziosa e tranquilla, ottima per stare comodo, con più margine di respiro rispetto a un hotel nel cuore della medina. Piscina e staff disponibile secondo le recensioni. L\'unico compromesso reale è la posizione, un po\' fuori dal centro, da mettere in conto per gli spostamenti serali.\n\nEconomiche: Central House Marrakech Medina, Equity Point Marrakech · fascia media: Riad Nelia, Riad Yasmine · lux (non eccessiva): IZZA, Riad Kaiss.',
    doveMangiare: 'Kui Zin (cena di benvenuto), Narwama (dinner show), Safran by Koya.',
    usciteSerali: 'Churchill Bar o la Pergola.',
    comeArrivare: 'Volo internazionale su Marrakech.',
    comeSpostarsi: 'Van privato con guida, a piedi nella medina, taxi per il Jardin Majorelle (50 MAD a corsa).',
    periodoMigliore: 'inizio maggio',
    costi: 'Medersa 50 MAD, Palazzo della Bahia 70 MAD, Tombe Saadiane 70 MAD, Jardin Majorelle 150 MAD a persona.',
    erroriDaEvitare: ['Prenotare il Jardin Majorelle in anticipo: gli ingressi sono contingentati e nelle ore centrali si riempie in fretta'],
    miaEsperienza:
      'Il tour guidato è stato un ottimo modo per orientarsi nella medina, ma è Jemaa El-Fna — vista di nuovo dopo il tour, di sera, tra incantatori di serpenti, musicisti e bancarelle di ogni tipo — a restare il ricordo più forte di Marrakech.',
    esperienzeSlugs: ['tour-marrakech', 'jardin-majorelle'],
    tripSlugs: ['marocco-360'],
    imageAlt: 'La piazza Jemaa El-Fna animata di sera a Marrakech, Marocco',
    immagine: '/images/marocco/marrakech-stock.jpg',
  },
  {
    slug: 'ait-benhaddou',
    paeseSlug: 'marocco',
    ordine: 2,
    nome: 'Kasbah di Telouet e Aït Benhaddou',
    tipologia: ['storia', 'kasbah'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'L\'antica residenza della famiglia Glaoui a Telouet e il celebre ksar di Aït Benhaddou, Patrimonio UNESCO e set di innumerevoli film, da Il Gladiatore a Game of Thrones.',
    percheAndarci: 'Per uno dei villaggi fortificati di fango meglio conservati del Marocco, che sembra uscito da un\'altra epoca.',
    cosaVedere: ['La Kasbah di Telouet, con interni riccamente decorati', 'Il ksar di Aït Benhaddou'],
    cosaFare: ['Visita alla Kasbah di Telouet', 'Visita al ksar di Aït Benhaddou'],
    doveDormire:
      'Ksar El Janoub — la struttura meglio recensita della zona, con camere pulite e curate, piscina con vista sul paesaggio e un servizio descritto come attento e cordiale (diverse recensioni citano il proprietario, Khalid, come particolarmente ospitale).\n\nEconomiche: Riad Caravane, Dar Mouna · fascia media: Kasbah Tebi, Kasbah El Hajja · lux (non eccessiva): Kasbah Rayane, Caravane Hotel (Ounila Valley).',
    doveMangiare: 'Tawesna, per pranzo dopo la visita al ksar.',
    comeArrivare: 'Circa 2h30 da Marrakech per Telouet, poi circa 1h per Aït Benhaddou.',
    comeSpostarsi: 'A piedi nel ksar.',
    periodoMigliore: 'mattina, per la luce migliore sulla facciata in terra battuta',
    costi: 'da completare',
    erroriDaEvitare: ['Ricaricare i power bank in vista della notte nel deserto: niente prese elettriche ai campi tendati'],
    miaEsperienza:
      'Il contrasto tra l\'esterno in terra battuta ormai in parte crollato della Kasbah di Telouet e i suoi interni riccamente decorati è stata una sorpresa, e il ksar di Aït Benhaddou dal vivo è ancora più suggestivo di quanto lasci intuire nei film che lo hanno reso famoso.',
    esperienzeSlugs: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Il ksar fortificato di Aït Benhaddou, Patrimonio UNESCO, Marocco',
    immagine: '/images/marocco/ait-benhaddou-stock.jpg',
  },
  {
    slug: 'merzouga',
    paeseSlug: 'marocco',
    ordine: 3,
    nome: 'Gole di Todra e Merzouga',
    tipologia: ['deserto', 'natura'],
    giorniConsigliati: '2 giorni, 1 notte nel deserto',
    visitataPersonalmente: true,
    introduzione: 'Le spettacolari Gole di Todra lungo il tragitto, e una notte a Erg Chebbi con cammellata, quad e un cielo stellato senza pari.',
    percheAndarci: 'L\'ingresso nel Sahara e uno dei momenti più belli di tutto il viaggio: il cielo stellato del deserto, lontano da ogni luce artificiale.',
    cosaVedere: ['Le Gole di Todra', 'Le dune di Erg Chebbi'],
    cosaFare: [
      'Visita alle Gole di Todra (30 minuti)',
      'Notte nel deserto a Erg Chebbi — vedi la scheda esperienza dedicata',
      'Giro in cammello al tramonto e all\'alba',
      'Quad nel deserto — vedi la scheda esperienza dedicata',
    ],
    doveDormire:
      'Camp La Source — un campo tendato ai piedi delle dune di Erg Chebbi: tende ampie e curate, gestione familiare descritta come molto accogliente, cielo stellato lontano da ogni luce artificiale.\n\nEconomiche: Hostel La Liberte Merzouga, Merzouga Camp and Hostel · fascia media: Auberge La Khaima, Nomad Palace Camp · lux (non eccessiva): Merzouga Luxury Desert Camp, Sahara Desert Luxury Camp.',
    doveMangiare: 'Cena al campo tendato, con possibilità di segnalare allergie/intolleranze in anticipo.',
    comeArrivare: 'Circa 3h da Aït Benhaddou per le Gole di Todra, poi circa 3h per Erg Chebbi.',
    comeSpostarsi: 'Cammello e quad nel deserto.',
    periodoMigliore: 'inizio maggio, notti ancora fresche',
    costi: 'Quad 350 MAD a persona.',
    erroriDaEvitare: ['Comprare turbanti e pashmine al mercato locale prima di entrare nel deserto, utili contro sabbia e freddo notturno', 'Fare rifornimento di alcolici e snack prima di Merzouga: nel deserto le scorte sono limitate'],
    miaEsperienza:
      'Nella notte, il cielo stellato senza pari, lontano da ogni luce artificiale, è stato uno dei momenti più belli di tutto il viaggio. Il giro in cammello all\'alba, con le dune che cambiano colore con la luce del sole nascente, è stata la degna chiusura di quella notte.',
    esperienzeSlugs: ['notte-deserto-erg-chebbi', 'gole-todra', 'quad-deserto-merzouga'],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Cielo stellato sopra il campo tendato nel deserto di Erg Chebbi, Marocco',
    immagine: '/images/copertine/marocco-360.jpg',
  },
  {
    slug: 'agdz',
    paeseSlug: 'marocco',
    ordine: 4,
    nome: 'Agdz e la valle del Draa',
    tipologia: ['kasbah', 'natura'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'La valle del Draa e la Kasbah di Tamnougalt, una delle meglio conservate della zona.',
    percheAndarci: 'Una tappa più tranquilla tra il deserto e la costa, con una delle kasbah meglio conservate del Marocco.',
    cosaVedere: ['La Kasbah di Tamnougalt'],
    cosaFare: ['Visita alla Kasbah di Tamnougalt', 'Tempo libero in piscina'],
    doveDormire:
      'Kasbah Trane — una notte lungo la valle del Draa, zona tranquilla, buon punto d\'appoggio per visitare la vicina Kasbah di Tamnougalt (nessuna recensione specifica trovata per il nome esatto della struttura).\n\nEconomiche: Kasbah Maktob Tamnougalt, Guest House Jardin de Tamnougalt · fascia media: Maison d\'Hôtes Kasbah Azul, Dar Jnane - La Maison Du Jardin · lux (non eccessiva): Hotel and Restaurant Kasbah Draa, Kasbah Kissane.',
    doveMangiare: 'Cena in hotel.',
    comeArrivare: 'Circa 4h da Merzouga.',
    comeSpostarsi: 'A piedi nella kasbah.',
    periodoMigliore: 'sera, per la visita alla Kasbah di Tamnougalt',
    costi: 'Kasbah di Tamnougalt 20 MAD a persona + 200 MAD di mancia per la guida locale.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Dopo l\'intensità del deserto, Agdz è stata una tappa di decompressione ben piazzata, con la Kasbah di Tamnougalt a ricordare quanto valga la pena uscire dagli itinerari più battuti.',
    esperienzeSlugs: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'La Kasbah di Tamnougalt nella valle del Draa, Marocco',
    immagine: '/images/marocco/agdz-stock.jpg',
  },
  {
    slug: 'agadir',
    paeseSlug: 'marocco',
    ordine: 5,
    nome: 'Agadir e Taghazout',
    tipologia: ['mare', 'surf'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'Taliouine, la capitale marocchina dello zafferano, e una lezione di surf a Taghazout, uno dei villaggi di riferimento del surf in Marocco.',
    percheAndarci: 'Il contrappunto costiero dopo giorni di deserto e kasbah, con una tappa golosa a Taliouine lungo il percorso.',
    cosaVedere: ['La città vecchia di Taliouine', 'Il centro storico di Taroudant'],
    cosaFare: [
      'Acquisto di zafferano a Taliouine',
      'Yoga al tramonto con Khalid',
      'Lezione di surf a Taghazout — vedi la scheda esperienza dedicata',
    ],
    doveDormire:
      'Hotel Oasis — una notte comoda per la vicinanza al mare e ai ristoranti, ma con recensioni online piuttosto contrastanti: buona la posizione e la colazione a buffet, meno la manutenzione delle camere, descritta da diversi ospiti come datata.\n\nEconomiche: Hotel Sindibad Agadir, Résidence IGOUDAR · fascia media: Riad Dar Maktoub, Hôtel Riad Salam Agadir · lux (non eccessiva): Sofitel Agadir Thalassa Sea & Spa, Hotel Riu Palace Tikida Agadir.',
    doveMangiare: 'Les Blancs (rooftop vista mare, cucina spagnola/mediterranea); pranzo a Taghazout dopo il surf.',
    usciteSerali: 'LOFT, narghilè e birre, atmosfera da discoteca araba.',
    comeArrivare: 'Circa 2h30 da Agdz per Taliouine, poi circa 3h per Agadir.',
    comeSpostarsi: 'Van privato, a piedi a Taghazout.',
    periodoMigliore: 'inizio maggio, buone condizioni per iniziare a surfare',
    costi: 'Lezione di surf 250 MAD a persona (docce 10 MAD).',
    erroriDaEvitare: ['Comprare lo zafferano solo nei posti consigliati dalla guida a Taliouine, evitando i negozi lungo la strada pensati per i turisti di passaggio'],
    miaEsperienza:
      'Una mattinata diversa da tutto il resto del viaggio: dopo giorni di deserto e kasbah, il surf a Taghazout è stato un tuffo (letterale) in un registro completamente diverso.',
    esperienzeSlugs: ['surf-taghazout'],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Lezione di surf sulle onde di Taghazout, Marocco',
    immagine: '/images/marocco/agadir-stock.jpg',
  },
  {
    slug: 'essaouira',
    paeseSlug: 'marocco',
    ordine: 6,
    nome: 'Essaouira',
    tipologia: ['città', 'mare', 'relax'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'La città portuale fortificata affacciata sull\'Atlantico, con la medina bianca e blu tra le più suggestive del Marocco.',
    percheAndarci: 'Per un\'atmosfera diversa da tutto il resto del viaggio, tra shopping più conveniente che a Marrakech e un buon momento di relax.',
    cosaVedere: ['La medina bianca e blu di Essaouira', 'Il porto fortificato', 'Il Ranch de Diabat'],
    cosaFare: [
      'Tour guidato di Essaouira (1h30)',
      'Hammam da Kenza — vedi la scheda esperienza dedicata',
      'Avventura in quad al Ranch de Diabat, con possibile passeggiata a cavallo',
    ],
    doveDormire:
      'Maison De Sud — una notte in pieno centro storico, a pochi passi dai souk e dal porto: casa piena di carattere, con decorazioni artigianali e uno staff molto attento secondo le recensioni. Camere piccole e richiami alla preghiera percepibili di notte, normale nel cuore della medina.\n\nEconomiche: La Smala, Riad Al Madina · fascia media: Lyon Mogador, Riad Chakir Mogador · lux (non eccessiva): Heure Bleue Palais, Riad Dar Maya.',
    doveMangiare: 'Triskala, La Table by Madada o Des Rêves.',
    comeArrivare: 'Circa 2h30 da Agadir via Taghazout.',
    comeSpostarsi: 'A piedi nella medina.',
    periodoMigliore: 'tardo pomeriggio, per il tour guidato con luce migliore',
    costi: 'Hammam 250 MAD a persona; shopping generalmente più economico che a Marrakech.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Dopo giorni di van, deserto e visite, l\'ora passata all\'hammam da Kenza è stato uno dei momenti di puro relax di tutto il viaggio, e la medina bianca e blu di Essaouira resta una delle atmosfere più suggestive di tutto il Marocco.',
    esperienzeSlugs: ['hammam-essaouira'],
    tripSlugs: ['marocco-360'],
    imageAlt: 'La medina bianca e blu della città portuale di Essaouira, Marocco',
    immagine: '/images/marocco/essaouira-stock.jpg',
  },
]
