import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "New York 360°" (src/content/viaggi/08-new-york-360.md).
// A differenza degli altri Paesi del sito, qui le "destinazioni" sono zone di
// un'unica città (New York), non città diverse. Dove un dato non è nel diario
// originale resta con una nota esplicita "da confermare/da completare".
//
// Le immagini sono foto stock temporanee (Pixabay/Pexels, licenze free-use),
// scelte per rappresentare davvero il luogo in attesa di foto originali.

export const destinazioniNewYork: Destinazione[] = [
  {
    slug: 'times-square-midtown',
    paeseSlug: 'new-york',
    ordine: 1,
    nome: 'Times Square e Midtown',
    tipologia: ['città', 'nightlife'],
    giorniConsigliati: '1-2 giorni, base logistica per l\'intero soggiorno',
    visitataPersonalmente: true,
    introduzione: 'Il cuore pulsante di Manhattan, con Times Square di notte, l\'Empire State Building e Broadway a due passi dall\'hotel.',
    percheAndarci: 'È la base più comoda per muoversi in metro verso il resto della città, con l\'impatto scenico di Times Square la sera dell\'arrivo.',
    cosaVedere: ['Times Square di notte', 'Empire State Building', 'Rockefeller Center'],
    cosaFare: [
      'Salita serale all\'Empire State Building',
      'Musical a Broadway — vedi la scheda esperienza dedicata',
      'Cena-spettacolo da Ellen\'s Stardust Diner, con cameriere che cantano',
    ],
    doveDormire:
      'Ho dormito al Paramount Hotel (oggi "Paramount Times Square – A Generator Hotel"), 235 W 46th St, in pieno Theater District. La posizione è il vero punto di forza, con punteggi "location" su Booking.com tra i più alti della zona (9-9.3/10). Le camere però sono piccole, in alcuni casi minuscole anche per gli standard newyorkesi, con isolamento acustico non eccezionale — lobby e aree comuni sono invece un plus, con atmosfera vivace e staff cordiale. Punteggio complessivo 6.6-7.1/10.\n\nAlternative a Midtown/Theater District — economiche: Row NYC (700 8th Ave), Pod Times Square (400 W 42nd St, formula "pod hotel") · fascia media (qui rientra il Paramount, verso il basso della fascia per via delle camere ridotte): Novotel New York Times Square (226 W 52nd St), DoubleTree by Hilton New York Times Square West (350 W 40th St) · lusso senza eccessi: citizenM New York Times Square (218 W 50th St), Moxy NYC Times Square (485 7th Ave, rooftop bar molto frequentato).',
    doveMangiare: 'Shake Shack, Kesté Pizza (napoletana), Ellen\'s Stardust Diner; colazione da Junior\'s per la cheesecake.',
    usciteSerali: 'Magic Hour Bar; 230 Rooftop (vista su Flatiron, Chrysler ed Empire State, ingresso gratuito, cocktail 9-15$).',
    comeArrivare: 'Volo internazionale su New York (JFK, Newark o LaGuardia).',
    comeSpostarsi: 'Metro, Uber/Lyft (soprattutto di notte) e a piedi — media di 15-20 km al giorno.',
    periodoMigliore: 'settembre',
    costi: 'Camera "Broadway Petite" al Paramount da circa 13 mq; cocktail al 230 Rooftop 9-15$.',
    erroriDaEvitare: ['Prenotare Top of the Rock e i musical di Broadway con anticipo: in alta stagione i biglietti migliori vanno a ruba'],
    miaEsperienza:
      'Times Square di notte, la prima sera, è stato l\'impatto scenico più forte del viaggio — luci e cartelloni che, per quanto già visti in mille foto, colpiscono comunque dal vivo.',
    esperienzeSlugs: ['musical-broadway'],
    tripSlugs: ['new-york-360'],
    imageAlt: 'Le luci e i cartelloni pubblicitari di Times Square di notte, New York',
    immagine: '/images/new-york/times-square-stock.jpg',
  },
  {
    slug: 'harlem-central-park',
    paeseSlug: 'new-york',
    ordine: 2,
    nome: 'Harlem e Central Park',
    tipologia: ['cultura', 'natura'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Il lato di New York meno da cartolina: una messa gospel di quartiere, l\'Apollo Theater, e il grande parco cittadino in bicicletta fino a Strawberry Fields.',
    percheAndarci: 'Per vedere una New York più autentica e meno turistica rispetto a Manhattan, prima di tornare al verde di Central Park nel pomeriggio.',
    cosaVedere: ['L\'Apollo Theater', 'Strawberry Fields a Central Park'],
    cosaFare: [
      'Messa gospel di quartiere — vedi la scheda esperienza dedicata',
      'Walking tour di Harlem (275$ + mancia, circa 2h)',
      'Noleggio bici a Central Park, dal Met fino a Strawberry Fields',
    ],
    doveDormire: 'Non ho pernottato qui: giornata da Midtown.',
    doveMangiare: 'The Monkey Cup ad Harlem per colazione; Gray\'s Papaya per hot dog economici, un classico newyorkese.',
    comeArrivare: 'Metro da Midtown.',
    comeSpostarsi: 'A piedi per il walking tour; bici a noleggio a Central Park.',
    periodoMigliore: 'la domenica mattina, per la messa gospel',
    costi: 'Walking tour di Harlem 275$ + mancia.',
    erroriDaEvitare: [],
    miaEsperienza:
      'La messa gospel di domenica mattina è stata un\'esperienza di quartiere autentica, molto diversa da un tour organizzato — nessun obbligo di offerta, ci si può alzare e uscire quando si vuole, ma vale la pena restare fino alla fine.',
    esperienzeSlugs: ['messa-gospel-harlem'],
    tripSlugs: ['new-york-360'],
    imageAlt: 'La facciata storica dell\'Apollo Theater ad Harlem, New York',
    immagine: '/images/new-york/harlem-stock.jpg',
  },
  {
    slug: 'rockefeller-chelsea',
    paeseSlug: 'new-york',
    ordine: 3,
    nome: 'Rockefeller Center, MoMA e Chelsea',
    tipologia: ['cultura', 'città'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Dalla Cattedrale di San Patrizio al MoMA, fino alla High Line e The Vessel a Hudson Yards.',
    percheAndarci: 'Per l\'arte al MoMA e per una delle migliori rigenerazioni urbane della città: l\'ex ferrovia sopraelevata trasformata nella High Line.',
    cosaVedere: ['Cattedrale di San Patrizio', 'MoMA (Museum of Modern Art)', 'The Vessel a Hudson Yards', 'Grand Central Station e la Public Library'],
    cosaFare: [
      'Visita al MoMA (ingresso da 11 West 53rd Street, circa 2 ore, priorità al quarto e quinto piano)',
      'High Line e The Vessel — vedi la scheda esperienza dedicata',
      'Rooftop Edge o Summit a Hudson Yards',
      'Pranzo o passeggiata a Chelsea Market',
    ],
    doveDormire: 'Non ho pernottato qui: giornata da Midtown.',
    doveMangiare: 'Chelsea Market per pranzo; Shake Shack Midtown East, Five Guys nelle vicinanze del MoMA.',
    comeArrivare: 'A piedi da Midtown, passando per il Rockefeller Center.',
    comeSpostarsi: 'A piedi.',
    periodoMigliore: 'da confermare',
    costi: 'da completare — ingresso MoMA non specificato nel diario.',
    erroriDaEvitare: ['Scaricare in anticipo l\'app Bloomberg Connects per mappa e audioguida del MoMA, disponibili solo online'],
    miaEsperienza:
      'La passeggiata sulla High Line fino a The Vessel (circa un miglio e mezzo, 1h30-2h in totale) è stata uno dei momenti più piacevoli e meno frenetici del viaggio — un buon contrappunto al ritmo serrato delle altre giornate.',
    esperienzeSlugs: ['high-line-vessel'],
    tripSlugs: ['new-york-360'],
    imageAlt: 'La passeggiata pensile della High Line tra i grattacieli di Manhattan, New York',
    immagine: '/images/new-york/high-line-stock.jpg',
  },
  {
    slug: 'statua-liberta-wall-street',
    paeseSlug: 'new-york',
    ordine: 4,
    nome: 'Statua della Libertà, Wall Street e Chinatown',
    tipologia: ['storia', 'cultura'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Dalla storia dell\'immigrazione a Ellis Island al cuore finanziario di Wall Street, fino ai vicoli di SoHo, Little Italy e Chinatown.',
    percheAndarci: 'Per la Statua della Libertà vista da vicino e per attraversare in poche ore alcuni dei quartieri storici più densi di Manhattan.',
    cosaVedere: [
      'La Statua della Libertà (visita dal basso) ed Ellis Island, il museo dell\'immigrazione',
      'Il Charging Bull e la Borsa di New York',
      'Trinity Church, Zuccotti Park, l\'Oculus, Ground Zero',
      'Mulberry Street a Little Italy, ormai ridotta a poco più della scritta iconica',
      'Pell Street, Doyers Street e Columbus Park a Chinatown',
    ],
    cosaFare: [
      'Traghetto (da prenotare) verso Statua della Libertà ed Ellis Island — vedi la scheda esperienza dedicata',
      'Giro a piedi di Wall Street, SoHo, Little Italy e Chinatown (circa un\'ora)',
      'Musical a Broadway in serata',
    ],
    doveDormire: 'Non ho pernottato qui: giornata da Midtown.',
    doveMangiare: 'Liberty Bagels; Me La Wa o Uncle Lo a Chinatown (spesso fila); Prince Street Pizza a SoHo, famosa per la pepperoni pizza in stile americano; Lombardi\'s Pizza a Little Italy (non memorabile, ma un\'opzione).',
    comeArrivare: 'Metro verso il Financial District.',
    comeSpostarsi: 'Traghetto per la Statua della Libertà; metro verso Canal Street; a piedi tra i quartieri.',
    periodoMigliore: 'da confermare',
    costi: 'da completare',
    erroriDaEvitare: ['Prenotare il traghetto per la Statua della Libertà in anticipo'],
    miaEsperienza:
      'Il museo dell\'immigrazione a Ellis Island racconta una parte di storia americana che si sente ancora molto presente camminando per la città — una delle tappe più dense di significato di tutto il viaggio.',
    esperienzeSlugs: ['statua-liberta-ellis-island'],
    tripSlugs: ['new-york-360'],
    imageAlt: 'La Statua della Libertà su Liberty Island, New York',
    immagine: '/images/new-york/statua-liberta-stock.jpg',
  },
  {
    slug: 'ground-zero-dumbo',
    paeseSlug: 'new-york',
    ordine: 5,
    nome: 'Ground Zero e DUMBO',
    tipologia: ['storia', 'città'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Dal Memoriale dell\'11 settembre allo scorcio più fotografato di Brooklyn, con il ponte di Manhattan sullo sfondo, fino alla traversata a piedi del Brooklyn Bridge.',
    percheAndarci: 'Per un momento di riflessione a Ground Zero e per uno dei panorami urbani più iconici di New York a DUMBO.',
    cosaVedere: [
      'Ground Zero e il 9/11 Museum',
      'The Oculus',
      'L\'incrocio tra Water Street e Washington Street a DUMBO, con il ponte di Manhattan sullo sfondo',
      'Jane\'s Carousel, la giostra storica di DUMBO',
    ],
    cosaFare: [
      'Visita al 9/11 Museum',
      'DUMBO e traversata a piedi del Brooklyn Bridge — vedi la scheda esperienza dedicata',
      'Brooklyn Flea Market (solo la domenica)',
      'Tramonto al Top of the Rock — vedi la scheda esperienza dedicata',
    ],
    doveDormire: 'Non ho pernottato qui: giornata da Midtown, con rientro in serata.',
    doveMangiare: 'Pisillo per panini; Vinegar Hill House e Bluestone Lane a DUMBO.',
    comeArrivare: 'Metro verso il Financial District, poi a piedi o metro verso DUMBO.',
    comeSpostarsi: 'A piedi, incluso l\'attraversamento del Brooklyn Bridge.',
    periodoMigliore: 'da confermare — l\'11 settembre stesso, se le date coincidono con il viaggio, per la cerimonia di commemorazione',
    costi: 'da completare',
    erroriDaEvitare: [],
    miaEsperienza:
      'DUMBO, con il ponte di Manhattan che si allinea perfettamente tra i palazzi di Water Street e Washington Street, è lo scorcio più fotografato di Brooklyn per un motivo — e il tramonto al Top of the Rock la sera stessa ha chiuso una delle giornate più belle del viaggio.',
    esperienzeSlugs: ['dumbo-brooklyn-bridge', 'top-of-the-rock'],
    tripSlugs: ['new-york-360'],
    imageAlt: 'Il ponte di Manhattan visto dall\'incrocio di Water Street a DUMBO, Brooklyn, New York',
    immagine: '/images/new-york/dumbo-stock.jpg',
  },
]
