import type { Destinazione } from '@/lib/types'

// Contenuto riutilizzato dal viaggio "Lofoten in 7 giorni" (src/content/viaggi/01-lofoten-estate-2025.md).
// Dove un dato non è nel diario originale, il campo resta vuoto o con una nota
// esplicita "da confermare/da completare" — nessun fatto inventato.
//
// Le immagini sono foto stock temporanee (Pixabay/Pexels, licenze free-use),
// scelte per rappresentare davvero il luogo in attesa delle foto reali del
// viaggio — vanno sostituite non appena disponibili gli scatti originali.

export const destinazioniNorvegia: Destinazione[] = [
  {
    slug: 'oslo',
    paeseSlug: 'norvegia',
    ordine: 1,
    nome: 'Oslo',
    tipologia: ['cultura'],
    giorniConsigliati: '1 giorno, sia all\'andata che al ritorno',
    visitataPersonalmente: true,
    introduzione:
      'La capitale norvegese, punto di ingresso e di uscita del viaggio: giardini reali, lungomare di Aker Brygge, musei d\'arte contemporanea e l\'Opera House affacciata sul fiordo.',
    percheAndarci: 'Un giorno di cultura e passeggiate a piedi che funziona bene sia per aprire sia per chiudere il viaggio, prima o dopo il volo interno verso Bodø.',
    cosaVedere: [
      'Giardini del Palazzo Reale',
      'Lungomare di Aker Brygge',
      'Museo Astrup Fearnley (edificio di Renzo Piano)',
      'Oslo Opera House, con salita sul tetto per la vista su città e mare',
    ],
    cosaFare: [
      'Passeggiata a piedi dal Palazzo Reale ad Aker Brygge fino all\'Opera House',
      'Salita sul tetto dell\'Opera House per la vista, con una sosta per un tè caldo nel bar interno',
    ],
    doveDormire:
      'Ho dormito al Citybox Hotel, a 5 minuti a piedi da Oslo S: design-hotel economico, check-in automatico, camere essenziali ma pulite, letti comodi, macchina del caffè in stanza. Le recensioni (Tripadvisor, oltre 2.400 giudizi, punteggio 4/5) confermano l\'impressione diretta — ottimo rapporto qualità-prezzo per gli standard di Oslo e posizione imbattibile, a fronte di uno stile volutamente minimal (niente reception fisica) e qualche lamentela su stanze rumorose se affacciate sul tram. Consiglio di chiedere una camera sul lato interno.\n\nAlternative a Oslo — economiche: Saga Poshtel (a pochi passi da Oslo S), Comfort Hotel Xpress Central Station (due minuti da Jernbanetorget) · fascia media (qui rientra anche il Citybox scelto): Comfort Hotel Karl Johan (250 m da Oslo S) · fascia alta senza esagerare: Amerikalinjen (hotel storico e boutique vicino alla stazione), The Thief (design hotel sul lungomare di Tjuvholmen, con spa interna).',
    doveMangiare:
      'Cena da Rorbua (Aker Brygge): cucina norvegese tradizionale, porzioni generose, prezzi nella media, atmosfera calda in legno. Se si torna a Oslo a fine viaggio, Café Sara è un\'ottima ultima cena — locale semplice ma aperto fino a tardi, comodo dopo un volo serale (consigliata prenotazione nel weekend).',
    comeArrivare: 'Volo internazionale su Oslo Gardermoen; dall\'aeroporto il treno Flytoget porta al centro in 19 minuti (circa 210 NOK, partenze ogni 10 minuti).',
    comeSpostarsi: 'A piedi in centro; Flytoget per/dall\'aeroporto.',
    periodoMigliore: 'da confermare',
    costi: 'Flytoch circa 210 NOK a tratta; cene nella media per gli standard norvegesi (comunque cari rispetto all\'Italia).',
    erroriDaEvitare: ['Se si torna a Café Sara nel weekend, prenotare: è un locale molto frequentato la sera'],
    miaEsperienza:
      'Oslo l\'ho vissuta come tappa breve ma piacevole su entrambi i lati del viaggio: un pomeriggio di passeggiata tranquilla il primo giorno, e un\'ultima cena rilassata da Café Sara al rientro, dopo una settimana di trekking.',
    esperienzeSlugs: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Facciata in vetro e marmo dell\'Oslo Opera House, con persone sul tetto spiovente',
    immagine: '/images/norvegia/oslo-stock.jpg',
  },
  {
    slug: 'bodo',
    paeseSlug: 'norvegia',
    ordine: 2,
    nome: 'Bodø',
    tipologia: ['natura'],
    giorniConsigliati: 'poche ore, tappa di passaggio due volte (andata e ritorno)',
    visitataPersonalmente: true,
    introduzione: 'Il punto di transito obbligato tra Oslo e le Lofoten: qui si arriva in aereo, si ritira l\'auto a noleggio e si prendono i traghetti verso l\'arcipelago.',
    percheAndarci: 'Serve comunque attraversarla, e ha abbastanza da offrire per occupare bene qualche ora tra un volo e un traghetto.',
    cosaVedere: ['Nyholms Fort, punto panoramico a 10 minuti a piedi dal porto', 'Spiaggia di Mjelle'],
    cosaFare: [
      'Giro del centro e del molo a piedi',
      'Traghetto verso Misten/Kjerringøy (circa 10 minuti, si resta in auto, arrivare 30 minuti prima): onestamente non entusiasma particolarmente, ma è un\'opzione onesta per occupare qualche ora — se gioca il Bodø/Glimt in casa, può valere la pena assistere alla partita',
    ],
    doveDormire: 'Non ho pernottato a Bodø, solo tappe di passaggio — struttura da confermare per chi vuole fermarsi una notte.',
    doveMangiare:
      'Bryggerikaia (apre a metà mattina): ottimi panini "mega farciti" da asporto, da consumare al punto panoramico della città. Melkebaren per colazione — buono, ma il servizio è lento, da mettere in conto con i tempi stretti.',
    comeArrivare: 'Volo interno da Oslo Gardermoen.',
    comeSpostarsi: 'A piedi in centro; auto a noleggio per il resto degli spostamenti.',
    periodoMigliore: 'da confermare',
    costi: 'da completare',
    erroriDaEvitare: ['Mettere in conto il servizio lento da Melkebaren se si ha poco tempo tra un traghetto e l\'altro'],
    miaEsperienza:
      'Una tappa puramente logistica sia all\'andata che al ritorno, ma con abbastanza da fare (spiaggia di Mjelle, il punto panoramico di Nyholms Fort) da non sembrare tempo perso.',
    esperienzeSlugs: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Vista dall\'alto del porto di Bodø, con casette rosse sul molo e la strada costiera',
    immagine: '/images/norvegia/bodo-stock.jpg',
  },
  {
    slug: 'svolvaer',
    paeseSlug: 'norvegia',
    ordine: 3,
    nome: 'Svolvær',
    tipologia: ['natura', 'avventura'],
    giorniConsigliati: '2-3 notti, prima base del viaggio',
    visitataPersonalmente: true,
    introduzione: 'Il porto principale delle Lofoten e la prima base logistica del viaggio: da qui si parte per l\'escursione in gommone al Trollfjord e per la gita a Henningsvær.',
    percheAndarci: 'Posizione centrale per le prime giornate nell\'arcipelago, con il ristorante migliore di tutto il viaggio.',
    cosaVedere: ['Il porto di Svolvær'],
    cosaFare: ['Escursione in RIB al Trollfjord — vedi la scheda esperienza dedicata', 'Colazione da Kringla, panetteria molto buona vicino agli appartamenti'],
    doveDormire:
      'Ho dormito in un appartamento con vista sul porto al Nordis Apartment: finestroni, terrazza panoramica, angolo cottura. Su Booking.com ha un punteggio di 8,7/10 (417 recensioni) e 9,7/10 per la posizione — dati che confermano l\'impressione diretta: spazi ampi e puliti, vista che da sola vale il soggiorno, comodo per chi vuole cucinare la sera invece di uscire sempre.\n\nAlternative a Svolvær — economiche: Lofoten Feriesenter (campeggio e cabine, da circa 200 NOK a persona), Lofoten Sommerhotell og Vandrerhjem (ostello a Kabelvåg, sauna e colazione inclusa) · fascia media (qui rientra il Nordis Apartment scelto): Thon Hotel Lofoten (centrale, vista sul porto) · fascia alta senza esagerare: Thon Hotel Svolvær (grande hotel sul lungomare, binocolo in ogni stanza), Svinøya Rorbuer (rorbu storici con cucina propria, il più quotato di Svolvær su Tripadvisor).',
    doveMangiare:
      'Bacalo per una cena nella media. Paleo Arctic è stato il ristorante migliore di tutto il viaggio: prezzi leggermente sopra la media, ma qualità nettamente superiore — da prenotare per tempo.',
    comeArrivare: 'Da Bodø: circa 3h15 di guida fino a Bognes, traghetto Bognes-Lødingen (arrivare con 40 minuti di anticipo), poi altre 1h40 d\'auto fino a Svolvær.',
    comeSpostarsi: 'Auto a noleggio.',
    periodoMigliore: 'da confermare',
    costi: 'da completare',
    erroriDaEvitare: ['Prenotare per tempo sia il Trollfjord sia una cena da Paleo Arctic: sono le due esperienze più richieste della zona'],
    miaEsperienza:
      'Svolvær è stata la base perfetta per le prime giornate: comoda per il Trollfjord, per Henningsvær, e con la cena più memorabile di tutto il viaggio al Paleo Arctic.',
    esperienzeSlugs: ['trollfjord-rib'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'La chiesa di Svolvær con le case rosse del porto sullo sfondo di un cielo tempestoso, Lofoten',
    immagine: '/images/norvegia/svolvaer-stock.jpg',
  },
  {
    slug: 'henningsvaer',
    paeseSlug: 'norvegia',
    ordine: 4,
    nome: 'Henningsvær',
    tipologia: ['cultura', 'natura'],
    giorniConsigliati: 'mezza giornata, in gita da Svolvær (circa 30 minuti d\'auto)',
    visitataPersonalmente: true,
    introduzione: 'La "piccola Venezia" delle Lofoten: un villaggio di pescatori con il campo da calcio più fotografato di Norvegia e un\'atmosfera bohémien tra bakery, artigianato e boutique vintage.',
    percheAndarci: 'Uno dei villaggi più fotogenici dell\'arcipelago, con un ottimo pranzo sul canale e il punto di partenza per il Festvågtind trail.',
    cosaVedere: ['Il celebre campo da calcio, ottimo per foto/drone', 'Il canale del villaggio', 'Boutique vintage e artigianato locale'],
    cosaFare: [
      'Pranzo da Fiskekrogen, sul canale del villaggio — l\'effetto "piccola Venezia" è vero, meglio prenotare e chiedere un tavolo vicino alla finestra',
      'Giro del villaggio, piccolo ma vivace',
      'Festvågtind trail nel pomeriggio — vedi la scheda esperienza dedicata',
    ],
    doveDormire: 'Non ho pernottato a Henningsvær: si dorme a Svolvær, a circa 30 minuti d\'auto.',
    doveMangiare: 'Fiskekrogen, sul canale — cibo ottimo, ma meglio prenotare in anticipo, soprattutto per un tavolo vicino alla finestra.',
    comeArrivare: '30 minuti d\'auto da Svolvær.',
    comeSpostarsi: 'A piedi, il villaggio è piccolo.',
    periodoMigliore: 'da confermare',
    costi: 'da completare',
    erroriDaEvitare: ['Non prenotare Fiskekrogen: nelle ore di punta il ristorante si riempie in fretta'],
    miaEsperienza:
      'Henningsvær è stata una delle sorprese del viaggio: il pranzo sul canale, il campo da calcio, e nel pomeriggio un trekking (il Festvågtind) più selvaggio e meno affollato del Reinebringen.',
    esperienzeSlugs: ['festvagtind-trail'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Vista aerea del celebre campo da calcio di Henningsvær incastonato tra il mare e le montagne',
    immagine: '/images/norvegia/henningsvaer-stock.jpg',
  },
  {
    slug: 'reine',
    paeseSlug: 'norvegia',
    ordine: 5,
    nome: 'Reine',
    tipologia: ['natura', 'avventura'],
    giorniConsigliati: '1-2 giorni, base per Reinebringen e la gita alla spiaggia di Bunes',
    visitataPersonalmente: true,
    introduzione: 'Il villaggio simbolo delle Lofoten, base per il trekking più iconico dell\'arcipelago e punto di partenza del traghetto verso una delle spiagge più belle della zona.',
    percheAndarci: 'Il Reinebringen è il trekking che tutti associano alle Lofoten, e da qui si parte anche per la spiaggia di Bunes — due delle esperienze più forti di tutto il viaggio.',
    cosaVedere: ['Il villaggio di Reine', 'Il Reinebringen dall\'alto'],
    cosaFare: [
      'Trekking al Reinebringen — vedi la scheda esperienza dedicata',
      'Traghetto ed escursione alla spiaggia di Bunes — vedi la scheda esperienza dedicata',
      'Tappa al Viking Museum di Borg lungo il tragitto da Svolvær — vedi la scheda esperienza dedicata',
    ],
    doveDormire: 'Non ho pernottato a Reine: si dorme a Nesland/Flakstad, a pochi minuti d\'auto.',
    doveMangiare: 'Non ho annotato ristoranti specifici a Reine — la Coop Prix del paese è comoda per organizzare un pranzo al sacco prima delle escursioni.',
    comeArrivare: 'Da Svolvær via Leknes (con tappa al Viking Museum di Borg), circa 55 minuti d\'auto da Svolvær fino a Borg, poi altri 20-30 minuti fino a Reine.',
    comeSpostarsi: 'Parcheggio a pagamento in paese (200 NOK/3h).',
    periodoMigliore: 'Il Reinebringen vale davvero solo con cielo sereno — controllare le previsioni prima di programmare la giornata.',
    costi: 'Parcheggio 200 NOK/3h.',
    erroriDaEvitare: [
      'Il Reinebringen richiede un minimo di allenamento per il dislivello; se il cielo è coperto, meglio rimandarlo — la vista è tutto',
      'Per il traghetto verso Vindstad/Bunes, arrivare con almeno 30 minuti di anticipo anche con posti riservati',
    ],
    miaEsperienza:
      'Reine è stata il punto più intenso del viaggio: il Reinebringen (1h50 il mio tempo totale, tra salita, sosta e discesa) e la spiaggia di Bunes il giorno dopo, raggiungibile solo in traghetto — due ricordi che porto a casa più di ogni altra tappa.',
    esperienzeSlugs: ['reinebringen', 'spiaggia-di-bunes', 'viking-museum-borg'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Vista aerea dal Reinebringen sul villaggio di Reine e i fiordi circostanti',
    immagine: '/images/norvegia/reinebringen-stock.jpg',
  },
  {
    slug: 'nesland-flakstad',
    paeseSlug: 'norvegia',
    ordine: 6,
    nome: 'Nesland / Flakstad',
    tipologia: ['natura'],
    giorniConsigliati: '2-3 notti, seconda base del viaggio',
    visitataPersonalmente: true,
    introduzione: 'La base più isolata e silenziosa del viaggio: un rorbu affacciato direttamente sul fiordo, punto di partenza per la passeggiata panoramica verso Nusfjord.',
    percheAndarci: 'Per staccare dal ritmo dei trekking più famosi con una base tranquilla, e per la passeggiata verso Nusfjord — meno battuta ma altrettanto bella.',
    cosaVedere: ['Il fiordo davanti al rorbu', 'Il villaggio di Nusfjord, in fondo alla passeggiata panoramica'],
    cosaFare: [
      'Passeggiata panoramica Nesland-Nusfjord — vedi la scheda esperienza dedicata',
      'Barbecue serale nella rorbu con la spesa fatta a Ramberg',
    ],
    doveDormire:
      'Ho dormito in un rorbu privato affacciato sul fiordo, Casa Flakstad — la sistemazione più isolata e silenziosa del viaggio. È una struttura piccola, senza un riscontro significativo di recensioni online da poter citare onestamente: un rorbu semplice ed essenziale, poche luci, tanto silenzio, il fiordo a pochi passi.\n\nAlternative a Nesland/Flakstad — economiche: Ramberg Gjestegård (cabine semplici, 850-1050 NOK a notte, sconto in bassa stagione), Lofoten Beach Camp (campeggio a conduzione familiare a Ramberg, sauna e area pic-nic) · fascia media (qui rientra il rorbu scelto): Lofoten Nesland Guesthouse (punteggio molto alto nelle recensioni, posizione tranquilla con vista sull\'oceano) · fascia alta senza esagerare: Nusfjord Village & Resort (rorbu storici ristrutturati nel villaggio di Nusfjord, sauna e vasche idromassaggio incluse — caro ma con recensioni entusiaste).',
    doveMangiare:
      'Cena al Ramberg Resort, buona posizione a due passi dalla spiaggia di Ramberg per una passeggiata digestiva. Il supermercato di Ramberg è più fornito ed economico rispetto alla Coop di Reine ed è il punto di riferimento per organizzare un barbecue serale (salmone, verdure, contorni) — attenzione, vende solo birra, niente vino o superalcolici.',
    comeArrivare: 'Pochi minuti d\'auto da Reine.',
    comeSpostarsi: 'Auto a noleggio.',
    periodoMigliore: 'da confermare',
    costi: 'Cabine da 850-1050 NOK/notte per le opzioni economiche della zona.',
    erroriDaEvitare: ['Il supermercato di Ramberg non vende vino/superalcolici, solo birra: pianificare la spesa di conseguenza'],
    miaEsperienza:
      'Il rorbu di Nesland è stato il posto più silenzioso di tutto il viaggio: nessuna luce artificiale, il fiordo a pochi passi, e una serata di barbecue tra le più rilassate della settimana.',
    esperienzeSlugs: ['nesland-nusfjord'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Rorbu rosse tradizionali con una montagna avvolta dalla nebbia sullo sfondo, Lofoten',
    immagine: '/images/norvegia/nesland-stock.jpg',
  },
  {
    slug: 'a',
    paeseSlug: 'norvegia',
    ordine: 7,
    nome: 'Å',
    tipologia: ['cultura'],
    giorniConsigliati: 'mezza giornata, in gita da Nesland/Flakstad (circa 50 minuti d\'auto)',
    visitataPersonalmente: true,
    introduzione: 'Il villaggio dal nome più corto del mondo, e probabilmente il più autentico e "storico" di tutta la zona: bakery tradizionale e Museo dei Pescatori.',
    percheAndarci: 'Per capire davvero lo stile di vita delle comunità di pescatori delle Lofoten, con una tappa golosa alla bakery del paese.',
    cosaVedere: ['Il villaggio storico', 'La bakery tradizionale'],
    cosaFare: ['Visita guidata al Museo dei Pescatori — vedi la scheda esperienza dedicata', 'Pranzo lungo la strada a Sakrisøy da Anita\'s Seafood'],
    doveDormire: 'Non ho pernottato ad Å: si dorme a Nesland/Flakstad.',
    doveMangiare:
      'La bakery storica del paese (pochi posti a sedere, ma dolci ottimi). Lungo la strada, a Sakrisøy, Anita\'s Seafood: panini farciti, zuppe, sushi, vista sul fiordo — si ordina al bancone, niente servizio al tavolo.',
    comeArrivare: 'Circa 50 minuti d\'auto da Nesland/Flakstad.',
    comeSpostarsi: 'A piedi, il villaggio è piccolo.',
    periodoMigliore: 'da confermare',
    costi: 'da completare',
    erroriDaEvitare: [],
    miaEsperienza:
      'Å mi ha colpito anche sotto la pioggia: il Museo dei Pescatori, con la visita guidata in inglese, racconta bene una parte di storia locale che altrove nel viaggio si vede solo di sfuggita.',
    esperienzeSlugs: ['museo-dei-pescatori'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Rastrelliere tradizionali per l\'essiccazione dello stoccafisso al tramonto, con montagne innevate sullo sfondo, Lofoten',
    immagine: '/images/norvegia/a-stock.jpg',
  },
  {
    slug: 'tromso',
    paeseSlug: 'norvegia',
    ordine: 8,
    nome: 'Tromsø',
    tipologia: ['natura', 'avventura'],
    giorniConsigliati: '5 giorni, viaggio a sé rispetto alle Lofoten',
    visitataPersonalmente: true,
    introduzione:
      'La "capitale artica" della Norvegia, ben più a nord delle Lofoten: base per la caccia all\'aurora boreale, husky sledding e cultura sami, con la Cattedrale Artica come simbolo della città.',
    percheAndarci: 'Per l\'aurora boreale e per un pacchetto di attività artiche molto concentrato in pochi giorni, con la città stessa come base comoda a piedi.',
    cosaVedere: [
      'Cattedrale Artica (Ishavskatedralen), a forma di iceberg, con una delle vetrate a mosaico più grandi d\'Europa',
      'Fjellheisen, la funivia che sale sul monte Storsteinen (465 m) con vista su città e fiordi',
      'Polar Museum e Polaria, sulla storia delle spedizioni polari e la fauna artica',
    ],
    cosaFare: [
      'Aurora chase in minibus — vedi la scheda esperienza dedicata',
      'Husky sledding — vedi la scheda esperienza dedicata',
      'Esperienza sami con le renne — vedi la scheda esperienza dedicata',
    ],
    doveDormire: 'Non ho ricordi precisi sulla struttura scelta — da completare. La zona più comoda è quella del porto/Storgata, a pochi passi da negozi, bar e dal punto di ritrovo di gran parte delle escursioni.',
    doveMangiare: 'Ricordi generici più che locali precisi: la cucina locale ruota molto intorno a granchio reale (kongekrabbe) e baccalà essiccato (tørrfisk/lutefisk), diffusi nei ristoranti della zona di Storgata.',
    comeArrivare: 'Volo diretto o con scalo su Tromsø.',
    comeSpostarsi: 'A piedi in centro; minibus/pullman organizzati per le escursioni fuori città.',
    periodoMigliore: 'da fine settembre a fine marzo per l\'aurora, con notte polare (poca luce diurna) tra dicembre e gennaio',
    costi: 'Doppia in hotel centrale in alta stagione intorno ai 170€/notte; escursioni organizzate (aurora, husky, sami) da circa 150-200€ a persona.',
    erroriDaEvitare: [
      'Prenotare le escursioni serali con un minimo di anticipo, soprattutto nei mesi di punta (novembre-marzo)',
      'Sottovalutare il vento sul lungomare: si sente più del previsto',
    ],
    miaEsperienza:
      'Di questo viaggio mi sono rimasti soprattutto flash più che un diario dettagliato: il freddo pungente appena scesi dall\'aereo, il buio della notte polare, e l\'aurora vista muoversi nel cielo per la prima volta durante l\'aurora chase in minibus.',
    esperienzeSlugs: ['aurora-chase-minibus-tromso', 'husky-sledding-tromso', 'sami-renne-lavvu-tromso', 'whale-watching-tromso', 'glass-igloo-lyngen'],
    tripSlugs: ['tromso'],
    imageAlt: 'Cattedrale Artica di Tromsø illuminata di sera con aurora boreale sullo sfondo',
    immagine: '/images/norvegia/tromso-stock.jpg',
  },
]
