import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Sri Lanka in 12 giorni" (src/content/viaggi/04-sri-lanka-2023.md).

export const destinazioniSriLanka: Destinazione[] = [
  {
    slug: 'negombo',
    paeseSlug: 'sri-lanka',
    ordine: 1,
    nome: 'Negombo',
    tipologia: ['mare', 'arrivo'],
    giorniConsigliati: '1 giorno, andata e ritorno',
    visitataPersonalmente: true,
    introduzione: 'La prima e l\'ultima tappa del viaggio, vicina all\'aeroporto di Colombo, con il suo celebre mercato del pesce all\'alba.',
    percheAndarci: 'È il punto di appoggio naturale per chi arriva o riparte da Colombo, e il fish market della mattina presto è uno spettacolo da non perdere.',
    cosaVedere: ['Il fish market di Negombo all\'alba'],
    cosaFare: [
      'Cena di benvenuto/addio tra Salt Restaurant, Tuk Tuk Wine & Dine o Jude Restaurant',
      'Dopocena al Rodeo o allo Sky Lounge',
      'Fish market la mattina presto',
    ],
    doveDormire:
      'Andata: Regal Réseau Hotel & Spa (4/5 su Tripadvisor, circa 400 recensioni) — apprezzato per il rooftop con piscina a sfioro, anche se la musica del bar sale fino alle camere secondo alcuni ospiti. Ritorno: Goldi Sands Hotel (4/5, oltre 1.700 recensioni) — colazione a buffet sopra le aspettative e posizione comoda, ma arredi descritti da alcuni recensori come datati.\n\nEconomiche: Icebear Guesthouse, Ocean Beauty Guest House · fascia media: Jetwing Sea, Jetwing Lagoon · lusso (contenuto): Jetwing Blue, Sentido Heritance Negombo.',
    doveMangiare: 'Jude Restaurant (pesce buono ma servizio lento, circa 12€ a testa); SeaJoy per pranzo economico.',
    usciteSerali: 'Rodeo, Sky Lounge, o beach party chiedendo a guida e locali.',
    comeArrivare: 'Transfer dall\'aeroporto di Colombo, circa 6.000 LKR a macchina.',
    comeSpostarsi: 'Van privato con autista.',
    periodoMigliore: 'novembre',
    costi: 'Cena circa 12€ a testa; transfer aeroporto 5.000-6.000 LKR.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Il fish market di Negombo la mattina presto è stato uno spettacolo genuino, un buon modo per rompere il ghiaccio con il paese appena arrivati.',
    esperienzeSlugs: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Barche da pesca colorate sulla spiaggia di Negombo, Sri Lanka',
    immagine: '/images/sri-lanka/negombo-stock.jpg',
  },
  {
    slug: 'anuradhapura',
    paeseSlug: 'sri-lanka',
    ordine: 2,
    nome: 'Anuradhapura',
    tipologia: ['storia', 'religione'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'La prima delle "città sacre" del triangolo culturale singalese: dagoba immense, alberi sacri e rovine che raccontano oltre duemila anni di storia buddhista.',
    percheAndarci: 'Per capire le radici del buddhismo in Sri Lanka, con il Sri Maha Bodhi, discendente diretto dell\'albero sotto cui il Buddha raggiunse l\'illuminazione.',
    cosaVedere: ['Le dagoba del sito archeologico', 'Il Sri Maha Bodhi, l\'albero sacro'],
    cosaFare: ['Visita guidata al sito archeologico (circa 3h) con Anil in bicicletta o Lalith'],
    doveDormire:
      'Miridiya Lake Resort — voto medio 3/5 su Tripadvisor (circa 400 recensioni), ma sotto una nuova gestione recente sembra migliorato parecchio (ingresso, cibo, camere). Vista sul lago Nuwara Wewa molto apprezzata, qualche lamentela su docce e umidità nei bagni.\n\nEconomiche: Saubagya Inn, Why Not Palace · fascia media: Kings Town Hotel, Monaara Leisure · lusso: Ulagalla by Uga Escapes, Divulgaha Gedara Boutique Hotel.',
    doveMangiare: 'Buffet in hotel (circa 2.200 LKR + bevande).',
    comeArrivare: 'Circa 5h di van da Negombo.',
    comeSpostarsi: 'Bicicletta con guida all\'interno del sito.',
    periodoMigliore: 'pomeriggio, dopo l\'arrivo',
    costi: 'Guida circa 6.500 LKR (19€) più mancia.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Le dagoba immense di Anuradhapura danno subito la scala della storia buddhista dell\'isola, un buon primo impatto con il triangolo culturale prima delle tappe più note come Sigiriya.',
    esperienzeSlugs: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Le dagoba antiche del sito archeologico di Anuradhapura, Sri Lanka',
    immagine: '/images/sri-lanka/anuradhapura-stock.jpg',
  },
  {
    slug: 'dambulla-sigiriya',
    paeseSlug: 'sri-lanka',
    ordine: 3,
    nome: 'Dambulla e Sigiriya',
    tipologia: ['storia', 'trekking', 'natura'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'Mihintale, il safari a Minneriya, il tramonto da Pidurangala Rock, la Rocca del Leone di Sigiriya e il Tempio d\'Oro scavato nella roccia: il cuore del triangolo culturale.',
    percheAndarci: 'La concentrazione più alta di momenti clou del viaggio: storia, natura e trekking in due giorni intensi.',
    cosaVedere: [
      'Mihintale, dove secondo la tradizione il buddhismo arrivò per la prima volta in Sri Lanka',
      'Sigiriya, la Rocca del Leone, con le fondamenta del palazzo reale del V secolo e gli affreschi delle fanciulle celesti',
      'Il Tempio d\'Oro di Dambulla, cinque grotte scavate nella roccia',
      'Il panorama su Sigiriya da Pidurangala Rock',
    ],
    cosaFare: [
      'Safari a Minneriya (elefanti) — vedi la scheda esperienza dedicata',
      'Trekking al tramonto a Pidurangala Rock (30 minuti di salita)',
      'Trekking a Sigiriya (1h30-2h di salita) — vedi la scheda esperienza dedicata',
      'Visita al Tempio d\'Oro di Dambulla',
      'Dambulla Wholesale Market, il più grande mercato all\'ingrosso dello Sri Lanka',
    ],
    doveDormire:
      'Tropical Life Resort — il migliore dei nove hotel del viaggio sulla carta: #1 tra le strutture specialty di Dambulla, 4/5 su Tripadvisor. Camere pulite e ben accessoriate, buffet abbondante, atmosfera immersa nel verde. Qualche recensione segnala assenza di WiFi in camera.\n\nEconomiche: Relax Guesthouse, Lake Island Homestay · fascia media: Lake Lodge Boutique Hotel, Kalundewa Retreat · lusso: Heritance Kandalama (il celebre hotel firmato Geoffrey Bawa), Aliya Resort & Spa.',
    doveMangiare: 'Mom\'s Kitchen e Golden Palace a Dambulla/Sigiriya.',
    comeArrivare: 'Circa 1h30 di trasferimento da Anuradhapura via Mihintale e il safari.',
    comeSpostarsi: 'Van privato, a piedi per i trekking.',
    periodoMigliore: 'mattina presto per Sigiriya, per evitare il caldo',
    costi: 'Mihintale: ingresso 500 LKR + sarong 50 LKR; safari a Minneriya circa 12.000 LKR a jeep + ingresso; Sigiriya 10.000-30 USD a persona a seconda della tariffa applicata; Pidurangala 1.000 LKR.',
    erroriDaEvitare: ['Partire presto per Sigiriya per evitare il caldo peggiore durante la salita'],
    miaEsperienza:
      'Il tramonto da Pidurangala Rock, con la vista sulla Rocca di Sigiriya di fronte, è uno dei panorami più belli di tutto il viaggio, forse ancora più bello della salita a Sigiriya stessa che tutti fanno di corsa senza fermarsi qui.',
    esperienzeSlugs: ['safari-minneriya', 'trekking-sigiriya'],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'La Rocca del Leone di Sigiriya vista da Pidurangala Rock, Sri Lanka',
    immagine: '/images/copertine/sri-lanka-2023.jpg',
  },
  {
    slug: 'polonnaruwa',
    paeseSlug: 'sri-lanka',
    ordine: 4,
    nome: 'Polonnaruwa',
    tipologia: ['storia'],
    giorniConsigliati: 'mezza giornata',
    visitataPersonalmente: true,
    introduzione: 'La seconda capitale medievale di Sri Lanka, girata in bicicletta tra templi e statue del Buddha.',
    percheAndarci: 'Un\'alternativa più leggera e diretta rispetto a Sigiriya, ugualmente ricca di storia.',
    cosaVedere: ['I templi e le statue del Buddha della città medievale'],
    cosaFare: ['Giro in bicicletta a noleggio (1.000 LKR) tra i templi', 'Pranzo al Priyamali gedara, con vista sulle risaie'],
    doveDormire: 'Non ho pernottato qui: gita di mezza giornata da Dambulla.',
    doveMangiare: 'Priyamali gedara, ristorante di campagna con vista sulle risaie, molto buono.',
    comeArrivare: 'Circa 1h10 di trasferimento da Sigiriya.',
    comeSpostarsi: 'Bicicletta a noleggio all\'interno del sito.',
    periodoMigliore: 'mattina o pomeriggio',
    costi: 'Bicicletta 1.000 LKR (circa 2,5€); guida (Indu) 6.000 LKR + mancia.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Girare Polonnaruwa in bicicletta è stato un bel cambio di ritmo rispetto alla salita di Sigiriya del giorno prima, e il pranzo al Priyamali gedara con vista sulle risaie è stato uno dei migliori del viaggio.',
    esperienzeSlugs: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Statue del Buddha tra le rovine della città medievale di Polonnaruwa, Sri Lanka',
    immagine: '/images/sri-lanka/polonnaruwa-stock.jpg',
  },
  {
    slug: 'kandy',
    paeseSlug: 'sri-lanka',
    ordine: 5,
    nome: 'Kandy',
    tipologia: ['cultura', 'religione'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Il Tempio del Dente con la sua cerimonia serale, il mercato del pesce migliore per i souvenir, e il lago cittadino.',
    percheAndarci: 'Per la cerimonia serale al Tempio del Dente, uno dei momenti più spirituali e sentiti di tutto il viaggio.',
    cosaVedere: ['Il Tempio del Dente (Temple of the Tooth)', 'La statua del Buddha di Bahiravokanda', 'Il lago cittadino'],
    cosaFare: [
      'Ranweli Spice Garden, con visita alla piantagione di spezie',
      'Kandy Fish Market, il posto migliore del viaggio per souvenir (spezie, tessuti)',
      'Cerimonia serale al Tempio del Dente — vedi la scheda esperienza dedicata',
    ],
    doveDormire:
      'Rivendell Hotel — 4/5 su Tripadvisor ma con pareri contrastanti: chi lo apprezza parla di posizione tranquilla fuori dal centro e viste sulle colline; altre recensioni lo giudicano caro per quel che offre, con rumore mattutino da un tempio vicino.\n\nEconomiche: 256 Townhouse Rest, Sharon Inn Kandy · fascia media: Hotel Suisse, OZO Kandy · lusso: Earl\'s Regency, The Grand Kandyan.',
    doveMangiare: 'Ranweli Spice Garden per pranzo; un ristorante indiano del sud scovato sul posto, economico e ottimo (servizio un po\' confuso con gli ordini).',
    comeArrivare: 'Circa 2h di trasferimento da Dambulla, con sosta al Ranweli Spice Garden.',
    comeSpostarsi: 'A piedi in centro.',
    periodoMigliore: 'tardo pomeriggio/sera, per arrivare in tempo alla cerimonia del Tempio del Dente',
    costi: 'Ingresso Tempio del Dente 2.000 LKR.',
    erroriDaEvitare: ['Arrivare al Tempio del Dente con largo anticipo: la fila si forma già dal tardo pomeriggio'],
    miaEsperienza:
      'La cerimonia serale al Tempio del Dente, con i tamburi che iniziano poco prima del calare della luce, è stata uno dei momenti più intensi e spirituali di tutto il viaggio.',
    esperienzeSlugs: ['tempio-del-dente'],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Il Tempio del Dente (Temple of the Tooth) di Kandy, Sri Lanka',
    immagine: '/images/sri-lanka/kandy-stock.jpg',
  },
  {
    slug: 'nallathanniya',
    paeseSlug: 'sri-lanka',
    ordine: 6,
    nome: 'Nallathanniya e Adam\'s Peak',
    tipologia: ['trekking', 'religione', 'avventura'],
    giorniConsigliati: '1 giorno e mezzo, incluso rafting a Kitulgala',
    visitataPersonalmente: true,
    introduzione: 'Il rafting sul fiume Kelani a Kitulgala e la scalata notturna dell\'Adam\'s Peak, la vera sfida fisica del viaggio.',
    percheAndarci: 'Per la scalata notturna verso l\'alba in cima, condivisa con centinaia di pellegrini locali: un\'esperienza che vale più per il percorso che per la meta.',
    cosaVedere: ['Il fiume Kelani, dove fu girato Il ponte sul fiume Kwai', 'L\'alba dalla cima dell\'Adam\'s Peak (2.243 m)'],
    cosaFare: [
      'Rafting sul fiume Kelani a Kitulgala — vedi la scheda esperienza dedicata',
      'Scalata notturna dell\'Adam\'s Peak (2h30-3h di salita) — vedi la scheda esperienza dedicata',
    ],
    doveDormire:
      'Wathsala Inn — base per la scalata, 3/5 su Tripadvisor: vista notevole sulla valle e sul Peak, staff cortese, ma parecchie recensioni segnalano problemi di manutenzione (docce, lenzuola, infiltrazioni). Va preso per quello che è: un punto d\'appoggio essenziale per partire di notte, non una struttura da vacanza.\n\nEconomiche: Slightly Chilled, Sun Mount Adam\'s Peak · fascia media: White House Adam\'s Peak, Adams Peak Grand · qui non ci sono vere strutture di lusso: è un villaggio di partenza per il trekking.',
    doveMangiare: 'Cena in hotel prima della partenza notturna.',
    comeArrivare: 'Circa 2h di trasferimento da Kandy via Kitulgala.',
    comeSpostarsi: 'A piedi per tutta la scalata.',
    periodoMigliore: 'stagione di pellegrinaggio, dicembre-maggio, per il percorso illuminato (ma anche più affollato)',
    costi: 'da completare — rafting e attività extra a Kitulgala da concordare con l\'operatore.',
    erroriDaEvitare: ['Portare assolutamente una felpa: in cima fa 3-6°C con vento'],
    miaEsperienza:
      'La notte di scalata dell\'Adam\'s Peak, in fila indiana con centinaia di pellegrini locali su una scalinata interamente illuminata, è stata la vera sfida fisica del viaggio. Il freddo in cima è tagliente, ma la sensazione di condividere il pellegrinaggio con chi lo fa per fede, non per turismo, vale più dell\'alba stessa.',
    esperienzeSlugs: ['rafting-kitulgala', 'scalata-adams-peak'],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'La scalinata di pellegrinaggio illuminata che sale verso la cima dell\'Adam\'s Peak, Sri Lanka',
    immagine: '/images/sri-lanka/adams-peak-stock.jpg',
  },
  {
    slug: 'nuwara-eliya',
    paeseSlug: 'sri-lanka',
    ordine: 7,
    nome: 'Nuwara Eliya',
    tipologia: ['natura', 'relax'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'La "piccola Inghilterra" di Sri Lanka, a 1.868 metri di quota, tra piantagioni di tè e l\'altopiano di Horton Plains.',
    percheAndarci: 'Per il contrasto climatico e paesaggistico con il resto del viaggio, tra tè, aria fresca e (per chi vuole) uno dei trekking più spettacolari dell\'isola.',
    cosaVedere: ['La Pedro Tea Plantation e la sua fabbrica di lavorazione', 'World\'s End a Horton Plains, un ciglio di altopiano a strapiombo per 870 metri'],
    cosaFare: [
      'Visita alla piantagione di tè Pedro',
      'Relax: massaggio, cerimonia del tè al Grand Hotel, Victoria Park, cascate di Ravana o dei Lover\'s Leap',
      'Avventura: trekking a World\'s End a Horton Plains (3h)',
    ],
    doveDormire:
      'Araliya RED — uno dei più prenotati della zona, 4/5 con quasi 2.000 recensioni: piscina riscaldata molto apprezzata, staff ospitale, vista sulla città dal rooftop. Qualche segnalazione di rumori dalle camere vicine e odore di gasolio all\'ingresso.\n\nEconomiche: Galaxy Grand Hotel, Star Gate Private Villa · fascia media: Jetwing St. Andrew\'s, Clifton Inn · lusso: Heritance Tea Factory, The Grand Hotel Nuwara Eliya.',
    doveMangiare: 'De Silva Food Center, Grand Indian, Grand Thai o Themparadu (il più locale); dopocena al Lakeview Pub.',
    comeArrivare: 'Trasferimento da Hatton/Nallathanniya via Pedro Tea Plantation.',
    comeSpostarsi: 'Van privato per Horton Plains, a piedi in città.',
    periodoMigliore: 'giornata di sole per il trekking a World\'s End',
    costi: 'Attività a Nuwara Eliya (massaggio, cerimonia del tè) 5.000-8.000 LKR.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Il trasferimento alla Pedro Tea Plantation si è rivelato molto più breve del previsto, un bel bonus per godersi di più il pomeriggio libero tra le vallate di tè verdissime attorno a Nuwara Eliya.',
    esperienzeSlugs: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Le vallate di tè verdi attorno a Nuwara Eliya, Sri Lanka',
    immagine: '/images/sri-lanka/nuwara-eliya-stock.jpg',
  },
  {
    slug: 'ella',
    paeseSlug: 'sri-lanka',
    ordine: 8,
    nome: 'Ella',
    tipologia: ['natura', 'avventura'],
    giorniConsigliati: '1 giorno, più il treno panoramico per arrivarci',
    visitataPersonalmente: true,
    introduzione: 'Il treno panoramico da Nuwara Eliya, il Nine Arches Bridge e i punti panoramici tra le colline da tè più fotografate dello Sri Lanka.',
    percheAndarci: 'Per il treno panoramico più famoso dell\'isola e per la concentrazione di punti panoramici a portata di mano dal villaggio.',
    cosaVedere: ['Il Nine Arches Bridge', 'Lipton\'s Seat', 'Le cascate dei Lover\'s Leap'],
    cosaFare: [
      'Treno panoramico Nuwara Eliya-Ella — vedi la scheda esperienza dedicata',
      'Zip line Flying Ravana (circa 20€, 15 minuti da Ella)',
      'Massaggio alla Spa Ceylon',
      'Cooking class con cena organizzata dal DMC',
    ],
    doveDormire:
      '88th Hotel — 4/5 su Tripadvisor, uno dei posti più raccomandati della zona: posizione centrale vicino a Ella Rock e Nine Arches Bridge, ospitalità calorosa. Attenzione alle aspettative: niente aria condizionata, niente ascensore, letto rigido con solo lenzuola.\n\nEconomiche: Ella Alpine Resort, Rock Side Inn · fascia media: Arawe Retreat, Zion View Ella Green Retreat · lusso: 98 Acres Resort & Spa, Nine Skies.',
    doveMangiare: 'Cooking class con cena del DMC; dopocena al One Love Ella (attenzione ai drink offerti al tavolo, spesso non inclusi nel conto).',
    comeArrivare: 'Treno panoramico da Nuwara Eliya (stazione di Nanu Oya), sulla carta 3 ore ma con orari reali imprevedibili.',
    comeSpostarsi: 'A piedi per i punti panoramici vicini al villaggio.',
    periodoMigliore: 'da confermare',
    costi: 'Zip line Flying Ravana circa 20€.',
    erroriDaEvitare: ['Prenotare i biglietti del treno panoramico con largo anticipo: vanno a ruba, soprattutto in alta stagione'],
    miaEsperienza:
      'Il treno panoramico è arrivato con ore di ritardo rispetto al previsto e senza alcun servizio di ristorazione a bordo, ma le vallate di tè a perdita d\'occhio viste dal finestrino restano tra le immagini più belle di tutto il viaggio: va preso con lo spirito giusto, i ritardi sono la norma.',
    esperienzeSlugs: ['treno-panoramico-ella'],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Il Nine Arches Bridge tra le piantagioni di tè di Ella, Sri Lanka',
    immagine: '/images/sri-lanka/ella-stock.jpg',
  },
  {
    slug: 'hikkaduwa',
    paeseSlug: 'sri-lanka',
    ordine: 9,
    nome: 'Hikkaduwa',
    tipologia: ['mare', 'relax'],
    giorniConsigliati: '2-3 giorni, incluso il safari a Yala lungo il tragitto',
    visitataPersonalmente: true,
    introduzione: 'Il safari al Parco Nazionale di Yala e le spiagge del sud, il contrappunto rilassato dopo giorni di templi e trekking.',
    percheAndarci: 'Per chiudere il viaggio con il mare, dopo la densità di templi, safari e trekking dei giorni precedenti.',
    cosaVedere: ['Il Parco Nazionale di Yala', 'Il Tsunami Museum'],
    cosaFare: [
      'Safari a Yala, il parco con la più alta densità di leopardi al mondo — vedi la scheda esperienza dedicata',
      'Nuoto con le tartarughe, il punto migliore davanti all\'Hikka Tranz by Cinnamon Hotel',
      'Tsunami Museum',
      'Big Buddha, surf, snorkeling, diving, boat safari sul fiume Madu',
    ],
    doveDormire:
      'Sapphire Seas Beachfront Hotel — recensioni molto positive: hotel boutique proprio davanti al mare, camere spaziose e pulizia tra le più citate positivamente, descritto da alcuni come "un\'oasi" rispetto alle zone più trafficate di Hikkaduwa.\n\nEconomiche: Hilda Guest House, Amaroo Hikkaduwa · fascia media: Sea Star Boutique Hotel, Hikka Tranz by Cinnamon · lusso: Crystal Sands, Aditya Resort.',
    doveMangiare: 'Cena in spiaggia (provato il red snapper, servizio lento ma cena ottima); Steffi\'s Mandala (vegetariano) o Thambili Cafe per pranzo; Sea Salt Society o Canal View per cena.',
    comeArrivare: 'Circa 2h15-2h40 di trasferimento da Ella via il safari a Yala.',
    comeSpostarsi: 'A piedi in spiaggia.',
    periodoMigliore: 'novembre, anche se già inizio bassa stagione per le piogge sulla costa',
    costi: 'Safari a Yala 12.000-16.000 LKR a jeep + ingresso (27-30€ a persona) + mancia.',
    erroriDaEvitare: ['Diffidare dei "pescatori su palafitta" lungo la costa sud: ormai quasi sempre una messa in scena a pagamento per turisti'],
    miaEsperienza:
      'Dopo giorni densi di templi e trekking, le spiagge di Hikkaduwa sono state il contrappunto perfetto per chiudere il viaggio: il pesce rosso mangiato in spiaggia una sera, con il servizio lento e il mare a due passi, resta uno dei ricordi più veri di tutto lo Sri Lanka.',
    esperienzeSlugs: ['safari-yala'],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'La spiaggia di Hikkaduwa sulla costa sud dello Sri Lanka',
    immagine: '/images/sri-lanka/hikkaduwa-stock.jpg',
  },
]
