import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Thailandia" (src/content/viaggi/06-thailandia.md).
// A differenza degli altri Paesi, il markdown copre più viaggi nel tempo:
// un giro principale di 11 giorni (Bangkok-Hua Hin-Chumphon-Khao Sok-Krabi-
// Koh Phi Phi-Bangkok) più zone visitate in viaggi separati (Bangkok più
// volte, Chiang Mai, Phuket/Similan). Il Golfo di Thailandia (Koh Samui,
// Koh Phangan, Koh Tao) non è mai stato visitato di persona: il markdown lo
// tratta in voce guida generica, per questo resta visitataPersonalmente: false.

export const destinazioniThailandia: Destinazione[] = [
  {
    slug: 'bangkok',
    paeseSlug: 'thailandia',
    ordine: 1,
    nome: 'Bangkok',
    tipologia: ['città', 'cibo', 'nightlife'],
    giorniConsigliati: '2-3 giorni, in più viaggi diversi',
    visitataPersonalmente: true,
    introduzione: 'Rooftop bar, templi, street food da stella Michelin e vita notturna in tutte le sue forme, visitata più volte nel corso di diversi viaggi in Thailandia.',
    percheAndarci: 'Il punto di ingresso quasi obbligato di ogni viaggio in Thailandia, con abbastanza varietà da meritare più visite nel tempo.',
    cosaVedere: [
      'Il Grand Palace e il Wat Phra Kaew',
      'Wat Pho, con il grande Buddha sdraiato dorato',
      'Wat Arun, il Tempio dell\'Alba',
      'Chatuchak Market, il mercato più grande del sud-est asiatico',
    ],
    cosaFare: [
      'Rooftop bar al tramonto (Vertigo & Moon Bar, Lebua at State Tower, MahaNakhon SkyWalk)',
      'Street food da Jay Fai, l\'unica bancarella al mondo con stella Michelin — vedi la scheda esperienza dedicata',
      'Muay Thai dal vivo agli stadi Rajadamnern o Lumpinee',
      'Serata a Khao San Road',
      'Gita di giornata ad Ayutthaya',
    ],
    doveDormire: 'da completare — le fonti del viaggio non specificano un hotel fisso a Bangkok, visitata in più occasioni diverse.',
    doveMangiare: 'Jay Fai, Thipsamai (il pad thai più famoso), Nai Ek Roll Noodle a Chinatown, Charoen Saeng per il khao kha moo.',
    usciteSerali: 'Khao San Road per un\'atmosfera da backpacker; Thonglor/Ekkamai per locali più curati; Rot Fai Night Market e Asiatique The Riverfront per lo shopping serale.',
    comeArrivare: 'Volo internazionale su Bangkok (aeroporti BKK o Don Mueang).',
    comeSpostarsi: 'Grab per taxi e moto-taxi, barca per Wat Arun.',
    periodoMigliore: 'tutto l\'anno',
    costi: 'Grand Palace circa 500 baht; Wat Pho circa 200 baht; Wat Arun circa 100 baht.',
    erroriDaEvitare: ['Arrivare da Jay Fai prima delle 8:00 o prenotare via email con largo anticipo', 'Rispettare il dress code nei templi e nei rooftop bar (pantaloni lunghi, spalle coperte)'],
    miaEsperienza:
      'Bangkok è una città che si presta a essere rivista più volte: ogni visita ho scoperto una zona diversa, dallo street food di Chinatown ai rooftop bar di Sathorn, senza mai esaurire la lista di cose da fare.',
    esperienzeSlugs: ['jay-fai-bangkok'],
    tripSlugs: ['thailandia'],
    imageAlt: 'Il Wat Arun, il Tempio dell\'Alba, sul fiume Chao Phraya a Bangkok, Thailandia',
    immagine: '/images/thailandia/bangkok-stock.jpg',
  },
  {
    slug: 'hua-hin',
    paeseSlug: 'thailandia',
    ordine: 2,
    nome: 'Hua Hin',
    tipologia: ['mare', 'mercati'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Tappa del giro principale tra Bangkok e il sud, con il mercato galleggiante, il mercato del treno e mercati serali di street food.',
    percheAndarci: 'Una tappa intermedia comoda tra Bangkok e le mete del sud, con i classici mercati "instagrammabili" della Thailandia centrale.',
    cosaVedere: ['Il Floating Market', 'Il Train Market di Maeklong'],
    cosaFare: ['Visita al mercato galleggiante e al mercato del treno', 'Cena ai mercati serali: Cicada Market, Tamarind Market o Chatchai Market'],
    doveDormire: 'da completare — hotel non specificato nelle fonti del viaggio.',
    doveMangiare: 'Cicada Market, Tamarind Market o Chatchai Market, tutti mercati serali di street food.',
    comeArrivare: 'Van da Bangkok, con tappa ai mercati lungo il percorso.',
    comeSpostarsi: 'A piedi nei mercati.',
    periodoMigliore: 'mattina per i mercati, sera per il mercato serale',
    costi: 'da completare',
    erroriDaEvitare: [],
    miaEsperienza:
      'Il mercato galleggiante e il mercato del treno sono onestamente molto turistici, con prezzi gonfiati rispetto a un mercato locale qualunque — ma se è la prima volta in Thailandia vale comunque la pena farli: sono scorci curiosi e il treno che sfiora le bancarelle resta un\'esperienza genuinamente divertente.',
    esperienzeSlugs: [],
    tripSlugs: ['thailandia'],
    imageAlt: 'Barche colorate cariche di frutta al mercato galleggiante vicino a Bangkok, Thailandia',
    immagine: '/images/thailandia/hua-hin-stock.jpg',
  },
  {
    slug: 'sam-roi-yot-kui-buri',
    paeseSlug: 'thailandia',
    ordine: 3,
    nome: 'Sam Roi Yot e Kui Buri',
    tipologia: ['natura', 'trekking'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Il Parco Nazionale di Sam Roi Yot, con la Grotta di Phra Nakorn e il suo padiglione reale, e il safari a Kui Buri per bufali rossi ed elefanti selvatici.',
    percheAndarci: 'Uno degli scorci più fotografati della Thailandia (la grotta) unito a un\'esperienza di safari onesta sui suoi limiti.',
    cosaVedere: ['La spiaggia di Laem Sala', 'La Grotta di Phra Nakorn, con il padiglione reale illuminato dall\'alto'],
    cosaFare: [
      'Trekking o barca fino alla spiaggia di Laem Sala',
      'Escursione nella foresta di sabbia fino alla Grotta di Phra Nakorn',
      'Safari al Kui Buri National Park per bufali rossi ed elefanti selvatici',
    ],
    doveDormire: 'Non ho pernottato qui: tappa di passaggio verso Chumphon.',
    doveMangiare: 'Pranzo verso mezzogiorno, dopo il relax in spiaggia.',
    comeArrivare: 'Van da Hua Hin, mattina presto.',
    comeSpostarsi: 'Barca (15 min) o trekking (40 min) per Laem Sala; veicolo dedicato per il safari a Kui Buri.',
    periodoMigliore: 'mattina, per la luce migliore nella Grotta di Phra Nakorn',
    costi: 'Ingresso Sam Roi Yot 200 THB a persona; Kui Buri 1.050 THB a persona.',
    erroriDaEvitare: ['Non aspettarsi un safari "africano": gli animali a Kui Buri si vedono spesso solo da lontano, a volte non si vedono affatto'],
    miaEsperienza:
      'La Grotta di Phra Nakorn, con la luce che filtra dall\'alto sul padiglione reale, è stata una delle sorprese più belle di questo tratto di viaggio — uno degli scorci più fotografati della Thailandia per un buon motivo.',
    esperienzeSlugs: [],
    tripSlugs: ['thailandia'],
    imageAlt: 'Il padiglione reale illuminato dall\'alto nella Grotta di Phra Nakorn, Sam Roi Yot, Thailandia',
    immagine: '/images/thailandia/sam-roi-yot-stock.jpg',
  },
  {
    slug: 'khao-sok',
    paeseSlug: 'thailandia',
    ordine: 4,
    nome: 'Khao Sok',
    tipologia: ['natura', 'giungla'],
    giorniConsigliati: '2 giorni, 1 notte sul lago',
    visitataPersonalmente: true,
    introduzione: 'La giungla pluviale più antica del mondo e il lago Cheow Lan, con le sue torri calcaree che emergono dall\'acqua, spesso paragonato a una piccola Guilin.',
    percheAndarci: 'Uno degli scenari più spettacolari di tutta la Thailandia, vissuto con una notte in un resort galleggiante sul lago.',
    cosaVedere: ['Il lago Cheow Lan e le sue formazioni calcaree', 'Il resort galleggiante sul lago'],
    cosaFare: [
      'Attività opzionali nella giungla: elephant safari, bamboo rafting, night safari, trekking',
      'Pacchetto "2 giorni 1 notte" sul lago con crociera al tramonto',
    ],
    doveDormire:
      'Smiley Bungalows (base a terra) e una notte in resort galleggiante essenziale sul lago Cheow Lan (niente copertura telefonica garantita, wifi solo a volte in reception).',
    doveMangiare: 'Bamboo Bistro Khao Sok.',
    comeArrivare: 'Van da Chumphon, circa 4h30 con due soste.',
    comeSpostarsi: 'Barca sul lago (circa 1h30 di navigazione).',
    periodoMigliore: 'stagione secca',
    costi: 'Ingresso al parco 220 THB a persona; mancia opzionale per guida/autista circa 500 baht per auto.',
    erroriDaEvitare: ['Prenotare le attività tramite l\'hotel con almeno 24h di anticipo, mai con fornitori esterni non autorizzati', 'Rispettare le regole del resort galleggiante: niente rumore dopo cena, niente birra portata da fuori'],
    miaEsperienza:
      'La crociera al tramonto sul lago Cheow Lan, tra le formazioni calcaree che emergono dall\'acqua, è una delle esperienze più belle di tutta la Thailandia — la sistemazione sul resort galleggiante è essenziale, ma è parte del fascino di dormire in un posto così isolato.',
    esperienzeSlugs: ['crociera-cheow-lan'],
    tripSlugs: ['thailandia'],
    imageAlt: 'Le torri calcaree che emergono dal lago Cheow Lan a Khao Sok, Thailandia',
    immagine: '/images/thailandia/khao-sok-stock.jpg',
  },
  {
    slug: 'krabi',
    paeseSlug: 'thailandia',
    ordine: 5,
    nome: 'Krabi',
    tipologia: ['mare', 'avventura'],
    giorniConsigliati: '3 giorni',
    visitataPersonalmente: true,
    introduzione: 'Railay Beach, Bond Island e il giro in canoa nella baia di Phang Nga: la base più autentica di Phuket per esplorare il mare delle Andamane.',
    percheAndarci: 'Più autentica di Phuket, e punto di partenza per alcune delle escursioni più spettacolari del sud della Thailandia.',
    cosaVedere: ['Railay Beach e Phra Nang Beach', 'Koh Ta Poo (Bond Island) e Koh Ping Gun', 'Il villaggio di pescatori di Koh Panyee'],
    cosaFare: [
      'Barca verso Railay Beach e camminata fino a Phra Nang Beach',
      'Spettacolo gratuito di fuoco ad Ao Nang Beach',
      'Escursione di giornata intera a Bond Island e canoa fino a Tham Lot — vedi la scheda esperienza dedicata',
      'Visita alla Monkey Cave e relax alle cascate',
    ],
    doveDormire: 'da completare — hotel non specificato nelle fonti del viaggio.',
    doveMangiare: 'Last Fisherman, Sea Salt Krabi Restaurant, Reeve Beach Club Krabi.',
    usciteSerali: 'Carlito\'s o Slinky (più disco).',
    comeArrivare: 'Da Khao Sok: 1h di barca + 2h di strada.',
    comeSpostarsi: 'Barca per Railay Beach e le escursioni, a piedi in città.',
    periodoMigliore: 'novembre-aprile, stagione secca',
    costi: 'Barca per Railay 200 THB a tratta.',
    erroriDaEvitare: [],
    miaEsperienza:
      'Bond Island vista dal vivo, con le sue rocce a fungo che emergono dall\'acqua, sembra ancora più scenografica che nel film da cui prende il soprannome — uno dei panorami più belli di tutto il viaggio nel sud.',
    esperienzeSlugs: ['bond-island-canoa'],
    tripSlugs: ['thailandia'],
    imageAlt: 'Le formazioni rocciose calcaree di Railay Beach vicino a Krabi, Thailandia',
    immagine: '/images/thailandia/krabi-stock.jpg',
  },
  {
    slug: 'koh-phi-phi',
    paeseSlug: 'thailandia',
    ordine: 6,
    nome: 'Koh Phi Phi',
    tipologia: ['isole', 'nightlife'],
    giorniConsigliati: '2 giorni',
    visitataPersonalmente: true,
    introduzione: 'L\'isola resa celebre dal film The Beach, tra baie spettacolari, vita notturna concentrata a Tonsai Village e il turismo di massa che si fa sentire soprattutto in alta stagione.',
    percheAndarci: 'Uno scenario da cartolina, per chi cerca un mix di paesaggio, vita da isola e serate più che il mare più incontaminato in assoluto.',
    cosaVedere: ['Maya Bay, la baia del film The Beach, riaperta con accessi contingentati', 'Il punto panoramico sull\'isola'],
    cosaFare: [
      'Gita in barca a Bamboo Island',
      'Diving con Blue View Divers',
      'Serata al Reggae Bar, con incontri amatoriali di Muay Thai',
    ],
    doveDormire: 'da completare — hotel non specificato nelle fonti del viaggio.',
    doveMangiare: 'Dow Restaurant o ACQUA Restaurant.',
    usciteSerali: 'Reggae Bar o Backpacker Bar.',
    comeArrivare: 'Traghetto da Ao Nopparat Thara Pier (Krabi), circa 2h30.',
    comeSpostarsi: 'A piedi a Tonsai Village, barca per le altre baie.',
    periodoMigliore: 'novembre-aprile',
    costi: 'da completare',
    erroriDaEvitare: ['Fare il check-in al traghetto almeno 30 minuti prima della partenza'],
    miaEsperienza:
      'Nonostante il turismo di massa evidente soprattutto a Tonsai Village, la vista dall\'alto sul punto panoramico resta uno scenario pazzesco, capace di far capire perché l\'isola sia diventata così iconica.',
    esperienzeSlugs: [],
    tripSlugs: ['thailandia'],
    imageAlt: 'Le baie di Koh Phi Phi viste dal punto panoramico, Thailandia',
    immagine: '/images/thailandia/koh-phi-phi-stock.jpg',
  },
  {
    slug: 'chiang-mai',
    paeseSlug: 'thailandia',
    ordine: 7,
    nome: 'Chiang Mai',
    tipologia: ['cultura', 'natura', 'montagna'],
    giorniConsigliati: '3-4 giorni, viaggio separato dal giro principale',
    visitataPersonalmente: true,
    introduzione: 'Il nord culturale della Thailandia: templi nella Città Vecchia, il Doi Suthep arroccato sulla montagna e un santuario etico degli elefanti.',
    percheAndarci: 'Un\'atmosfera completamente diversa da Bangkok e dal sud: più lenta, più verde, più "montagna".',
    cosaVedere: [
      'Wat Phra Singh, Wat Chedi Luang e Wat Sri Suphan nella Città Vecchia',
      'Wat Phra That Doi Suthep, con la scalinata di 300 gradini fiancheggiata da naga',
      'Wat Pha Lat, il tempio "nascosto" nella giungla',
    ],
    cosaFare: [
      'Visita a un santuario etico degli elefanti come l\'Elephant Nature Park — vedi la scheda esperienza dedicata',
      'Mercati notturni: Night Bazaar e Sunday Walking Street Market',
      'Corso di cucina thailandese con visita al mercato locale',
      'Escursione al Doi Inthanon National Park',
    ],
    doveDormire: 'da completare — hotel non specificato nelle fonti del viaggio.',
    doveMangiare: 'Quartiere di Nimman per caffetterie di specialità; mercati notturni per street food del nord.',
    usciteSerali: 'Night Bazaar tutte le sere; Sunday Walking Street Market la domenica.',
    comeArrivare: 'Volo interno da Bangkok.',
    comeSpostarsi: 'Songthaew, moto o tour organizzato per il Doi Suthep.',
    periodoMigliore: 'novembre-febbraio, stagione fresca e secca',
    costi: 'da completare',
    erroriDaEvitare: ['Verificare sempre l\'eticità dei santuari degli elefanti prima di prenotare: non tutti quelli che si definiscono "santuari" lo sono davvero'],
    miaEsperienza:
      'Il contrasto con Bangkok e il sud è netto fin dal primo giorno: Chiang Mai ha un ritmo più lento, e la mattinata passata con gli elefanti dell\'Elephant Nature Park, senza mai cavalcarli, resta uno dei ricordi più belli di tutta la Thailandia.',
    esperienzeSlugs: ['elephant-nature-park'],
    tripSlugs: ['thailandia'],
    imageAlt: 'Il tempio Wat Phra That Doi Suthep arroccato sulla montagna sopra Chiang Mai, Thailandia',
    immagine: '/images/thailandia/chiang-mai-stock.jpg',
  },
  {
    slug: 'phuket-similan',
    paeseSlug: 'thailandia',
    ordine: 8,
    nome: 'Phuket e Isole Similan',
    tipologia: ['mare', 'isole'],
    giorniConsigliati: '3-4 giorni, viaggio separato',
    visitataPersonalmente: true,
    introduzione: 'Il grande hub del sud-ovest e, al largo, il parco marino disabitato delle Similan: probabilmente il miglior snorkeling/diving raggiungibile in giornata in tutta la Thailandia.',
    percheAndarci: 'Per il mare più bello del paese, in un parco marino protetto senza hotel né vita notturna.',
    cosaVedere: ['Le spiagge di Patong, Kata e Karon a Phuket', 'Le acque cristalline e il granito bianco delle Isole Similan'],
    cosaFare: [
      'Gita in barca alle Isole Similan da Phuket o Khao Lak — vedi la scheda esperienza dedicata',
      'Snorkeling e diving alle Similan',
      'Vita notturna a Patong',
    ],
    doveDormire: 'da completare — hotel non specificato nelle fonti del viaggio.',
    doveMangiare: 'da completare',
    usciteSerali: 'Patong per la vita notturna.',
    comeArrivare: 'Volo su Phuket, aeroporto internazionale.',
    comeSpostarsi: 'Tour organizzato in barca per le Similan.',
    periodoMigliore: 'novembre-metà maggio, le Similan chiudono da metà maggio a metà ottobre',
    costi: 'da completare',
    erroriDaEvitare: ['Pianificare la visita alle Similan con calendario alla mano: il parco chiude a stagione'],
    miaEsperienza:
      'La differenza con Koh Phi Phi si sente subito: alle Similan non ci sono hotel né folla, solo acqua cristallina e la migliore barriera corallina della costa andamana. Se l\'obiettivo è il mare in sé, vincono loro.',
    esperienzeSlugs: ['snorkeling-similan'],
    tripSlugs: ['thailandia'],
    imageAlt: 'Le acque cristalline e le rocce di granito bianco delle Isole Similan, Thailandia',
    immagine: '/images/thailandia/similan-stock.jpg',
  },
  {
    slug: 'golfo-thailandia',
    paeseSlug: 'thailandia',
    ordine: 9,
    nome: 'Golfo di Thailandia: Koh Samui, Koh Phangan, Koh Tao',
    tipologia: ['isole', 'nightlife'],
    giorniConsigliati: 'da valutare',
    visitataPersonalmente: false,
    introduzione: 'Le tre isole del Golfo di Thailandia, con stagioni sfasate rispetto al mare delle Andamane: Koh Samui più comoda, Koh Phangan nota per il Full Moon Party, Koh Tao il paradiso dei sub.',
    percheAndarci: 'Un\'alternativa quando le Andamane sono in stagione delle piogge, o per il Full Moon Party su Koh Phangan.',
    cosaVedere: ['Le spiagge di Koh Samui', 'Thong Nai Pan, il lato tranquillo di Koh Phangan'],
    cosaFare: [
      'Full Moon Party a Haad Rin, Koh Phangan — vedi la scheda esperienza dedicata',
      'Brevetto PADI a Koh Tao',
      'Relax nei resort di Koh Samui',
    ],
    doveDormire: 'da completare',
    doveMangiare: 'da completare',
    comeArrivare: 'Volo su Koh Samui (aeroporto sull\'isola), poi traghetto per Koh Phangan e Koh Tao.',
    comeSpostarsi: 'Traghetti tra le tre isole, songthaew su Koh Phangan.',
    periodoMigliore: 'gennaio-aprile e luglio-settembre',
    costi: 'da completare',
    erroriDaEvitare: ['Diffidare di chi vende "biglietti" online per il Full Moon Party: si paga solo in contanti ai cancelli della spiaggia'],
    esperienzeSlugs: ['full-moon-party'],
    tripSlugs: [],
    imageAlt: 'Spiaggia tropicale su un\'isola del Golfo di Thailandia',
    immagine: '/images/thailandia/koh-phangan-stock.jpg',
  },
]
