import type { Destinazione } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Transilvania Express in 5 giorni" (src/content/viaggi/10-transilvania-express.md).

export const destinazioniTransilvania: Destinazione[] = [
  {
    slug: 'bucarest',
    paeseSlug: 'transilvania',
    ordine: 1,
    nome: 'Bucarest',
    tipologia: ['città', 'storia'],
    giorniConsigliati: '1 giorno all\'arrivo, 1-2 al rientro',
    visitataPersonalmente: true,
    introduzione: 'Il punto di arrivo e di rientro del viaggio: il Palazzo del Parlamento, il quartiere storico di Lipscani e, all\'ultimo giorno, le Terme.',
    percheAndarci: 'Per il Palazzo del Parlamento, il secondo edificio più grande al mondo dopo il Pentagono, e l\'atmosfera del centro storico di Lipscani.',
    cosaVedere: ['Il Palazzo del Parlamento', 'Il Romanian Athenaeum', 'Il quartiere storico di Lipscani'],
    cosaFare: [
      'Visita guidata al Palazzo del Parlamento — vedi la scheda esperienza dedicata',
      'Walking tour serale con guida locale',
      'Cena tipica da Caru\' cu Bere, con spettacoli folk',
      'Terme di Bucarest l\'ultimo giorno — vedi la scheda esperienza dedicata',
    ],
    doveDormire:
      'Arrivo: Hotel Duke Romana (zona Piața Romană), un 3 stelle con recensioni miste ma nel complesso positive: colazione buona, letti comodi e buon rapporto qualità-prezzo, con qualche lamentela sulle camere mansardate. Rientro: Hotel Continental Forum (zona Palazzo del Parlamento), un 4 stelle rinnovato nel 2021, con recensioni decisamente positive su colazione, staff e camere.\n\nAlternative arrivo: economiche: Hello Hotels Bucharest, Trianon Hotel · fascia media: Casa Mendeleev · lusso (contenuto): Epoque Hotel, Grand Hotel Continental.\n\nAlternative rientro: economiche: Hotel Parliament, Volo Hotel Bucharest · fascia media: Filitti Boutique Hotel · lusso (contenuto): Radisson Blu Hotel Bucharest, JW Marriott Bucharest Grand Hotel.',
    doveMangiare: 'Caru\' cu Bere per la cena di benvenuto; Hanu\' lui Manuc o Excalibur per la cena di arrivederci.',
    usciteSerali: 'Il quartiere di Lipscani, pieno di bar e locali con musica fino a tardi; Freddo, St. Patrick, il giardino di Grădina Dorobanți.',
    comeArrivare: 'Volo internazionale su Bucarest; taxi dall\'aeroporto (tariffa non oltre 60 LEI con Cobălcescu o Cris Taxi).',
    comeSpostarsi: 'A piedi in centro, Uber/Bolt/taxi per il resto.',
    periodoMigliore: 'ponte di Halloween/inizio novembre',
    costi: 'Palazzo del Parlamento circa 12,5€/pax; Romanian Athenaeum 2€/pax; Terme 35€ per l\'intera giornata.',
    erroriDaEvitare: ['Prelevare contante appena atterrati: molti ristoranti tipici accettano solo lei in contanti'],
    miaEsperienza:
      'Il Palazzo del Parlamento, con le sue dimensioni fuori scala, dà subito l\'idea della megalomania del regime di Ceaușescu prima ancora di entrare: una delle visite guidate più impressionanti del viaggio.',
    esperienzeSlugs: ['palazzo-parlamento', 'terme-bucarest'],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Il Palazzo del Parlamento di Bucarest, Romania',
    immagine: '/images/transilvania/bucarest-stock.jpg',
  },
  {
    slug: 'peles-bran',
    paeseSlug: 'transilvania',
    ordine: 2,
    nome: 'Castello di Peleș e Castello di Bran',
    tipologia: ['storia', 'castelli'],
    giorniConsigliati: '1 giorno',
    visitataPersonalmente: true,
    introduzione: 'Il Castello di Peleș, forse il più bello architettonicamente di tutto il viaggio, e il Castello di Bran, il celebre "Castello di Dracula".',
    percheAndarci: 'Per vedere due dei castelli più famosi di Romania nella stessa giornata, in un contrasto tra lo sfarzo neorinascimentale di Peleș e l\'aria gotica di Bran.',
    cosaVedere: [
      'Il Castello di Peleș, residenza estiva di Carlo I con oltre 160 stanze',
      'Il Monastero di Sinaia',
      'Il Castello di Bran, la fortezza medievale del XIII secolo',
      'Il Castello di Cantacuzino (sosta fotografica facoltativa)',
    ],
    cosaFare: [
      'Visita al Castello di Peleș (primo e secondo piano) — vedi la scheda esperienza dedicata',
      'Visita al Castello di Bran — vedi la scheda esperienza dedicata',
    ],
    doveDormire: 'Non ho pernottato qui: tappa di passaggio tra Bucarest e Brașov.',
    doveMangiare: 'Restaurant Bucegi (terrazza) a Sinaia, o pranzo al sacco/street food per guadagnare tempo.',
    comeArrivare: 'Circa 2h di auto da Bucarest a Sinaia, poi circa 1h da Sinaia a Bran.',
    comeSpostarsi: 'Auto a noleggio.',
    periodoMigliore: 'mattina, per evitare la ressa ai castelli',
    costi: 'Peleș circa 20€/pax (primo e secondo piano); Bran biglietti acquistabili online, guida ufficiale 30-40 minuti in contanti in loco.',
    erroriDaEvitare: ['Attenzione ai prezzi delle bancarelle e dei ristoranti intorno al Castello di Bran: vere e proprie trappole per turisti'],
    miaEsperienza:
      'Peleș è probabilmente il castello più bello architettonicamente di tutto il viaggio, con un livello di dettaglio negli interni che Bran, per quanto affascinante, non ha. Il legame di Bran con Dracula resta più una costruzione turistica che una realtà storica, ma il castello vale comunque la visita di per sé.',
    esperienzeSlugs: ['castello-peles', 'castello-bran'],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Il Castello di Bran, il "Castello di Dracula", in Transilvania, Romania',
    immagine: '/images/copertine/transilvania-express.jpg',
  },
  {
    slug: 'brasov',
    paeseSlug: 'transilvania',
    ordine: 3,
    nome: 'Brașov',
    tipologia: ['storia', 'natura'],
    giorniConsigliati: '1 giorno e una notte',
    visitataPersonalmente: true,
    introduzione: 'La Fortezza di Râșnov in cima a una rocca, la scritta cittadina in stile hollywoodiano e il centro storico con Piața Sfatului e la Chiesa Nera.',
    percheAndarci: 'Per la Fortezza di Râșnov, molto meno affollata del Castello di Bran ma altrettanto suggestiva, con un\'atmosfera più epica che vampiresca.',
    cosaVedere: [
      'La Fortezza di Râșnov',
      'La scritta "RASNOV" in stile hollywoodiano',
      'Piața Sfatului e la Torre dell\'Orologio',
      'La Chiesa Nera (Biserica Neagră), la più grande chiesa gotica di Romania',
    ],
    cosaFare: ['Fortezza di Râșnov, a piedi o in cabinovia — vedi la scheda esperienza dedicata', 'Passeggiata nel centro storico'],
    doveDormire:
      'Curtea Brașoveana, una decina di minuti a piedi dal centro storico, tra le più apprezzate della città (9,4 su Booking su quasi 600 recensioni): staff estremamente disponibile, camere pulite, bel giardino.\n\nAlternative: economiche: Drachenhaus, Pensiunea Casa Cranta · fascia media: Vila Katharina · lusso (contenuto): Casa Wagner, Radisson Blu Aurum Hotel Brașov.',
    doveMangiare: 'Sergiana (zuppe fumanti in pagnotte scavate, stufati alla paprika) o Casa Românească; dopocena al Deane\'s Irish Pub & Grill o al Musik Cafe.',
    comeArrivare: 'Circa mezz\'ora di auto da Bran.',
    comeSpostarsi: 'A piedi o in cabinovia per la Fortezza di Râșnov.',
    periodoMigliore: 'tardo pomeriggio, per la luce sulla rocca',
    costi: 'da completare — prezzi di Sergiana non specificati nel diario, ma segnalati sopra la media per vino e palinka.',
    erroriDaEvitare: ['Prenotare per tempo i ristoranti tipici più piccoli'],
    miaEsperienza:
      'La Fortezza di Râșnov, con la scritta "RASNOV" in stile hollywoodiano visibile dalla rocca, ha un\'atmosfera più da Signore degli Anelli che da Dracula: una delle chicche meno turistiche di tutto il viaggio.',
    esperienzeSlugs: ['fortezza-rasnov'],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'La Fortezza di Râșnov su una rocca vicino a Brașov, Romania',
    immagine: '/images/transilvania/brasov-stock.jpg',
  },
  {
    slug: 'sighisoara-salina-turda',
    paeseSlug: 'transilvania',
    ordine: 4,
    nome: 'Sighișoara e Salina Turda',
    tipologia: ['storia', 'unesco'],
    giorniConsigliati: '1 giorno, il più lungo al volante (5 ore totali)',
    visitataPersonalmente: true,
    introduzione: 'Il borgo medievale UNESCO di Sighișoara, casa natale del Conte Dracula, e le spettacolari saline sotterranee di Salina Turda.',
    percheAndarci: 'Per Salina Turda, una delle attrazioni più spettacolari di tutto il viaggio, e per le vie acciottolate di Sighișoara.',
    cosaVedere: [
      'La Torre dell\'Orologio di Sighișoara',
      'La casa natale del Conte Dracula',
      'The Covered Stairway, la scalinata coperta in legno',
      'Il laghetto sotterraneo di Salina Turda',
      'Il villaggio sassone di Viscri, con la sua Chiesa Fortificata UNESCO (tappa facoltativa)',
    ],
    cosaFare: [
      'Salita alla Torre dell\'Orologio e alla casa natale di Dracula',
      'Salita alla parte alta della città lungo The Covered Stairway',
      'Visita a Salina Turda, con biliardino, ping pong e barchette sul laghetto — vedi la scheda esperienza dedicata',
      'Tappa facoltativa a Viscri e alla sua Chiesa Fortificata',
    ],
    doveDormire: 'Non ho pernottato qui: giornata di passaggio verso Sibiu.',
    doveMangiare: 'Gasthaus Altepost o Vlad Dracul Restaurant a Sighișoara.',
    comeArrivare: 'Circa 1h20 da Brașov a Viscri, poi verso Sighișoara; circa 2h di auto da Sighișoara a Salina Turda.',
    comeSpostarsi: 'Auto a noleggio; a piedi nei centri storici.',
    periodoMigliore: 'partenza presto: è la giornata più lunga al volante del viaggio',
    costi: 'Viscri 12 LEI/pax; casa natale di Dracula 5 LEI; Salina Turda 10€ nei giorni feriali, 12€ nel weekend; guida a Salina Turda 100 LEI in contanti.',
    erroriDaEvitare: ['Rispettare rigorosamente le tempistiche: è la giornata più lunga al volante di tutto il viaggio (5 ore totali)'],
    miaEsperienza:
      'Salina Turda è stata una delle sorprese più belle del viaggio: scendere nella salina sotterranea e trovare un laghetto navigabile e persino un biliardino è qualcosa che non mi aspettavo da una miniera di sale.',
    esperienzeSlugs: ['salina-turda'],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Le case colorate e le vie acciottolate del centro storico di Sighișoara, Romania',
    immagine: '/images/transilvania/sighisoara-stock.jpg',
  },
  {
    slug: 'sibiu-transfagarasan',
    paeseSlug: 'transilvania',
    ordine: 5,
    nome: 'Sibiu e Transfăgărășan',
    tipologia: ['storia', 'natura', 'strada panoramica'],
    giorniConsigliati: '1 giorno, con lungo tratto di guida (fino a 3h45 non-stop)',
    visitataPersonalmente: true,
    introduzione: 'Il centro storico UNESCO di Sibiu e la Transfăgărășan, una delle strade panoramiche più famose al mondo, con tornanti fino a 2.000 metri di quota.',
    percheAndarci: 'Per la Transfăgărășan in sé, con il Lago Bâlea e la possibilità (rara) di avvistare orsi lungo la strada.',
    cosaVedere: [
      'Piața Mare e il Museo Brukenthal a Sibiu',
      'Il Ponte delle Bugie (Podul Minciunilor)',
      'I tornanti della Transfăgărășan fino al Lago Bâlea',
      'La Diga di Vidraru',
    ],
    cosaFare: [
      'City tour di Sibiu con guida locale (2h)',
      'Percorrere la Transfăgărășan — vedi la scheda esperienza dedicata',
      'Sosta al Balea Lac Restaurant sul Lago Bâlea',
    ],
    doveDormire:
      'MyContinental Sibiu, struttura moderna vicino al centro storico (8,5 su Booking): camere ai piani alti con vista sulla città e colazione abbondante i punti più citati, con qualche lamentela su wifi lento e ascensori.\n\nAlternative: economiche: Casa Timpuri Vechi, Pensiunea Central Sibiu · fascia media: Casa Luxemburg · lusso (contenuto): Noblesse Boutique Hotel, Mina Luxury Boutique Hotel.',
    doveMangiare: 'Crama Sibiul Vechi (cantina rustica, pochi tavoli, prenotazione obbligatoria), La Dobrun o Crama Ileana; dopocena Oldie\'s Pub o Geea Caffe.',
    comeArrivare: 'Circa 1h30 di auto da Salina Turda a Sibiu.',
    comeSpostarsi: 'Auto a noleggio per la Transfăgărășan, a piedi nel centro di Sibiu.',
    periodoMigliore: '20 giugno - 31 ottobre, quando la Transfăgărășan è percorribile in auto',
    costi: 'da completare.',
    erroriDaEvitare: ['Verificare l\'apertura della Transfăgărășan sul sito ufficiale prima di partire', 'Non dare da mangiare agli orsi né scendere dall\'auto se se ne avvista uno'],
    miaEsperienza:
      'La Transfăgărășan mantiene esattamente la fama che si porta dietro: i tornanti che salgono fino al Lago Bâlea sono uno degli scenari di guida più belli che abbia mai visto, anche se il lungo rientro a Bucarest lo stesso giorno si fa sentire.',
    esperienzeSlugs: ['transfagarasan'],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'I tornanti della Transfăgărășan tra le montagne della Romania',
    immagine: '/images/transilvania/transfagarasan-stock.jpg',
  },
]
