import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Bulgaria on the snow" (src/content/viaggi/11-bulgaria-bansko-rila.md).

export const esperienzeBulgaria: Esperienza[] = [
  {
    slug: 'sci-bansko',
    paeseSlug: 'bulgaria',
    destinazioneSlug: 'bansko',
    nome: 'Sci sulle piste di Bansko Ski Zone',
    localita: 'Bansko',
    cosE: 'Circa 70-75 km di piste distribuite su tre stazioni (Bunderishka Polyana, Chalin Valog e Shiligarnika), collegate da una gondola a 8 posti che sale da 990 a 1.660 metri, fino a un\'altitudine massima di 2.560 metri sul Todorka Peak.',
    percheFarla: 'Un comprensorio onesto ma senza pretese, con impianti moderni, code quasi inesistenti rispetto alle Alpi e prezzi molto più bassi.',
    durata: '3 giorni pieni',
    periodo: '1 dicembre - metà aprile',
    costo: 'skipass giornaliero 35-40€ (scontato fino al 25% acquistando online), noleggio attrezzatura a prezzi bassi nei negozi del centro',
    comePrenotare: 'skipass online in anticipo per lo sconto',
    cosaPortare: 'abbigliamento tecnico da sci/snowboard, strati termici',
    perChiEAdatta: 'tutti i livelli: piste blu per principianti, diverse rosse, due nere tra cui quella del Todorka',
    miaEsperienza:
      'Il livello del comprensorio è onesto ma senza pretese, niente a che vedere con le grandi stazioni alpine, ma perfetto per qualche giorno rilassato con impianti moderni e code quasi inesistenti.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['bulgaria-bansko-rila'],
    imageAlt: 'Sciatori sulle piste innevate di Bansko, Bulgaria',
  },
  {
    slug: 'discesa-notturna-bansko',
    paeseSlug: 'bulgaria',
    destinazioneSlug: 'bansko',
    nome: 'Discesa illuminata per lo sci notturno',
    localita: 'Bansko',
    cosE: 'Una lunga pista a valle di circa 7,5 km che scende fino al centro di Bansko, illuminata una volta a settimana per lo sci notturno.',
    percheFarla: 'Il momento più suggestivo delle giornate sulla neve: sciare di sera con le luci del centro storico che si avvicinano man mano si scende.',
    durata: 'una sera, controllare il calendario settimanale',
    periodo: 'stagione sciistica, dicembre-aprile',
    costo: 'incluso nello skipass',
    comePrenotare: 'nessuna prenotazione, verificare l\'orario settimanale di apertura serale',
    cosaPortare: 'strati caldi extra: le temperature scendono rapidamente al calare del sole',
    perChiEAdatta: 'sciatori di livello intermedio, vista la lunghezza della pista',
    miaEsperienza:
      'La discesa illuminata di 7,5 km fino al centro di Bansko resta il momento più suggestivo di tutte le giornate sulla neve: un\'esperienza che vale la pena programmare in anticipo.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['bulgaria-bansko-rila'],
    imageAlt: 'La pista illuminata per lo sci notturno che scende verso il centro di Bansko, Bulgaria',
  },
  {
    slug: 'visita-monastero-rila',
    paeseSlug: 'bulgaria',
    destinazioneSlug: 'monastero-rila',
    nome: 'Visita al Monastero di Rila',
    localita: 'Monastero di Rila',
    cosE: 'Il complesso monastico più importante di Bulgaria, con la Chiesa della Natività della Vergine a cinque cupole completamente ricoperta da affreschi, e il Museo di Storia Ecclesiastica con la celebre Croce di Rafail.',
    percheFarla: 'Il vero colpo di scena del viaggio, un contrasto totale con le giornate sulla neve appena trascorse.',
    durata: '2-3 ore',
    periodo: 'tutto l\'anno, lungo il tragitto di rientro verso Sofia',
    costo: 'ingresso al complesso e alla chiesa gratuito; Museo di Storia Ecclesiastica circa 8 BGN (4€)',
    comePrenotare: 'nessuna prenotazione necessaria',
    cosaPortare: 'abbigliamento che copra spalle e ginocchia',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Gli affreschi coloratissimi della Chiesa della Natività della Vergine, uniti al silenzio della montagna intorno al monastero, restano il ricordo più vivido di tutto il viaggio in Bulgaria, molto più delle giornate sulla neve stesse.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['bulgaria-bansko-rila'],
    imageAlt: 'Gli affreschi colorati della Chiesa della Natività della Vergine al Monastero di Rila, Bulgaria',
  },
]
