import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Costa Rica 360° in 13 giorni" (src/content/viaggi/12-costa-rica-360.md).

export const esperienzeCostaRica: Esperienza[] = [
  {
    slug: 'tour-cahuita',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'puerto-viejo',
    nome: 'Tour completo del Parco Nazionale di Cahuita',
    localita: 'Cahuita',
    cosE: 'Un tour guidato da José che unisce la passeggiata nel Parco Nazionale di Cahuita, il bagno in spiaggia, la visita alla comunità indigena Bribrì, un laboratorio di cioccolato tradizionale e una cascata finale.',
    percheFarla: 'Un\'esperienza culturale autentica, spesso sottovalutata rispetto alle attività più adrenaliniche del resto del viaggio.',
    durata: 'giornata intera',
    periodo: 'da organizzare con almeno una settimana d\'anticipo',
    costo: '50$ a persona, da pagare in contanti',
    comePrenotare: 'tramite la guida locale José, contattabile su WhatsApp',
    cosaPortare: 'scarpe da acqua, costume, repellente per zanzare, contanti',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il laboratorio di cioccolato con la comunità Bribrì, dove il capo villaggio racconta le proprietà delle piante tradizionali, è stata la chicca meno turistica di tutto il tour: un\'esperienza culturale che vale quanto (se non più) delle attività più adrenaliniche del resto del viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Il Parco Nazionale di Cahuita sulla costa caraibica della Costa Rica',
  },
  {
    slug: 'barca-tortuguero',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'tortuguero',
    nome: 'Navigazione in barca verso Tortuguero',
    localita: 'Moín - Tortuguero',
    cosE: 'Tre ore di navigazione in barca attraverso canali immersi nella giungla, con alte probabilità di avvistare coccodrilli, caimani, uccelli e scimmie lungo le rive.',
    percheFarla: 'Uno dei trasferimenti più belli del viaggio, uno spettacolo naturale in sé e non solo un modo per raggiungere la tappa successiva.',
    durata: '3 ore',
    periodo: 'tutto l\'anno',
    costo: 'incluso nel pacchetto, pranzo a bordo incluso',
    comePrenotare: 'organizzato dal DMC',
    cosaPortare: 'macchina fotografica, repellente per zanzare, cappello',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il tragitto in barca tra i canali di giungla, con scimmie e uccelli visibili dalle rive, è stato uno dei momenti più belli del viaggio, tutt\'altro che un semplice trasferimento.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Una barca che naviga tra i canali di giungla verso Tortuguero, Costa Rica',
  },
  {
    slug: 'kayak-tortuguero',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'tortuguero',
    nome: 'Kayak tra le mangrovie all\'alba',
    localita: 'Tortuguero',
    cosE: 'Due ore di kayak, singolo o doppio, tra i canali di Tortuguero prima dell\'alba, il momento migliore per avvistare la fauna selvatica.',
    percheFarla: 'La luce dell\'alba e il silenzio del kayak (rispetto al motore della barca) rendono più facile avvistare la fauna nei canali.',
    durata: '2 ore',
    periodo: 'prima dell\'alba',
    costo: 'incluso nel pacchetto',
    comePrenotare: 'organizzato dal DMC',
    cosaPortare: 'repellente per zanzare, cambio asciutto, macchina fotografica impermeabile',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Uscire in kayak prima dell\'alba, con i canali ancora silenziosi, ha dato una prospettiva completamente diversa sulla giungla rispetto al viaggio in barca del giorno prima.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Kayak tra le mangrovie dei canali di Tortuguero all\'alba, Costa Rica',
  },
  {
    slug: 'rafting-sarapiqui',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'sarapiqui',
    nome: 'Rafting sul fiume Sarapiquí',
    localita: 'Sarapiquí',
    cosE: 'Rafting sul fiume Sarapiquí, con soste per acqua e frutta lungo il percorso, un\'esperienza più regolare tutto l\'anno rispetto al più estremo Pacuaré.',
    percheFarla: 'Adatto anche a chi rafta per la prima volta, a differenza del Pacuaré che richiede più esperienza.',
    durata: 'mattinata, fino a mezzogiorno circa',
    periodo: 'tutto l\'anno',
    costo: 'incluso e prepagato nel pacchetto',
    comePrenotare: 'organizzato dal DMC',
    cosaPortare: 'costume, scarpe da acqua, cambio asciutto',
    perChiEAdatta: 'chiunque, anche alla prima esperienza di rafting',
    miaEsperienza:
      'A differenza del più estremo Pacuaré (fatto da alcuni del gruppo qualche giorno prima), il Sarapiquí è stato un\'esperienza più regolare e godibile, perfetta per chi rafta per la prima volta.',
    giudizio: 'la-rifarei',
    alternative: ['Pacuaré rafting, più estremo, da organizzare separatamente con una settimana d\'anticipo'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Un gommone da rafting sul fiume Sarapiquí, Costa Rica',
  },
  {
    slug: 'cascata-fortuna-termales',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'arenal',
    nome: 'Cascada de La Fortuna e sorgenti termali di El Choyin',
    localita: 'La Fortuna',
    cosE: 'La cascata più fotografata del paese, con una piscina naturale alla base, seguita dalle sorgenti termali gratuite di El Choyin nel tardo pomeriggio.',
    percheFarla: 'El Choyin è gratuita e molto più autentica delle terme "da spa" a pagamento della zona, come Termalitas de Arenal.',
    durata: 'mezza giornata',
    periodo: 'pomeriggio per le sorgenti termali',
    costo: 'Cascada de La Fortuna 18-20$; sorgenti di El Choyin gratuite',
    comePrenotare: 'ingresso alla cascata da pagare con la cassa comune, nessuna prenotazione per El Choyin',
    cosaPortare: 'scarpe da fiume, costume, torcia frontale in sacca impermeabile (niente asciugamani: può piovere e non ci sono spogliatoi)',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Le sorgenti termali gratuite di El Choyin, in un tratto di fiume naturale senza le infrastrutture delle terme a pagamento, sono state il momento più suggestivo e autentico di tutta la giornata ad Arenal.',
    giudizio: 'imperdibile',
    alternative: ['Termalitas de Arenal, a pagamento ma con servizi extra come il barbecue'],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Le sorgenti termali naturali di El Choyin vicino ad Arenal, Costa Rica',
  },
  {
    slug: 'camminata-notturna-monteverde',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'monteverde',
    nome: 'Camminata notturna nella foresta nebulosa',
    localita: 'Monteverde',
    cosE: 'Un tour guidato (Kinkajou Night Walk) di circa 1h30 nella foresta nebulosa di notte, per osservare la fauna che si muove solo dopo il tramonto.',
    percheFarla: 'Uno dei modi migliori per vedere una fauna completamente diversa da quella diurna, in un ambiente silenzioso e suggestivo.',
    durata: 'circa 1h30',
    periodo: 'sera',
    costo: '28$ a persona',
    comePrenotare: 'tramite il DMC o direttamente con Kinkajou Night Walk Tour',
    cosaPortare: 'torcia frontale, scarpe comode, giacca leggera',
    perChiEAdatta: 'chiunque, ma la durata non è piaciuta a tutti allo stesso modo',
    miaEsperienza:
      'La fauna notturna della foresta nebulosa, illuminata solo dalle torce del gruppo, crea un\'atmosfera molto diversa dal resto del viaggio: suggestiva, anche se la durata di 1h30 può risultare lunga per chi si aspettava qualcosa di più breve.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'La foresta nebulosa di Monteverde illuminata di notte, Costa Rica',
  },
  {
    slug: 'zipline-monteverde',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'monteverde',
    nome: 'Zipline avventura a Monteverde',
    localita: 'Monteverde',
    cosE: 'Le tirolesi di Monteverde, considerate tra le migliori del paese e più lunghe di quelle di La Fortuna, per circa 3 ore complessive.',
    percheFarla: 'Un\'esperienza adrenalinica sopra la foresta nebulosa, con la possibilità di fermarsi a metà per chi non se la sente di continuare.',
    durata: 'circa 3 ore',
    periodo: 'mattina presto o tarda mattinata',
    costo: 'circa 60$ a persona (rimborso 75% per chi si ferma dopo la terza linea)',
    comePrenotare: 'tramite il DMC',
    cosaPortare: 'scarpe chiuse, capelli legati, niente oggetti sciolti nelle tasche',
    perChiEAdatta: 'chiunque, con possibilità di fermarsi a metà percorso',
    miaEsperienza:
      'Le zipline di Monteverde, più lunghe di quelle già viste altrove nel paese, regalano una prospettiva dall\'alto sulla foresta nebulosa che nessun sentiero a terra può dare.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Una linea di zipline sopra la foresta nebulosa di Monteverde, Costa Rica',
  },
  {
    slug: 'whale-watching-uvita',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'uvita',
    nome: 'Whale watching a Uvita',
    localita: 'Uvita',
    cosE: 'Un\'escursione in barca di 3h30-4h per avvistare le balene al largo della costa pacifica di Uvita, con acqua e frutta incluse.',
    percheFarla: 'Uvita è uno dei pochi posti al mondo dove è possibile avvistare le balene in due stagioni diverse durante l\'anno.',
    durata: '3h30-4h',
    periodo: 'gennaio-marzo e luglio-ottobre sono le stagioni migliori; novembre-dicembre offre meno incontri',
    costo: '70$ a persona',
    comePrenotare: 'solo tramite il DMC, evitando fornitori locali senza assicurazione adeguata',
    cosaPortare: 'crema solare, cappello, macchina fotografica con zoom',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'L\'escursione era in programma come giornata dedicata dell\'itinerario, anche se nei documenti di viaggio non è annotato con certezza quante balene siano state effettivamente avvistate quel giorno: novembre non è comunque il mese migliore per l\'avvistamento a Uvita.',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Una barca per il whale watching al largo della costa di Uvita, Costa Rica',
  },
  {
    slug: 'parco-manuel-antonio',
    paeseSlug: 'costa-rica',
    destinazioneSlug: 'manuel-antonio',
    nome: 'Visita guidata al Parco Nazionale Manuel Antonio',
    localita: 'Manuel Antonio',
    cosE: 'Una visita guidata di 1-2 ore nel parco, per avvistare bradipi, scimmie, iguane e colibrì lungo i sentieri, seguita da tempo libero su una delle spiagge più belle del paese.',
    percheFarla: 'Tra le tappe più belle di tutto il Costa Rica, con altissima probabilità di avvistare fauna selvatica grazie all\'occhio esperto della guida.',
    durata: '1-2 ore di visita guidata, più tempo libero in spiaggia',
    periodo: 'mattina presto; il parco è chiuso il martedì',
    costo: 'incluso nel pacchetto',
    comePrenotare: 'organizzato dal DMC',
    cosaPortare: 'costume, scarpe comode, repellente per zanzare',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'La guida ha reso possibile avvistare bradipi, scimmie e iguane che da soli sarebbero stati praticamente impossibili da notare: una delle tappe più dense di fauna selvatica di tutto il viaggio, chiusa da una delle spiagge più belle del Costa Rica.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['costa-rica-360'],
    imageAlt: 'Un bradipo tra gli alberi del Parco Nazionale Manuel Antonio, Costa Rica',
  },
]
