import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Florida 360° in 10 giorni" (src/content/viaggi/09-florida-360.md).

export const esperienzeFlorida: Esperienza[] = [
  {
    slug: 'hemingway-home',
    paeseSlug: 'florida',
    destinazioneSlug: 'key-west-marathon',
    nome: 'Hemingway Home and Museum',
    localita: 'Key West',
    cosE: 'La casa dove visse Ernest Hemingway a Key West, con il suo studio e i giardini pieni dei celebri gatti a sei dita, discendenti del gatto originale dello scrittore.',
    percheFarla: 'Una delle attrazioni più iconiche di Key West, che unisce storia letteraria e un\'atmosfera più autentica rispetto alle vie più turistiche.',
    durata: '1 ora',
    periodo: 'tutto l\'anno',
    costo: '$17 (sconto da 12 persone in su prenotando)',
    comePrenotare: 'consigliata la prenotazione per gruppi numerosi',
    cosaPortare: 'macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'I gatti a sei dita che girano liberamente per il giardino sono una sorpresa piacevole anche per chi non conosce bene la storia di Hemingway: un\'ora ben spesa nel mezzo della giornata a Key West.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['florida-360'],
    imageAlt: 'Il giardino della Hemingway Home a Key West, Florida',
  },
  {
    slug: 'snorkeling-bahia-honda',
    paeseSlug: 'florida',
    destinazioneSlug: 'key-west-marathon',
    nome: 'Snorkeling a Bahia Honda State Park',
    localita: 'Bahia Honda, Florida Keys',
    cosE: 'Snorkeling sulla barriera corallina di Bahia Honda State Park, con un\'altra vista sulla Seven Mile Bridge dalla spiaggia.',
    percheFarla: 'Uno dei punti migliori delle Keys per lo snorkeling accessibile, in uno dei parchi statali più belli della Florida.',
    durata: 'mezza giornata',
    periodo: 'tutto l\'anno',
    costo: '$10/auto per l\'ingresso al parco, più $30 + noleggio maschera per il tour di snorkeling',
    comePrenotare: 'prenotare il tour del pomeriggio ed essere presenti entro mezzogiorno',
    cosaPortare: 'costume, asciugamano, crema solare',
    perChiEAdatta: 'chiunque sappia nuotare',
    miaEsperienza:
      'La vista sulla Seven Mile Bridge dalla spiaggia di Bahia Honda, con l\'acqua turchese in primo piano, è una delle inquadrature più belle di tutte le Keys.',
    giudizio: 'la-rifarei',
    alternative: ['Kayak a noleggio (18$/ora doppio, 12$/ora singolo)', 'Diving con Captain Hook Diving a Marathon (80-90$ + attrezzatura)'],
    tripSlugs: ['florida-360'],
    imageAlt: 'La spiaggia di Bahia Honda State Park con vista sulla Seven Mile Bridge, Florida Keys',
  },
  {
    slug: 'everglades-airboat',
    paeseSlug: 'florida',
    destinazioneSlug: 'everglades-naples',
    nome: 'Everglades Airboat Tour',
    localita: 'Everglades',
    cosE: 'Un tour in airboat attraverso le paludi delle Everglades, tra alligatori, uccelli e la vegetazione tipica di questo ecosistema unico.',
    percheFarla: 'Il modo più efficace e adrenalinico di esplorare una palude altrimenti inaccessibile, con alta probabilità di avvistare alligatori da vicino.',
    durata: 'circa 30-45 minuti di tour, mezza giornata considerando gli spostamenti',
    periodo: 'mattina presto, prima del caldo peggiore',
    costo: 'incluso nel GoCity Pass',
    comePrenotare: 'tramite gocity.com, presentando il pass alla biglietteria dell\'Everglades Alligator Farm',
    cosaPortare: 'repellente per zanzare, crema solare, giacca antipioggia, pantaloni lunghi',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il rumore dell\'airboat che sfreccia tra le canne e l\'acqua bassa, con gli alligatori che si vedono a pochi metri di distanza, rende le Everglades uno degli ecosistemi più impressionanti visti dal vivo.',
    giudizio: 'imperdibile',
    alternative: ['Shark Valley in bici o tram, su una strada chiusa alle auto'],
    tripSlugs: ['florida-360'],
    imageAlt: 'Un airboat che attraversa le paludi delle Everglades, Florida',
  },
  {
    slug: 'parco-tema-orlando',
    paeseSlug: 'florida',
    destinazioneSlug: 'orlando',
    nome: 'Giornata al parco a tema (Universal o Disney)',
    localita: 'Orlando',
    cosE: 'Una giornata intera in uno dei due grandi complessi di parchi a tema di Orlando: Universal Studios (con Islands of Adventure) o Disney World (con i suoi quattro parchi).',
    percheFarla: 'I parchi a tema più famosi al mondo, con attrazioni che vanno dai roller coaster più adrenalinici alle esperienze immersive come il mondo di Harry Potter.',
    durata: 'giornata intera, dall\'apertura fino allo show serale',
    periodo: 'tutto l\'anno, meglio evitare i giorni di massima affluenza',
    costo: 'Universal 130-210$ a seconda dei parchi scelti; Disney World da 250€ per minimo 2 giorni',
    comePrenotare: 'online con largo anticipo, anche tramite getyourguide.com per i biglietti cancellabili fino a 24h prima',
    cosaPortare: 'zaino piccolo (i grandi non entrano nei lockers), acqua, snack leggeri, scarpe comode',
    perChiEAdatta: 'chiunque, con qualche attenzione alle attrazioni più adrenaliniche per chi soffre il movimento',
    giudizio: 'da-verificare',
    alternative: ['Il complesso alternativo a quello scelto (Universal se si sceglie Disney, o viceversa)'],
    tripSlugs: [],
    imageAlt: 'Attrazioni illuminate di un parco a tema a Orlando, Florida',
  },
  {
    slug: 'kennedy-space-center',
    paeseSlug: 'florida',
    destinazioneSlug: 'cape-canaveral',
    nome: 'Kennedy Space Center',
    localita: 'Cape Canaveral',
    cosE: 'Il complesso della NASA a Cape Canaveral, con il Rocket Garden, la ricostruzione della control room dell\'Apollo/Saturn V, uno space shuttle vero nell\'Atlantis Building e un cinema IMAX.',
    percheFarla: 'Un complesso davvero impressionante, che racconta la storia della corsa allo spazio americana attraverso oggetti autentici, non solo ricostruzioni.',
    durata: 'almeno mezza giornata',
    periodo: 'controllare in anticipo se è previsto un lancio nel giorno della visita',
    costo: '$57',
    comePrenotare: 'acquistabile sul posto o online',
    cosaPortare: 'macchina fotografica, cappello per il caldo',
    perChiEAdatta: 'chiunque, particolarmente adatto anche alle famiglie',
    miaEsperienza:
      'Vedere il razzo Saturn V vero, enorme, dopo aver assistito alla ricostruzione della control room che lo lancia, rende concreta la scala della missione Apollo in un modo che nessuna foto rende davvero.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['florida-360'],
    imageAlt: 'Il razzo Saturn V esposto al Kennedy Space Center, Cape Canaveral, Florida',
  },
  {
    slug: 'speedboat-thriller-miami',
    paeseSlug: 'florida',
    destinazioneSlug: 'miami',
    nome: 'Speed Boat Tour "Thriller Miami"',
    localita: 'Miami',
    cosE: 'Un tour in motoscafo ad alta velocità lungo la baia di Miami, con vista sulle case dei vip e sullo skyline della città.',
    percheFarla: 'Un modo adrenalinico e scenografico di vedere Miami dall\'acqua, diverso dalla solita giornata in spiaggia.',
    durata: 'circa 1 ora',
    periodo: 'tutto l\'anno',
    costo: 'incluso nel GoCity Pass',
    comePrenotare: 'tramite gocity.com, presentandosi 45 minuti prima della partenza con liberatoria firmata (compilabile online in anticipo)',
    cosaPortare: 'costume, cambio asciutto, occhiali da sole con laccetto',
    perChiEAdatta: 'chiunque',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Un motoscafo veloce nella baia di Miami, Florida',
  },
  {
    slug: 'salsa-night-miami',
    paeseSlug: 'florida',
    destinazioneSlug: 'miami',
    nome: 'Salsa Night: lezioni, mojito e balli',
    localita: 'Miami',
    cosE: 'Una serata organizzata con lezioni di salsa, mojito e balli fino a tardi, dress code "glamour tropicale".',
    percheFarla: 'Un modo divertente e diverso di passare una serata a Miami, tra musica latina e atmosfera conviviale.',
    durata: 'una serata',
    periodo: 'tutto l\'anno',
    costo: 'incluso nel GoCity Pass, cena al tavolo a pagamento separato',
    comePrenotare: 'prenotazione obbligatoria in anticipo, info al numero di Salsa Mia',
    cosaPortare: 'abbigliamento "glamour tropicale": niente cappellini da baseball, canottiere o costumi da bagno',
    perChiEAdatta: 'chiunque, anche senza esperienza di ballo',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Coppie che ballano salsa in un locale di Miami',
  },
]
