import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Giappone in 12 giorni" (src/content/viaggi/05-giappone-360.md).
// chureito-monte-fuji è collegata a una giornata aggiunta editorialmente (non
// vissuta realmente): giudizio 'da-verificare', nessuna miaEsperienza, tripSlugs vuoto.

export const esperienzeGiappone: Esperienza[] = [
  {
    slug: 'sakura-chasing-tokyo',
    paeseSlug: 'giappone',
    destinazioneSlug: 'tokyo',
    nome: 'Sakura chasing a Tokyo',
    localita: 'Tokyo',
    cosE: 'Un giro tra i migliori punti di Tokyo per vedere i ciliegi in fiore: Chidorigafuchi, Shinjuku Gyoen, Ueno Park e il Meguro River.',
    percheFarla: 'La fioritura dei sakura è uno degli eventi naturali più iconici del Giappone, e ogni punto della città offre una prospettiva diversa.',
    durata: 'un pomeriggio',
    periodo: 'fine marzo-inizio aprile, con Shinjuku Gyoen la scelta più sicura anche a stagione inoltrata',
    costo: 'gratuito (Shinjuku Gyoen ha un piccolo ingresso)',
    comePrenotare: 'nessuna prenotazione necessaria',
    cosaPortare: 'macchina fotografica, scarpe comode',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Con qualche giorno di scarto rispetto al picco, i ciliegi di Tokyo erano già verso la fine, tra petali che cadevano come neve rosa (lo hanafubuki) e i rami più spogli. Un lato diverso, ma altrettanto bello, della fioritura.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Ciliegi in fiore lungo il canale del Meguro River a Tokyo, Giappone',
  },
  {
    slug: 'shibuya-crossing',
    paeseSlug: 'giappone',
    destinazioneSlug: 'tokyo',
    nome: 'Shibuya Crossing dall\'alto',
    localita: 'Tokyo',
    cosE: 'Il celebre incrocio pedonale di Shibuya visto dall\'alto, gratis dall\'ottavo piano dell\'Edificio del Centro per il Turismo o a pagamento dal rooftop Mag8.',
    percheFarla: 'Uno dei simboli più riconoscibili del Giappone contemporaneo, ancora più suggestivo di sera.',
    durata: '30-45 minuti',
    periodo: 'sera',
    costo: 'gratuito dall\'ottavo piano del Centro per il Turismo; 1.500 yen con drink incluso dal Mag8',
    comePrenotare: 'nessuna prenotazione per l\'opzione gratuita',
    cosaPortare: 'macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Vedere l\'incrocio dall\'alto, con il via vai costante di persone in ogni direzione, rende ancora più chiaro perché sia diventato uno dei simboli del Giappone urbano.',
    giudizio: 'imperdibile',
    alternative: ['Shibuya Scramble Square (14° piano, poi Sky Observatory), visto in un\'altra giornata del viaggio'],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Shibuya Crossing illuminato di sera, visto dall\'alto, Tokyo, Giappone',
  },
  {
    slug: 'chureito-monte-fuji',
    paeseSlug: 'giappone',
    destinazioneSlug: 'monte-fuji-chureito',
    nome: 'Pagoda Chureito con vista Monte Fuji',
    localita: 'Fujiyoshida',
    cosE: 'La salita di 398 gradini fino al punto panoramico più iconico del Giappone: la pagoda rossa a cinque piani in primo piano, il Monte Fuji sullo sfondo.',
    percheFarla: 'L\'immagine simbolo del Giappone, e un\'occasione per recuperare i sakura mancati a Tokyo, dato che la fioritura qui arriva con una settimana di ritardo.',
    durata: 'mezza giornata, incluso il trasferimento da Tokyo',
    periodo: 'metà aprile per i sakura in piena fioritura',
    costo: 'gratuito l\'accesso al parco',
    comePrenotare: 'nessuna prenotazione, treno o bus da prenotare per gli orari di punta',
    cosaPortare: 'scarpe comode per i 398 gradini',
    perChiEAdatta: 'chiunque',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'La Pagoda Chureito con il Monte Fuji sullo sfondo, Giappone',
  },
  {
    slug: 'fushimi-inari',
    paeseSlug: 'giappone',
    destinazioneSlug: 'kyoto',
    nome: 'Fushimi Inari',
    localita: 'Kyoto',
    cosE: 'Il santuario dei mille torii vermigli, con un percorso di 2h30 per il giro completo fino alla cima della montagna.',
    percheFarla: 'Uno dei luoghi più fotografati e riconoscibili del Giappone, spettacolare anche senza arrivare fino in vetta.',
    durata: '1-2h30 secondo quanto si vuole salire',
    periodo: 'presto al mattino, per evitare la folla',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione',
    cosaPortare: 'scarpe da cammino',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il primo tratto, quello fotografato da tutti, è spettacolare di per sé: non serve arrivare fino in cima per portarsi a casa l\'immagine simbolo di Fushimi Inari.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'La galleria di torii vermigli di Fushimi Inari, Kyoto, Giappone',
  },
  {
    slug: 'kinkaku-ji',
    paeseSlug: 'giappone',
    destinazioneSlug: 'kyoto',
    nome: 'Kinkaku-ji, il Tempio d\'Oro',
    localita: 'Kyoto',
    cosE: 'Il padiglione ricoperto di foglia d\'oro che si riflette nello stagno, uno dei simboli assoluti del Giappone.',
    percheFarla: 'Semplicemente iconico: una delle immagini più riconoscibili di tutto il Giappone.',
    durata: '45 minuti - 1 ora',
    periodo: 'apertura mattutina o tardo pomeriggio, per meno folla',
    costo: 'da completare',
    comePrenotare: 'nessuna prenotazione',
    cosaPortare: 'macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il riflesso del padiglione dorato nello stagno è uno di quei momenti che, per quanto già visti in mille foto, colpiscono comunque dal vivo.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Il padiglione dorato del Kinkaku-ji riflesso nello stagno, Kyoto, Giappone',
  },
  {
    slug: 'torii-miyajima',
    paeseSlug: 'giappone',
    destinazioneSlug: 'hiroshima-miyajima',
    nome: 'Il torii galleggiante di Miyajima',
    localita: 'Miyajima',
    cosE: 'Il celebre torii "galleggiante" sull\'acqua del Santuario Itsukushima, uno dei panorami più iconici del Giappone.',
    percheFarla: 'Un\'immagine simbolo del Giappone, ancora più suggestiva con l\'alta marea che fa sembrare il torii sospeso sull\'acqua.',
    durata: 'un pomeriggio, incluso il traghetto',
    periodo: 'alta marea, per l\'effetto "galleggiante" più marcato',
    costo: 'traghetto incluso nel JR Pass',
    comePrenotare: 'nessuna prenotazione per il traghetto standard',
    cosaPortare: 'macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Vedere il torii "galleggiante" nel pomeriggio, dopo la visita al Memoriale della Pace la mattina, ha dato alla giornata un equilibrio raro tra riflessione e meraviglia.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Il torii galleggiante del Santuario Itsukushima a Miyajima, Giappone',
  },
  {
    slug: 'cervi-nara',
    paeseSlug: 'giappone',
    destinazioneSlug: 'nara',
    nome: 'I cervi sacri di Nara',
    localita: 'Nara',
    cosE: 'I cervi sacri semi-liberi (Sika deer) che passeggiano tra i templi del Parco di Nara, avvicinandosi senza timore ai visitatori.',
    percheFarla: 'Un\'esperienza quasi surreale, unica nel suo genere in Giappone.',
    durata: '1-2 ore',
    periodo: 'mattina, per meno folla nel parco',
    costo: 'gratuito (i biscotti per i cervi si acquistano a parte)',
    comePrenotare: 'nessuna prenotazione',
    cosaPortare: 'attenzione a borse e mappe: i cervi possono provare a mangiarle',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Vedere i cervi passeggiare liberi tra i templi, senza timore dei visitatori, è stata una delle esperienze più surreali e piacevoli di tutto il viaggio in Giappone.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giappone-360'],
    imageAlt: 'Un cervo sacro semi-libero nel Parco di Nara, Giappone',
  },
]
