import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Giordania 360°" (src/content/viaggi/03-giordania-360.md),
// con il feedback diretto dell'autore su Amman, Mar Morto, Petra, Wadi Rum e il diving ad Aqaba.

export const esperienzeGiordania: Esperienza[] = [
  {
    slug: 'cittadella-amman',
    paeseSlug: 'giordania',
    destinazioneSlug: 'amman',
    nome: 'La Cittadella di Amman',
    localita: 'Amman',
    cosE: 'La collina storica nel cuore di Amman, con il Tempio di Ercole, il Palazzo Omayyade e vista panoramica su tutta la città vecchia.',
    percheFarla: 'Il modo più rapido per orientarsi sulla storia di Amman e avere un colpo d\'occhio su tutta la città vecchia.',
    durata: '1-2 ore',
    periodo: 'mattina o tardo pomeriggio, per la luce migliore sulla città',
    costo: 'incluso nel Jordan Pass',
    comePrenotare: 'nessuna prenotazione necessaria',
    cosaPortare: 'scarpe comode, cappello per il sole',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'La vista sulla città vecchia dalla Cittadella è carina, un buon modo per chiudere il viaggio prima del rientro, senza essere il momento più memorabile della Giordania.',
    giudizio: 'bella-non-essenziale',
    alternative: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Le colonne del Tempio di Ercole sulla Cittadella di Amman, Giordania',
  },
  {
    slug: 'bagno-mar-morto',
    paeseSlug: 'giordania',
    destinazioneSlug: 'mar-morto',
    nome: 'Bagno nel Mar Morto al tramonto',
    localita: 'Mar Morto',
    cosE: 'Il galleggiamento nelle acque iper-saline del punto più basso della Terra, con le colline della Cisgiordania sullo sfondo.',
    percheFarla: 'Un\'esperienza fisica impossibile da replicare altrove, ancora più suggestiva se vissuta al tramonto.',
    durata: '1-2 ore',
    periodo: 'tramonto',
    costo: 'incluso nel soggiorno in resort',
    comePrenotare: 'accesso diretto dalla spiaggia privata del resort',
    cosaPortare: 'costume, ciabatte (il fondale è roccioso), evitare di radersi nei giorni precedenti per il bruciore del sale',
    perChiEAdatta: 'chiunque, con qualche accortezza per chi ha tagli o irritazioni sulla pelle',
    miaEsperienza:
      'Galleggiare a pelo d\'acqua guardando il sole calare dietro le colline della Cisgiordania è stato un momento unico, uno di quelli che resta impresso più della media delle tappe "turistiche" del viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Galleggiamento nelle acque del Mar Morto al tramonto, Giordania',
  },
  {
    slug: 'salita-monastero-petra',
    paeseSlug: 'giordania',
    destinazioneSlug: 'petra',
    nome: 'Salita al Monastero (Ad-Deir)',
    localita: 'Petra',
    cosE: 'La camminata di oltre 800 gradini scolpiti nella roccia che porta al Monastero, il secondo grande monumento di Petra dopo il Tesoro.',
    percheFarla: 'Il Monastero è ancora più massiccio del Tesoro (45 metri di altezza per 50 di larghezza) e va visto per capire davvero l\'estensione di Petra oltre il Siq.',
    durata: '40-45 minuti di salita, più il tempo alla sommità',
    periodo: 'mattina, per evitare il caldo peggiore nella salita',
    costo: 'incluso nell\'ingresso a Petra (Jordan Pass)',
    comePrenotare: 'nessuna prenotazione, si accede a piedi dal sito',
    cosaPortare: 'scarpe da trekking, acqua, cappello',
    perChiEAdatta: 'chi ha una base di allenamento fisico: la salita è ripida e lunga',
    miaEsperienza:
      'Ogni singolo gradino viene ripagato dalla vista del Monastero, ancora più imponente del Tesoro. Un tè alla menta al chiosco davanti al monumento è la chiusura perfetta prima del rientro.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Il Monastero (Ad-Deir) scolpito nella roccia in cima alla salita di Petra, Giordania',
  },
  {
    slug: 'hammam-wadi-musa',
    paeseSlug: 'giordania',
    destinazioneSlug: 'petra',
    nome: 'Hammam da Al Yhakor',
    localita: 'Wadi Musa',
    cosE: 'Un hammam e bagno turco tradizionale da Al Yakhor Turkish Bath, a Wadi Musa.',
    percheFarla: 'Il modo perfetto per sciogliere le gambe dopo una giornata intera di cammino a Petra, inclusa la salita al Monastero.',
    durata: '1-1h30',
    periodo: 'sera, dopo la visita a Petra',
    costo: 'da completare',
    comePrenotare: 'direttamente in loco o tramite il DMC del viaggio',
    cosaPortare: 'costume da bagno',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Dopo una giornata intera passata a camminare a Petra, incluso il Monastero, l\'hammam da Al Yhakor è stato esattamente quello che serviva per recuperare le gambe.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Interni di un hammam tradizionale a Wadi Musa, Giordania',
  },
  {
    slug: 'jeep-safari-wadi-rum',
    paeseSlug: 'giordania',
    destinazioneSlug: 'wadi-rum',
    nome: 'Jeep safari a Wadi Rum',
    localita: 'Wadi Rum',
    cosE: 'Un giro di 4-6 ore sui classici pick-up beduini tra le tappe iconiche del deserto: la Sorgente di Lawrence, il canyon di Khazali, le dune rosse, i ponti di roccia naturali come Umm Fruth e la Casa di Lawrence.',
    percheFarla: 'Il modo più completo per vedere Wadi Rum in una sola giornata, con soste per sandboarding e la possibilità di guidare la jeep in prima persona.',
    durata: '4-6 ore',
    periodo: 'giornata, con tramonto sulle dune all\'arrivo al campo',
    costo: 'incluso nel pacchetto del campo tendato',
    comePrenotare: 'tramite il campo tendato o il DMC del viaggio',
    cosaPortare: 'occhiali da sole, foulard o turbante contro la sabbia, macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Tra canyon, dune rosse e il sandboarding, il jeep safari è stata una delle giornate più divertenti di tutto il viaggio, chiusa alla perfezione dal tramonto sulle dune all\'arrivo al campo.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Jeep 4x4 tra le dune rosse di Wadi Rum, Giordania',
  },
  {
    slug: 'capodanno-deserto',
    paeseSlug: 'giordania',
    destinazioneSlug: 'wadi-rum',
    nome: 'Capodanno nel deserto',
    localita: 'Wadi Rum',
    cosE: 'La festa di fine anno al campo tendato nel cuore del deserto di Wadi Rum, sotto uno dei cieli stellati più belli del mondo.',
    percheFarla: 'Un modo di salutare l\'anno completamente fuori dagli schemi, lontano da ogni inquinamento luminoso.',
    durata: 'la serata',
    periodo: '31 dicembre',
    costo: 'incluso nel pacchetto del campo tendato',
    comePrenotare: 'tramite il campo tendato o il DMC del viaggio',
    cosaPortare: 'strati pesanti per il freddo notturno',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Difficile immaginare un modo più assurdo di salutare l\'anno vecchio: cena beduina, zarb cotto sotto la sabbia e un cielo stellato senza pari, lontano da ogni luce artificiale.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Cielo stellato sopra il campo tendato nel deserto di Wadi Rum, Giordania',
  },
  {
    slug: 'diving-aqaba',
    paeseSlug: 'giordania',
    destinazioneSlug: 'aqaba',
    nome: 'Diving ad Aqaba',
    localita: 'Aqaba',
    cosE: 'Un\'immersione sulle barriere coralline del Mar Rosso, dal lato giordano ad Aqaba.',
    percheFarla: 'Un modo diverso di vivere il Mar Rosso, dopo giorni di deserto e siti archeologici, anche se non tra i punti di diving più rinomati della regione.',
    durata: 'mezza giornata',
    periodo: 'tutto l\'anno',
    costo: 'da completare',
    comePrenotare: 'tramite un diving center locale ad Aqaba',
    cosaPortare: 'costume, attrezzatura fornita dal diving center',
    perChiEAdatta: 'chi ha già un brevetto sub, o chi vuole provare un battesimo del mare',
    miaEsperienza:
      'Carino ma niente di memorabile rispetto ad altri punti del Mar Rosso più rinomati per il diving, l\'Egitto su tutti. Resta comunque un\'aggiunta piacevole alla giornata di mare ad Aqaba.',
    giudizio: 'bella-non-essenziale',
    alternative: ['Snorkeling sulle barriere coralline, più semplice e ugualmente scenografico'],
    tripSlugs: ['giordania-360'],
    imageAlt: 'Barriera corallina del Mar Rosso vista durante un\'immersione ad Aqaba, Giordania',
  },
]
