import type { Esperienza } from '@/lib/types'

// Una esperienza-bandiera per isola, contenuto guida generale (non ancora
// un ricordo personale: miaEsperienza resta assente di proposito, vedi
// src/content/destinazioni/indonesia.ts per la nota completa). Prezzi e
// modalità sono indicativi e vanno sempre riverificati prima di prenotare.

export const esperienzeIndonesia: Esperienza[] = [
  {
    slug: 'trekking-oranghi-bukit-lawang',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'sumatra',
    nome: 'Trekking oranghi a Bukit Lawang',
    localita: 'Bukit Lawang, Parco Nazionale del Gunung Leuser',
    cosE:
      'Un trekking nella giungla del Gunung Leuser, uno degli ultimi habitat al mondo dove osservare oranghi di Sumatra allo stato selvatico, oltre a gibboni, macachi e una fitta vegetazione pluviale. Le durate variano da mezza giornata a 3-4 giorni con pernottamento in campo nella foresta.',
    percheFarla: 'È l\'esperienza che rende Sumatra unica nell\'arcipelago: un incontro ravvicinato ma regolamentato con una specie in pericolo critico di estinzione.',
    durata: 'da mezza giornata (trekking breve) fino a 3-4 giorni con campo nella giungla',
    periodo: 'tutto l\'anno, meglio nella stagione secca (giugno-settembre) per sentieri più asciutti',
    costo: 'indicativamente 25-40€ per il trekking di mezza giornata, di più per i trekking multi-giorno con campo e pasti inclusi',
    comePrenotare: 'Tramite guide certificate registrate presso il centro visitatori del parco a Bukit Lawang — da evitare le guide non ufficiali che offrono prezzi più bassi ma senza le regole di sicurezza per gli animali.',
    cosaPortare: 'Scarpe da trekking con buona presa (sentieri spesso fangosi), repellente per insetti, sacchetto impermeabile per elettronica.',
    perChiEAdatta: 'Camminatori con una base di forma fisica; i trekking multi-giorno richiedono più resistenza per il caldo umido e il terreno accidentato.',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Orango femmina con cucciolo tra i rami della giungla di Bukit Lawang, Sumatra',
  },
  {
    slug: 'alba-bromo-jeep',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'giava',
    nome: 'Alba al Gunung Bromo in jeep',
    localita: 'Monte Penanjakan, Parco Nazionale Bromo Tengger Semeru, Giava est',
    cosE:
      'Una partenza notturna in jeep 4x4 verso il punto panoramico del Monte Penanjakan per assistere all\'alba sul cratere fumante del Bromo, circondato dal cosiddetto Mare di Sabbia. Dopo l\'alba, i jeep scendono fino ai piedi del vulcano per la salita a piedi/a cavallo fino all\'orlo del cratere.',
    percheFarla: 'Una delle albe più fotografate del sud-est asiatico, con il Bromo che fuma in primo piano e altri vulcani (Semeru, Batok) sullo sfondo.',
    durata: 'circa 5-6 ore, partenza verso le 3:00-3:30 del mattino',
    periodo: 'maggio-settembre per cieli più tersi; possibile tutto l\'anno con condizioni più variabili',
    costo: 'il jeep condiviso (fino a 6 persone) si aggira sui 400.000-600.000 IDR (circa 25-35€) a jeep, più il biglietto d\'ingresso al parco',
    comePrenotare: 'Tramite il guesthouse/hotel di Cemoro Lawang o agenzie locali; il jeep viene condiviso tra più viaggiatori per abbattere il costo.',
    cosaPortare: 'Strati pesanti (le temperature notturne in quota sono molto più basse rispetto alla pianura), mascherina per la sabbia vulcanica sollevata dal vento.',
    perChiEAdatta: 'Adatta a tutti, nessuna difficoltà fisica rilevante: la parte a piedi fino al cratere è breve.',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Fila di jeep al punto panoramico del Monte Penanjakan all\'alba, con il Bromo sullo sfondo',
  },
  {
    slug: 'giornata-nusa-penida',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'bali',
    nome: 'Giornata a Nusa Penida',
    localita: 'Nusa Penida, isola al largo della costa sud-est di Bali',
    cosE:
      'Un\'escursione in barca veloce da Sanur o Padang Bai fino a Nusa Penida, con giro in auto/scooter tra i punti panoramici più fotografati dell\'isola: Kelingking Beach (a forma di T-Rex), Angel\'s Billabong, Broken Beach, e i punti snorkeling con le manta ray a Manta Point.',
    percheFarla: 'Concentra in una sola giornata alcuni dei panorami più iconici di tutta Bali, con la possibilità di aggiungere lo snorkeling con le manta.',
    durata: 'giornata intera, partenza presto al mattino, rientro nel tardo pomeriggio',
    periodo: 'aprile-ottobre, mare più calmo per la traversata in barca veloce',
    costo: 'tour organizzato di giornata indicativamente 30-50€ a persona, incluso trasporto in barca e auto/scooter sull\'isola; snorkeling con le manta come extra',
    comePrenotare: 'Tramite agenzie locali o direttamente al porto di Sanur; consigliato prenotare il giorno prima in alta stagione.',
    cosaPortare: 'Scarpe con buona presa per Kelingking (discesa ripida), costume e attrezzatura da snorkeling se non inclusa nel tour.',
    perChiEAdatta: 'La maggior parte dei punti panoramici richiede solo brevi camminate; Kelingking Beach ha una discesa/risalita ripida non adatta a chi ha problemi di mobilità.',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Vista dall\'alto di Kelingking Beach a forma di T-Rex, Nusa Penida',
  },
  {
    slug: 'diving-bunaken-national-park',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'sulawesi',
    nome: 'Diving al Bunaken National Park',
    localita: 'Bunaken, al largo di Manado, Sulawesi nord',
    cosE:
      'Immersioni lungo le pareti coralline verticali del Bunaken National Park, uno dei parchi marini più ricchi di biodiversità del sud-est asiatico, con oltre 300 specie di coralli e centinaia di specie di pesci.',
    percheFarla: 'Un contrappunto marino alla parte più culturale del viaggio a Tana Toraja, con pareti coralline tra le più spettacolari dell\'Indonesia.',
    durata: 'giornata singola (2-3 immersioni) o pacchetti di più giorni con pernottamento su Bunaken',
    periodo: 'maggio-ottobre per la migliore visibilità',
    costo: 'indicativamente 60-90€ per una giornata con 2-3 immersioni, attrezzatura inclusa; pacchetti multi-giorno con alloggio disponibili presso i resort dell\'isola',
    comePrenotare: 'Tramite dive center a Manado o direttamente sui resort dell\'isola di Bunaken.',
    cosaPortare: 'Certificazione diving se non alla prima esperienza; per chi non è certificato, molti centri offrono corsi introduttivi o snorkeling come alternativa.',
    perChiEAdatta: 'Diving certificato per le immersioni vere e proprie; lo snorkeling lungo gli stessi reef è un\'alternativa accessibile a tutti.',
    giudizio: 'da-verificare',
    alternative: ['Snorkeling lungo gli stessi reef per chi non è certificato al diving'],
    tripSlugs: [],
    imageAlt: 'Parete corallina verticale ricca di pesci tropicali al Bunaken National Park',
  },
  {
    slug: 'trekking-gunung-rinjani',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'lombok-gili',
    nome: 'Trekking al Gunung Rinjani',
    localita: 'Parco Nazionale del Gunung Rinjani, Lombok',
    cosE:
      'Trekking di 2-4 giorni sul secondo vulcano più alto dell\'Indonesia (3.726 m), con pernottamento in campo lungo il tragitto e discesa fino al lago craterico di Segara Anak, dalle acque calde sulfuree.',
    percheFarla: 'La sfida fisica più impegnativa tra le otto isole, ripagata da un panorama sul lago craterico tra i più belli del paese.',
    durata: '2 giorni per il percorso base fino al bordo del cratere, 3-4 giorni per includere la discesa al lago e la salita in vetta',
    periodo: 'aprile-dicembre; il parco chiude durante la stagione delle piogge (gennaio-marzo) per motivi di sicurezza',
    costo: 'i pacchetti guidati con guida, portatori, campo e pasti partono indicativamente da 150-250€ a persona a seconda della durata',
    comePrenotare: 'Tramite operatori autorizzati dal parco nazionale a Senaru o Sembalun, i due punti di partenza del trekking; guida obbligatoria per legge.',
    cosaPortare: 'Scarpe da trekking robuste, sacco a pelo/strato termico per le notti in quota (temperature vicine allo zero), torcia frontale per la salita in vetta all\'alba.',
    perChiEAdatta: 'Richiede una buona forma fisica: il percorso è lungo, ripido in più tratti e in quota.',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Lago craterico di Segara Anak visto dal bordo del vulcano Rinjani, Lombok',
  },
  {
    slug: 'trekking-draghi-komodo',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'komodo',
    nome: 'Trekking per vedere i draghi di Komodo',
    localita: 'Isola di Komodo o isola di Rinca, Parco Nazionale di Komodo',
    cosE:
      'Un trekking guidato da un ranger del parco, su sentieri segnalati, per osservare i draghi di Komodo nel loro habitat naturale — l\'ultimo grande predatore terrestre rimasto sulla Terra, endemico di questa manciata di isole.',
    percheFarla: 'È l\'unico posto al mondo dove osservare questa specie allo stato selvatico, con probabilità di avvistamento molto alte su entrambe le isole.',
    durata: 'da 1 a 3 ore a seconda del percorso scelto (breve, medio o lungo)',
    periodo: 'aprile-dicembre, stagione secca',
    costo: 'incluso nel biglietto d\'ingresso al parco più il costo del ranger, indicativamente 15-25€ a persona sommando le voci; spesso parte di un tour in barca più ampio',
    comePrenotare: 'Tramite gli operatori di tour in barca da Labuan Bajo, che includono la tappa sull\'isola come parte dell\'itinerario.',
    cosaPortare: 'Scarpe chiuse, cappello e protezione solare: i sentieri sono spesso privi di ombra.',
    perChiEAdatta: 'Adatto a tutti i livelli di camminatori; il rispetto rigoroso delle indicazioni del ranger è obbligatorio per sicurezza.',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Drago di Komodo osservato a distanza di sicurezza durante un trekking guidato',
  },
  {
    slug: 'alba-kelimutu',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'flores',
    nome: 'Alba al Kelimutu',
    localita: 'Parco Nazionale del Kelimutu, vicino a Moni, Flores',
    cosE:
      'Una salita mattutina al punto panoramico del Kelimutu per vedere i suoi tre laghi craterici, ognuno con un colore diverso (che può variare nel tempo per fenomeni chimici) — turchese, verde scuro e quasi nero nelle configurazioni più comuni.',
    percheFarla: 'Un fenomeno naturale raro, tra i simboli più riconoscibili di tutta l\'Indonesia orientale.',
    durata: 'mezza giornata, partenza verso le 4:00-4:30 dal villaggio di Moni',
    periodo: 'maggio-ottobre per cieli più tersi; possibile tutto l\'anno',
    costo: 'biglietto d\'ingresso al parco nazionale, pochi euro; trasporto da Moni da aggiungere se non incluso in un tour',
    comePrenotare: 'Tramite il guesthouse a Moni, che spesso organizza il trasporto condiviso verso il parco, o tour operator locali.',
    cosaPortare: 'Giacca per il freddo mattutino in quota, torcia se si sale ancora al buio.',
    perChiEAdatta: 'Adatto a tutti: la salita dal parcheggio al punto panoramico è breve.',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'I tre laghi craterici del Kelimutu di colori diversi visti all\'alba, Flores',
  },
  {
    slug: 'diving-liveaboard-raja-ampat',
    paeseSlug: 'indonesia',
    destinazioneSlug: 'raja-ampat',
    nome: 'Diving in liveaboard a Raja Ampat',
    localita: 'Parco marino di Raja Ampat, Papua occidentale',
    cosE:
      'Un tour in barca (liveaboard) di più giorni tra i reef di Raja Ampat, considerati tra i più biodiversi al mondo, con soste per diving/snorkeling e per i belvedere sulle isole a fungo di Piaynemo e Wayag.',
    percheFarla: 'È il modo più completo per esplorare un arcipelago dove le distanze via terra non esistono e i punti migliori sono sparsi su una vasta area di mare.',
    durata: 'liveaboard da 4 a 10 giorni, a seconda dell\'itinerario scelto',
    periodo: 'ottobre-aprile, quando il mare è più calmo e la visibilità migliore',
    costo: 'tra le esperienze più costose del viaggio: i liveaboard partono indicativamente da 150-250€ al giorno a persona, più il permesso obbligatorio del parco marino (PIN Raja Ampat)',
    comePrenotare: 'Tramite operatori specializzati in liveaboard, con prenotazione con largo anticipo per la stagione alta (i posti sono limitati).',
    cosaPortare: 'Certificazione diving per le immersioni; attrezzatura da snorkeling propria se non inclusa a bordo.',
    perChiEAdatta: 'Diving certificato per le immersioni più impegnative; molte soste sono accessibili anche solo con lo snorkeling.',
    giudizio: 'da-verificare',
    alternative: ['Base fissa a terra (Waisai o un resort) con uscite giornaliere in barca invece del liveaboard'],
    tripSlugs: [],
    imageAlt: 'Barca liveaboard ancorata tra le isole a fungo di Raja Ampat',
  },
]
