import type { Esperienza } from '@/lib/types'

// Contenuto riutilizzato dal viaggio "Islanda in tenda: 9 giorni sull'isola del
// ghiaccio e del fuoco" (src/content/viaggi/02-islanda-2024.md).

export const esperienzeIslanda: Esperienza[] = [
  {
    slug: 'campeggio-in-islanda',
    paeseSlug: 'islanda',
    destinazioneSlug: 'vik',
    nome: 'Campeggio in tenda in Islanda',
    localita: 'lungo tutta la Ring Road — 6 notti su 8 in tenda in questo viaggio',
    cosE:
      'Il modo più economico e autentico di girare l\'Islanda: tenda a noleggio (non serve portarla dall\'Italia) e una rete di campeggi attrezzati praticamente in ogni tappa della Ring Road, spesso con cucine comuni, docce ed elettricità.',
    percheFarla: 'Abbatte drasticamente il costo degli alloggi (i più cari della spesa in un\'isola già cara di suo) e trasforma il viaggio in un\'esperienza on the road molto più immersiva rispetto a hotel prenotati in anticipo.',
    durata: 'l\'intero viaggio, 6 notti su 8 in questo itinerario',
    periodo: 'estate (giugno-agosto), quando la maggior parte dei campeggi sono aperti; alcuni (es. Ásbyrgi) aprono da metà maggio a fine ottobre',
    costo: 'indicativamente 1.500-2.800 ISK a persona a notte per il campeggio, più il noleggio della tenda',
    comePrenotare:
      'Tenda a noleggio da RENTATENT (Vesturvör 32b, Kópavogur, vicino a Keflavík, aperto dalle 9:00) — ritirata lo stesso giorno dell\'auto. I campeggi lungo la Ring Road quasi sempre non richiedono prenotazione, tranne quelli più piccoli/remoti in alta stagione (es. Ásbyrgi).',
    cosaPortare:
      'Sacco a pelo, materassino e cuscino da campeggio (se non inclusi nel noleggio tenda); intimo termico; giacca a vento impermeabile con cappuccio (niente ombrelli, il vento è troppo forte); scarpe da trekking con riserva; cappello, guanti, calzini alti e spessi; power bank (ricarica possibile di solito una sola volta al giorno nei campeggi); borraccia (l\'acqua del rubinetto islandese è ottima); coltellino svizzero e tazza personale.',
    perChiEAdatta: 'chi vuole risparmiare sugli alloggi e non ha problemi a dormire con temperature vicine allo 0°C anche in piena estate; utile essere in due persone che sanno guidare, per alternarsi nei tratti più lunghi tra un campeggio e l\'altro',
    miaEsperienza:
      'Sei notti su otto in tenda, con temperature che di notte si avvicinavano allo 0°C anche a luglio. Il vento è la vera variabile da tenere sotto controllo — va sempre chiuse le portiere dell\'auto per non rischiare di romperle. I campeggi meglio attrezzati (Hamrar ad Akureyri, Camp Egilsstaðir) avevano cucine al chiuso, lavatrici e wifi; altri, più remoti (Ásbyrgi), solo i servizi essenziali ma comunque puliti.',
    giudizio: 'la-rifarei',
    alternative: ['Percorso identico ma in hotel/guesthouse ad ogni tappa, molto più caro ma senza pensieri di logistica campeggio'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Tenda da campeggio islandese con vista su un paesaggio vulcanico al tramonto',
  },
  {
    slug: 'vulcano-reykjanes',
    paeseSlug: 'islanda',
    destinazioneSlug: 'keflavik',
    nome: 'Vulcano in eruzione a Reykjanes',
    localita: 'penisola di Reykjanes, vicino Keflavík (zona Grindavík/Fagradalsfjall)',
    cosE:
      'La possibilità di vedere da vicino la lava di un\'eruzione vulcanica attiva: la penisola di Reykjanes è entrata in eruzione più volte tra il 2023 e il 2024, e in alcuni periodi sono stati organizzati percorsi di accesso in sicurezza per i visitatori.',
    percheFarla: 'Un\'esperienza rarissima altrove al mondo: vedere lava attiva da vicino, in un\'area geologicamente tra le più attive d\'Europa e a pochi minuti dall\'aeroporto.',
    durata: 'variabile a seconda del tipo di escursione (a piedi fino a un\'area di osservazione, o in elicottero/tour organizzato)',
    periodo: 'dipende dall\'attività vulcanica in corso — da verificare sempre con le autorità islandesi (Protezione Civile islandese, safetravel.is) prima di avvicinarsi, per sicurezza',
    costo: 'da completare',
    comePrenotare: 'da completare — verificare sempre lo stato di accesso e le zone di sicurezza aperte al pubblico su safetravel.is prima di organizzare qualsiasi escursione',
    cosaPortare: 'scarpe da trekking robuste, maschera antigas/fazzoletto per i fumi sulfurei se ci si avvicina, seguire sempre le indicazioni delle autorità locali',
    perChiEAdatta: 'chi è disposto a seguire rigorosamente le indicazioni di sicurezza; l\'accesso alle zone eruttive viene chiuso e riaperto in base all\'attività, mai da tentare in autonomia senza verificare lo stato ufficiale',
    miaEsperienza:
      'Vedere la lava da vicino è stata una delle esperienze più forti di tutto il viaggio — sto ancora ricostruendo con precisione giorno e modalità esatte (se in tour organizzato o punto di osservazione autonomo), da confermare con foto e ricordi.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Colata di lava incandescente durante un\'eruzione vulcanica sulla penisola di Reykjanes, Islanda',
  },
  {
    slug: 'trekking-ghiacciaio-vatnajokull',
    paeseSlug: 'islanda',
    destinazioneSlug: 'skaftafell-jokulsarlon',
    nome: 'Trekking sul ghiacciaio Vatnajökull',
    localita: 'Skaftafell, Parco Nazionale del Vatnajökull',
    cosE:
      'Un\'escursione guidata sulla lingua glaciale del Vatnajökull, il ghiacciaio più grande d\'Europa, con ramponi e piccozza forniti dalla guida alpina.',
    percheFarla: 'Camminare letteralmente sopra un ghiacciaio, tra crepacci e formazioni di ghiaccio blu, è un\'esperienza che non si dimentica — e Skaftafell è uno dei punti di accesso più organizzati per farlo in sicurezza.',
    durata: 'da completare (variabile in base al tour scelto, indicativamente 3-5 ore)',
    periodo: 'tutto l\'anno, condizioni migliori in estate',
    costo: 'da completare',
    comePrenotare: 'con le guide alpine locali di Skaftafell, meglio con anticipo in alta stagione',
    cosaPortare: 'scarpe da trekking robuste (i ramponi vengono forniti), strati caldi anche in estate, guanti',
    perChiEAdatta: 'chiunque abbia una condizione fisica normale; non serve esperienza di alpinismo, l\'attrezzatura tecnica è fornita e la guida imposta il ritmo',
    miaEsperienza:
      'Una delle attività più intense di tutto il viaggio: crepacci, formazioni di ghiaccio blu e il silenzio assoluto del ghiacciaio. Sto ancora recuperando durata e operatore esatti da foto e ricevute.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Escursionisti con ramponi che camminano sul ghiacciaio Vatnajökull, Islanda',
  },
  {
    slug: 'kayak-jokulsarlon',
    paeseSlug: 'islanda',
    destinazioneSlug: 'skaftafell-jokulsarlon',
    nome: 'Kayak tra gli iceberg a Jökulsárlón',
    localita: 'Laguna glaciale di Jökulsárlón',
    cosE:
      'Un\'uscita in kayak tra gli iceberg che si staccano dal ghiacciaio Vatnajökull e galleggiano nella laguna di Jökulsárlón, spesso con foche a pochi metri di distanza.',
    percheFarla: 'Un modo molto più immersivo di vivere la laguna rispetto al solo punto panoramico, sempre affollato di turisti — qui si pagaia letteralmente tra i blocchi di ghiaccio.',
    durata: 'da completare (indicativamente 1-1h30)',
    periodo: 'estate, quando le condizioni della laguna sono più stabili',
    costo: 'da completare',
    comePrenotare: 'con gli operatori locali di Jökulsárlón, meglio con anticipo in alta stagione',
    cosaPortare: 'cambio asciutto, giacca impermeabile (l\'attrezzatura tecnica per il kayak è generalmente fornita)',
    perChiEAdatta: 'chiunque sappia stare in acqua con un minimo di equilibrio; nessuna esperienza di kayak richiesta',
    miaEsperienza:
      'Pagaiare tra i blocchi di ghiaccio che si staccano dal ghiacciaio, con le foche spesso a pochi metri, è stato tra i momenti più belli del viaggio — molto diverso dal semplice punto panoramico affollato di turisti. Sto ancora recuperando durata e operatore esatti.',
    giudizio: 'imperdibile',
    alternative: ['Punto panoramico gratuito sulla riva della laguna, senza kayak'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Kayak tra gli iceberg nella laguna glaciale di Jökulsárlón, Islanda',
  },
  {
    slug: 'relitto-aereo-solheimasandur',
    paeseSlug: 'islanda',
    destinazioneSlug: 'vik',
    nome: 'Relitto dell\'aereo a Sólheimasandur',
    localita: 'Sólheimasandur, vicino Vík',
    cosE:
      'Il relitto di un DC-3 della marina americana, abbandonato sulla spiaggia di sabbia nera di Sólheimasandur dal 1973, oggi uno dei soggetti fotografici più iconici d\'Islanda.',
    percheFarla: 'La combinazione di isolamento, luce islandese e il relitto stesso lo rende uno dei posti più fotogenici e surreali dell\'isola — soprattutto se raggiunto a piedi con il sole di mezzanotte.',
    durata: '4 km a tratta (40-60 minuti a piedi per direzione), quindi 1h30-2h totali andata e ritorno',
    periodo: 'tutto l\'anno; in estate con il sole di mezzanotte si può fare anche a tarda sera/notte',
    costo: 'gratuito (accesso a piedi dal parcheggio sulla Ring Road)',
    comePrenotare: 'nessuna prenotazione, accesso libero — non è più permesso arrivare in auto fin dentro alla spiaggia, solo a piedi o in bicicletta dal parcheggio',
    cosaPortare: 'scarpe comode, strati per il vento (la sabbia nera è completamente esposta), power bank/torcia se ci si va in tarda serata',
    perChiEAdatta: 'chi non ha problemi a camminare 8 km totali su terreno piatto ma esposto al vento',
    miaEsperienza:
      'Grazie al sole di mezzanotte di inizio luglio, ho deciso all\'ultimo di andarci dopo cena invece che il mattino dopo come da programma: quattro chilometri di sabbia nera e vento per raggiungere un pezzo di metallo abbandonato nel nulla, con la luce che non è mai calata del tutto. Una vera sfacchinata dopo una giornata già piena, ma probabilmente il momento più assurdo e memorabile di tutto il viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Relitto di un aereo DC-3 abbandonato sulla sabbia nera di Sólheimasandur al crepuscolo, Islanda',
  },
  {
    slug: 'golden-circle',
    paeseSlug: 'islanda',
    destinazioneSlug: 'vik',
    nome: 'Golden Circle (Geysir e Gullfoss)',
    localita: 'sud-ovest dell\'Islanda, tra Reykjavík e Vík',
    cosE:
      'Il percorso turistico più classico d\'Islanda: l\'area geotermica di Geysir, con géiser attivi che eruttano regolarmente, e la cascata Gullfoss, la "cascata dorata" a due salti sul fiume Hvítá.',
    percheFarla: 'È il modo più semplice per vedere in poche ore due dei simboli naturali dell\'Islanda, ed è comunque sulla strada per il sud del paese.',
    durata: 'mezza giornata, indicativamente 15-25 minuti a Geysir più il tempo a Gullfoss',
    periodo: 'tutto l\'anno',
    costo: 'gratuito (parcheggio a pagamento in alcune zone)',
    comePrenotare: 'accesso libero, nessuna prenotazione necessaria',
    cosaPortare: 'scarpe comode, giacca a vento (Gullfoss produce spruzzi d\'acqua)',
    perChiEAdatta: 'chiunque, percorsi accessibili e ben organizzati',
    miaEsperienza:
      'Il Geysir erutta ogni 6-7 minuti — bastano 15-25 minuti per vederlo un paio di volte da vicino. Gullfoss, con i suoi due salti da 11 e 21 metri, è uno di quei posti che valgono la fama nonostante l\'affluenza turistica.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Eruzione del geyser attivo nell\'area geotermica di Geysir, Islanda',
  },
  {
    slug: 'whale-watching-husavik',
    paeseSlug: 'islanda',
    destinazioneSlug: 'akureyri',
    nome: 'Whale watching a Húsavík',
    localita: 'Húsavík, baia di Skjálfandi',
    cosE:
      'Un tour classico in barca di circa 3 ore, a bordo di una delle tradizionali barche in legno di quercia restaurate, alla ricerca di megattere, balenottere minori e, con un po\' di fortuna, orche o balenottere azzurre.',
    percheFarla: 'Húsavík è considerata la "capitale mondiale" del whale watching: la baia di Skjálfandi ha una delle concentrazioni di cetacei più alte d\'Islanda.',
    durata: 'circa 3 ore',
    periodo: 'primavera-autunno, con l\'estate come periodo di massima probabilità di avvistamenti',
    costo: 'da completare',
    comePrenotare: 'con gli operatori del porto vecchio di Húsavík, meglio con anticipo in alta stagione',
    cosaPortare: 'strati pesanti anche in estate (fa molto freddo in mare aperto), bustina impermeabile per il telefono/macchina fotografica',
    perChiEAdatta: 'chiunque; le barche forniscono tute termiche per il freddo in mare aperto',
    miaEsperienza: 'Un classico che vale la fama: tre ore in mare aperto nella baia di Skjálfandi, con buone probabilità di avvistamento vista la concentrazione di cetacei della zona.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Megattera che emerge dall\'acqua durante un tour di whale watching a Húsavík, Islanda',
  },
  {
    slug: 'zona-geotermale-myvatn',
    paeseSlug: 'islanda',
    destinazioneSlug: 'akureyri',
    nome: 'Zona geotermica di Mývatn',
    localita: 'lago Mývatn',
    cosE:
      'Un concentrato di fenomeni geotermici e vulcanici attorno al lago Mývatn: Grjótagjá (grotta lavica con sorgente termale, location di una scena di Game of Thrones), Hverfjall (cratere vulcanico ad anello), Hverir (fumarole e pozze di fango bollente) e Dimmuborgir (labirinto di formazioni laviche).',
    percheFarla: 'In poche ore si vedono più tipi di fenomeni geotermici che in qualsiasi altra zona dell\'Islanda: crateri, fumarole, grotte laviche e formazioni rocciose spettacolari.',
    durata: 'mezza giornata, per visitare con calma le tappe principali',
    periodo: 'tutto l\'anno',
    costo: 'gratuito nella maggior parte dei siti',
    comePrenotare: 'accesso libero, nessuna prenotazione necessaria',
    cosaPortare: 'scarpe robuste, attenzione al forte odore di zolfo a Hverir',
    perChiEAdatta: 'chiunque, percorsi brevi e accessibili',
    miaEsperienza: 'Hverir, con le sue fumarole e pozze di fango bollente e il forte odore di zolfo, è il punto più "alieno" di tutta l\'Islanda — un contrasto totale con il ghiaccio visto pochi giorni prima al Vatnajökull.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Fumarole e terreno colorato di zolfo nella zona geotermica di Hverir, lago Mývatn, Islanda',
  },
  {
    slug: 'terme-naturali-islanda',
    paeseSlug: 'islanda',
    destinazioneSlug: 'egilsstadir',
    nome: 'Terme naturali islandesi',
    localita: 'Vök Baths (Egilsstaðir) e altre sorgenti calde lungo il West Iceland',
    cosE:
      'Piscine termali alimentate da sorgenti calde naturali, dalla vasca galleggiante dei Vök Baths sul lago Urriðavatn alle piscine più semplici e meno turistiche del West Iceland come Guðrúnarlaug.',
    percheFarla: 'Dopo giorni di trekking, vento e notti in tenda, un bagno caldo naturale è la pausa perfetta — e le opzioni meno turistiche costano una frazione della Blue Lagoon.',
    durata: '1-2 ore per tappa',
    periodo: 'tutto l\'anno, particolarmente piacevole dopo giornate fredde o ventose',
    costo: 'Vök Baths a pagamento (prezzo da completare); Guðrúnarlaug a ingresso gratuito, spogliatoio essenziale',
    comePrenotare: 'Vök Baths accessibile senza prenotazione nella maggior parte dei periodi; le sorgenti naturali minori sono ad accesso libero',
    cosaPortare: 'costume da bagno non nuovo/prezioso (le acque geotermali rovinano i tessuti se non sciacquati subito), asciugamano, ciabatte',
    perChiEAdatta: 'chiunque cerchi una pausa rilassante lungo il percorso',
    miaEsperienza:
      'I Vök Baths, con le due vasche che galleggiano letteralmente sul lago, sono arrivati al momento giusto: il primo vero bagno caldo del viaggio dopo due giorni tra trekking e vento. Lungo il tragitto verso Reykjavík ho fatto anche una sosta in una sorgente naturale meno battuta, molto più semplice ma altrettanto piacevole.',
    giudizio: 'la-rifarei',
    alternative: ['Blue Lagoon, molto più turistica e cara, vicino a Keflavík'],
    tripSlugs: ['islanda-2024'],
    imageAlt: 'Vasca termale galleggiante dei Vök Baths sul lago Urriðavatn, Islanda',
  },
]
