import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Marocco 360°" (src/content/viaggi/07-marocco-360.md).

export const esperienzeMarocco: Esperienza[] = [
  {
    slug: 'notte-deserto-erg-chebbi',
    paeseSlug: 'marocco',
    destinazioneSlug: 'merzouga',
    nome: 'Notte nel deserto a Erg Chebbi',
    localita: 'Erg Chebbi, Merzouga',
    cosE: 'Una notte in campo tendato ai piedi delle dune di Erg Chebbi, con giro in cammello al tramonto e all\'alba, cena al campo e un cielo stellato lontano da ogni luce artificiale.',
    percheFarla: 'Uno dei momenti più belli di tutto il Marocco: il cielo stellato del Sahara, lontano da ogni inquinamento luminoso, è un\'esperienza che non si dimentica.',
    durata: 'una notte intera',
    periodo: 'tutto l\'anno, con notti fresche anche in primavera/estate',
    costo: 'incluso nel pacchetto del campo tendato',
    comePrenotare: 'tramite la guida/tour operator che organizza il viaggio',
    cosaPortare: 'turbante o pashmina (contro sabbia e freddo notturno), power bank carico (niente prese elettriche ai campi), strati pesanti per la notte',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Nella notte, il cielo stellato senza pari, lontano da ogni luce artificiale, è stato uno dei momenti più belli di tutto il viaggio. Il giro in cammello all\'alba, con le dune che cambiano colore con la luce del sole nascente, è stata la degna chiusura di quella notte.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Cielo stellato sopra il campo tendato nel deserto di Erg Chebbi, Marocco',
  },
  {
    slug: 'gole-todra',
    paeseSlug: 'marocco',
    destinazioneSlug: 'merzouga',
    nome: 'Gole di Todra',
    localita: 'Todra, lungo il tragitto verso Merzouga',
    cosE: 'Pareti di roccia che si stringono fino a pochi metri di distanza, tra le gole più spettacolari del Marocco.',
    percheFarla: 'Una sosta di appena mezz\'ora, ma tra le più fotogeniche del tragitto verso il deserto.',
    durata: '30 minuti',
    periodo: 'tutto l\'anno',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione, sosta lungo il tragitto',
    cosaPortare: 'scarpe comode',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Le pareti che si stringono fino a pochi metri di distanza creano un effetto quasi claustrofobico ma bellissimo — una sosta breve che vale molto più del tempo che richiede.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Le pareti a strapiombo delle Gole di Todra, Marocco',
  },
  {
    slug: 'quad-deserto-merzouga',
    paeseSlug: 'marocco',
    destinazioneSlug: 'merzouga',
    nome: 'Quad nel deserto',
    localita: 'Merzouga',
    cosE: 'Un giro in quad tra le dune del deserto vicino a Merzouga, in alternativa (per chi ha la patente) alla moto.',
    percheFarla: 'Un modo diverso e adrenalinico di vivere il paesaggio del Sahara, dopo l\'esperienza più lenta del cammello.',
    durata: 'un\'ora circa',
    periodo: 'tutto l\'anno, meglio in mattinata per evitare il caldo peggiore',
    costo: '350 MAD a persona',
    comePrenotare: 'da concordare con la guida; la moto (alternativa al quad) va prenotata con qualche giorno di anticipo per la disponibilità limitata',
    cosaPortare: 'occhiali/foulard contro la sabbia, protezione solare',
    perChiEAdatta: 'chiunque per il quad; serve la patente per la moto',
    miaEsperienza:
      'Dopo la lentezza contemplativa del cammello la sera prima, il quad nel deserto la mattina dopo è stato un bel cambio di ritmo — puro divertimento tra le dune.',
    giudizio: 'la-rifarei',
    alternative: ['Moto nel deserto, per chi ha la patente e prenota con anticipo'],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Quad che attraversa le dune del deserto vicino a Merzouga, Marocco',
  },
  {
    slug: 'surf-taghazout',
    paeseSlug: 'marocco',
    destinazioneSlug: 'agadir',
    nome: 'Lezione di surf a Taghazout',
    localita: 'Taghazout',
    cosE: 'Una lezione di surf di 2 ore con la scuola Chillout, nel villaggio di pescatori diventato uno dei punti di riferimento del surf in Marocco.',
    percheFarla: 'Taghazout è uno dei posti migliori del paese per iniziare a surfare, con onde adatte anche ai principianti.',
    durata: '2 ore',
    periodo: 'tutto l\'anno, con condizioni migliori in autunno-inverno per i surfisti più esperti',
    costo: '250 MAD a persona (docce disponibili a 10 MAD)',
    comePrenotare: 'tramite la scuola Chillout o la guida del viaggio',
    cosaPortare: 'costume, telo, cambio asciutto',
    perChiEAdatta: 'anche principianti assoluti',
    miaEsperienza:
      'Una mattinata diversa da tutto il resto del viaggio: dopo giorni di deserto e kasbah, il surf a Taghazout è stato un tuffo (letterale) in un registro completamente diverso.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Lezione di surf sulle onde di Taghazout, Marocco',
  },
  {
    slug: 'hammam-essaouira',
    paeseSlug: 'marocco',
    destinazioneSlug: 'essaouira',
    nome: 'Hammam da Kenza',
    localita: 'Essaouira',
    cosE: 'Un hammam tradizionale marocchino da Kenza, un\'ora di pausa e relax nel cuore della medina di Essaouira.',
    percheFarla: 'Un momento di pausa ben piazzato dopo giorni di van e visite, in una delle tappe più rilassate del viaggio.',
    durata: 'un\'ora',
    periodo: 'tutto l\'anno',
    costo: '250 MAD a persona',
    comePrenotare: 'direttamente da Kenza o tramite la guida',
    cosaPortare: 'costume da bagno',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Dopo giorni di van, deserto e visite, l\'ora passata all\'hammam da Kenza è stato uno dei momenti di puro relax di tutto il viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Interni di un hammam tradizionale a Essaouira, Marocco',
  },
  {
    slug: 'tour-marrakech',
    paeseSlug: 'marocco',
    destinazioneSlug: 'marrakech',
    nome: 'Tour guidato di Marrakech',
    localita: 'Marrakech',
    cosE: 'Un tour guidato tra i monumenti principali della medina: Medersa Ali Ben Youssef, Palazzo della Bahia, Tombe Saadiane, Moschea Koutoubia (solo esterno) e Piazza Jemaa El-Fna.',
    percheFarla: 'Il modo più efficiente per vedere i monumenti principali della città in una sola mattinata, con il contesto storico spiegato da una guida.',
    durata: 'una mattinata',
    periodo: 'tutto l\'anno, meglio la mattina per il caldo',
    costo: 'incluso nel pacchetto del viaggio, mancia 200 MAD totali; Medersa 50 MAD, Palazzo della Bahia 70 MAD, Tombe Saadiane 70 MAD (ingressi separati)',
    comePrenotare: 'tramite la guida del viaggio',
    cosaPortare: 'abbigliamento comodo, si cammina molto tra i vicoli della medina',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il tour guidato è stato un ottimo modo per orientarsi nella medina, ma è Jemaa El-Fna — vista di nuovo dopo il tour, di sera — a restare il ricordo più forte di Marrakech.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'La Medersa Ali Ben Youssef con i suoi intricati intagli decorativi, Marrakech, Marocco',
  },
  {
    slug: 'jardin-majorelle',
    paeseSlug: 'marocco',
    destinazioneSlug: 'marrakech',
    nome: 'Jardin Majorelle',
    localita: 'Marrakech',
    cosE: 'Il giardino blu cobalto creato dal pittore Jacques Majorelle e poi appartenuto a Yves Saint Laurent, con piante esotiche e architetture Art Déco dipinte del celebre "blu Majorelle".',
    percheFarla: 'Una tappa quasi obbligata a Marrakech, con un\'atmosfera completamente diversa dal caos della medina.',
    durata: 'un\'ora, un\'ora e mezza',
    periodo: 'tutto l\'anno, aperto dal mattino presto fino a sera con ultimo ingresso nel tardo pomeriggio',
    costo: '150 MAD a persona',
    comePrenotare: 'da prenotare in anticipo, i posti sono contingentati',
    cosaPortare: 'macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il blu cobalto del giardino, contro il verde delle piante esotiche, crea un\'atmosfera sorprendentemente calma dopo il caos ordinato della medina — una delle pause più belle del viaggio a Marrakech.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['marocco-360'],
    imageAlt: 'Architetture blu cobalto tra le piante esotiche del Jardin Majorelle, Marrakech, Marocco',
  },
]
