import type { Esperienza } from '@/lib/types'

// Contenuto riutilizzato dal viaggio "Messico Beach Life" (src/content/viaggi/13-messico-beach-life.md).

export const esperienzeMessico: Esperienza[] = [
  {
    slug: 'squalo-balena-holbox',
    paeseSlug: 'messico',
    destinazioneSlug: 'holbox',
    nome: 'Nuotare con lo squalo balena',
    localita: 'Holbox',
    cosE:
      'Un\'escursione in barca al largo di Holbox per nuotare, con maschera e boccaglio, accanto agli squali balena — il più grande pesce del mondo, ma completamente innocuo, che nuota placido filtrando plancton in superficie.',
    percheFarla: 'È il momento clou di tutto l\'itinerario: un\'esperienza che non capita in molti altri posti al mondo con questa facilità.',
    durata: '8 ore (giornata intera)',
    periodo: 'stagionale, da confermare con l\'operatore in base all\'anno',
    costo: 'costo elevato, cifra esatta da confermare',
    comePrenotare: 'da completare — nel mio viaggio è stata organizzata dalla DMC locale',
    cosaPortare: 'costume, crema solare biodegradabile (obbligatoria in molte aree marine protette), maschera propria se si preferisce non usare quella a noleggio',
    perChiEAdatta: 'chiunque sappia stare in acqua con maschera e boccaglio; nessuna esperienza di immersione richiesta',
    miaEsperienza:
      'È IL must della vacanza. Costa parecchio, ma vale ogni peso speso — se dovessi consigliare una sola attività di tutto l\'itinerario, sarebbe questa, ed è probabilmente la conclusione perfetta per chiudere il viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Squalo balena visto da sott\'acqua al largo di Holbox',
  },
  {
    slug: 'bioluminescenza-holbox',
    paeseSlug: 'messico',
    destinazioneSlug: 'holbox',
    nome: 'Bioluminescenza a Punta Mosquito',
    localita: 'Holbox, Punta Mosquito',
    cosE:
      'Un\'uscita serale nelle acque basse di Punta Mosquito, dove micro-organismi marini emettono luce al minimo movimento dell\'acqua: muovendo le mani o i piedi, il mare si illumina di blu.',
    percheFarla: 'Uno dei fenomeni naturali più suggestivi di tutto il viaggio, difficile da vedere altrove con questa facilità.',
    durata: 'una serata (uscita serale, un paio d\'ore indicativamente)',
    periodo: 'migliore da aprile a novembre, dipende da fasi lunari e condizioni meteo',
    costo: 'da completare',
    comePrenotare: 'in autonomia con i "carritos" locali fino al punto, oppure con tour organizzato',
    cosaPortare: 'repellente anti-zanzare in abbondanza — le zanzare a Punta Mosquito sono spietate',
    perChiEAdatta: 'chiunque, attività tranquilla in acque basse',
    miaEsperienza: 'Molto, molto suggestiva — uno dei momenti più belli del viaggio. L\'unico vero avvertimento è portarsi repellente in abbondanza.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Acqua che si illumina di blu bioluminescente di notte a Punta Mosquito',
  },
  {
    slug: 'temazcal',
    paeseSlug: 'messico',
    destinazioneSlug: 'mahahual',
    nome: 'Temazcal',
    localita: 'Yax Ha (tra Mérida/Campeche) e Mahahual — il mio viaggio ne includeva due',
    cosE:
      'Una cerimonia rituale di origine maya guidata da uno sciamano, che si svolge in una capanna bassa e chiusa, al buio: a tutti gli effetti una sauna molto lunga, con pietre roventi ed erbe aromatiche, pensata come rito di purificazione.',
    percheFarla: 'Un\'esperienza che va oltre il semplice "spa": è un rito comunitario, capace di creare un momento di connessione diverso da tutto il resto del viaggio.',
    durata: 'la cerimonia dura circa 1-2 ore, spesso seguita da una cena inclusa',
    periodo: 'tutto l\'anno',
    costo: 'circa 450 MXN a Yax Ha (Scheda pratica del viaggio)',
    comePrenotare: 'da completare',
    cosaPortare: 'costume (in alcuni casi ci si può cambiare dopo), disponibilità mentale a un ambiente buio e molto caldo',
    perChiEAdatta:
      'la maggior parte delle persone, ma chi soffre di claustrofobia dovrebbe saperlo prima: è una sauna lunga, al buio, in uno spazio chiuso',
    miaEsperienza:
      'Un\'esperienza "spirituale" che ha unito emotivamente il gruppo — oltre al rito con lo sciamano è una sauna a tutti gli effetti, molto lunga, al buio. I miei compagni di viaggio lo rifarebbero: è una di quelle esperienze che non si dimentica.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Capanna tradizionale per il rito del Temazcal nella selva dello Yucatán',
  },
  {
    slug: 'cenote-yucatan',
    paeseSlug: 'messico',
    destinazioneSlug: 'valladolid',
    nome: 'Bagno in un cenote',
    localita: 'diffusi in tutto lo Yucatán — nel mio viaggio: Xcanché, Santa Bárbara, Miguel Colorado',
    cosE:
      'I cenote sono voragini naturali di roccia calcarea riempite d\'acqua dolce trasparente, spesso collegate a fiumi sotterranei — una delle esperienze più caratteristiche dello Yucatán.',
    percheFarla: 'Ogni cenote è diverso (a cielo aperto, in grotta, con radici che scendono dall\'alto): vale la pena farne più di uno durante il viaggio.',
    durata: 'in genere 1-2 ore per visita',
    periodo: 'tutto l\'anno',
    costo: 'variabile: nel mio viaggio, indicativamente 120-320 MXN a seconda del cenote',
    comePrenotare: 'quasi sempre accesso diretto in loco, pagamento alla cassa',
    cosaPortare: 'costume, crema solare biodegradabile (obbligatoria in molti cenote per proteggere l\'ecosistema), scarpe d\'acqua utili su alcuni fondali',
    perChiEAdatta: 'chiunque sappia nuotare; alcuni cenote hanno zone più profonde di altri',
    miaEsperienza:
      'Il cenote Xcanché, subito dopo Ek Balam, è stato uno dei combo migliori del viaggio: acqua fresca dopo la visita al sito archeologico, empanadas preparate sul momento appena usciti dall\'acqua.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Cenote naturale con acqua turchese trasparente e radici che scendono dal soffitto di roccia',
  },
  {
    slug: 'chichen-itza',
    paeseSlug: 'messico',
    destinazioneSlug: 'valladolid',
    nome: 'Chichén Itzá',
    localita: 'tra Valladolid e Mérida',
    cosE:
      'Una delle Nuove Sette Meraviglie del Mondo: il grande complesso archeologico maya dominato dalla piramide di Kukulcán (El Castillo).',
    percheFarla: 'È probabilmente il sito archeologico più famoso del Messico, e va vissuto con calma nonostante l\'affluenza.',
    durata: 'circa 2-2h30 per la visita completa',
    periodo: 'aperto tutti i giorni dalle 8:00 alle 17:00 (ultimo ingresso alle 16:00) — meglio arrivare in mattinata per evitare folla e caldo peggiore',
    costo: '614 MXN a persona (biglietto sito, dato dalla Scheda pratica del viaggio — verificare prima della partenza, i prezzi dei siti archeologici cambiano)',
    comePrenotare: 'ingresso diretto in loco; timbro gratuito sul passaporto disponibile all\'ufficio dietro l\'ingresso',
    cosaPortare: 'cappello, crema solare, acqua — il sito è quasi del tutto scoperto e può fare molto caldo',
    perChiEAdatta: 'chiunque, sito accessibile e ben organizzato',
    miaEsperienza: 'Sono entrato in mattinata, con circa due ore per la visita completa — tempo giusto per non avere fretta ma anche non perdere il resto della giornata (Izamal e il cenote Santa Bárbara erano ancora da fare).',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Piramide di Kukulcán a Chichén Itzá sotto un cielo azzurro',
  },
  {
    slug: 'ek-balam-cenote-xcanche',
    paeseSlug: 'messico',
    destinazioneSlug: 'valladolid',
    nome: 'Ek Balam e cenote Xcanché',
    localita: 'vicino Valladolid',
    cosE:
      'Un sito archeologico maya molto meno affollato di Chichén Itzá, con un cenote (Xcanché) a pochi minuti di distanza — spesso raggiungibile in bicicletta o navetta dal sito.',
    percheFarla: 'Combo perfetta tra rovine maya vissute con calma, senza folla, e acqua fresca subito dopo.',
    durata: 'mezza giornata, visita al sito più bagno al cenote',
    periodo: 'tutto l\'anno',
    costo: 'da completare',
    comePrenotare: 'guida prenotabile direttamente in loco (nel mio caso tramite il driver)',
    cosaPortare: 'costume per il cenote, scarpe comode per il sito archeologico',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Ek Balam si visita con guida (prenotata direttamente dal driver), e il cenote Xcanché è a pochi passi. Il mio driver aveva prenotato empanadas in una palapita proprio accanto al cenote: le ho mangiate appena uscito dall\'acqua, preparate sul momento — uno dei ricordi più genuini del viaggio.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Rovine maya di Ek Balam circondate dalla giungla dello Yucatán',
  },
  {
    slug: 'tour-barca-bacalar',
    paeseSlug: 'messico',
    destinazioneSlug: 'bacalar',
    nome: 'Tour in barca e kayak a Bacalar',
    localita: 'Bacalar',
    cosE:
      'Un giro in barca sulla laguna di Bacalar, la "laguna dai sette colori", spesso seguito da un\'ora libera di kayak.',
    percheFarla: 'I colori dell\'acqua, che cambiano visibilmente in base alla profondità, sono uno degli scorci più belli di tutto lo Yucatán.',
    durata: '2 ore di barca + 1 ora di kayak nel mio caso',
    periodo: 'tutto l\'anno',
    costo: 'da completare',
    comePrenotare: 'da completare — nel mio viaggio prenotato dalla DMC locale',
    cosaPortare: 'costume, crema solare biodegradabile, cambio asciutto',
    perChiEAdatta: 'chiunque, attività tranquilla',
    miaEsperienza:
      'Un tour di 2 ore sulla laguna, con un\'ora di kayak inclusa dopo la barca. L\'ho vista solo in giornata da Mahahual, e il tempo stretto si è sentito — con più tempo la rifarei con una notte in loco.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Barca sulla laguna dai sette colori di Bacalar',
  },
  {
    slug: 'snorkeling-tartarughe-mahahual',
    paeseSlug: 'messico',
    destinazioneSlug: 'mahahual',
    nome: 'Snorkeling con le tartarughe',
    localita: 'Mahahual',
    cosE: 'Uscita in snorkeling per nuotare accanto alle tartarughe marine nel loro habitat naturale, lungo la costa di Mahahual.',
    percheFarla: 'Un\'occasione diretta e non troppo affollata di vedere le tartarughe da vicino, senza il traffico turistico di altre zone della Riviera Maya.',
    durata: 'mezza giornata indicativamente',
    periodo: 'tutto l\'anno',
    costo: 'da completare',
    comePrenotare: 'da completare — nel mio viaggio organizzato in loco',
    cosaPortare: 'costume, maschera e boccaglio (spesso forniti), crema solare biodegradabile',
    perChiEAdatta: 'chiunque sappia stare in acqua con maschera e boccaglio',
    miaEsperienza: 'Molto bello e apprezzato — uno dei momenti migliori della giornata più densa del viaggio, insieme a Bacalar e al secondo Temazcal.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Tartaruga marina che nuota in acque turchesi vicino a Mahahual',
  },
  {
    slug: 'rio-lagartos',
    paeseSlug: 'messico',
    destinazioneSlug: 'valladolid',
    nome: 'Río Lagartos',
    localita: 'costa nord dello Yucatán, tra Cancún e Valladolid',
    cosE:
      'Un villaggio di pescatori sulla costa nord dello Yucatán, noto soprattutto per i tour in barca tra le mangrovie alla ricerca di fenicotteri rosa — nel mio viaggio è stata solo una breve sosta di passaggio.',
    percheFarla: 'Come tappa intermedia funziona bene per spezzare il tragitto verso Valladolid; per i fenicotteri servirebbe più tempo dedicato.',
    durata: 'nel mio viaggio, solo una sosta breve al porto',
    periodo: 'da confermare',
    costo: 'da completare',
    comePrenotare: 'da completare',
    cosaPortare: 'da completare',
    perChiEAdatta: 'chi vuole spezzare il tragitto Cancún-Valladolid, o chi ha tempo per un tour fenicotteri dedicato',
    miaEsperienza:
      'L\'ho vista solo come sosta al porto, dove c\'è un bar comodo per rifocillarsi lungo il tragitto verso Ek Balam — non ho fatto il tour dei fenicotteri, quindi non posso dare un giudizio completo su quella parte dell\'esperienza.',
    giudizio: 'bella-non-essenziale',
    alternative: [],
    tripSlugs: ['messico-beach-life'],
    imageAlt: 'Barche di pescatori sulla laguna di Río Lagartos, Yucatán',
  },
]
