import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "New York 360°" (src/content/viaggi/08-new-york-360.md).
// partita-sportiva-live è collegata a Times Square/Midtown come base logistica,
// dato che nessuna delle 5 zone del sito copre direttamente gli stadi di
// Bronx/Queens/Brooklyn dove si giocano le partite.

export const esperienzeNewYork: Esperienza[] = [
  {
    slug: 'musical-broadway',
    paeseSlug: 'new-york',
    destinazioneSlug: 'times-square-midtown',
    nome: 'Un musical a Broadway',
    localita: 'Theater District, Manhattan',
    cosE: 'Uno spettacolo dal vivo in uno dei teatri storici di Broadway, tappa quasi immancabile di qualunque viaggio a New York.',
    percheFarla: 'L\'esperienza teatrale più iconica della città, da vivere almeno una volta.',
    durata: '2-3 ore',
    periodo: 'sera',
    costo: 'variabile secondo lo spettacolo e la disponibilità',
    comePrenotare: 'con largo anticipo, soprattutto in alta stagione: i biglietti migliori vanno a ruba',
    cosaPortare: 'nessun dress code particolare, abbigliamento comodo',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Prenotare con anticipo si è rivelato fondamentale: i musical più richiesti si esauriscono in fretta, soprattutto per le serate del weekend.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['new-york-360'],
    imageAlt: 'Le insegne luminose dei teatri di Broadway a New York',
  },
  {
    slug: 'messa-gospel-harlem',
    paeseSlug: 'new-york',
    destinazioneSlug: 'harlem-central-park',
    nome: 'Messa gospel ad Harlem',
    localita: 'Harlem',
    cosE: 'Una funzione domenicale con canti gospel dal vivo alla Bethel Gospel Assembly o alla Canaan Baptist Church, di circa 2 ore.',
    percheFarla: 'Un\'esperienza di quartiere autentica, non un tour organizzato: il lato di New York meno da cartolina.',
    durata: 'circa 2 ore',
    periodo: 'domenica mattina',
    costo: 'gratuito, nessun obbligo di offerta',
    comePrenotare: 'nessuna prenotazione necessaria',
    cosaPortare: 'abbigliamento rispettoso',
    perChiEAdatta: 'chiunque sia curioso e rispettoso del contesto religioso',
    miaEsperienza:
      'Nessun obbligo di offerta, ci si può alzare e uscire quando si vuole, ma vale la pena restare fino alla fine: è stata un\'esperienza di quartiere autentica, molto diversa da un tour organizzato.',
    giudizio: 'imperdibile',
    alternative: ['Canaan Baptist Church, in alternativa alla Bethel Gospel Assembly'],
    tripSlugs: ['new-york-360'],
    imageAlt: 'Coro gospel durante una funzione domenicale ad Harlem, New York',
  },
  {
    slug: 'high-line-vessel',
    paeseSlug: 'new-york',
    destinazioneSlug: 'rockefeller-chelsea',
    nome: 'High Line e The Vessel',
    localita: 'Chelsea / Hudson Yards',
    cosE: 'La passeggiata sull\'ex ferrovia sopraelevata trasformata in parco lineare, fino alla struttura a nido d\'ape di The Vessel a Hudson Yards.',
    percheFarla: 'Uno dei migliori esempi di rigenerazione urbana della città, e uno dei momenti più rilassati del viaggio.',
    durata: '1h30-2h per circa un miglio e mezzo',
    periodo: 'pomeriggio',
    costo: 'gratuito (The Vessel può richiedere prenotazione)',
    comePrenotare: 'nessuna prenotazione per la High Line',
    cosaPortare: 'scarpe comode',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Uno dei momenti più piacevoli e meno frenetici del viaggio, un buon contrappunto al ritmo serrato delle altre giornate.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['new-york-360'],
    imageAlt: 'La passeggiata pensile della High Line tra i grattacieli di Manhattan, New York',
  },
  {
    slug: 'statua-liberta-ellis-island',
    paeseSlug: 'new-york',
    destinazioneSlug: 'statua-liberta-wall-street',
    nome: 'Statua della Libertà ed Ellis Island',
    localita: 'Liberty Island / Ellis Island',
    cosE: 'Il traghetto verso la Statua della Libertà, vista dal basso, e la visita al museo dell\'immigrazione di Ellis Island.',
    percheFarla: 'Un pezzo di storia americana raccontato da vicino, ancora molto presente camminando per la città.',
    durata: 'mezza giornata',
    periodo: 'mattina',
    costo: 'costo del traghetto variabile secondo l\'operatore',
    comePrenotare: 'il traghetto va prenotato in anticipo',
    cosaPortare: 'documento d\'identità, macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il museo dell\'immigrazione a Ellis Island racconta una parte di storia americana che si sente ancora molto presente camminando per la città — una delle tappe più dense di significato di tutto il viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['new-york-360'],
    imageAlt: 'La Statua della Libertà su Liberty Island, New York',
  },
  {
    slug: 'dumbo-brooklyn-bridge',
    paeseSlug: 'new-york',
    destinazioneSlug: 'ground-zero-dumbo',
    nome: 'DUMBO e traversata del Brooklyn Bridge',
    localita: 'DUMBO, Brooklyn',
    cosE: 'L\'incrocio tra Water Street e Washington Street, con il ponte di Manhattan perfettamente incorniciato tra i palazzi, e la traversata a piedi del Brooklyn Bridge.',
    percheFarla: 'Lo scorcio più fotografato di Brooklyn, e una traversata iconica tra Manhattan e Brooklyn.',
    durata: '2-3 ore',
    periodo: 'pomeriggio',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione necessaria',
    cosaPortare: 'scarpe comode per la traversata del ponte',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il ponte di Manhattan che si allinea perfettamente tra i palazzi di Water Street e Washington Street è lo scorcio più fotografato di Brooklyn per un motivo: dal vivo è ancora più scenografico che in foto.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['new-york-360'],
    imageAlt: 'Il ponte di Manhattan visto dall\'incrocio di Water Street a DUMBO, Brooklyn, New York',
  },
  {
    slug: 'top-of-the-rock',
    paeseSlug: 'new-york',
    destinazioneSlug: 'ground-zero-dumbo',
    nome: 'Tramonto al Top of the Rock',
    localita: 'Rockefeller Center',
    cosE: 'L\'osservatorio panoramico del Rockefeller Center, con vista aperta su Central Park e sull\'Empire State Building.',
    percheFarla: 'Spesso preferito dagli stessi newyorkesi rispetto all\'Empire State come punto panoramico, per la vista che include l\'Empire State stesso.',
    durata: '1 ora',
    periodo: 'tramonto',
    costo: 'da completare',
    comePrenotare: 'con anticipo: i biglietti per il tramonto sono i più richiesti',
    cosaPortare: 'macchina fotografica, giacca leggera (può fare vento in cima)',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il tramonto al Top of the Rock ha chiuso una delle giornate più belle del viaggio, con una vista che include l\'Empire State Building stesso, cosa impossibile se si sale su quest\'ultimo.',
    giudizio: 'imperdibile',
    alternative: ['Empire State Building, se si preferisce averlo come soggetto principale della foto invece che nel panorama'],
    tripSlugs: ['new-york-360'],
    imageAlt: 'Il tramonto su Manhattan visto dal Top of the Rock, New York',
  },
  {
    slug: 'partita-sportiva-live',
    paeseSlug: 'new-york',
    destinazioneSlug: 'times-square-midtown',
    nome: 'Una partita sportiva dal vivo',
    localita: 'Yankee Stadium (Bronx), Citi Field (Queens) o Barclays Center (Brooklyn)',
    cosE: 'Una partita di baseball MLB (Yankees o Mets) in piena corsa playoff, oppure di basket WNBA con le New York Liberty al Barclays Center.',
    percheFarla: 'Il modo più autentico di vivere la città come un newyorkese qualunque per una sera, tra hot dog, birra e la settima inning stretch.',
    durata: 'una serata, circa 3 ore',
    periodo: 'settembre, per unire i playoff MLB con i playoff WNBA (la stagione NBA inizia solo a ottobre)',
    costo: 'variabile secondo evento e posto, i biglietti WNBA generalmente più economici di una partita NBA',
    comePrenotare: 'con qualche giorno di anticipo, soprattutto per le partite serali più richieste',
    cosaPortare: 'nessun requisito particolare',
    perChiEAdatta: 'chiunque voglia un\'esperienza sportiva americana autentica',
    giudizio: 'da-verificare',
    alternative: ['New York Liberty (WNBA) al Barclays Center, alternativa al baseball se si preferisce il basket in questo periodo dell\'anno'],
    tripSlugs: [],
    imageAlt: 'Stadio gremito durante una partita sportiva serale a New York',
  },
]
