import type { Esperienza } from '@/lib/types'

// Contenuto riutilizzato dal viaggio "Lofoten in 7 giorni" (src/content/viaggi/01-lofoten-estate-2025.md).

export const esperienzeNorvegia: Esperienza[] = [
  {
    slug: 'trollfjord-rib',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'svolvaer',
    nome: 'Trollfjord in gommone (RIB)',
    localita: 'Svolvær',
    cosE:
      'Un\'escursione in RIB (gommone veloce) organizzata da Lofoten Explorer verso il Trollfjord, un fiordo stretto e spettacolare, con avvistamento di aquile di mare a pochi metri dalla barca.',
    percheFarla: 'Una delle esperienze più belle di tutto il viaggio: velocità, paesaggio e fauna selvatica in un\'unica uscita, con guide professionali e simpatiche.',
    durata: 'circa 2 ore',
    periodo: 'stagione estiva, quando le uscite sono operative',
    costo: 'da completare',
    comePrenotare: 'con Lofoten Explorer, meglio con anticipo — è l\'esperienza più richiesta della zona',
    cosaPortare: 'tuta termica (fornita dall\'operatore), guanti e sottoguanti propri, cappellino',
    perChiEAdatta: 'chiunque, tute termiche fornite; il gommone va veloce quindi meglio vestirsi comunque a strati',
    miaEsperienza:
      'Tute termiche fornite, avvistamento di aquile di mare a pochi metri dalla barca, guide professionali e simpatiche — una delle esperienze più belle del viaggio. Consiglio di portare guanti/sottoguanti e cappellino: il vento in barca si sente parecchio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Gommone veloce che naviga nel Trollfjord tra le montagne, Lofoten',
  },
  {
    slug: 'reinebringen',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'reine',
    nome: 'Reinebringen',
    localita: 'Reine',
    cosE:
      'Il trekking più iconico delle Lofoten: 1.978 scalini in pietra costruiti da sherpa nepalesi, per 448 metri di dislivello in appena 1,1 km, fino a un punto panoramico che domina Reine e i fiordi circostanti.',
    percheFarla: 'È il panorama-simbolo di tutte le Lofoten, quello che si vede su ogni cartolina e ogni guida di viaggio.',
    durata: 'tempo medio 2-4 ore; il mio tempo totale è stato di 1h50 (45 min salita, 30 min sosta, 30 min discesa)',
    periodo: 'estate, con cielo sereno — è l\'unica condizione che rende il trekking davvero valido',
    costo: 'gratuito (parcheggio a Reine 200 NOK/3h)',
    comePrenotare: 'nessuna prenotazione necessaria, accesso libero al sentiero',
    cosaPortare: 'scarpe da trekking con buon grip, acqua, strati per il vento in quota',
    perChiEAdatta: 'chi ha un minimo di allenamento: il sentiero è tecnicamente semplice (solo scalini) ma il dislivello si sente',
    miaEsperienza:
      'Sentiero semplice dal punto di vista tecnico (solo scalini) ma il dislivello si sente. Vista mozzafiato, ma vale davvero solo con cielo sereno — con la nebbia o le nuvole basse perde gran parte del senso.',
    giudizio: 'imperdibile',
    alternative: ['Festvågtind trail, più tecnico e meno affollato'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Vista dall\'alto del Reinebringen sul villaggio di Reine e i fiordi, Lofoten',
  },
  {
    slug: 'festvagtind-trail',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'henningsvaer',
    nome: 'Festvågtind trail',
    localita: 'Henningsvær (parcheggio al Festvågtind Parking)',
    cosE:
      'Un trekking di 3 km per 500 m di dislivello, più tecnico del Reinebringen: tratti rocciosi e terreno sabbioso/irregolare, con un punto panoramico intermedio su un laghetto alpino dopo circa 40 minuti.',
    percheFarla: 'Un\'alternativa più selvaggia e meno affollata al Reinebringen, con la possibilità di scegliere tra un belvedere più semplice o la vetta vera e propria, più impegnativa.',
    durata: 'circa 40 minuti fino al punto panoramico intermedio; di più per la vetta',
    periodo: 'estate, con buone condizioni meteo per i tratti rocciosi',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione, accesso libero dal parcheggio dedicato',
    cosaPortare: 'scarpe da trekking con buon grip (i tratti rocciosi e sabbiosi richiedono più attenzione che al Reinebringen)',
    perChiEAdatta: 'chi ha già un po\' di esperienza in montagna, o chi ha già fatto il Reinebringen e cerca qualcosa di più tecnico',
    miaEsperienza:
      'Più tecnico e "selvaggio" del Reinebringen: tratti rocciosi e terreno irregolare che richiedono più attenzione. Dal punto panoramico intermedio si può proseguire a destra verso un belvedere più semplice o a sinistra verso la vetta, più impegnativa.',
    giudizio: 'la-rifarei',
    alternative: ['Reinebringen, più semplice tecnicamente ma più affollato'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Sentiero roccioso del Festvågtind trail con vista sul mare, Lofoten',
  },
  {
    slug: 'spiaggia-di-bunes',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'reine',
    nome: 'Spiaggia di Bunes',
    localita: 'Vindstad (raggiungibile in traghetto da Reine)',
    cosE:
      'Una spiaggia immensa e aperta sull\'oceano, incastonata tra le montagne, raggiungibile solo via traghetto fino a Vindstad e poi con una camminata di circa un\'ora tra sentieri pianeggianti e un breve tratto in salita.',
    percheFarla: 'Una delle spiagge più suggestive di tutta la Norvegia, e uno dei pochi posti dell\'itinerario raggiungibile solo via mare — un\'esperienza diversa dai trekking "classici".',
    durata: 'mezza giornata: traghetto (~40 min a tratta) + circa 40-50 minuti di cammino per direzione',
    periodo: 'estate, quando il servizio traghetti è attivo',
    costo: 'da completare (biglietto traghetto)',
    comePrenotare: 'traghetto per Vindstad da Reine, meglio arrivare con 30 minuti di anticipo anche con posti riservati',
    cosaPortare: 'pranzo al sacco, scarpe comode, strati per il vento in spiaggia',
    perChiEAdatta: 'chiunque, cammino semplice e pianeggiante per la maggior parte del percorso',
    miaEsperienza:
      'Dopo il traghetto e una sosta alla "casetta gialla" (ex scuola, oggi bar comunitario gestito da volontari, ottimi cinnamon roll), il sentiero pianeggiante porta a una casetta bianca fotogenica, poi una salita leggera costeggia un piccolo cimitero fino a un colle panoramico e infine alla spiaggia: immensa, aperta sull\'oceano, incastonata tra le montagne. Ho fatto pranzo al sacco alla casetta gialla in attesa del traghetto di ritorno — tra i ricordi più forti di tutto il viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Spiaggia di Bunes incastonata tra le montagne, raggiungibile solo in traghetto, Lofoten',
  },
  {
    slug: 'viking-museum-borg',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'reine',
    nome: 'Viking Museum di Borg',
    localita: 'Borg (circa 55 minuti d\'auto da Svolvær, sul tragitto verso Reine)',
    cosE:
      'Un museo dedicato alla storia vichinga delle Lofoten, con un film introduttivo, un\'esposizione curata e la ricostruzione di una longhouse vichinga a grandezza naturale.',
    percheFarla: 'Una pausa culturale ben fatta lungo il tragitto tra Svolvær e Reine, utile per capire il contesto storico della zona.',
    durata: 'film introduttivo di circa 20 minuti + tempo libero per l\'esposizione, indicativamente 1-1h30 in totale',
    periodo: 'apertura verso metà mattina, da verificare in base alla stagione',
    costo: 'da completare',
    comePrenotare: 'ingresso diretto in loco',
    cosaPortare: 'da completare',
    perChiEAdatta: 'chi vuole spezzare il tragitto Svolvær-Reine con una tappa culturale; le attività esterne (tiro con l\'arco, lancio dell\'ascia, giri a cavallo/in barca) sono su prenotazione separata',
    miaEsperienza:
      'Visita con calma: film introduttivo, esposizione ben curata, ricostruzione della longhouse vichinga. Le attività esterne (tiro con l\'arco, lancio dell\'ascia, giri a cavallo/in barca su prenotazione) le ho saltate per il freddo e i tempi di attesa — ma il museo da solo vale la tappa.',
    giudizio: 'bella-non-essenziale',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Ricostruzione di una longhouse vichinga al Viking Museum di Borg, Lofoten',
  },
  {
    slug: 'museo-dei-pescatori',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'a',
    nome: 'Museo dei Pescatori',
    localita: 'Å',
    cosE:
      'Un museo che racconta lo stile di vita delle comunità di pescatori delle Lofoten, con visita guidata in inglese.',
    percheFarla: 'Il modo migliore per capire la storia e la cultura locale, in uno dei villaggi più autentici dell\'arcipelago.',
    durata: 'circa un\'ora (visita guidata)',
    periodo: 'tutto l\'anno, visite guidate in tarda mattinata',
    costo: 'da completare',
    comePrenotare: 'in loco, verificare gli orari delle visite guidate in inglese',
    cosaPortare: 'da completare',
    perChiEAdatta: 'chiunque sia interessato alla storia locale; interessante anche nei giorni di pioggia',
    miaEsperienza:
      'Un\'ora ben spesa per capire davvero lo stile di vita delle comunità di pescatori delle Lofoten — interessante anche sotto la pioggia, quando le opzioni all\'aperto si riducono.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Casette rosse tradizionali dei pescatori al Museo dei Pescatori di Å, Lofoten',
  },
  {
    slug: 'nesland-nusfjord',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'nesland-flakstad',
    nome: 'Passeggiata Nesland-Nusfjord',
    localita: 'da Nesland al villaggio di Nusfjord',
    cosE:
      'Una passeggiata panoramica di circa 11 km andata e ritorno lungo il fiordo, tra bosco e tratti rocciosi, senza difficoltà tecniche, fino al villaggio di Nusfjord.',
    percheFarla: 'Un\'ottima alternativa più leggera dopo i trekking impegnativi dei giorni precedenti (Reinebringen, Festvågtind), e senza le folle dei sentieri più famosi.',
    durata: '11 km A/R, alcune ore a passo tranquillo',
    periodo: 'estate, quando il sentiero è libero da neve',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione, accesso libero dal villaggio di Nesland',
    cosaPortare: 'scarpe da trekking, acqua, eventualmente pranzo al sacco',
    perChiEAdatta: 'chiunque, nessuna difficoltà tecnica, buon livello di camminata generale richiesto per gli 11 km totali',
    miaEsperienza:
      'L\'ho fatta appena il cielo si è aperto, nel pomeriggio: senza difficoltà tecniche, ma con panorami che non hanno nulla da invidiare ai trekking più famosi — e senza le folle del Reinebringen.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Sentiero panoramico lungo il fiordo tra Nesland e Nusfjord, Lofoten',
  },
  {
    slug: 'aurora-chase-minibus-tromso',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'tromso',
    nome: 'Aurora chase in minibus',
    localita: 'Tromsø e dintorni',
    cosE:
      'Un\'escursione serale con guida in minibus (in genere gruppi piccoli, 8-16 persone) per inseguire il cielo sereno e l\'aurora boreale, allontanandosi dall\'inquinamento luminoso della città. La rotta non è fissa: parte dal centro di Tromsø e la guida decide in tempo reale se dirigersi verso la costa, nell\'entroterra o, in certe serate, anche oltre confine in Finlandia, seguendo le previsioni meteo e l\'indice dell\'aurora. Diversi operatori includono un momento con fuoco/tè caldo e consigli di fotografia notturna.',
    percheFarla: 'È il modo più efficace per vedere l\'aurora da Tromsø: la guida sceglie in tempo reale dove il cielo è più sereno, invece di affidarsi al caso restando in città.',
    durata: 'una serata, tipicamente 6-8 ore incluso il tempo di ricerca del cielo sereno',
    periodo: 'da fine settembre a fine marzo, con il periodo di notte polare (dicembre-gennaio) che allunga le ore di buio utili',
    costo: 'indicativamente 100-160€ a persona; operatori come Chasing Lights e Tromsø Friluftsenter sono tra i più noti della zona',
    comePrenotare: 'tour organizzato con guida, meglio con un minimo di anticipo nei mesi di punta (novembre-marzo); ritrovo tipicamente in centro città',
    cosaPortare: 'strati pesanti, si resta fermi all\'aperto per lunghi tratti in attesa del cielo sereno — molti operatori forniscono tute termiche extra',
    perChiEAdatta: 'chiunque, nessuna difficoltà fisica; è però una serata lunga e all\'aperto, da mettere in conto per chi soffre particolarmente il freddo',
    miaEsperienza:
      'Il ricordo più nitido di tutto il viaggio: dopo un\'attesa nel freddo, l\'aurora che ha iniziato a muoversi nel cielo per la prima volta.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['tromso'],
    imageAlt: 'Minibus fermo su una strada innevata con aurora boreale visibile in cielo vicino a Tromsø',
  },
  {
    slug: 'husky-sledding-tromso',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'tromso',
    nome: 'Husky sledding',
    localita: 'Tromsø Villmarkssenter, isola di Kvaløya',
    cosE:
      'Un\'escursione in slitta trainata da husky organizzata da centri come Tromsø Villmarkssenter, che ospita circa 200 husky alaskani. Dopo un trasferimento di circa 25 minuti dal centro città si riceve una tuta termica e degli stivali, poi si parte: nella formula più diffusa si viene portati da un musher esperto (comoda per famiglie, anziani, fotografi), ma esistono anche formule "guida tu stesso" per chi vuole prendere in mano le redini. Al ritorno si visita il canile e si conoscono alcuni dei cuccioli, con caffè e dolce offerti.',
    percheFarla: 'Un classico delle attività artiche, con l\'adrenalina della partenza e il silenzio quasi totale una volta in corsa — e un dopo-slitta genuino tra i cani, non solo una foto ricordo.',
    durata: 'la slitta vera e propria dura circa 45 minuti; con transfer, vestizione e visita al canile l\'uscita occupa mezza giornata',
    periodo: 'inverno, indicativamente da dicembre a fine marzo con neve al suolo',
    costo: 'indicativamente 170-320€ a persona, a seconda della formula (passeggero o self-drive) e degli extra inclusi',
    comePrenotare: 'tour organizzato con guida, prenotabile direttamente sul sito di Tromsø Villmarkssenter o tramite le principali piattaforme di attività — consigliato prenotare con anticipo, è tra i tour più richiesti della città',
    cosaPortare: 'tuta termica e stivali forniti dall\'operatore; propri guanti pesanti e un cambio caldo sono comunque utili',
    perChiEAdatta: 'chiunque nella formula "passeggero", adatta anche a famiglie con bambini piccoli e persone con mobilità ridotta; la formula self-drive richiede un minimo di equilibrio',
    miaEsperienza:
      'I cani che scalpitano prima della partenza, il freddo pungente attutito dal movimento, e un silenzio quasi totale una volta in corsa.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['tromso'],
    imageAlt: 'Slitta trainata da husky su un sentiero innevato vicino a Tromsø',
  },
  {
    slug: 'sami-renne-lavvu-tromso',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'tromso',
    nome: 'Esperienza sami con le renne',
    localita: 'dintorni di Tromsø (tour con operatori come Tromsø Arctic Reindeer)',
    cosE:
      'Un\'escursione con guida sami tra centinaia di renne al pascolo (alcuni operatori ne hanno circa 300), con un momento dedicato a nutrirle a mano, un giro in slitta trainata dalle renne stesse, e infine un ritrovo in una tenda tradizionale (lavvu) riscaldata da un fuoco centrale, con racconti sulla cultura sami, una cena tipica e spesso un joik (il canto tradizionale sami) intonato dalle guide.',
    percheFarla: 'Il modo più diretto per avvicinarsi alla cultura sami, con un\'esperienza che unisce gli animali, il racconto e il cibo tradizionale in un\'unica uscita.',
    durata: 'mezza giornata (circa 3-4 ore); alcuni operatori offrono anche la versione giornata intera',
    periodo: 'stagione invernale, indicativamente da inizio novembre a inizio aprile',
    costo: 'da circa 145€ a persona per la versione base con slitta e cena; le versioni più lunghe/complete arrivano fino a 250-260€',
    comePrenotare: 'tour organizzato, ritrovo tipicamente al terminal bus del porto di Tromsø (Prostneset) con partenze mattutine o pomeridiane',
    cosaPortare: 'strati pesanti, si passa diverso tempo all\'aperto tra le renne prima del ritrovo al caldo nella lavvu',
    perChiEAdatta: 'chiunque, adatto anche a chi è alla prima esperienza con animali di questo tipo e a famiglie',
    miaEsperienza:
      'Le renne al pascolo, il momento di nutrirle da vicino, e poi il calore della lavvu dopo ore al freddo — con i racconti delle guide sami che restano tra le cose più belle del viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['tromso'],
    imageAlt: 'Renne al pascolo nella neve vicino a una tenda sami tradizionale (lavvu) al tramonto',
  },
  {
    slug: 'whale-watching-tromso',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'tromso',
    nome: 'Whale watching invernale',
    localita: 'fiordi intorno a Skjervøy e Kvænangen, in barca da Tromsø',
    cosE:
      'Un\'uscita in barca verso i fiordi a nord di Tromsø, dove tra ottobre e gennaio orche e megattere si concentrano per nutrirsi delle grandi quantità di aringa che svernano in quelle acque. Molti tour combinano un trasferimento in pullman/minibus fino a Skjervøy (circa 2h30 da Tromsø) con l\'uscita in barca vera e propria; alcuni operatori, come Brim Explorer, usano imbarcazioni ibride-elettriche silenziose per non disturbare gli animali.',
    percheFarla: 'Una delle esperienze naturalistiche più forti della zona, non fatta in questo viaggio ma da tenere in considerazione per tornare: la concentrazione di orche e megattere in questo periodo è tra le più alte al mondo.',
    durata: 'giornata intera, partenza presto al mattino (7:30-8:00) e rientro nel tardo pomeriggio',
    periodo: 'circa metà ottobre-fine gennaio, stagione di orche e megattere legata ai banchi di aringa',
    costo: 'indicativamente 130-260€ a persona, con forti differenze tra operatori — non conviene necessariamente scegliere l\'opzione più economica, la qualità della guida e della barca cambia molto l\'esperienza',
    comePrenotare: 'diversi operatori attivi in zona (es. Brim Explorer e altri specializzati), prenotazione online con largo anticipo nei weekend di alta stagione',
    cosaPortare: 'strati pesanti e impermeabili, si è esposti al freddo e agli spruzzi in barca per gran parte della giornata',
    perChiEAdatta: 'chiunque non soffra il mare, giornata lunga e prevalentemente all\'aperto',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Pinna di orca che emerge dall\'acqua di un fiordo norvegese in inverno',
  },
  {
    slug: 'glass-igloo-lyngen',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'tromso',
    nome: 'Notte in igloo di vetro nel Lyngenfjord',
    localita: 'Lyngen North, zona del Lyngenfjord, circa 1h30-2h da Tromsø',
    cosE:
      'Un pernottamento in un igloo con pareti/soffitto in vetro (non ghiaccio: struttura permanente riscaldata, il "glass" è nel nome), pensato per osservare l\'aurora boreale direttamente dal letto. Il resort più noto della zona, Lyngen North, offre igloo "180°" e "360°" da 22 m² per 2 persone, oltre a Sky Suites, con sauna a botte, lavvu tradizionale e vasca idromassaggio esterna in comune.',
    percheFarla: 'Un\'esperienza scenografica diversa dalle escursioni giornaliere, non fatta in questo viaggio ma segnalata come possibile tappa extra per un prossimo: gli igloo sono pochi e vanno a ruba nella stagione dell\'aurora.',
    durata: 'una notte (o più)',
    periodo: 'stagione dell\'aurora, indicativamente settembre-aprile',
    costo: 'indicativamente 380-420€ a notte per l\'igloo di vetro (2 persone)',
    comePrenotare: 'direttamente su lyngen-north.com, con largo anticipo — la disponibilità nella stagione dell\'aurora si esaurisce in fretta',
    cosaPortare: 'nulla di particolare, è una struttura riscaldata e attrezzata',
    perChiEAdatta: 'chi vuole vivere l\'aurora in modo più intimo, senza uscite organizzate, e non ha problemi di budget per una notte fuori dall\'ordinario',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Igloo di vetro innevato con aurora boreale visibile attraverso il soffitto trasparente',
  },
]
