import type { Esperienza } from '@/lib/types'

// Contenuto riutilizzato dal viaggio "Lofoten in 7 giorni" (src/content/viaggi/01-lofoten-estate-2025.md).

export const esperienzeNorvegia: Esperienza[] = [
  {
    slug: 'trollfjord-rib',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'svolvaer',
    nome: 'Trollfjord in gommone (RIB)',
    localita: 'Svolvær',
    cosE:
      'Un\'escursione in RIB (gommone veloce) organizzata da Lofoten Explorer verso il Trollfjord, un fiordo stretto e spettacolare, con avvistamento di aquile di mare a pochi metri dalla barca.',
    percheFarla: 'Una delle esperienze più belle di tutto il viaggio: velocità, paesaggio e fauna selvatica in un\'unica uscita, con guide professionali e simpatiche.',
    durata: 'circa 2 ore',
    periodo: 'stagione estiva, quando le uscite sono operative',
    costo: 'da completare',
    comePrenotare: 'con Lofoten Explorer, meglio con anticipo — è l\'esperienza più richiesta della zona',
    cosaPortare: 'tuta termica (fornita dall\'operatore), guanti e sottoguanti propri, cappellino',
    perChiEAdatta: 'chiunque, tute termiche fornite; il gommone va veloce quindi meglio vestirsi comunque a strati',
    miaEsperienza:
      'Tute termiche fornite, avvistamento di aquile di mare a pochi metri dalla barca, guide professionali e simpatiche — una delle esperienze più belle del viaggio. Consiglio di portare guanti/sottoguanti e cappellino: il vento in barca si sente parecchio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Gommone veloce che naviga nel Trollfjord tra le montagne, Lofoten',
  },
  {
    slug: 'reinebringen',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'reine',
    nome: 'Reinebringen',
    localita: 'Reine',
    cosE:
      'Il trekking più iconico delle Lofoten: 1.978 scalini in pietra costruiti da sherpa nepalesi, per 448 metri di dislivello in appena 1,1 km, fino a un punto panoramico che domina Reine e i fiordi circostanti.',
    percheFarla: 'È il panorama-simbolo di tutte le Lofoten, quello che si vede su ogni cartolina e ogni guida di viaggio.',
    durata: 'tempo medio 2-4 ore; il mio tempo totale è stato di 1h50 (45 min salita, 30 min sosta, 30 min discesa)',
    periodo: 'estate, con cielo sereno — è l\'unica condizione che rende il trekking davvero valido',
    costo: 'gratuito (parcheggio a Reine 200 NOK/3h)',
    comePrenotare: 'nessuna prenotazione necessaria, accesso libero al sentiero',
    cosaPortare: 'scarpe da trekking con buon grip, acqua, strati per il vento in quota',
    perChiEAdatta: 'chi ha un minimo di allenamento: il sentiero è tecnicamente semplice (solo scalini) ma il dislivello si sente',
    miaEsperienza:
      'Sentiero semplice dal punto di vista tecnico (solo scalini) ma il dislivello si sente. Vista mozzafiato, ma vale davvero solo con cielo sereno — con la nebbia o le nuvole basse perde gran parte del senso.',
    giudizio: 'imperdibile',
    alternative: ['Festvågtind trail, più tecnico e meno affollato'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Vista dall\'alto del Reinebringen sul villaggio di Reine e i fiordi, Lofoten',
  },
  {
    slug: 'festvagtind-trail',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'henningsvaer',
    nome: 'Festvågtind trail',
    localita: 'Henningsvær (parcheggio al Festvågtind Parking)',
    cosE:
      'Un trekking di 3 km per 500 m di dislivello, più tecnico del Reinebringen: tratti rocciosi e terreno sabbioso/irregolare, con un punto panoramico intermedio su un laghetto alpino dopo circa 40 minuti.',
    percheFarla: 'Un\'alternativa più selvaggia e meno affollata al Reinebringen, con la possibilità di scegliere tra un belvedere più semplice o la vetta vera e propria, più impegnativa.',
    durata: 'circa 40 minuti fino al punto panoramico intermedio; di più per la vetta',
    periodo: 'estate, con buone condizioni meteo per i tratti rocciosi',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione, accesso libero dal parcheggio dedicato',
    cosaPortare: 'scarpe da trekking con buon grip (i tratti rocciosi e sabbiosi richiedono più attenzione che al Reinebringen)',
    perChiEAdatta: 'chi ha già un po\' di esperienza in montagna, o chi ha già fatto il Reinebringen e cerca qualcosa di più tecnico',
    miaEsperienza:
      'Più tecnico e "selvaggio" del Reinebringen: tratti rocciosi e terreno irregolare che richiedono più attenzione. Dal punto panoramico intermedio si può proseguire a destra verso un belvedere più semplice o a sinistra verso la vetta, più impegnativa.',
    giudizio: 'la-rifarei',
    alternative: ['Reinebringen, più semplice tecnicamente ma più affollato'],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Sentiero roccioso del Festvågtind trail con vista sul mare, Lofoten',
  },
  {
    slug: 'spiaggia-di-bunes',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'reine',
    nome: 'Spiaggia di Bunes',
    localita: 'Vindstad (raggiungibile in traghetto da Reine)',
    cosE:
      'Una spiaggia immensa e aperta sull\'oceano, incastonata tra le montagne, raggiungibile solo via traghetto fino a Vindstad e poi con una camminata di circa un\'ora tra sentieri pianeggianti e un breve tratto in salita.',
    percheFarla: 'Una delle spiagge più suggestive di tutta la Norvegia, e uno dei pochi posti dell\'itinerario raggiungibile solo via mare — un\'esperienza diversa dai trekking "classici".',
    durata: 'mezza giornata: traghetto (~40 min a tratta) + circa 40-50 minuti di cammino per direzione',
    periodo: 'estate, quando il servizio traghetti è attivo',
    costo: 'da completare (biglietto traghetto)',
    comePrenotare: 'traghetto per Vindstad da Reine, meglio arrivare con 30 minuti di anticipo anche con posti riservati',
    cosaPortare: 'pranzo al sacco, scarpe comode, strati per il vento in spiaggia',
    perChiEAdatta: 'chiunque, cammino semplice e pianeggiante per la maggior parte del percorso',
    miaEsperienza:
      'Dopo il traghetto e una sosta alla "casetta gialla" (ex scuola, oggi bar comunitario gestito da volontari, ottimi cinnamon roll), il sentiero pianeggiante porta a una casetta bianca fotogenica, poi una salita leggera costeggia un piccolo cimitero fino a un colle panoramico e infine alla spiaggia: immensa, aperta sull\'oceano, incastonata tra le montagne. Ho fatto pranzo al sacco alla casetta gialla in attesa del traghetto di ritorno — tra i ricordi più forti di tutto il viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Spiaggia di Bunes incastonata tra le montagne, raggiungibile solo in traghetto, Lofoten',
  },
  {
    slug: 'viking-museum-borg',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'reine',
    nome: 'Viking Museum di Borg',
    localita: 'Borg (circa 55 minuti d\'auto da Svolvær, sul tragitto verso Reine)',
    cosE:
      'Un museo dedicato alla storia vichinga delle Lofoten, con un film introduttivo, un\'esposizione curata e la ricostruzione di una longhouse vichinga a grandezza naturale.',
    percheFarla: 'Una pausa culturale ben fatta lungo il tragitto tra Svolvær e Reine, utile per capire il contesto storico della zona.',
    durata: 'film introduttivo di circa 20 minuti + tempo libero per l\'esposizione, indicativamente 1-1h30 in totale',
    periodo: 'apertura verso metà mattina, da verificare in base alla stagione',
    costo: 'da completare',
    comePrenotare: 'ingresso diretto in loco',
    cosaPortare: 'da completare',
    perChiEAdatta: 'chi vuole spezzare il tragitto Svolvær-Reine con una tappa culturale; le attività esterne (tiro con l\'arco, lancio dell\'ascia, giri a cavallo/in barca) sono su prenotazione separata',
    miaEsperienza:
      'Visita con calma: film introduttivo, esposizione ben curata, ricostruzione della longhouse vichinga. Le attività esterne (tiro con l\'arco, lancio dell\'ascia, giri a cavallo/in barca su prenotazione) le ho saltate per il freddo e i tempi di attesa — ma il museo da solo vale la tappa.',
    giudizio: 'bella-non-essenziale',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Ricostruzione di una longhouse vichinga al Viking Museum di Borg, Lofoten',
  },
  {
    slug: 'museo-dei-pescatori',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'a',
    nome: 'Museo dei Pescatori',
    localita: 'Å',
    cosE:
      'Un museo che racconta lo stile di vita delle comunità di pescatori delle Lofoten, con visita guidata in inglese.',
    percheFarla: 'Il modo migliore per capire la storia e la cultura locale, in uno dei villaggi più autentici dell\'arcipelago.',
    durata: 'circa un\'ora (visita guidata)',
    periodo: 'tutto l\'anno, visite guidate in tarda mattinata',
    costo: 'da completare',
    comePrenotare: 'in loco, verificare gli orari delle visite guidate in inglese',
    cosaPortare: 'da completare',
    perChiEAdatta: 'chiunque sia interessato alla storia locale; interessante anche nei giorni di pioggia',
    miaEsperienza:
      'Un\'ora ben spesa per capire davvero lo stile di vita delle comunità di pescatori delle Lofoten — interessante anche sotto la pioggia, quando le opzioni all\'aperto si riducono.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Casette rosse tradizionali dei pescatori al Museo dei Pescatori di Å, Lofoten',
  },
  {
    slug: 'nesland-nusfjord',
    paeseSlug: 'norvegia',
    destinazioneSlug: 'nesland-flakstad',
    nome: 'Passeggiata Nesland-Nusfjord',
    localita: 'da Nesland al villaggio di Nusfjord',
    cosE:
      'Una passeggiata panoramica di circa 11 km andata e ritorno lungo il fiordo, tra bosco e tratti rocciosi, senza difficoltà tecniche, fino al villaggio di Nusfjord.',
    percheFarla: 'Un\'ottima alternativa più leggera dopo i trekking impegnativi dei giorni precedenti (Reinebringen, Festvågtind), e senza le folle dei sentieri più famosi.',
    durata: '11 km A/R, alcune ore a passo tranquillo',
    periodo: 'estate, quando il sentiero è libero da neve',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione, accesso libero dal villaggio di Nesland',
    cosaPortare: 'scarpe da trekking, acqua, eventualmente pranzo al sacco',
    perChiEAdatta: 'chiunque, nessuna difficoltà tecnica, buon livello di camminata generale richiesto per gli 11 km totali',
    miaEsperienza:
      'L\'ho fatta appena il cielo si è aperto, nel pomeriggio: senza difficoltà tecniche, ma con panorami che non hanno nulla da invidiare ai trekking più famosi — e senza le folle del Reinebringen.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['lofoten-estate-2025'],
    imageAlt: 'Sentiero panoramico lungo il fiordo tra Nesland e Nusfjord, Lofoten',
  },
]
