import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Sri Lanka in 12 giorni" (src/content/viaggi/04-sri-lanka-2023.md).

export const esperienzeSriLanka: Esperienza[] = [
  {
    slug: 'safari-minneriya',
    paeseSlug: 'sri-lanka',
    destinazioneSlug: 'dambulla-sigiriya',
    nome: 'Safari a Minneriya',
    localita: 'Minneriya',
    cosE: 'Un safari in jeep nel Parco Nazionale di Minneriya, tra i migliori posti al mondo per vedere elefanti selvatici in libertà.',
    percheFarla: 'Il "gathering" di elefanti a Minneriya è uno degli spettacoli naturalistici più belli dello Sri Lanka.',
    durata: 'mezza giornata',
    periodo: 'da confermare secondo la stagione (alternative valide: Hurulu o Kaudulla, secondo dove si spostano gli elefanti)',
    costo: 'circa 12.000 LKR a jeep (max 6-7 persone) + ingresso',
    comePrenotare: 'tramite il DMC locale del viaggio',
    cosaPortare: 'macchina fotografica con zoom, cappello, acqua',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Vedere gli elefanti selvatici radunarsi a Minneriya è stato uno dei momenti più belli del triangolo culturale, con un pranzo tipico ottimo consumato lungo il percorso di rientro.',
    giudizio: 'imperdibile',
    alternative: ['Safari a Hurulu o Kaudulla, secondo dove si sono spostati gli elefanti nel periodo del viaggio'],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Elefanti selvatici nel Parco Nazionale di Minneriya, Sri Lanka',
  },
  {
    slug: 'trekking-sigiriya',
    paeseSlug: 'sri-lanka',
    destinazioneSlug: 'dambulla-sigiriya',
    nome: 'Trekking a Sigiriya',
    localita: 'Sigiriya',
    cosE: 'La salita alla Rocca del Leone, con le fondamenta del palazzo reale del V secolo e gli affreschi delle fanciulle celesti lungo la parete a specchio.',
    percheFarla: 'Uno dei siti archeologici più spettacolari dell\'Asia, e uno dei momenti clou di tutto il viaggio.',
    durata: '1h30-2h di salita',
    periodo: 'mattina presto, per evitare il caldo',
    costo: '10.000-30 USD a persona a seconda della tariffa applicata',
    comePrenotare: 'biglietto acquistabile in loco',
    cosaPortare: 'sarong, acqua, snack, scarpe da trekking',
    perChiEAdatta: 'chi ha una base di allenamento fisico',
    miaEsperienza:
      'La vista dalla cima, con le fondamenta dell\'antico palazzo reale e gli affreschi delle fanciulle celesti lungo la parete a specchio, è uno dei momenti clou del viaggio, anche se personalmente ho trovato il tramonto da Pidurangala il giorno prima altrettanto memorabile.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'La Rocca del Leone di Sigiriya con le rovine del palazzo reale in cima, Sri Lanka',
  },
  {
    slug: 'tempio-del-dente',
    paeseSlug: 'sri-lanka',
    destinazioneSlug: 'kandy',
    nome: 'Cerimonia serale al Tempio del Dente',
    localita: 'Kandy',
    cosE: 'La cerimonia serale al Temple of the Tooth, che custodisce una reliquia sacra del Buddha: tamburi, luci che calano, atmosfera spirituale intensa.',
    percheFarla: 'Una delle esperienze più autentiche e sentite di tutto lo Sri Lanka, ben oltre la semplice visita turistica.',
    durata: 'circa 1 ora, più l\'attesa in fila',
    periodo: 'tardo pomeriggio/sera',
    costo: '2.000 LKR',
    comePrenotare: 'nessuna prenotazione, biglietto in loco',
    cosaPortare: 'sarong (obbligatorio), abbigliamento che copra le spalle e le ginocchia',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'I tamburi che iniziano poco prima del calare della luce, con la fila già formata dal tardo pomeriggio, creano un\'atmosfera spirituale che resta impressa più di molti siti "da cartolina" del viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Il Tempio del Dente illuminato durante la cerimonia serale, Kandy, Sri Lanka',
  },
  {
    slug: 'rafting-kitulgala',
    paeseSlug: 'sri-lanka',
    destinazioneSlug: 'nallathanniya',
    nome: 'Rafting sul fiume Kelani a Kitulgala',
    localita: 'Kitulgala',
    cosE: 'Rafting sul fiume Kelani, lo stesso dove fu girato Il ponte sul fiume Kwai, con possibile combinazione di canyoning e tuffi in cascata.',
    percheFarla: 'Una giornata di sport d\'acqua che rompe il ritmo tra templi e trekking, in un\'ambientazione cinematografica.',
    durata: 'mezza giornata',
    periodo: 'da confermare',
    costo: 'da completare',
    comePrenotare: 'tramite il DMC locale del viaggio',
    cosaPortare: 'costume, cambio asciutto, scarpe da acqua',
    perChiEAdatta: 'chiunque, anche principianti',
    miaEsperienza:
      'Un bel diversivo prima della sfida fisica dell\'Adam\'s Peak la notte successiva: sapere di girare nello stesso fiume del Ponte sul fiume Kwai aggiunge un tocco cinematografico alla giornata.',
    giudizio: 'la-rifarei',
    alternative: ['Combinazione con canyoning e camminata nella giungla, da concordare con l\'operatore'],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Gommone da rafting sul fiume Kelani a Kitulgala, Sri Lanka',
  },
  {
    slug: 'scalata-adams-peak',
    paeseSlug: 'sri-lanka',
    destinazioneSlug: 'nallathanniya',
    nome: 'Scalata notturna dell\'Adam\'s Peak',
    localita: 'Nallathanniya',
    cosE: 'La salita notturna su una scalinata di pellegrinaggio illuminata fino alla cima a 2.243 metri, in tempo per l\'alba.',
    percheFarla: 'La vera sfida fisica del viaggio, condivisa con centinaia di pellegrini locali: vale più per il percorso che per la meta.',
    durata: '2h30-3h di salita, altrettante di discesa',
    periodo: 'stagione di pellegrinaggio, dicembre-maggio, per il percorso illuminato',
    costo: 'gratuito',
    comePrenotare: 'nessuna prenotazione, partenza libera dal villaggio di Nallathanniya',
    cosaPortare: 'felpa pesante (3-6°C in cima con vento), torcia frontale, scarpe da trekking',
    perChiEAdatta: 'chi ha una buona resistenza fisica: la salita è lunga e ripida',
    miaEsperienza:
      'La vera attrazione non è il tempio in cima ma la sfida fisica condivisa con centinaia di pellegrini locali, in fila indiana a passo di formica sull\'ultimo tratto. Il freddo in cima è pungente, ma resta una delle esperienze più intense di tutto il viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'La scalinata di pellegrinaggio illuminata verso la cima dell\'Adam\'s Peak, Sri Lanka',
  },
  {
    slug: 'treno-panoramico-ella',
    paeseSlug: 'sri-lanka',
    destinazioneSlug: 'ella',
    nome: 'Treno panoramico Nuwara Eliya-Ella',
    localita: 'Nanu Oya - Ella',
    cosE: 'La tratta ferroviaria più fotografata dello Sri Lanka, tra vallate di tè a perdita d\'occhio, ponti e gallerie.',
    percheFarla: 'Uno dei modi più iconici di attraversare le montagne del tè dello Sri Lanka.',
    durata: 'sulla carta 3 ore, ma gli orari reali sono imprevedibili',
    periodo: 'tutto l\'anno',
    costo: 'da completare',
    comePrenotare: 'con largo anticipo: i biglietti vanno a ruba, soprattutto in alta stagione, ed esiste un vero mercato nero dei posti a sedere',
    cosaPortare: 'snack e acqua: nessun servizio di ristorazione a bordo',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Partito nel primo pomeriggio e arrivato in tarda serata, ben oltre il previsto, senza alcun servizio di ristorazione a bordo. Ma le vallate di tè a perdita d\'occhio viste dal finestrino restano tra le immagini più belle di tutto il viaggio: va preso con lo spirito giusto, i ritardi sono la norma, non l\'eccezione.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Il treno panoramico tra le piantagioni di tè verdi vicino a Ella, Sri Lanka',
  },
  {
    slug: 'safari-yala',
    paeseSlug: 'sri-lanka',
    destinazioneSlug: 'hikkaduwa',
    nome: 'Safari al Parco Nazionale di Yala',
    localita: 'Yala',
    cosE: 'Un safari in jeep nel parco con la più alta densità di leopardi al mondo, oltre a elefanti, coccodrilli, bufali d\'acqua e ricca avifauna.',
    percheFarla: 'La possibilità concreta di avvistare un leopardo selvatico, oltre alla ricchezza generale di fauna del parco.',
    durata: 'circa 4 ore',
    periodo: 'mattina presto, prima dell\'alba',
    costo: '12.000-16.000 LKR a jeep + ingresso (27-30€ a persona) + mancia',
    comePrenotare: 'tramite il DMC locale del viaggio',
    cosaPortare: 'macchina fotografica con zoom, cappello, acqua, colazione al sacco',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'La sveglia prestissimo per il safari a Yala è stata ripagata da un\'ottima varietà di fauna, anche se l\'avvistamento di un leopardo resta sempre una questione di fortuna. Un bel modo per chiudere la parte più "wild" del viaggio prima delle spiagge del sud.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['sri-lanka-2023'],
    imageAlt: 'Jeep da safari nel Parco Nazionale di Yala, Sri Lanka',
  },
]
