import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Lapponia svedese: Capodanno sotto l'aurora"
// (src/content/viaggi/14-lapponia-svedese-abisko.md).

export const esperienzeSvezia: Esperienza[] = [
  {
    slug: 'aurora-sky-station',
    paeseSlug: 'svezia',
    destinazioneSlug: 'abisko',
    nome: 'Aurora Sky Station',
    localita: 'Abisko, monte Nuolja',
    cosE:
      'Una seggiovia che sale sul monte Nuolja fino a una stazione panoramica dedicata all\'osservazione dell\'aurora boreale, con cena servita in quota. Abisko ha un microclima secco che riduce la copertura nuvolosa rispetto al resto della regione — il cosiddetto "buco blu" sopra la valle — rendendolo uno dei punti con le probabilità di aurora più alte al mondo.',
    percheFarla: 'È l\'esperienza-simbolo di Abisko: unisce il panorama, la cena in quota e le migliori probabilità della zona di vedere davvero l\'aurora.',
    durata: 'una serata, tra salita, cena e osservazione',
    periodo: 'da fine dicembre a marzo, stagione dell\'aurora',
    costo: 'incluso nel budget escursioni del viaggio (450-500€ a persona per 3 tour con guida, cifra complessiva non scorporata per singola attività)',
    comePrenotare: 'seggiovia con partenza diretta dallo STF Abisko Turiststation',
    cosaPortare: 'strati pesanti, il freddo in quota si fa sentire più che a valle',
    perChiEAdatta: 'chiunque alloggi ad Abisko, nessuna difficoltà fisica particolare',
    miaEsperienza:
      'La prima sera ad Abisko, dopo il trasferimento in treno da Kiruna: seggiovia al buio, cena panoramica, e il cielo che verso Nuolja sembra davvero più pulito rispetto a quello visto altrove nel viaggio.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['lapponia-svedese-abisko'],
    imageAlt: 'Stazione panoramica Aurora Sky Station illuminata sul monte Nuolja con aurora boreale sullo sfondo',
  },
  {
    slug: 'motoslitta-lago-ghiacciato',
    paeseSlug: 'svezia',
    destinazioneSlug: 'abisko',
    nome: 'Motoslitta sul lago ghiacciato',
    localita: 'Abisko, parco nazionale',
    cosE: 'Un\'escursione in motoslitta sulla superficie ghiacciata di uno dei laghi del parco nazionale di Abisko.',
    percheFarla: 'L\'attività più adrenalinica del soggiorno ad Abisko, e un modo diverso di attraversare il paesaggio artico rispetto al passo lento dell\'husky sledding del giorno dopo.',
    durata: 'alcune ore',
    periodo: 'inverno, quando il lago è completamente ghiacciato',
    costo: 'incluso nel budget escursioni del viaggio (450-500€ a persona per 3 tour con guida, cifra complessiva non scorporata per singola attività)',
    comePrenotare: 'tour organizzato con guida, da confermare l\'operatore esatto',
    cosaPortare: 'tuta termica (spesso fornita dall\'operatore, da verificare), guanti pesanti',
    perChiEAdatta: 'chiunque, nessuna esperienza pregressa richiesta',
    miaEsperienza:
      'Il giorno più adrenalinico di Abisko: velocità sul ghiaccio e un silenzio surreale ogni volta che la motoslitta si fermava per godersi il panorama.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['lapponia-svedese-abisko'],
    imageAlt: 'Motoslitta che attraversa un lago ghiacciato circondato da montagne innevate in Lapponia',
  },
  {
    slug: 'husky-sledding-caccia-aurora',
    paeseSlug: 'svezia',
    destinazioneSlug: 'abisko',
    nome: 'Husky sledding con caccia all\'aurora',
    localita: 'Abisko, parco nazionale',
    cosE: 'Un\'escursione serale in slitta trainata da husky nei dintorni di Abisko, organizzata per coincidere con le ore più probabili di osservazione dell\'aurora.',
    percheFarla: 'La serata più suggestiva del viaggio: il movimento della slitta, il fiato dei cani nell\'aria gelida, e il cielo che — se le condizioni sono buone — si accende sopra la testa.',
    durata: 'una serata',
    periodo: 'da fine dicembre a marzo',
    costo: '240€ a persona (dalla guida ai costi del preventivo)',
    comePrenotare: 'tour organizzato con guida, meglio con un minimo di anticipo nel periodo di Capodanno',
    cosaPortare: 'strati pesanti, guanti e sottoguanti — si resta fermi e immobili sulla slitta per buona parte del tempo, il freddo si sente più che nelle attività "attive"',
    perChiEAdatta: 'chiunque, nessuna difficoltà fisica particolare',
    miaEsperienza:
      'Il silenzio prima della partenza, rotto solo dall\'agitazione dei cani impazienti di correre, e poi la corsa vera e propria nel buio quasi totale — con l\'aurora che quella sera si è fatta vedere, anche se non a lungo.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['lapponia-svedese-abisko'],
    imageAlt: 'Slitta trainata da husky sulla neve al crepuscolo con aurora boreale visibile in cielo',
  },
  {
    slug: 'icehotel-jukkasjarvi',
    paeseSlug: 'svezia',
    destinazioneSlug: 'kiruna',
    nome: 'ICEHOTEL di Jukkasjärvi',
    localita: 'Jukkasjärvi, a circa 20 minuti da Kiruna',
    cosE:
      'Il più famoso hotel di ghiaccio al mondo, ricostruito ogni inverno con blocchi di ghiaccio del fiume Torne: camere e suite scolpite da artisti diversi ogni anno, oltre a una parte "warm" aperta tutto l\'anno con bar di ghiaccio.',
    percheFarla: 'È una delle attrazioni più conosciute di tutta la Lapponia svedese, a pochi minuti da Kiruna — non l\'abbiamo fatta in questo viaggio, ma vale la pena saperlo per organizzarne uno futuro.',
    durata: 'da una visita di poche ore a un pernottamento vero e proprio (con opzione di stanza riscaldata di riserva)',
    periodo: 'dicembre-aprile per la versione di ghiaccio stagionale',
    costo: 'da verificare, varia molto tra semplice visita e pernottamento',
    comePrenotare: 'da verificare',
    cosaPortare: 'da verificare',
    perChiEAdatta: 'chi vuole un\'esperienza estrema anche solo per una notte, o semplicemente una visita guidata per chi preferisce dormire altrove',
    giudizio: 'da-verificare',
    alternative: [],
    tripSlugs: [],
    imageAlt: 'Camera scolpita nel ghiaccio con letto di ghiaccio illuminato all\'ICEHOTEL di Jukkasjärvi',
  },
]
