import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Thailandia" (src/content/viaggi/06-thailandia.md).
// full-moon-party è collegata al Golfo di Thailandia, mai visitato di persona
// secondo le fonti: giudizio 'da-verificare', nessuna miaEsperienza, tripSlugs vuoto.

export const esperienzeThailandia: Esperienza[] = [
  {
    slug: 'jay-fai-bangkok',
    paeseSlug: 'thailandia',
    destinazioneSlug: 'bangkok',
    nome: 'Jay Fai, la bancarella stellata Michelin',
    localita: 'Bangkok',
    cosE: 'L\'unica bancarella di strada al mondo ad aver ottenuto una stella Michelin, con la chef ottantenne che cucina personalmente ogni piatto indossando gli iconici occhiali da saldatore.',
    percheFarla: 'Un\'esperienza a sé: street food e alta cucina che si incontrano in un\'unica bancarella.',
    durata: '1-2 ore, inclusa l\'attesa',
    periodo: 'presto al mattino, prima delle 8:00',
    costo: 'l\'omelette al granchio (kai jeaw poo) costa oltre 1.000 THB',
    comePrenotare: 'arrivare presto e mettersi in lista su un foglio, oppure prenotare via email con largo anticipo',
    cosaPortare: 'pazienza per l\'attesa',
    perChiEAdatta: 'chiunque ami lo street food e non abbia fretta',
    miaEsperienza:
      'Un\'esperienza da fare almeno una volta nella vita: cara per essere street food, ma vedere la chef lavorare dal vivo con la fiamma del carbone vale l\'attesa.',
    giudizio: 'imperdibile',
    alternative: ['Thipsamai per il pad thai più famoso di Bangkok, meno attesa'],
    tripSlugs: ['thailandia'],
    imageAlt: 'La bancarella di street food Jay Fai a Bangkok, Thailandia',
  },
  {
    slug: 'crociera-cheow-lan',
    paeseSlug: 'thailandia',
    destinazioneSlug: 'khao-sok',
    nome: 'Crociera al tramonto sul lago Cheow Lan',
    localita: 'Khao Sok',
    cosE: 'Una crociera al tramonto con guida anglofona locale tra le formazioni calcaree che emergono dal lago Cheow Lan, spesso paragonato a una piccola Guilin.',
    percheFarla: 'Uno degli scenari più spettacolari di tutta la Thailandia.',
    durata: '1-2 ore',
    periodo: 'tramonto',
    costo: 'incluso nel pacchetto "2 giorni 1 notte" sul lago',
    comePrenotare: 'tramite l\'hotel/Smiley Bungalows con almeno 24h di anticipo',
    cosaPortare: 'macchina fotografica, giacca leggera per la sera',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Le torri calcaree che emergono dall\'acqua, illuminate dalla luce del tramonto, restano una delle immagini più belle di tutto il viaggio in Thailandia.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['thailandia'],
    imageAlt: 'Crociera al tramonto tra le torri calcaree del lago Cheow Lan, Thailandia',
  },
  {
    slug: 'bond-island-canoa',
    paeseSlug: 'thailandia',
    destinazioneSlug: 'krabi',
    nome: 'Bond Island e canoa nella baia di Phang Nga',
    localita: 'Krabi',
    cosE: 'Escursione di giornata intera con guida anglofona: Koh Ta Poo (Bond Island, resa famosa da L\'uomo dalla pistola d\'oro) e Koh Ping Gun, giro in canoa fino a Tham Lot, pranzo a Koh Panyee.',
    percheFarla: 'Panorami da film, letteralmente, in una delle baie più scenografiche della Thailandia.',
    durata: 'giornata intera',
    periodo: 'stagione secca, novembre-aprile',
    costo: 'ingresso al parco nazionale, pranzo, pick-up e drop-off inclusi',
    comePrenotare: 'tramite un tour operator locale a Krabi',
    cosaPortare: 'costume, cambio asciutto, protezione solare',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Bond Island vista dal vivo, con le sue rocce a fungo che emergono dall\'acqua, sembra ancora più scenografica che nel film da cui prende il soprannome — una delle giornate più belle di tutto il sud della Thailandia.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['thailandia'],
    imageAlt: 'Koh Ta Poo (Bond Island) nella baia di Phang Nga, Thailandia',
  },
  {
    slug: 'elephant-nature-park',
    paeseSlug: 'thailandia',
    destinazioneSlug: 'chiang-mai',
    nome: 'Elephant Nature Park',
    localita: 'Chiang Mai',
    cosE: 'Un santuario etico per elefanti salvati da sfruttamento e maltrattamenti, gestito da un\'associazione no profit: si osservano, si nutrono e si fa il bagno con loro nel fiume, senza mai cavalcarli.',
    percheFarla: 'Un modo etico e autentico di avvicinarsi agli elefanti, ben diverso dai centri che li sfruttano per le cavalcate turistiche.',
    durata: 'mezza giornata o giornata intera',
    periodo: 'tutto l\'anno',
    costo: 'da completare',
    comePrenotare: 'con anticipo tramite il sito dell\'Elephant Nature Park o un tour operator locale',
    cosaPortare: 'cambio asciutto per il bagno nel fiume, protezione solare',
    perChiEAdatta: 'chiunque, incluse le famiglie',
    miaEsperienza:
      'Vedere gli elefanti liberi di muoversi, nutrirsi e fare il bagno senza mai essere cavalcati, con lo staff a raccontare le storie di ognuno di loro salvato dallo sfruttamento, resta uno dei ricordi più belli di tutta la Thailandia.',
    giudizio: 'imperdibile',
    alternative: ['Altri centri etici della zona, verificando sempre che non prevedano di cavalcare gli animali'],
    tripSlugs: ['thailandia'],
    imageAlt: 'Elefanti che fanno il bagno nel fiume all\'Elephant Nature Park, Chiang Mai, Thailandia',
  },
  {
    slug: 'snorkeling-similan',
    paeseSlug: 'thailandia',
    destinazioneSlug: 'phuket-similan',
    nome: 'Snorkeling alle Isole Similan',
    localita: 'Isole Similan',
    cosE: 'Una giornata di snorkeling o diving nel parco marino nazionale disabitato delle Isole Similan, tra acque cristalline e la miglior barriera corallina della costa andamana.',
    percheFarla: 'Probabilmente il miglior snorkeling/diving raggiungibile in giornata da terraferma in tutta la Thailandia.',
    durata: 'giornata intera',
    periodo: 'metà ottobre-metà maggio, quando il parco è aperto',
    costo: 'da completare',
    comePrenotare: 'tour organizzato da Khao Lak o Phuket',
    cosaPortare: 'costume, crema solare biodegradabile (obbligatoria in molti tour), maschera propria se si preferisce',
    perChiEAdatta: 'chiunque sappia nuotare',
    miaEsperienza:
      'La differenza con le isole più turistiche si sente subito: niente hotel, niente folla, solo acqua cristallina e granito bianco. Se l\'obiettivo è il mare più bello della Thailandia, vale il viaggio in barca per arrivarci.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['thailandia'],
    imageAlt: 'Snorkeling nelle acque cristalline delle Isole Similan, Thailandia',
  },
  {
    slug: 'full-moon-party',
    paeseSlug: 'thailandia',
    destinazioneSlug: 'golfo-thailandia',
    nome: 'Full Moon Party',
    localita: 'Haad Rin, Koh Phangan',
    cosE: 'Una delle feste in spiaggia più grandi al mondo, ogni mese nella notte di luna piena: tra 10.000 e 30.000 persone, impianti audio multipli, spettacoli di fuoco e i celebri "bucket".',
    percheFarla: 'Un\'esperienza da fare almeno una volta, sapendo cosa aspettarsi.',
    durata: 'una notte intera',
    periodo: 'notte di luna piena, date pubblicate con un anno di anticipo',
    costo: '200 baht, in contanti ai cancelli della spiaggia',
    comePrenotare: 'nessun biglietto in prevendita: diffidare di chi li vende online',
    cosaPortare: 'vestiti che non dispiacerebbe rovinare (vernice fluorescente ovunque), poco contante, niente oggetti di valore',
    perChiEAdatta: 'chi cerca una notte di festa intensa, meno adatta a chi cerca tranquillità',
    giudizio: 'da-verificare',
    alternative: ['Il lato nord di Koh Phangan (Thong Nai Pan), molto più tranquillo fuori dalle notti di luna piena'],
    tripSlugs: [],
    imageAlt: 'La spiaggia di Haad Rin durante la Full Moon Party, Koh Phangan, Thailandia',
  },
]
