import type { Esperienza } from '@/lib/types'

// Contenuto ricostruito dal viaggio "Transilvania Express in 5 giorni" (src/content/viaggi/10-transilvania-express.md).

export const esperienzeTransilvania: Esperienza[] = [
  {
    slug: 'palazzo-parlamento',
    paeseSlug: 'transilvania',
    destinazioneSlug: 'bucarest',
    nome: 'Palazzo del Parlamento',
    localita: 'Bucarest',
    cosE: 'Il secondo edificio più grande al mondo dopo il Pentagono, voluto dal dittatore Nicolae Ceaușescu.',
    percheFarla: 'Un colpo d\'occhio sulla megalomania del regime comunista rumeno, in un edificio dalle dimensioni fuori scala.',
    durata: '1 ora',
    periodo: 'tutto l\'anno',
    costo: 'circa 12,5€/pax',
    comePrenotare: 'da pagare all\'ingresso, visita guidata obbligatoria',
    cosaPortare: 'documento d\'identità; niente deposito bagagli, va portato tutto con sé',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Le dimensioni del Palazzo del Parlamento colpiscono ancora prima di entrare: la visita guidata di un\'ora racconta bene la megalomania del regime di Ceaușescu dietro un edificio così fuori scala.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Il Palazzo del Parlamento di Bucarest, Romania',
  },
  {
    slug: 'castello-peles',
    paeseSlug: 'transilvania',
    destinazioneSlug: 'peles-bran',
    nome: 'Castello di Peleș',
    localita: 'Sinaia',
    cosE: 'La residenza estiva di Carlo I, primo sovrano di Romania, costruita tra il 1873 e il 1914 in stile neorinascimentale con oltre 160 stanze.',
    percheFarla: 'Considerato uno dei castelli più belli d\'Europa, con un livello di dettaglio negli interni superiore a qualunque altro castello del viaggio.',
    durata: '1-1h30',
    periodo: 'mattina, per evitare la ressa; in alta stagione meglio prenotare online',
    costo: 'circa 20€/pax per primo e secondo piano',
    comePrenotare: 'si entra in ordine di arrivo senza prenotazione obbligatoria, salvo alta stagione',
    cosaPortare: 'macchina fotografica',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Peleș è probabilmente il castello più bello dal punto di vista architettonico di tutto il viaggio: gli interni, con oltre 160 stanze, sono di un livello di dettaglio che il più celebre Castello di Bran non ha.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Il Castello di Peleș in stile neorinascimentale a Sinaia, Romania',
  },
  {
    slug: 'castello-bran',
    paeseSlug: 'transilvania',
    destinazioneSlug: 'peles-bran',
    nome: 'Castello di Bran',
    localita: 'Bran',
    cosE: 'La fortezza medievale del XIII secolo nota come "Castello di Dracula", anche se non esiste alcuna prova storica che Bram Stoker si sia ispirato proprio a questo castello.',
    percheFarla: 'Un castello affascinante di per sé, al di là del legame turistico con Dracula, in una delle location più fotografate della Romania.',
    durata: 'circa 1 ora',
    periodo: 'tutto l\'anno',
    costo: 'biglietti acquistabili online in anticipo; guida ufficiale 30-40 minuti da pagare in loco in contanti',
    comePrenotare: 'online in anticipo, soprattutto in alta stagione',
    cosaPortare: 'contanti in lei per la guida e le bancarelle intorno al castello',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Il legame con Dracula è in gran parte una costruzione turistica, ma il castello resta affascinante di per sé: le bancarelle e i ristoranti intorno sono però vere e proprie trappole per turisti, meglio saperlo in anticipo.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Il Castello di Bran, il "Castello di Dracula", in Romania',
  },
  {
    slug: 'fortezza-rasnov',
    paeseSlug: 'transilvania',
    destinazioneSlug: 'brasov',
    nome: 'Fortezza di Râșnov',
    localita: 'Râșnov, vicino Brașov',
    cosE: 'Una fortezza medievale in cima a una rocca, vicino alla scritta cittadina "RASNOV" in stile hollywoodiano.',
    percheFarla: 'Molto meno affollata del Castello di Bran ma altrettanto suggestiva, con un\'atmosfera più epica che vampiresca.',
    durata: '1-1h30',
    periodo: 'tardo pomeriggio, per la luce sulla rocca',
    costo: 'da completare',
    comePrenotare: 'nessuna prenotazione necessaria',
    cosaPortare: 'scarpe comode per la salita',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'La vista dalla rocca, con la scritta "RASNOV" in stile hollywoodiano sotto di sé, regala un\'atmosfera più da Signore degli Anelli che da Dracula: la chicca meno turistica di tutto il viaggio.',
    giudizio: 'imperdibile',
    alternative: ['Salita a piedi invece che in cabinovia, per chi vuole risparmiare'],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'La Fortezza di Râșnov su una rocca vicino a Brașov, Romania',
  },
  {
    slug: 'salina-turda',
    paeseSlug: 'transilvania',
    destinazioneSlug: 'sighisoara-salina-turda',
    nome: 'Salina Turda',
    localita: 'Turda',
    cosE: 'Una salina sotterranea spettacolare, con un laghetto navigabile alla base e giochi come biliardino e ping pong.',
    percheFarla: 'Una delle attrazioni più sorprendenti di tutta la Romania: una miniera di sale trasformata in un enorme parco sotterraneo.',
    durata: '2-3 ore',
    periodo: 'tutto l\'anno, temperatura costante tutto l\'anno essendo sotterranea',
    costo: '10€ nei giorni feriali, 12€ nel weekend; guida 100 LEI in contanti',
    comePrenotare: 'biglietti spesso inclusi nel pacchetto turistico',
    cosaPortare: 'una felpa leggera: la temperatura sottoterra è più fresca',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Scendere nella salina e trovare un laghetto navigabile con barchette a noleggio, oltre a un biliardino, è stata una delle sorprese più belle di tutto il viaggio: qualcosa che non mi aspettavo da una miniera di sale.',
    giudizio: 'imperdibile',
    alternative: [],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Il laghetto sotterraneo illuminato nelle saline di Salina Turda, Romania',
  },
  {
    slug: 'transfagarasan',
    paeseSlug: 'transilvania',
    destinazioneSlug: 'sibiu-transfagarasan',
    nome: 'La Transfăgărășan',
    localita: 'Monti Făgăraș',
    cosE: 'Una delle strade panoramiche più famose al mondo, con tornanti spettacolari fino a 2.000 metri di quota e sosta al Lago Bâlea.',
    percheFarla: 'Uno scenario di guida unico, tra i più belli d\'Europa, con la possibilità di avvistare orsi lungo la carreggiata.',
    durata: 'mezza giornata, incluso il rientro verso Bucarest',
    periodo: '20 giugno - 31 ottobre, quando la strada è percorribile in auto (altrimenti solo funivia fino al Lago Bâlea)',
    costo: 'gratuito, a parte pedaggio/parcheggi occasionali',
    comePrenotare: 'nessuna prenotazione, verificare sempre l\'apertura sul sito ufficiale prima di partire',
    cosaPortare: 'macchina fotografica, giacca calda anche in autunno per la quota',
    perChiEAdatta: 'chi ha esperienza di guida su strade di montagna con tornanti stretti',
    miaEsperienza:
      'I tornanti che salgono fino al Lago Bâlea mantengono esattamente la fama che la Transfăgărășan si porta dietro: uno degli scenari di guida più belli mai visti, anche se il lungo rientro a Bucarest lo stesso giorno (fino a 3h45 non-stop) si fa sentire.',
    giudizio: 'imperdibile',
    alternative: ['Salita al Lago Bâlea in funivia, nei periodi in cui la strada è chiusa'],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'I tornanti della Transfăgărășan tra le montagne della Romania',
  },
  {
    slug: 'terme-bucarest',
    paeseSlug: 'transilvania',
    destinazioneSlug: 'bucarest',
    nome: 'Terme di Bucarest',
    localita: 'Bucarest',
    cosE: 'Un parco termale enorme vicino all\'aeroporto, diviso in tre aree: giochi d\'acqua, relax, ristoranti/bar.',
    percheFarla: 'Un modo rilassante di chiudere un viaggio molto denso di chilometri, comodo perché a due passi dall\'aeroporto.',
    durata: 'mezza giornata o giornata intera',
    periodo: 'tutto l\'anno',
    costo: '35€ per l\'intera giornata, con braccialetto da saldare all\'uscita',
    comePrenotare: 'accesso diretto, nessuna prenotazione necessaria',
    cosaPortare: 'costume, ciabatte, accappatoio',
    perChiEAdatta: 'chiunque',
    miaEsperienza:
      'Dopo giorni di guida intensa tra castelli e tornanti di montagna, le Terme sono state il modo perfetto per staccare prima del volo, con la comodità di trovarsi proprio accanto all\'aeroporto.',
    giudizio: 'la-rifarei',
    alternative: [],
    tripSlugs: ['transilvania-express'],
    imageAlt: 'Le piscine termali di un parco acquatico a Bucarest, Romania',
  },
]
