// Indici landmark MediaPipe Pose (33 punti)
export const LM = {
  NOSE: 0,
  LEFT_EYE_INNER: 1,
  LEFT_EYE: 2,
  LEFT_EYE_OUTER: 3,
  RIGHT_EYE_INNER: 4,
  RIGHT_EYE: 5,
  RIGHT_EYE_OUTER: 6,
  LEFT_EAR: 7,
  RIGHT_EAR: 8,
  LEFT_SHOULDER: 11,
  RIGHT_SHOULDER: 12,
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
} as const

export const LANDMARK_GROUPS = {
  SHOULDERS: [LM.LEFT_SHOULDER, LM.RIGHT_SHOULDER],
  EYES: [LM.LEFT_EYE, LM.RIGHT_EYE],
  FACE: [LM.NOSE, LM.LEFT_EYE, LM.RIGHT_EYE, LM.LEFT_EAR, LM.RIGHT_EAR],
}
