import type { Paese } from '@/lib/types'

// Paese visitato di persona, due volte: i due itinerari collegati
// (cina-classica e cina-paesaggi) rispecchiano quella divisione.
// I campi miaEsperienza nelle destinazioni e nelle esperienze sono bozze
// scritte da Claude nella voce del diario, basate su ciò che è oggettivamente
// vero di ogni posto (code, quote, orari, regole d\'accesso) e non su ricordi
// reali: vanno riletti e sostituiti. Nessun nome di hotel, ristorante o
// operatore è stato inventato.
// La scheda pratica è la parte più delicata di tutto l\'archivio: in Cina le
// regole su visto, pagamenti, SIM e biglietteria cambiano più in fretta che
// altrove, e ogni voce va riverificata prima di partire.

export const cina: Paese = {
  slug: 'cina',
  nome: 'Cina',
  continente: 'Asia',
  titolo: 'Cina: come organizzarla davvero, tra treni, pagamenti e firewall',
  descrizione:
    'Il paese più difficile da organizzare e uno dei più facili da viaggiare, una volta dentro. La difficoltà non sono le distanze — l\'alta velocità le annulla — ma il fatto che quasi nulla di ciò che si usa per viaggiare altrove qui funziona: non Google, non WhatsApp, non le carte di credito, non i biglietti comprati sul posto. Chi risolve queste cose prima di partire trova un paese enorme, sicurissimo e sorprendentemente economico; chi le rimanda perde i primi tre giorni.',
  periodoMigliore:
    'aprile-maggio e settembre-ottobre, con una precisazione che vale più di ogni altra: la prima settimana di ottobre e quella di Capodanno cinese vanno evitate del tutto. Sono le settimane in cui si muove tutto il paese insieme.',
  durataConsigliata:
    '14-16 giorni per l\'asse classico Pechino-Xi\'an-Shanghai con Hong Kong e Macao; 16-18 giorni per la Cina dei paesaggi tra Hunan, Sichuan, Yunnan e Guangxi. Metterle insieme in un viaggio solo significa passare metà del tempo in treno.',
  budgetIndicativo:
    'sorprendentemente basso per quello che si vede: treni ad alta velocità 30-90€ a tratta, hotel di buon livello 40-70€ a notte fuori da Shanghai e Hong Kong, pasti 4-10€. Le voci che alzano il conto sono i voli interni sulle tratte lunghe, gli ingressi ai parchi naturali (Zhangjiajie e Yulong Xueshan costano più di quanto ci si aspetti) e Hong Kong, che è un altro paese anche nei prezzi.',
  stileViaggio: ['treni ad alta velocità', 'grandi classici', 'paesaggi', 'megalopoli'],
  scheda: {
    documenti:
      'Passaporto con almeno 6 mesi di validità residua. Per i cittadini italiani l\'ingresso è senza visto fino a 30 giorni consecutivi per turismo, in regime di esenzione prorogato fino al 31 dicembre 2026: gli ingressi multipli sono ammessi e ognuno riapre un nuovo periodo di 30 giorni. Attenzione a due cose. La prima: Hong Kong e Macao hanno frontiera e controllo passaporti propri, quindi andarci e tornare nella Cina continentale conta come una nuova entrata (senza visto anche loro per gli italiani, 90 giorni a Hong Kong, 30 a Macao). La seconda: ogni straniero va registrato presso la polizia entro 24 ore dall\'arrivo — gli hotel lo fanno in automatico al check-in, ma chi dorme in appartamenti privati o da amici deve andarci di persona, e non è una formalità trascurabile. Le regole cambiano spesso: vanno riverificate sul sito dell\'Ambasciata cinese prima di partire.',
    valuta: 'Renminbi o yuan (CNY), spesso indicato come ¥ o RMB. Il cambio in contanti si fa in Bank of China o in aeroporto; fuori dalle grandi città cambiare valuta estera è complicato.',
    pagamenti:
      'È il punto in cui più viaggiatori si bloccano. La Cina è un paese quasi interamente senza contanti: si paga con Alipay o WeChat Pay inquadrando un QR, dal taxi al banco della frutta. Entrambe le app permettono ormai di collegare una carta Visa o Mastercard estera senza conto cinese, ma la verifica dell\'identità va fatta prima di partire, con connessione stabile e passaporto a portata di mano: farlo una volta atterrati, senza accesso a certi servizi, è molto più difficile. Le carte fisiche si usano solo negli hotel di fascia alta e nei grandi centri commerciali. I contanti per legge non possono essere rifiutati, ma in pratica molti piccoli esercenti non hanno il resto e non sanno che farsene: vanno tenuti come rete di sicurezza, non come metodo principale. Gli ATM che accettano carte estere ci sono (Bank of China e ICBC sono i più affidabili), ma non tutti. Ultimo dettaglio che manda in blocco le app: il VPN va spento al momento del pagamento, perché il mismatch tra IP e posizione fa scattare l\'antifrode.',
    connettivita:
      'Il Great Firewall blocca Google in ogni sua forma (ricerca, Gmail, Maps, Drive), WhatsApp, Instagram, Facebook, YouTube, X e buona parte dei siti di informazione occidentali. Due strade. La prima, di gran lunga la più semplice: usare una eSIM estera in roaming, che instrada il traffico fuori dalla Cina e aggira il problema senza fare nulla. La seconda: una SIM locale (China Mobile, China Unicom), che costa meno, si compra col passaporto e passa attraverso il firewall, quindi va accompagnata da un VPN — che va però installato e testato prima di partire, perché gli app store in Cina non lo offrono e i siti dei fornitori sono spesso irraggiungibili. Da scaricare comunque prima: mappe offline, un traduttore con fotocamera (inquadrare un menu e vederlo tradotto è ciò che rende autonomi) e, se si vuole navigare come i locali, Amap o Baidu Maps.',
    salute:
      'Nessuna vaccinazione obbligatoria. L\'acqua del rubinetto non si beve: ovunque, anche negli hotel più semplici, c\'è un bollitore o un erogatore di acqua calda, ed è l\'abitudine locale. La sanità nelle grandi città è di buon livello ma gli ospedali pubblici sono caotici e quasi solo in cinese; le cliniche internazionali di Pechino e Shanghai sono ottime e costose, quindi l\'assicurazione sanitaria è indispensabile. L\'inquinamento atmosferico resta un tema nelle città del nord in inverno, molto meno di dieci anni fa ma non risolto: chi ha problemi respiratori controlli l\'indice AQI giorno per giorno. Sull\'altitudine: Shangri-La supera i 3.200 metri e la funivia dello Yulong Xueshan arriva a 4.500, dove le bombole di ossigeno in vendita all\'ingresso non sono un gadget.',
    sicurezza:
      'Tra i paesi più sicuri al mondo per quanto riguarda la criminalità comune: si cammina di notte ovunque senza pensarci, e il borseggio è raro anche nella folla. Il rischio vero sono le truffe rivolte agli stranieri, sempre le stesse da vent\'anni e sempre efficaci: la cerimonia del tè, in cui una coppia di giovani gentilissimi e in ottimo inglese propone di accompagnarti in una sala da tè e il conto arriva a centinaia di euro; la variante dello "studente d\'arte" che invita a visitare una mostra e finisce in una galleria con prezzi assurdi. Succedono attorno a Tiananmen, sulla Nanjing Road a Shanghai e nelle vie turistiche di Xi\'an, e la regola è una sola: non seguire in un locale chi ti ha fermato per strada. Da sapere anche che fotografare installazioni militari, posti di polizia e manifestazioni è un problema serio, e che nello Xinjiang e in Tibet valgono regole d\'accesso e di controllo completamente diverse dal resto del paese.',
    trasportiInterni:
      'L\'alta velocità è la spina dorsale del viaggio e funziona meglio di qualsiasi rete europea: Pechino-Xi\'an in 4h30, Pechino-Shanghai in 4h30, con treni ogni mezz\'ora. La prenotazione è però il vero scoglio. I biglietti si aprono esattamente 15 giorni prima della partenza, alle 8 del mattino ora di Pechino, e sulle tratte forti si esauriscono in poche ore; l\'app ufficiale 12306 ha ormai una versione inglese che accetta la registrazione col passaporto e il pagamento con carta estera, ma la verifica dell\'account richiede tempo e va fatta prima. In alternativa Trip.com accetta prenotazioni fino a due mesi prima e le converte in biglietto appena la vendita ufficiale apre, con una commissione: costa qualcosa in più e toglie l\'ansia. Il biglietto è elettronico e legato al passaporto, che diventa il titolo di viaggio: si appoggia al lettore del tornello e si passa. In stazione servono 30-40 minuti di margine, perché i controlli di sicurezza sono seri e le stazioni sono grandi come aeroporti, e i gate chiudono qualche minuto prima della partenza senza eccezioni. Per le tratte lunghissime — Shanghai-Lijiang, per dire — il volo interno resta più sensato: sono economici e frequenti.',
    costoVita:
      'Molto più basso di quanto la reputazione lasci pensare, con l\'eccezione di Hong Kong, Macao e del centro di Shanghai. Un pasto in un ristorante di quartiere sta sotto i 10€, la metropolitana costa pochi centesimi, un hotel nuovo e pulito in una città di provincia si trova a 40€. Le voci che pesano sono gli ingressi ai parchi naturali (Zhangjiajie con le funivie supera facilmente i 60€ a testa) e i biglietti degli spettacoli.',
    lingua:
      'Cinese mandarino. Fuori dagli hotel di fascia alta e dagli uffici turistici l\'inglese è praticamente assente, in modo molto più netto che in Giappone o in Thailandia: cartelli, menu, biglietterie e app sono in cinese. Non è un ostacolo insormontabile, ma va affrontato con gli strumenti giusti — un traduttore con fotocamera e traduzione vocale, l\'indirizzo dell\'hotel salvato in caratteri cinesi da mostrare al tassista, e la disponibilità a comunicare a gesti. Chi impara a leggere quattro caratteri (entrata, uscita, uomini, donne) si semplifica la giornata.',
    elettricita: '220V, 50Hz. Le prese sono di tipo A (piatte, americane) e di tipo I (australiane), spesso combinate nella stessa presa multipla; le spine italiane a due poli tondi non entrano, quindi l\'adattatore serve davvero.',
    fusoOrario: 'UTC+8 per tutto il paese, dal confine con l\'Afghanistan a Shanghai: un unico fuso orario per 5.000 chilometri, motivo per cui a ovest il sole sorge tardissimo. Sono 6 ore avanti rispetto all\'Italia in ora legale, 7 in inverno.',
    clima:
      'Un continente, quindi tutti i climi insieme. Pechino ha inverni secchi e gelidi ed estati afose; Shanghai è umida tutto l\'anno, con un\'estate pesante e una stagione dei tifoni tra luglio e settembre; il Sichuan e Chongqing vivono sotto una cappa grigia per gran parte dell\'anno, con estati torride; lo Yunnan ha il clima migliore del paese, primaverile quasi sempre, ma le notti in quota sono fredde in ogni stagione; Zhangjiajie è spesso nella nebbia, che è insieme il suo problema e il motivo per cui le montagne sembrano quelle di Avatar. Le due finestre buone per quasi tutto il paese sono aprile-maggio e settembre-ottobre.',
    festivita:
      'Due periodi da evitare in modo categorico. La Settimana d\'oro della Festa Nazionale, dal 1° al 7 ottobre, quando centinaia di milioni di persone si spostano insieme: treni esauriti con settimane di anticipo, siti presi d\'assalto, prezzi triplicati. E il Capodanno cinese (tra fine gennaio e metà febbraio, data mobile), con il chunyun, la più grande migrazione umana annuale del pianeta: bellissimo da vedere, impossibile da attraversare da turista, con metà delle attività chiuse. Anche i primi giorni di maggio sono festivi e affollati. Fuori da queste date, il paese si muove normalmente.',
    emergenze: 'Polizia 110, ambulanza 120, vigili del fuoco 119. L\'Ambasciata d\'Italia è a Pechino, con Consolati generali a Shanghai, Canton, Chongqing e Hong Kong.',
    aggiornatoAl: 'settembre 2026',
  },
  heroImageAlt: 'La Grande Muraglia Cinese che sale sul crinale tra le montagne a nord di Pechino',
  tripPrincipaleSlug: 'cina-classica',
}
