import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "L'altra Cina in 18 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/17-cina-paesaggi.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.
// I pernottamenti sono indicati per zona e non per struttura: i nomi effettivi
// non sono ancora stati annotati (statoPernottamento 'da-confermare').

export const cinaPaesaggiMeta: TripMeta = {
  tripSlug: 'cina-paesaggi',
  paeseSlug: 'cina',
  ritmo: 'Impegnativo: diciotto giorni tra parchi, quota e due giorni di trek, con tre voli interni a ricucire le distanze',
  trasporti: 'Alta velocità nell\'Hunan, tre voli interni (Zhangjiajie-Chengdu, Chengdu-Lijiang, Lijiang-Guilin), autista o bus per i parchi, due giorni a piedi lungo la Gola del Salto della Tigre',
  stile: ['paesaggi', 'trekking', 'montagna'],
  adattoA: [
    'chi è già stato in Cina una volta e vuole quello che non compare nelle brochure',
    'chi cammina volentieri e non ha problemi con la quota fino a 4.500 metri',
    'chi accetta di essere spesso l\'unico straniero in vista, con l\'inglese che sparisce del tutto',
  ],
  puntiForti: [
    'Il sentiero alto della Gola del Salto della Tigre, due giorni di cammino su un versante quasi deserto',
    'Impression Lijiang a 3.100 metri, con il massiccio del Drago di Giada come unico fondale',
    'Zhangjiajie all\'apertura, prima che le code all\'ascensore di Bailong diventino di un\'ora e mezza',
  ],
  criticita: [
    'Gli ingressi ai parchi sono la voce di spesa più alta del viaggio, più dei voli: Zhangjiajie, Tianmen Shan e Yulong Xueshan insieme superano tutto il resto',
    'Quasi ogni attrazione principale ha quote giornaliere e ingresso nominale legato al passaporto: senza prenotazione anticipata si resta fuori',
    'La quota va rispettata: da Lijiang a 2.400 metri si sale a 4.506 con la funivia, e Shangri-La supera i 3.200',
    'Il trek della gola non è praticabile tra giugno e agosto, quando le frane chiudono tratti di sentiero',
    'Fuori dalle città l\'inglese è assente: il traduttore con fotocamera passa da comodità a necessità',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con voli interni e ingressi ai parchi prenotati in anticipo',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'I due giorni lungo la Gola del Salto della Tigre, Impression Lijiang sotto il ghiacciaio, la zattera sul fiume Li al mattino presto',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Chongqing', destinazioneSlug: 'chongqing' },
    { nome: 'Furong Zhen', destinazioneSlug: 'furong-zhen' },
    { nome: 'Zhangjiajie', destinazioneSlug: 'zhangjiajie' },
    { nome: 'Chengdu', destinazioneSlug: 'chengdu' },
    { nome: 'Lijiang', destinazioneSlug: 'lijiang' },
    { nome: 'Gola del Salto della Tigre e Shangri-La', destinazioneSlug: 'yulong-shangri-la' },
    { nome: 'Yangshuo', destinazioneSlug: 'yangshuo' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Chongqing',
      tratta: 'Arrivo su CKG',
      pernottamento: 'Chongqing, penisola di Yuzhong',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'chongqing',
      immagine: '/images/viaggi/cina-paesaggi/giorno-1-chongqing.jpg',
      imageAlt: 'Lo skyline di Chongqing di notte, visto dall\'ansa dello Yangtze',
    },
    {
      titoloGiorno: 'Giorno 2 — Chongqing verticale',
      pernottamento: 'Chongqing, penisola di Yuzhong',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'funivia sullo Yangtze pochi yuan, Hongya Dong gratuito',
      destinazioneSlug: 'chongqing',
      immagine: '/images/viaggi/cina-paesaggi/giorno-2-chongqing.jpg',
      imageAlt: 'Gli edifici a più piani di Hongya Dong addossati alla collina, con i grattacieli di Chongqing alle spalle',
    },
    {
      titoloGiorno: 'Giorno 3 — Furong Zhen, il borgo sulla cascata',
      tratta: 'Chongqing → Furong Zhen in alta velocità (poco più di 2h)',
      pernottamento: 'Furong Zhen, guesthouse dentro il borgo',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'ingresso al borgo circa 100 yuan',
      destinazioneSlug: 'furong-zhen',
      immagine: '/images/viaggi/cina-paesaggi/giorno-3-furong-zhen.jpg',
      imageAlt: 'Il borgo di Furong Zhen visto dall\'alto, con le case costruite sopra la cascata che cade nel fiume',
    },
    {
      titoloGiorno: 'Giorno 4 — Verso Zhangjiajie',
      tratta: 'Furong Zhen → Wulingyuan (circa 2h)',
      pernottamento: 'Wulingyuan',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'zhangjiajie',
      immagine: '/images/viaggi/cina-paesaggi/giorno-4-zhangjiajie.jpg',
      imageAlt: 'Un pilastro di arenaria coperto di pini nel Parco Nazionale di Zhangjiajie, con altre guglie sullo sfondo nella foschia',
    },
    {
      titoloGiorno: 'Giorno 5 — Yuanjiajie e l\'ascensore di Bailong',
      pernottamento: 'Wulingyuan',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso al parco circa 239 yuan (valido 4 giorni), ascensore di Bailong ~72 a corsa',
      destinazioneSlug: 'zhangjiajie',
      immagine: '/images/viaggi/cina-paesaggi/giorno-5-bailong.jpg',
      imageAlt: 'Le guglie di arenaria di Yuanjiajie, le "montagne di Avatar", viste dalla base dell\'ascensore di Bailong',
    },
    {
      titoloGiorno: 'Giorno 6 — Tianzi Shan e il fondovalle',
      pernottamento: 'Wulingyuan',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'incluso nel biglietto di 4 giorni, funivie a parte',
      destinazioneSlug: 'zhangjiajie',
      immagine: '/images/viaggi/cina-paesaggi/giorno-6-tianzishan.jpg',
      imageAlt: 'Le vette di Tianzi Shan tra le nuvole, con la funivia che attraversa le guglie di roccia',
    },
    {
      titoloGiorno: 'Giorno 7 — Tianmen Shan e volo per Chengdu',
      tratta: 'Wulingyuan → città di Zhangjiajie, poi volo DYG → Chengdu',
      pernottamento: 'Chengdu, zona Wenshu o Kuanzhai Xiangzi',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Tianmen Shan 250-280 yuan con funivia, fascia oraria da prenotare',
      destinazioneSlug: 'zhangjiajie',
      immagine: '/images/viaggi/cina-paesaggi/giorno-7-tianmenshan.jpg',
      imageAlt: 'L\'arco naturale della Porta del Paradiso sul Tianmen Shan, con la strada tortuosa e la passerella scavate nella parete rocciosa',
    },
    {
      titoloGiorno: 'Giorno 8 — Chengdu: panda, tè e hot pot',
      pernottamento: 'Chengdu, zona Wenshu o Kuanzhai Xiangzi',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'base dei panda circa 55 yuan, prenotazione nominale obbligatoria; hot pot 60-120 a persona',
      destinazioneSlug: 'chengdu',
      immagine: '/images/viaggi/cina-paesaggi/giorno-8-chengdu-panda.jpg',
      imageAlt: 'Un panda gigante seduto sull\'erba mentre mangia germogli di bambù a Chengdu',
    },
    {
      titoloGiorno: 'Giorno 9 — Leshan, poi volo per Lijiang',
      tratta: 'Chengdu → Leshan e ritorno, poi volo CTU/TFU → LJG',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Leshan circa 80 yuan',
      destinazioneSlug: 'chengdu',
      immagine: '/images/viaggi/cina-paesaggi/giorno-9-leshan.jpg',
      imageAlt: 'Il Grande Buddha di Leshan scolpito nella parete rocciosa, visto dal fiume',
    },
    {
      titoloGiorno: 'Giorno 10 — Lijiang e Baisha',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'lijiang',
      immagine: '/images/viaggi/cina-paesaggi/giorno-10-lijiang.jpg',
      imageAlt: 'Un canale della città vecchia di Lijiang tra le case in legno e mattoni grigi dai tetti in tegole',
    },
    {
      titoloGiorno: 'Giorno 11 — Yulong Xueshan e Impression Lijiang',
      tratta: 'Lijiang → parco dello Yulong Xueshan (circa 1h) e ritorno',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso parco ~100 yuan + navetta 20 + funivia ghiacciaio ~120; Impression Lijiang 190-280',
      destinazioneSlug: 'yulong-shangri-la',
      immagine: '/images/viaggi/cina-paesaggi/giorno-11-yulong-xueshan.jpg',
      imageAlt: 'Le vette innevate dello Yulong Xueshan, il Monte del Drago di Giada, al tramonto',
    },
    {
      titoloGiorno: 'Giorno 12 — Gola del Salto della Tigre, primo giorno',
      tratta: 'Lijiang → Qiaotou (circa 2h), poi 5-6h di cammino sul sentiero alto',
      pernottamento: 'Guesthouse lungo il sentiero alto',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso alla gola circa 65 yuan',
      destinazioneSlug: 'yulong-shangri-la',
      immagine: '/images/viaggi/cina-paesaggi/giorno-12-tiger-leaping-gorge.jpg',
      imageAlt: 'Il fiume Jinsha visto dall\'alto della Gola del Salto della Tigre, con i terrazzamenti coltivati sul fondovalle',
    },
    {
      titoloGiorno: 'Giorno 13 — Secondo giorno di trek e Shangri-La',
      tratta: '3-4h di cammino fino a Walnut Garden, poi trasferimento a Shangri-La (circa 2h)',
      pernottamento: 'Shangri-La, città vecchia di Dukezong',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'yulong-shangri-la',
      immagine: '/images/viaggi/cina-paesaggi/giorno-13-gola-trek.jpg',
      imageAlt: 'Il sentiero alto della Gola del Salto della Tigre, con il fiume Jinsha che serpeggia nella valle sottostante',
    },
    {
      titoloGiorno: 'Giorno 14 — Shangri-La e rientro a Lijiang',
      tratta: 'Shangri-La → Lijiang in treno (poco più di 1h)',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'monastero di Songzanlin circa 100 yuan',
      destinazioneSlug: 'yulong-shangri-la',
      immagine: '/images/viaggi/cina-paesaggi/giorno-14-songzanlin.jpg',
      imageAlt: 'Il monastero di Songzanlin (Ganden Sumtseling) sulla collina sopra Shangri-La, con i suoi tetti dorati',
    },
    {
      titoloGiorno: 'Giorno 15 — Volo per Guilin e trasferimento a Yangshuo',
      tratta: 'Volo LJG → KWL, poi circa 1h di bus fino a Yangshuo',
      pernottamento: 'Campagna lungo la Yulong River o Xingping',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'yangshuo',
      immagine: '/images/viaggi/cina-paesaggi/giorno-15-guilin-li-river.jpg',
      imageAlt: 'Le guglie carsiche intorno al fiume Li al tramonto, avvolte nella foschia della sera',
    },
    {
      titoloGiorno: 'Giorno 16 — Xingping in zattera e alba a Xianggong',
      pernottamento: 'Campagna lungo la Yulong River o Xingping',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'zattera di bambù 100-150 yuan per il tratto breve',
      destinazioneSlug: 'yangshuo',
      immagine: '/images/viaggi/cina-paesaggi/giorno-16-xingping.jpg',
      imageAlt: 'Le montagne carsiche di Xingping riflesse nel fiume Li, lo scorcio raffigurato sulla banconota da 20 yuan',
    },
    {
      titoloGiorno: 'Giorno 17 — Yangshuo in bicicletta',
      pernottamento: 'Campagna lungo la Yulong River o Xingping',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'bici elettrica pochi yuan al giorno; Impression Liu Sanjie biglietto a parte',
      destinazioneSlug: 'yangshuo',
      immagine: '/images/viaggi/cina-paesaggi/giorno-17-yangshuo.jpg',
      imageAlt: 'Risaie allagate nella campagna di Yangshuo, con i contadini al lavoro e le cime carsiche sullo sfondo nella foschia',
    },
    {
      titoloGiorno: 'Giorno 18 — Guilin e partenza',
      tratta: 'Yangshuo → Guilin (circa 1h), volo di rientro',
      intensita: 'leggero',
      destinazioneSlug: 'yangshuo',
      immagine: '/images/viaggi/cina-paesaggi/giorno-18-guilin-elephant-hill.jpg',
      imageAlt: 'L\'Elephant Trunk Hill di Guilin, la collina carsica a forma di proboscide che si immerge nel fiume Li',
    },
  ],
  budget: [
    { etichetta: 'Voli intercontinentali', valore: undefined },
    { etichetta: 'Tre voli interni', valore: 'indicativamente 60-120€ ciascuno prenotando in anticipo' },
    { etichetta: 'Alloggi', valore: '40€ a notte nelle città di provincia, meno nelle guesthouse del trek' },
    { etichetta: 'Ingressi ai parchi', valore: 'Zhangjiajie ~239 yuan + funivie, Tianmen Shan 250-280, Yulong Xueshan ~240 complessivi, gola ~65' },
    { etichetta: 'Spettacoli', valore: 'Impression Lijiang 190-280 yuan, Impression Liu Sanjie a parte' },
    { etichetta: 'Pasti', valore: 'sotto i 10€ quasi ovunque, pasti inclusi nelle guesthouse del trek' },
  ],
}
