import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Cina classica in 15 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/16-cina-classica.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.
// I pernottamenti sono indicati per zona e non per struttura: i nomi degli hotel
// effettivamente usati non sono ancora stati annotati (statoPernottamento 'da-confermare').

export const cinaClassicaMeta: TripMeta = {
  tripSlug: 'cina-classica',
  paeseSlug: 'cina',
  ritmo: 'Sostenuto ma non sfiancante: quattro basi in quindici giorni, con i trasferimenti affidati all\'alta velocità invece che alle giornate di viaggio',
  trasporti: 'Treni ad alta velocità sull\'asse Pechino-Xi\'an-Shanghai, volo o treno lungo per Hong Kong, traghetto per Macao; metropolitana ovunque in città',
  stile: ['grandi classici', 'alta velocità', 'megalopoli'],
  adattoA: [
    'chi va in Cina per la prima volta e vuole i luoghi simbolo senza rinunciare alle città',
    'chi si muove volentieri in treno e preferisce poche basi a molte tappe',
    'chi è disposto a organizzare prenotazioni e pagamenti prima di partire',
  ],
  puntiForti: [
    'La Grande Muraglia a Jinshanling, non restaurata e quasi deserta',
    'I giardini classici di Suzhou in un giorno feriale, a 25 minuti di treno da Shanghai',
    'La chiusura su Hong Kong e Macao, che sono Cina solo sulla carta',
  ],
  criticita: [
    'Tutta la preparazione è concentrata prima della partenza: pagamenti, connettività, account per i treni e prenotazioni dei musei vanno sistemati da casa, o si perdono i primi giorni',
    'Città Proibita ed Esercito di Terracotta hanno biglietterie fisiche chiuse e quote giornaliere: senza prenotazione non esiste un piano B in loco',
    'I biglietti dei treni si aprono 15 giorni prima alle 8 ora di Pechino e sulle tratte forti si esauriscono in poche ore',
    'Hong Kong ribalta il budget: è di gran lunga la tappa più cara, soprattutto sugli alloggi',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con treni e prenotazioni dei musei organizzati dall\'Italia',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'La Muraglia a Jinshanling, i giardini di Suzhou in un martedì mattina, la traversata del porto di Hong Kong in Star Ferry all\'ora blu',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Pechino', destinazioneSlug: 'pechino' },
    { nome: 'Xi\'an', destinazioneSlug: 'xian' },
    { nome: 'Shanghai', destinazioneSlug: 'shanghai' },
    { nome: 'Suzhou', destinazioneSlug: 'shanghai' },
    { nome: 'Hong Kong', destinazioneSlug: 'hong-kong' },
    { nome: 'Macao', destinazioneSlug: 'macao' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Pechino',
      tratta: 'Arrivo su PEK o PKX',
      pernottamento: 'Pechino, zona Dongcheng',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'pechino',
      immagine: '/images/viaggi/cina-classica/giorno-1-hutong-pechino.jpg',
      imageAlt: 'Un vicolo hutong a Pechino, tra i muri in mattoni grigi delle case a corte tradizionali',
    },
    {
      titoloGiorno: 'Giorno 2 — Città Proibita, Tiananmen e Jingshan',
      pernottamento: 'Pechino, zona Dongcheng',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Città Proibita circa 60 yuan in alta stagione, prenotazione obbligatoria',
      destinazioneSlug: 'pechino',
      immagine: '/images/viaggi/cina-classica/giorno-2-citta-proibita.jpg',
      imageAlt: 'La Sala dell\'Armonia Suprema nella Città Proibita, con la grande scalinata di marmo e i visitatori',
    },
    {
      titoloGiorno: 'Giorno 3 — La Grande Muraglia a Jinshanling',
      tratta: 'Pechino → Jinshanling e ritorno (2h30 per lato)',
      pernottamento: 'Pechino, zona Dongcheng',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso circa 65 yuan più trasferimento privato',
      destinazioneSlug: 'pechino',
      immagine: '/images/viaggi/cina-classica/giorno-3-muraglia-jinshanling.jpg',
      imageAlt: 'La Grande Muraglia che corre lungo le creste verdi di Jinshanling, non restaurata e quasi deserta',
    },
    {
      titoloGiorno: 'Giorno 4 — Tempio del Cielo, hutong e Palazzo d\'Estate',
      pernottamento: 'Pechino, zona Dongcheng',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Tempio del Cielo e Palazzo d\'Estate 30-60 yuan con biglietto combinato',
      destinazioneSlug: 'pechino',
      immagine: '/images/viaggi/cina-classica/giorno-4-tempio-del-cielo.jpg',
      imageAlt: 'La Sala della Preghiera per il Buon Raccolto nel Tempio del Cielo, con il suo tetto circolare a tre livelli',
    },
    {
      titoloGiorno: 'Giorno 5 — Treno per Xi\'an e mura in bicicletta',
      tratta: 'Pechino → Xi\'an in alta velocità (4h30)',
      pernottamento: 'Xi\'an, dentro le mura',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'mura 54 yuan più circa 45 di noleggio bici',
      destinazioneSlug: 'xian',
      immagine: '/images/viaggi/cina-classica/giorno-5-mura-xian.jpg',
      imageAlt: 'La sommità larga delle antiche mura di Xi\'an, percorsa a piedi e in bicicletta',
    },
    {
      titoloGiorno: 'Giorno 6 — Esercito di Terracotta',
      tratta: 'Xi\'an → Lintong e ritorno (bus 5/306)',
      pernottamento: 'Xi\'an, dentro le mura',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'ingresso circa 120 yuan, vendita aperta solo 7 giorni prima',
      destinazioneSlug: 'xian',
      immagine: '/images/viaggi/cina-classica/giorno-6-esercito-terracotta.jpg',
      imageAlt: 'Le file di guerrieri di terracotta nella fossa 1, con la scala del sito che si coglie tutta insieme',
    },
    {
      titoloGiorno: 'Giorno 7 — Treno per Shanghai e il Bund',
      tratta: 'Xi\'an → Shanghai in alta velocità (6h)',
      pernottamento: 'Shanghai, ex Concessione Francese',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'shanghai',
      immagine: '/images/viaggi/cina-classica/giorno-7-bund-shanghai.jpg',
      imageAlt: 'Lo skyline di Pudong illuminato di notte, visto dal Bund con il fiume Huangpu in primo piano',
    },
    {
      titoloGiorno: 'Giorno 8 — Shanghai: Concessione Francese, Yuyuan, Pudong',
      pernottamento: 'Shanghai, ex Concessione Francese',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Shanghai Tower circa 180 yuan',
      destinazioneSlug: 'shanghai',
      immagine: '/images/viaggi/cina-classica/giorno-8-yuyuan-garden.jpg',
      imageAlt: 'I padiglioni rossi del Giardino Yuyuan che si affacciano sullo stagno, nel cuore della città vecchia',
    },
    {
      titoloGiorno: 'Giorno 9 — Suzhou e i giardini classici',
      tratta: 'Shanghai → Suzhou in alta velocità (25 min) e ritorno',
      pernottamento: 'Shanghai, ex Concessione Francese',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'giardini 30-80 yuan ciascuno secondo la stagione',
      destinazioneSlug: 'shanghai',
      immagine: '/images/viaggi/cina-classica/giorno-9-giardino-suzhou.jpg',
      imageAlt: 'Uno stagno con padiglione nel Giardino dell\'Umile Amministratore a Suzhou, tra salici e rocce ornamentali',
    },
    {
      titoloGiorno: 'Giorno 10 — Un villaggio d\'acqua',
      tratta: 'Gita in giornata da Shanghai (Zhujiajiao, Tongli, Wuzhen o Nanxun)',
      pernottamento: 'Shanghai, ex Concessione Francese',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'ingresso al borgo 50-120 yuan secondo la scelta',
      destinazioneSlug: 'shanghai',
      immagine: '/images/viaggi/cina-classica/giorno-10-villaggio-acqua.jpg',
      imageAlt: 'Un canale tra case tradizionali in un villaggio d\'acqua dello Jiangnan, al tramonto',
    },
    {
      titoloGiorno: 'Giorno 11 — Verso Hong Kong',
      tratta: 'Shanghai → Hong Kong, volo (2h30) o alta velocità fino a West Kowloon (8h)',
      pernottamento: 'Hong Kong, lato isola o Tsim Sha Tsui',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'hong-kong',
      immagine: '/images/viaggi/cina-classica/giorno-11-hong-kong-skyline.jpg',
      imageAlt: 'Lo skyline di Hong Kong Island visto da Tsim Sha Tsui, con gli Star Ferry che attraversano il porto',
    },
    {
      titoloGiorno: 'Giorno 12 — Hong Kong: Peak, Star Ferry, mercati',
      pernottamento: 'Hong Kong, lato isola o Tsim Sha Tsui',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Peak Tram con piattaforma 100-150 HKD; Star Ferry pochi HKD',
      destinazioneSlug: 'hong-kong',
      immagine: '/images/viaggi/cina-classica/giorno-12-victoria-peak.jpg',
      imageAlt: 'Il porto di Victoria e i grattacieli di Hong Kong Island visti dall\'alto di Victoria Peak',
    },
    {
      titoloGiorno: 'Giorno 13 — Macao in giornata',
      tratta: 'Hong Kong → Macao in traghetto veloce (1h) o bus sul ponte',
      pernottamento: 'Hong Kong, lato isola o Tsim Sha Tsui',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'traghetto 160-200 HKD a tratta; centro storico quasi tutto gratuito',
      destinazioneSlug: 'macao',
      immagine: '/images/viaggi/cina-classica/giorno-13-rovine-san-paolo-macao.jpg',
      imageAlt: 'La facciata barocca delle Rovine di San Paolo a Macao, vista dal basso della grande scalinata',
    },
    {
      titoloGiorno: 'Giorno 14 — Lantau e la Hong Kong che non ci si aspetta',
      pernottamento: 'Hong Kong, lato isola o Tsim Sha Tsui',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'hong-kong',
      immagine: '/images/viaggi/cina-classica/giorno-14-tian-tan-buddha-lantau.jpg',
      imageAlt: 'Il grande Buddha di Tian Tan sulla cima della collina a Ngong Ping, isola di Lantau, tra le montagne verdi',
    },
    {
      titoloGiorno: 'Giorno 15 — Partenza',
      tratta: 'Hong Kong Central → HKG con Airport Express (24 min)',
      intensita: 'leggero',
      destinazioneSlug: 'hong-kong',
      immagine: '/images/viaggi/cina-classica/giorno-15-aeroporto-hong-kong.jpg',
      imageAlt: 'Il terminal dall\'iconico tetto ondulato dell\'aeroporto di Hong Kong al tramonto, ultimo scorcio prima della partenza',
    },
  ],
  budget: [
    { etichetta: 'Voli intercontinentali', valore: undefined },
    { etichetta: 'Treni ad alta velocità (3 tratte lunghe)', valore: 'indicativamente 40-90€ a tratta in seconda classe' },
    { etichetta: 'Volo o treno Shanghai-Hong Kong', valore: undefined },
    { etichetta: 'Alloggi', valore: '40-70€ a notte nella Cina continentale, molto di più a Hong Kong' },
    { etichetta: 'Ingressi principali', valore: 'Città Proibita ~60 yuan, Esercito di Terracotta ~120, mura di Xi\'an 54, giardini di Suzhou 30-80 ciascuno' },
    { etichetta: 'Traghetto per Macao', valore: '160-200 HKD a tratta' },
    { etichetta: 'Pasti', valore: '4-10€ a pasto nella Cina continentale, più cari a Hong Kong' },
  ],
}
