import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "L'altra Cina in 18 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/17-cina-paesaggi.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.
// I pernottamenti sono indicati per zona e non per struttura: i nomi effettivi
// non sono ancora stati annotati (statoPernottamento 'da-confermare').

export const cinaPaesaggiMeta: TripMeta = {
  tripSlug: 'cina-paesaggi',
  paeseSlug: 'cina',
  ritmo: 'Impegnativo: diciotto giorni tra parchi, quota e due giorni di trek, con tre voli interni a ricucire le distanze',
  trasporti: 'Alta velocità nell\'Hunan, tre voli interni (Zhangjiajie-Chengdu, Chengdu-Lijiang, Lijiang-Guilin), autista o bus per i parchi, due giorni a piedi lungo la Gola del Salto della Tigre',
  stile: ['paesaggi', 'trekking', 'montagna'],
  adattoA: [
    'chi è già stato in Cina una volta e vuole quello che non compare nelle brochure',
    'chi cammina volentieri e non ha problemi con la quota fino a 4.500 metri',
    'chi accetta di essere spesso l\'unico straniero in vista, con l\'inglese che sparisce del tutto',
  ],
  puntiForti: [
    'Il sentiero alto della Gola del Salto della Tigre, due giorni di cammino su un versante quasi deserto',
    'Impression Lijiang a 3.100 metri, con il massiccio del Drago di Giada come unico fondale',
    'Zhangjiajie all\'apertura, prima che le code all\'ascensore di Bailong diventino di un\'ora e mezza',
  ],
  criticita: [
    'Gli ingressi ai parchi sono la voce di spesa più alta del viaggio, più dei voli: Zhangjiajie, Tianmen Shan e Yulong Xueshan insieme superano tutto il resto',
    'Quasi ogni attrazione principale ha quote giornaliere e ingresso nominale legato al passaporto: senza prenotazione anticipata si resta fuori',
    'La quota va rispettata: da Lijiang a 2.400 metri si sale a 4.506 con la funivia, e Shangri-La supera i 3.200',
    'Il trek della gola non è praticabile tra giugno e agosto, quando le frane chiudono tratti di sentiero',
    'Fuori dalle città l\'inglese è assente: il traduttore con fotocamera passa da comodità a necessità',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con voli interni e ingressi ai parchi prenotati in anticipo',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'I due giorni lungo la Gola del Salto della Tigre, Impression Lijiang sotto il ghiacciaio, la zattera sul fiume Li al mattino presto',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Chongqing', destinazioneSlug: 'chongqing' },
    { nome: 'Furong Zhen', destinazioneSlug: 'furong-zhen' },
    { nome: 'Zhangjiajie', destinazioneSlug: 'zhangjiajie' },
    { nome: 'Chengdu', destinazioneSlug: 'chengdu' },
    { nome: 'Lijiang', destinazioneSlug: 'lijiang' },
    { nome: 'Gola del Salto della Tigre e Shangri-La', destinazioneSlug: 'yulong-shangri-la' },
    { nome: 'Yangshuo', destinazioneSlug: 'yangshuo' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Chongqing',
      tratta: 'Arrivo su CKG',
      pernottamento: 'Chongqing, penisola di Yuzhong',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'chongqing',
    },
    {
      titoloGiorno: 'Giorno 2 — Chongqing verticale',
      pernottamento: 'Chongqing, penisola di Yuzhong',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'funivia sullo Yangtze pochi yuan, Hongya Dong gratuito',
      destinazioneSlug: 'chongqing',
    },
    {
      titoloGiorno: 'Giorno 3 — Furong Zhen, il borgo sulla cascata',
      tratta: 'Chongqing → Furong Zhen in alta velocità (poco più di 2h)',
      pernottamento: 'Furong Zhen, guesthouse dentro il borgo',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'ingresso al borgo circa 100 yuan',
      destinazioneSlug: 'furong-zhen',
    },
    {
      titoloGiorno: 'Giorno 4 — Verso Zhangjiajie',
      tratta: 'Furong Zhen → Wulingyuan (circa 2h)',
      pernottamento: 'Wulingyuan',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'zhangjiajie',
    },
    {
      titoloGiorno: 'Giorno 5 — Yuanjiajie e l\'ascensore di Bailong',
      pernottamento: 'Wulingyuan',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso al parco circa 239 yuan (valido 4 giorni), ascensore di Bailong ~72 a corsa',
      destinazioneSlug: 'zhangjiajie',
    },
    {
      titoloGiorno: 'Giorno 6 — Tianzi Shan e il fondovalle',
      pernottamento: 'Wulingyuan',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'incluso nel biglietto di 4 giorni, funivie a parte',
      destinazioneSlug: 'zhangjiajie',
    },
    {
      titoloGiorno: 'Giorno 7 — Tianmen Shan e volo per Chengdu',
      tratta: 'Wulingyuan → città di Zhangjiajie, poi volo DYG → Chengdu',
      pernottamento: 'Chengdu, zona Wenshu o Kuanzhai Xiangzi',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Tianmen Shan 250-280 yuan con funivia, fascia oraria da prenotare',
      destinazioneSlug: 'zhangjiajie',
    },
    {
      titoloGiorno: 'Giorno 8 — Chengdu: panda, tè e hot pot',
      pernottamento: 'Chengdu, zona Wenshu o Kuanzhai Xiangzi',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'base dei panda circa 55 yuan, prenotazione nominale obbligatoria; hot pot 60-120 a persona',
      destinazioneSlug: 'chengdu',
    },
    {
      titoloGiorno: 'Giorno 9 — Leshan, poi volo per Lijiang',
      tratta: 'Chengdu → Leshan e ritorno, poi volo CTU/TFU → LJG',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Leshan circa 80 yuan',
      destinazioneSlug: 'chengdu',
    },
    {
      titoloGiorno: 'Giorno 10 — Lijiang e Baisha',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'lijiang',
    },
    {
      titoloGiorno: 'Giorno 11 — Yulong Xueshan e Impression Lijiang',
      tratta: 'Lijiang → parco dello Yulong Xueshan (circa 1h) e ritorno',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso parco ~100 yuan + navetta 20 + funivia ghiacciaio ~120; Impression Lijiang 190-280',
      destinazioneSlug: 'yulong-shangri-la',
    },
    {
      titoloGiorno: 'Giorno 12 — Gola del Salto della Tigre, primo giorno',
      tratta: 'Lijiang → Qiaotou (circa 2h), poi 5-6h di cammino sul sentiero alto',
      pernottamento: 'Guesthouse lungo il sentiero alto',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso alla gola circa 65 yuan',
      destinazioneSlug: 'yulong-shangri-la',
    },
    {
      titoloGiorno: 'Giorno 13 — Secondo giorno di trek e Shangri-La',
      tratta: '3-4h di cammino fino a Walnut Garden, poi trasferimento a Shangri-La (circa 2h)',
      pernottamento: 'Shangri-La, città vecchia di Dukezong',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'yulong-shangri-la',
    },
    {
      titoloGiorno: 'Giorno 14 — Shangri-La e rientro a Lijiang',
      tratta: 'Shangri-La → Lijiang in treno (poco più di 1h)',
      pernottamento: 'Lijiang, città vecchia di Dayan o Shuhe',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'monastero di Songzanlin circa 100 yuan',
      destinazioneSlug: 'yulong-shangri-la',
    },
    {
      titoloGiorno: 'Giorno 15 — Volo per Guilin e trasferimento a Yangshuo',
      tratta: 'Volo LJG → KWL, poi circa 1h di bus fino a Yangshuo',
      pernottamento: 'Campagna lungo la Yulong River o Xingping',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'yangshuo',
    },
    {
      titoloGiorno: 'Giorno 16 — Xingping in zattera e alba a Xianggong',
      pernottamento: 'Campagna lungo la Yulong River o Xingping',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'zattera di bambù 100-150 yuan per il tratto breve',
      destinazioneSlug: 'yangshuo',
    },
    {
      titoloGiorno: 'Giorno 17 — Yangshuo in bicicletta',
      pernottamento: 'Campagna lungo la Yulong River o Xingping',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'bici elettrica pochi yuan al giorno; Impression Liu Sanjie biglietto a parte',
      destinazioneSlug: 'yangshuo',
    },
    {
      titoloGiorno: 'Giorno 18 — Guilin e partenza',
      tratta: 'Yangshuo → Guilin (circa 1h), volo di rientro',
      intensita: 'leggero',
      destinazioneSlug: 'yangshuo',
    },
  ],
  budget: [
    { etichetta: 'Voli intercontinentali', valore: undefined },
    { etichetta: 'Tre voli interni', valore: 'indicativamente 60-120€ ciascuno prenotando in anticipo' },
    { etichetta: 'Alloggi', valore: '40€ a notte nelle città di provincia, meno nelle guesthouse del trek' },
    { etichetta: 'Ingressi ai parchi', valore: 'Zhangjiajie ~239 yuan + funivie, Tianmen Shan 250-280, Yulong Xueshan ~240 complessivi, gola ~65' },
    { etichetta: 'Spettacoli', valore: 'Impression Lijiang 190-280 yuan, Impression Liu Sanjie a parte' },
    { etichetta: 'Pasti', valore: 'sotto i 10€ quasi ovunque, pasti inclusi nelle guesthouse del trek' },
  ],
}
