import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Corea del Sud in 14 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/18-corea-del-sud-itinerario.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.
// I pernottamenti sono indicati per zona e non per struttura: i nomi effettivi
// non sono ancora stati annotati (statoPernottamento 'da-confermare').

export const coreaDelSudItinerarioMeta: TripMeta = {
  tripSlug: 'corea-del-sud-itinerario',
  paeseSlug: 'corea-del-sud',
  ritmo: 'Equilibrato: due blocchi urbani, due tappe rurali e una chiusura sull\'isola, con i trasferimenti affidati ad alta velocità e autobus express',
  trasporti: 'KTX sull\'asse Seoul-Gyeongju-Busan, autobus express per Sokcho e Andong, volo per Jeju, auto a noleggio solo sull\'isola',
  stile: ['storia contemporanea', 'cultura', 'gastronomia'],
  adattoA: [
    'chi viaggia per capire più che per spuntare monumenti',
    'chi vuole la parte storica del Novecento coreano senza rinunciare a montagna, mare e cucina',
    'chi si muove volentieri con i mezzi pubblici e accetta di prenotare in anticipo le poche cose contingentate',
  ],
  puntiForti: [
    'La DMZ preceduta dal Memoriale della Guerra a Seoul, che è ciò che la rende leggibile',
    'Le haenyeo di Jeju, con il museo prima e la costa orientale dopo',
    'Il templestay in un monastero di montagna, con il pasto rituale e la liturgia prima dell\'alba',
  ],
  criticita: [
    'Google Maps in Corea non calcola i percorsi: senza Naver Map o KakaoMap scaricate prima di partire si perde il primo giorno',
    'La JSA di Panmunjom non è garantita: l\'accesso civile è stato sospeso più volte dal 2023 e va tenuto come bonus, mai come perno del viaggio',
    'Alla DMZ serve il passaporto originale: nessuna copia viene accettata al checkpoint',
    'Le haenyeo non escono a orario: dipendono da maree, stagione e fermo biologico, e le uniche uscite prevedibili sono le dimostrazioni organizzate',
    'Diverse cose sono contingentate e vanno prenotate: Giardino Segreto di Changdeokgung, sentieri di vetta dell\'Hallasan, templestay',
    'Per noleggiare l\'auto a Jeju serve la patente internazionale, da fare in Italia prima di partire',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con treni, tour della DMZ e prenotazioni contingentate organizzati dall\'Italia',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'La stazione di Dorasan alla DMZ, il sumbisori delle haenyeo sulla costa est di Jeju, la liturgia delle quattro del mattino durante il templestay',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Seoul', destinazioneSlug: 'seoul' },
    { nome: 'DMZ', destinazioneSlug: 'dmz' },
    { nome: 'Sokcho e Seoraksan', destinazioneSlug: 'sokcho-seoraksan' },
    { nome: 'Andong', destinazioneSlug: 'andong' },
    { nome: 'Gyeongju', destinazioneSlug: 'gyeongju' },
    { nome: 'Busan', destinazioneSlug: 'busan' },
    { nome: 'Jeju', destinazioneSlug: 'jeju' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Seoul',
      tratta: 'Arrivo su ICN, AREX fino al centro (1h)',
      pernottamento: 'Seoul, Myeongdong o Jongno',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'seoul',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-1-seoul-skyline.jpg',
      imageAlt: 'Lo skyline di Seoul lungo il fiume Han, con i grattacieli di Yeouido sotto un cielo azzurro',
    },
    {
      titoloGiorno: 'Giorno 2 — Palazzi e Memoriale della Guerra',
      pernottamento: 'Seoul, Myeongdong o Jongno',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'palazzi circa 3.000 won, Giardino Segreto 5.000 in più, Memoriale della Guerra gratuito',
      destinazioneSlug: 'seoul',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-2-changdeokgung.jpg',
      imageAlt: 'Il padiglione sul laghetto di Buyongji, nel Giardino Segreto del palazzo di Changdeokgung',
    },
    {
      titoloGiorno: 'Giorno 3 — La DMZ',
      tratta: 'Seoul → Paju e ritorno, con tour autorizzato',
      pernottamento: 'Seoul, Myeongdong o Jongno',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'tour standard 50-90€, pranzo spesso incluso; passaporto originale obbligatorio',
      destinazioneSlug: 'dmz',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-3-dmz-jsa.jpg',
      imageAlt: 'Le baracche blu della Joint Security Area a Panmunjom, con le guardie sulla linea di demarcazione',
    },
    {
      titoloGiorno: 'Giorno 4 — Seoul: quartieri, fortezza, jjimjilbang',
      pernottamento: 'Seoul, Myeongdong o Jongno',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'jjimjilbang 8.000-15.000 won',
      destinazioneSlug: 'seoul',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-4-bukchon.jpg',
      imageAlt: 'Il vicolo in salita di Bukchon-ro fiancheggiato dai tetti tradizionali delle case hanok',
    },
    {
      titoloGiorno: 'Giorno 5 — Sokcho e il Seoraksan',
      tratta: 'Seoul → Sokcho in autobus express (2h30)',
      pernottamento: 'Sokcho',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'sokcho-seoraksan',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-5-seoraksan.jpg',
      imageAlt: 'Le guglie di roccia del Seoraksan viste dal Daecheongbong, la vetta più alta del parco',
    },
    {
      titoloGiorno: 'Giorno 6 — Seoraksan',
      pernottamento: 'Sokcho',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso al parco pochi euro; funivia per Gwongeumseong circa 11.000 won A/R',
      destinazioneSlug: 'sokcho-seoraksan',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-6-ulsanbawi.jpg',
      imageAlt: 'La cresta di granito di Ulsanbawi, con le montagne del Seoraksan che sfumano sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 7 — Andong e il villaggio di Hahoe',
      tratta: 'Sokcho → Andong, poi autobus locale per Hahoe (40 min)',
      pernottamento: 'Hahoe, in una hanok dentro il villaggio',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'ingresso a Hahoe circa 5.000 won',
      destinazioneSlug: 'andong',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-7-hahoe.jpg',
      imageAlt: "Vista dall'alto del villaggio di Hahoe, con le case dal tetto di paglia nell'ansa del fiume",
    },
    {
      titoloGiorno: 'Giorno 8 — Gyeongju',
      tratta: 'Andong → Gyeongju',
      pernottamento: 'Gyeongju, zona Daereungwon',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Daereungwon 3.000 won, Museo Nazionale gratuito',
      destinazioneSlug: 'gyeongju',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-8-cheomseongdae.jpg',
      imageAlt: "L'osservatorio astronomico di Cheomseongdae a Gyeongju, tra i più antichi dell'Asia orientale",
    },
    {
      titoloGiorno: 'Giorno 9 — Bulguksa, Seokguram e templestay',
      tratta: 'Gyeongju → monte Toham, poi monastero',
      pernottamento: 'Monastero buddista (templestay)',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Bulguksa e Seokguram circa 6.000 won ciascuno; templestay 50.000-100.000 won con pasti',
      destinazioneSlug: 'gyeongju',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-9-bulguksa.jpg',
      imageAlt: 'I tetti in tegole e la scalinata in pietra del tempio buddista di Bulguksa, sul monte Toham',
    },
    {
      titoloGiorno: 'Giorno 10 — Busan',
      tratta: 'Gyeongju → Busan (circa 30 min in KTX)',
      pernottamento: 'Busan, Nampo-dong o Seomyeon',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'busan',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-10-gamcheon.jpg',
      imageAlt: 'Le case colorate del villaggio di Gamcheon a Busan, arrampicate sulla collina al crepuscolo',
    },
    {
      titoloGiorno: 'Giorno 11 — Busan: il cimitero ONU e la costa',
      pernottamento: 'Busan, Nampo-dong o Seomyeon',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'cimitero ONU e tempio Haedong Yonggungsa gratuiti',
      destinazioneSlug: 'busan',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-11-haeundae.jpg',
      imageAlt: 'La spiaggia di Haeundae a Busan, con gli ombrelloni rossi e lo skyline della città sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 12 — Volo per Jeju e la costa orientale',
      tratta: 'Volo Busan → Jeju (meno di 1h), poi auto a noleggio',
      pernottamento: 'Jeju, costa orientale attorno a Seongsan',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Museo delle haenyeo circa 1.100 won; noleggio auto 40-60€ al giorno, patente internazionale obbligatoria',
      destinazioneSlug: 'jeju',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-12-jeju-costa.jpg',
      imageAlt: 'La costa lavica di Seopjikoji a Jeju, con il promontorio di Seongsan Ilchulbong sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 13 — Le haenyeo e Seongsan Ilchulbong',
      pernottamento: 'Jeju, costa orientale attorno a Seongsan',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Seongsan Ilchulbong 5.000 won, Manjanggul 4.000, Parco della Pace 4·3 gratuito',
      destinazioneSlug: 'jeju',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-13-seongsan-ilchulbong.jpg',
      imageAlt: 'Vista aerea del cratere erboso di Seongsan Ilchulbong, la "Punta del Sole" sulla costa di Jeju',
    },
    {
      titoloGiorno: 'Giorno 14 — Rientro',
      tratta: 'Volo Jeju → Gimpo e proseguimento per Incheon',
      intensita: 'leggero',
      destinazioneSlug: 'jeju',
      immagine: '/images/viaggi/corea-del-sud-itinerario/giorno-14-incheon-partenza.jpg',
      imageAlt: "La grande hall del Terminal 1 dell'aeroporto di Incheon, con i banchi check-in e i passeggeri in partenza",
    },
  ],
  budget: [
    { etichetta: 'Voli intercontinentali', valore: undefined },
    { etichetta: 'KTX e autobus express', valore: 'Seoul-Busan attorno ai 40€; le altre tratte meno' },
    { etichetta: 'Volo per Jeju', valore: 'spesso sotto i 50€ prenotando in anticipo' },
    { etichetta: 'Alloggi', valore: '60-90€ a notte per un buon livello; meno in hanok e nel templestay' },
    { etichetta: 'Tour della DMZ', valore: '50-90€ a persona, pranzo spesso incluso' },
    { etichetta: 'Auto a noleggio a Jeju', valore: '40-60€ al giorno, più cara in alta stagione' },
    { etichetta: 'Pasti', valore: '6-15€ a pasto, con i banchan sempre inclusi' },
  ],
}
