import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Costiera Amalfitana e le isole del golfo in 9 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/34-costiera-e-isole.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const costieraEIsoleMeta: TripMeta = {
  tripSlug: 'costiera-e-isole',
  paeseSlug: 'italia',
  ritmo: 'Quattro giorni di costiera con un giorno di cammino in quota, poi cinque giorni sulle isole senza mai fare una traversata di corsa',
  trasporti: 'Senza auto: traghetti e aliscafi, bus SITA per i paesi alti, e moltissimi scalini a piedi',
  stile: [
    'mare',
    'trekking',
    'isole',
  ],
  adattoA: [
    'chi accetta di non portare l\'auto, che è la scelta da cui dipende tutto il resto',
    'chi vuole i sentieri sopra la strada oltre alle spiagge',
    'chi dorme sulle isole invece di farle in giornata',
  ],
  puntiForti: [
    'Il Sentiero degli Dei da Bomerano a Nocelle, gratuito, con Positano sotto e Capri all\'orizzonte',
    'La Terrazza dell\'Infinito di Villa Cimbrone a Ravello',
    'Sorgeto a Ischia, dove le sorgenti bollenti escono direttamente nel mare in una baia di sassi',
  ],
  criticita: [
    'La statale amalfitana d\'estate è un ingorgo continuo: chi arriva in auto in agosto passa la vacanza in coda',
    'Con mare mosso le corse dei traghetti saltano: serve sempre un piano B via terra',
    'Capri, Ischia e Procida hanno limitazioni stagionali allo sbarco dei veicoli, da verificare ogni anno',
    'L\'accesso alla Grotta Azzurra dipende ogni giorno dalla marea e dallo stato del mare',
    'Gli stati di accesso di Via Krupp, Valle delle Ferriere, Vivara e Grotta dello Smeraldo cambiano',
    'Questa non è una vacanza di mare piatta: si misura in scalini, non in chilometri',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, senza auto, tutto in traghetto e a piedi',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'I terrazzamenti a limoni visti dal Sentiero degli Dei, il giro di Capri in barca sotto l\'arco dei Faraglioni, le pozze bollenti di Sorgeto al tramonto',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Positano e il Sentiero degli Dei', destinazioneSlug: 'costiera-amalfitana' },
    { nome: 'Amalfi, Atrani e Ravello', destinazioneSlug: 'costiera-amalfitana' },
    { nome: 'Capri e Anacapri', destinazioneSlug: 'isole-golfo-napoli' },
    { nome: 'Ischia', destinazioneSlug: 'isole-golfo-napoli' },
    { nome: 'Procida', destinazioneSlug: 'isole-golfo-napoli' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo e prima sera in Costiera',
      tratta: 'Arrivo in costiera via mare o via Sorrento',
      pernottamento: 'Praiano, Minori o Salerno',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'dormire a Praiano o Minori costa una frazione di Positano e Amalfi, sulla stessa costa',
      destinazioneSlug: 'costiera-amalfitana',
      immagine: '/images/viaggi/costiera-e-isole/giorno-1-positano.jpg',
      imageAlt: 'Positano al tramonto, con le case colorate arrampicate sulla costa e le barche nella baia',
    },
    {
      titoloGiorno: 'Giorno 2 — Il Sentiero degli Dei',
      tratta: 'Bus per Bomerano, Sentiero degli Dei fino a Nocelle, discesa su Positano',
      pernottamento: 'Praiano, Minori o Salerno',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'il sentiero è gratuito; la discesa finale su Positano è di oltre 1.700 gradini',
      destinazioneSlug: 'costiera-amalfitana',
      immagine: '/images/viaggi/costiera-e-isole/giorno-2-sentiero-degli-dei.jpg',
      imageAlt: 'Il Sentiero degli Dei in quota, con Positano e la costa sottostante e Capri all\'orizzonte',
    },
    {
      titoloGiorno: 'Giorno 3 — Amalfi, Atrani e Ravello',
      tratta: 'Traghetto per Amalfi, Atrani a piedi, bus per Ravello',
      pernottamento: 'Praiano, Minori o Salerno',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Villa Rufolo e Villa Cimbrone hanno biglietti contenuti',
      destinazioneSlug: 'costiera-amalfitana',
      immagine: '/images/viaggi/costiera-e-isole/giorno-3-amalfi-duomo.jpg',
      imageAlt: 'Il Duomo di Amalfi con la scalinata monumentale e il campanile decorato a maioliche',
    },
    {
      titoloGiorno: 'Giorno 4 — La costa orientale e la Valle delle Ferriere',
      tratta: 'Valle delle Ferriere, oppure Minori, Cetara e Vietri sul Mare',
      pernottamento: 'Praiano, Minori o Salerno',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'alcuni tratti della riserva hanno accesso regolamentato; la Grotta dello Smeraldo dipende dallo stato del mare',
      destinazioneSlug: 'costiera-amalfitana',
      immagine: '/images/viaggi/costiera-e-isole/giorno-4-valle-ferriere.jpg',
      imageAlt: 'Una cascata nella Valle delle Ferriere, la riserva naturale umida sopra Amalfi',
    },
    {
      titoloGiorno: 'Giorno 5 — Trasferimento a Capri',
      tratta: 'Traghetto per Capri, funicolare da Marina Grande',
      pernottamento: 'Capri',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'Capri costa di più, ma dormirci significa vederla dopo che i giornalieri sono ripartiti',
      destinazioneSlug: 'isole-golfo-napoli',
      immagine: '/images/viaggi/costiera-e-isole/giorno-5-marina-grande-capri.jpg',
      imageAlt: 'Avvicinamento in traghetto a Capri, con Marina Grande e la montagna dell\'isola',
    },
    {
      titoloGiorno: 'Giorno 6 — Capri, dall\'alto e dal mare',
      tratta: 'Anacapri, seggiovia per il Monte Solaro e giro dell\'isola in barca',
      pernottamento: 'Capri',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'la seggiovia costa pochissimo; la Grotta Azzurra vale solo se il mare è giusto e non c\'è fila',
      destinazioneSlug: 'isole-golfo-napoli',
      immagine: '/images/viaggi/costiera-e-isole/giorno-6-faraglioni-capri.jpg',
      imageAlt: 'I Faraglioni di Capri visti dall\'alto, con una barca a vela ancorata nella baia',
    },
    {
      titoloGiorno: 'Giorno 7 — Ischia: il Castello e le terme',
      tratta: 'Traghetto per Ischia, Castello Aragonese e parco termale',
      pernottamento: 'Ischia, versante occidentale',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'i parchi termali si pagano a giornata; le sorgenti libere come Sorgeto sono gratuite',
      destinazioneSlug: 'isole-golfo-napoli',
      immagine: '/images/viaggi/costiera-e-isole/giorno-7-castello-aragonese.jpg',
      imageAlt: 'Il Castello Aragonese di Ischia su un isolotto di roccia collegato da un ponte',
    },
    {
      titoloGiorno: 'Giorno 8 — Ischia: l\'Epomeo, Sorgeto e La Mortella',
      tratta: 'Monte Epomeo, Giardini La Mortella e Sorgeto al tramonto',
      pernottamento: 'Ischia',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'a Sorgeto servono scarpe di gomma: i sassi vicino alle bocche scottano davvero',
      destinazioneSlug: 'isole-golfo-napoli',
      immagine: '/images/viaggi/costiera-e-isole/giorno-8-sorgeto.jpg',
      imageAlt: 'La baia di Sorgeto a Ischia, con le persone immerse nelle pozze di acqua termale tra gli scogli',
    },
    {
      titoloGiorno: 'Giorno 9 — Procida e rientro',
      tratta: 'Traghetto per Procida, Marina Corricella e Terra Murata, poi rientro a Napoli',
      intensita: 'medio',
      costiNoti: 'Procida ha i prezzi più bassi delle tre isole; l\'accesso a Vivara è contingentato',
      destinazioneSlug: 'isole-golfo-napoli',
      immagine: '/images/viaggi/costiera-e-isole/giorno-9-marina-corricella.jpg',
      imageAlt: 'Marina Corricella a Procida, il borgo di pescatori con le case dipinte di rosa, giallo e ocra affacciate sul porto',
    },
  ],
  budget: [
    { etichetta: 'Traghetti e aliscafi', valore: 'pochi euro a tratta, e sono il miglior investimento di tutto il viaggio' },
    { etichetta: 'Alloggio', valore: 'la voce che determina il budget: Positano e Amalfi in stagione costano il doppio di Praiano e Minori' },
    { etichetta: 'Sentieri', valore: 'gratuiti, Sentiero degli Dei compreso' },
    { etichetta: 'Isole', valore: 'Capri è la più cara, Ischia intermedia, Procida nettamente la più economica' },
    { etichetta: 'Terme a Ischia', valore: 'i parchi si pagano a giornata; Sorgeto è libero e aperto sempre' },
  ],
}
