import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per il viaggio "Costa Rica 360° in 13 giorni". Il testo
// narrativo resta nel markdown (src/content/viaggi/12-costa-rica-360.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const costaRica360Meta: TripMeta = {
  tripSlug: 'costa-rica-360',
  paeseSlug: 'costa-rica',
  ritmo: 'Molto denso — probabilmente il viaggio più intenso di tutto l\'archivio, 13 giorni da una costa all\'altra del paese',
  trasporti: 'Van privato con autista per tutti i trasferimenti principali, più barche per Tortuguero e alcune escursioni',
  stile: ['giungla', 'vulcani', 'pura vida'],
  adattoA: ['chi vuole vedere il Costa Rica da costa a costa in un unico viaggio', 'chi ama la natura e la fauna selvatica', 'chi non ha problemi con un ritmo molto denso e trasferimenti lunghi'],
  puntiForti: [
    'Il tragitto in barca fino a Tortuguero, uno dei trasferimenti più belli del viaggio',
    'Le sorgenti termali gratuite di El Choyin ad Arenal',
    'Il Parco Nazionale Manuel Antonio, tra le tappe più belle di tutto il paese',
  ],
  criticita: [
    'Il ritmo è molto denso per 13 giorni, con sveglie prestissimo quasi ogni giorno',
    'Non è confermato quali attività opzionali (Cahuita, Pacuaré rafting, canyoning, nidificazione tartarughe, equitazione) siano state effettivamente scelte dal gruppo',
    'Novembre non è il mese migliore per il whale watching a Uvita: non è annotato con certezza se e quante balene siano state avvistate',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'organizzato tramite un tour operator (WeRoad) con il DMC locale MR Adventure Travel, van privato con autista',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'Il tragitto in barca verso Tortuguero, le sorgenti termali di El Choyin, il Parco Nazionale Manuel Antonio',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'San José', destinazioneSlug: 'san-jose' },
    { nome: 'Puerto Viejo', destinazioneSlug: 'puerto-viejo' },
    { nome: 'Tortuguero', destinazioneSlug: 'tortuguero' },
    { nome: 'Sarapiquí', destinazioneSlug: 'sarapiqui' },
    { nome: 'Arenal', destinazioneSlug: 'arenal' },
    { nome: 'Monteverde', destinazioneSlug: 'monteverde' },
    { nome: 'Uvita', destinazioneSlug: 'uvita' },
    { nome: 'Manuel Antonio', destinazioneSlug: 'manuel-antonio' },
    { nome: 'San José', destinazioneSlug: 'san-jose' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — San José',
      tratta: 'Arrivo a San José',
      pernottamento: 'Casa Boutique Las Orquídeas',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'san-jose',
    },
    {
      titoloGiorno: 'Giorno 2 — Puerto Viejo, tra Caribe e giungla',
      tratta: 'San José → Puerto Viejo (4-4h30)',
      pernottamento: 'Escape Caribeño',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'puerto-viejo',
    },
    {
      titoloGiorno: 'Giorno 3 — Parco Nazionale di Cahuita',
      tratta: 'Giornata dedicata a Cahuita (opzionale)',
      pernottamento: 'Escape Caribeño',
      statoPernottamento: 'provato',
      intensita: 'medio',
      costiNoti: 'Tour Cahuita 50$ a persona',
      destinazioneSlug: 'puerto-viejo',
    },
    {
      titoloGiorno: 'Giorno 4 — Verso Tortuguero, tra fiume e giungla',
      tratta: 'Puerto Viejo → Moín → Tortuguero (1h30 van + 3h barca)',
      pernottamento: 'Hotel Icaco Tortuguero',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'tortuguero',
    },
    {
      titoloGiorno: 'Giorno 5 — Tortuguero: kayak tra le mangrovie, poi Sarapiquí',
      tratta: 'Tortuguero → Sarapiquí (1h30 barca + 2h30 van)',
      pernottamento: 'Epic Adventure Lodge',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      destinazioneSlug: 'sarapiqui',
    },
    {
      titoloGiorno: 'Giorno 6 — Rafting sul fiume Sarapiquí',
      tratta: 'Rafting sul Sarapiquí, poi eventuale Bajos del Toro',
      pernottamento: 'Epic Adventure Lodge',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'sarapiqui',
    },
    {
      titoloGiorno: 'Giorno 7 — Arenal: cascate, vulcano e sorgenti termali',
      tratta: 'Sarapiquí → La Fortuna (1h20)',
      pernottamento: 'Hotel Campos Arenal',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Cascada de La Fortuna 18-20$; tour combo 90-120$',
      destinazioneSlug: 'arenal',
    },
    {
      titoloGiorno: 'Giorno 8 — Monteverde, nella foresta nebulosa',
      tratta: 'La Fortuna → Monteverde (3-3h30)',
      pernottamento: 'Hotel Jardines de Monteverde',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      destinazioneSlug: 'monteverde',
    },
    {
      titoloGiorno: 'Giorno 9 — Zipline a Monteverde, poi verso il Pacifico e Uvita',
      tratta: 'Monteverde → Uvita (fino a 4 ore)',
      pernottamento: 'El Tecal',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Zipline circa 60$ a persona',
      destinazioneSlug: 'uvita',
    },
    {
      titoloGiorno: 'Giorno 10 — Uvita: avvistamento balene',
      tratta: 'Giornata dedicata al whale watching',
      pernottamento: 'El Tecal',
      statoPernottamento: 'provato',
      intensita: 'medio',
      costiNoti: 'Whale watching 70$ a persona',
      destinazioneSlug: 'uvita',
    },
    {
      titoloGiorno: 'Giorno 11 — Uvita: giornata libera tra surf, cavalli e yoga',
      tratta: 'Giornata libera a Uvita',
      pernottamento: 'El Tecal',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'uvita',
    },
    {
      titoloGiorno: 'Giorno 12 — Parco Nazionale Manuel Antonio e rientro a San José',
      tratta: 'Uvita → Manuel Antonio → San José (1h30 + 3h30-4h)',
      pernottamento: 'Casa Boutique Las Orquídeas',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      destinazioneSlug: 'manuel-antonio',
    },
    {
      titoloGiorno: 'Giorno 13 — Check-out e rientro',
      tratta: 'San José → rientro',
      pernottamento: 'nessun pernottamento (giorno di partenza)',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'san-jose',
    },
  ],
  budget: [
    { etichetta: 'Voli', valore: undefined },
    { etichetta: 'Cassa comune di partenza', valore: '350€ a persona' },
    { etichetta: 'Attività extra', valore: '250€ a testa circa' },
    { etichetta: 'Totale gruppi precedenti', valore: '350-500€ complessivi' },
  ],
}
