import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per il viaggio "Florida 360° in 10 giorni". Il testo
// narrativo resta nel markdown (src/content/viaggi/09-florida-360.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const florida360Meta: TripMeta = {
  tripSlug: 'florida-360',
  paeseSlug: 'florida',
  ritmo: 'Molto intenso — quasi 1.800 km al volante in 10 giorni, con un giorno (Naples-Orlando) di 5h di guida',
  trasporti: 'Auto a noleggio self-drive (Sixt) per quasi tutto il tour, Uber/Lyft per gli spostamenti serali in città',
  stile: ['on the road', 'road trip', 'mare'],
  adattoA: ['chi vuole vedere il meglio della Florida in un unico giro ad anello', 'chi non ha problemi a guidare molto ogni giorno', 'famiglie o gruppi che vogliono unire spiagge, natura e parchi a tema'],
  puntiForti: [
    'La Seven Mile Bridge e il turchese delle Florida Keys',
    'Il contrasto tra le Everglades primordiali e l\'eleganza di Naples nello stesso giorno',
    'Il Kennedy Space Center, con oggetti autentici della corsa allo spazio, non solo ricostruzioni',
  ],
  criticita: [
    'Il ritmo è molto denso, con giornate di guida anche di 5 ore',
    'Diversi hotel (Key West/Marathon, Naples/Everglades) non sono annotati per nome per policy del DMC organizzatore: restano segnalati con alternative invece di un giudizio inventato',
    'Non è confermato quale tra Universal Studios e Disney World sia stato effettivamente scelto al Giorno 6',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'organizzato tramite un tour operator (WeRoad), con auto a noleggio self-drive',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'La Seven Mile Bridge alle Keys, il Saturn V al Kennedy Space Center, l\'airboat tour nelle Everglades',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Miami', destinazioneSlug: 'miami' },
    { nome: 'Key West e Marathon', destinazioneSlug: 'key-west-marathon' },
    { nome: 'Everglades e Naples', destinazioneSlug: 'everglades-naples' },
    { nome: 'Orlando', destinazioneSlug: 'orlando' },
    { nome: 'Cape Canaveral', destinazioneSlug: 'cape-canaveral' },
    { nome: 'Miami', destinazioneSlug: 'miami' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Miami',
      tratta: 'Arrivo a Miami',
      pernottamento: 'Generator Miami',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'miami',
    },
    {
      titoloGiorno: 'Giorno 2 — Key West',
      tratta: 'Miami → Key West',
      pernottamento: 'hotel non annotato (Key West/Marathon)',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'key-west-marathon',
    },
    {
      titoloGiorno: 'Giorno 3 — Key West e Marathon',
      tratta: 'Key West → Bahia Honda → Marathon',
      pernottamento: 'hotel non annotato (Key West/Marathon)',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'key-west-marathon',
    },
    {
      titoloGiorno: 'Giorno 4 — Everglades e Naples',
      tratta: 'Marathon → Everglades → Naples',
      pernottamento: 'hotel non annotato (Naples/Everglades)',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'everglades-naples',
    },
    {
      titoloGiorno: 'Giorno 5 — Da Naples a Orlando via Clearwater',
      tratta: 'Naples → Orlando (280 miglia, 5h)',
      pernottamento: 'villa privata in affitto (Kissimmee/Championsgate)',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      destinazioneSlug: 'orlando',
    },
    {
      titoloGiorno: 'Giorno 6 — Orlando (parco a tema)',
      tratta: 'Giornata intera al parco a tema',
      pernottamento: 'villa privata in affitto (Kissimmee/Championsgate)',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Universal 130-210$; Disney World da 250€ per 2 giorni',
      destinazioneSlug: 'orlando',
    },
    {
      titoloGiorno: 'Giorno 7 — Orlando e Kennedy Space Center',
      tratta: 'Orlando → Cape Canaveral → Miami (200 miglia, 3h15)',
      pernottamento: 'nessun pernottamento a Cape Canaveral, rientro a Miami',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Kennedy Space Center $57',
      destinazioneSlug: 'cape-canaveral',
    },
    {
      titoloGiorno: 'Giorno 8 — Miami Beach',
      tratta: 'Riconsegna auto, giornata a Miami Beach',
      pernottamento: 'Generator Miami',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'miami',
    },
    {
      titoloGiorno: 'Giorno 9 — Miami "di terra"',
      tratta: 'Wynwood → Little Havana → Coconut Grove',
      pernottamento: 'Generator Miami',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'miami',
    },
    {
      titoloGiorno: 'Giorno 10 — Check-out e rientro',
      tratta: 'Miami → rientro',
      pernottamento: 'nessun pernottamento (giorno di partenza)',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'miami',
    },
  ],
  budget: [
    { etichetta: 'Voli', valore: undefined },
    { etichetta: 'Cassa comune (auto e attività)', valore: '270€ a persona' },
    { etichetta: 'Biglietto parco a tema di Orlando', valore: '130-260$ a seconda di stagione e numero di parchi' },
    { etichetta: 'Kennedy Space Center', valore: 'circa 70$' },
    { etichetta: 'Spesa media personale nel resto del viaggio', valore: '900-1.000$ a testa' },
    { etichetta: 'Totale', valore: undefined },
  ],
}
