import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per il viaggio "Giappone in 12 giorni". Il
// testo narrativo resta nel markdown (src/content/viaggi/05-giappone-360.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N (DD.MM) — ..."
// del file markdown. Il Giorno 3 (Monte Fuji/Chureito) è una giornata aggiunta
// editorialmente, non vissuta realmente: statoPernottamento riflette questo.

export const giappone360Meta: TripMeta = {
  tripSlug: 'giappone-360',
  paeseSlug: 'giappone',
  ritmo: 'Molto denso — un anello classico Tokyo-Kyoto-Hiroshima-Osaka-Nara-Tokyo in poco più di una settimana e mezzo',
  trasporti: 'JR Pass attivato dal quarto giorno (Shinkansen e linee locali), carta PASMO/IC per metro e bus, treno diretto per il Monte Fuji',
  stile: ['sakura', 'cultura', 'cibo'],
  adattoA: ['chi vuole un giro completo del Giappone classico in circa 12 giorni', 'chi viaggia nel periodo dei sakura', 'chi vuole alternare grandi città e siti storici'],
  puntiForti: [
    'La caccia ai sakura in più punti diversi di Tokyo, con l\'aggiunta di Chureito per recuperare la fioritura in ritardo',
    'Un mix equilibrato tra grandi classici (Fushimi Inari, Kinkaku-ji, Miyajima) e chicche meno ovvie (i cervi di Nara, il castello di Himeji)',
    'Il cibo come vero filo conduttore del viaggio, dagli izakaya di Tokyo al cibo di strada di Osaka',
  ],
  criticita: [
    'Tokyo viene vissuta solo a spizzichi (arrivo e ultimi due giorni): con più tempo meriterebbe 4-5 giorni pieni',
    'Il ritmo è molto denso, quasi ogni giorno con cambio di città o tappa lunga',
    'La giornata del Monte Fuji (Giorno 3) è stata aggiunta editorialmente per completare il capitolo Tokyo: non è stata vissuta realmente durante il viaggio',
  ],
  budgetTotale: 'circa 600-750€ per l\'intero soggiorno sul posto, esclusi voli e JR Pass',
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'JR Pass per i grandi spostamenti in treno, attivato dal quarto giorno in poi',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'Fushimi Inari al mattino presto, il torii galleggiante di Miyajima, i cervi sacri di Nara',
    cosaCambierei: 'Dare più giorni a Tokyo invece di spezzarla in tre momenti diversi del viaggio',
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Tokyo', destinazioneSlug: 'tokyo' },
    { nome: 'Kamakura', destinazioneSlug: 'kamakura' },
    { nome: 'Monte Fuji e Chureito', destinazioneSlug: 'monte-fuji-chureito' },
    { nome: 'Kyoto', destinazioneSlug: 'kyoto' },
    { nome: 'Hiroshima e Miyajima', destinazioneSlug: 'hiroshima-miyajima' },
    { nome: 'Himeji', destinazioneSlug: 'himeji' },
    { nome: 'Osaka', destinazioneSlug: 'osaka' },
    { nome: 'Nara', destinazioneSlug: 'nara' },
    { nome: 'Tokyo', destinazioneSlug: 'tokyo' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 (06.04) — Tokyo, Asakusa e la caccia ai sakura',
      tratta: 'Arrivo a Tokyo, Asakusa',
      pernottamento: 'Agora Place Asakusa',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'tokyo',
    },
    {
      titoloGiorno: 'Giorno 2 (07.04) — Kamakura, l\'antica capitale sul mare',
      tratta: 'Tokyo → Kamakura → Tokyo',
      pernottamento: 'Agora Place Asakusa',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Engaku-ji 400 yen; Kencho-ji 450 yen',
      destinazioneSlug: 'kamakura',
    },
    {
      titoloGiorno: 'Giorno 3 (08.04) — NUOVO: Monte Fuji e Pagoda Chureito',
      tratta: 'Tokyo → Kawaguchiko → Tokyo',
      pernottamento: 'Agora Place Asakusa (giornata aggiunta editorialmente, non vissuta realmente)',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Treno Fuji Excursion ~4.130 yen (o supplemento Fujikyu ~1.770 yen con JR Pass); onsen ~1.200 yen',
      destinazioneSlug: 'monte-fuji-chureito',
    },
    {
      titoloGiorno: 'Giorno 4 (09.04) — Tokyo-Kyoto',
      tratta: 'Tokyo → Kyoto, Shinkansen Hikari (2h40)',
      pernottamento: 'Agora Kyoto Shijo',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'kyoto',
    },
    {
      titoloGiorno: 'Giorno 5 (10.04) — Kyoto: Arashiyama, la foresta di bambù e Gion',
      tratta: 'Kyoto → Arashiyama → Kyoto',
      pernottamento: 'Agora Kyoto Shijo',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Okochi Sanso Garden 1.000 yen',
      destinazioneSlug: 'kyoto',
    },
    {
      titoloGiorno: 'Giorno 6 (11.04) — Kyoto: Fushimi Inari, Nijo Castle, Kinkaku-ji',
      tratta: 'Fushimi Inari → Nijo Castle → Kinkaku-ji → Gion',
      pernottamento: 'Agora Kyoto Shijo',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Cerimonia del tè 2.700 yen + 3.000 yen kimono',
      destinazioneSlug: 'kyoto',
    },
    {
      titoloGiorno: 'Giorno 7 (12.04) — Kyoto-Hiroshima-Miyajima',
      tratta: 'Kyoto → Hiroshima (Shinkansen ~2h) → Miyajima',
      pernottamento: 'Toyoko Inn Hiroshima Station (o minshuku/ryokan, da confermare)',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'hiroshima-miyajima',
    },
    {
      titoloGiorno: 'Giorno 8 (13.04) — Hiroshima-Himeji-Osaka (o Kobe)',
      tratta: 'Hiroshima → Himeji → Osaka',
      pernottamento: 'Sarasa Hotel Namba',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Castello di Himeji + Giardini Kokoen 1.060 yen',
      destinazioneSlug: 'osaka',
    },
    {
      titoloGiorno: 'Giorno 9 (14.04) — Osaka e Nara',
      tratta: 'Osaka → Nara → Osaka',
      pernottamento: 'Sarasa Hotel Namba',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Torre di Tsutenkaku 900 yen; cheesecake 900-1.000 yen',
      destinazioneSlug: 'nara',
    },
    {
      titoloGiorno: 'Giorno 10 (15.04) — Osaka-Tokyo: Harajuku e Shibuya',
      tratta: 'Osaka → Tokyo, Shinkansen Hikari (circa 3h)',
      pernottamento: 'Sunshine City Prince Hotel',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'tokyo',
    },
    {
      titoloGiorno: 'Giorno 11 (16.04) — Tokyo: Tsukiji, Akihabara, Senso-ji, Shinjuku',
      tratta: 'Tokyo, giro tra i quartieri',
      pernottamento: 'Sunshine City Prince Hotel',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      destinazioneSlug: 'tokyo',
    },
    {
      titoloGiorno: 'Giorno 12 (17.04) — Check out',
      tratta: 'Tokyo → rientro',
      pernottamento: 'nessun pernottamento (giorno di partenza)',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'tokyo',
    },
  ],
  budget: [
    { etichetta: 'Voli', valore: undefined },
    { etichetta: 'JR Pass', valore: undefined },
    { etichetta: 'Soggiorno sul posto (cibo, ingressi, attività)', valore: '600-750€' },
    { etichetta: 'Totale', valore: undefined },
  ],
}
