import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Le grandi città in 12 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/25-grandi-citta-italia.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const grandiCittaItaliaMeta: TripMeta = {
  tripSlug: 'grandi-citta-italia',
  paeseSlug: 'italia',
  ritmo: 'Denso ma senza trasferimenti faticosi: quattro basi collegate dall\'alta velocità, con giornate piene',
  trasporti: 'Solo alta velocità tra le città, mezzi pubblici e piedi dentro. L\'auto è inutile o dannosa in tutte e quattro',
  stile: ['città d\'arte', 'archeologia', 'gastronomia'],
  adattoA: [
    'chi vuole rivedere le quattro grandi città nel modo giusto invece che in coda',
    'chi può viaggiare da ottobre a marzo',
    'chi accetta di prenotare online settimane prima le cose contingentate',
  ],
  puntiForti: [
    'San Clemente a Roma: tre epoche sovrapposte a quattrocento metri dal Colosseo, con sei persone',
    'Venezia alle sette del mattino, che è l\'unica finestra in cui è quello che ci si aspettava',
    'Ercolano dopo Pompei, con i piani superiori e le travi carbonizzate ancora al loro posto',
  ],
  criticita: [
    'Quasi tutto è contingentato: Colosseo e Pompei con biglietto nominativo e documento originale, Uffizi, cupola, Galleria Borghese e Cenacolo su prenotazione con settimane di anticipo',
    'Pompei ha un tetto di 20.000 visitatori al giorno: esaurita la quota non si entra né online né in biglietteria',
    'Il contributo di accesso di Venezia si applica a chi entra in giornata senza pernottare, in un calendario che cambia ogni anno',
    'Da giugno ad agosto le temperature rendono le visite faticose e in certi casi rischiose',
    'I giorni di chiusura dei musei sono diversi per ciascuno e sono l\'errore di programmazione più frequente',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, spostandosi solo in alta velocità',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'I tre livelli di San Clemente, Venezia alle sette del mattino, le case a due piani di Ercolano',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Roma', destinazioneSlug: 'roma', lat: 41.9028, lng: 12.4964 },
    { nome: 'Firenze', destinazioneSlug: 'firenze', lat: 43.7696, lng: 11.2558 },
    { nome: 'Venezia', destinazioneSlug: 'venezia', lat: 45.4408, lng: 12.3155 },
    { nome: 'Napoli', destinazioneSlug: 'napoli', lat: 40.8518, lng: 14.2681 },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Roma',
      tratta: 'Arrivo a Roma',
      pernottamento: 'Roma, Monti o Trastevere',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'roma',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-01-roma-trastevere.jpg',
      imageAlt: 'Piazza di Santa Maria in Trastevere a Roma, con la basilica, la fontana ottagonale e i passanti sul selciato',
    },
    {
      titoloGiorno: 'Giorno 2 — Roma antica',
      pernottamento: 'Roma, Monti o Trastevere',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'biglietto unico Colosseo-Foro-Palatino, nominativo: serve il documento originale',
      destinazioneSlug: 'roma',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-02-foro-colosseo.jpg',
      imageAlt: 'Il Foro Romano all\'alba con le colonne dei templi in primo piano e il Colosseo illuminato sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 3 — Vaticano e le chiese',
      pernottamento: 'Roma, Monti o Trastevere',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Musei Vaticani su prenotazione; chiese gratuite',
      destinazioneSlug: 'roma',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-03-san-pietro.jpg',
      imageAlt: 'Vista aerea di Piazza San Pietro dal colonnato del Bernini, con l\'obelisco al centro e Roma che si estende sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 4 — La Roma sotterranea e l\'Appia',
      pernottamento: 'Roma, Monti o Trastevere',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'San Clemente ingresso contenuto; Appia Antica gratuita',
      destinazioneSlug: 'roma',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-04-appia-antica.jpg',
      imageAlt: 'Il basolato originale della Via Appia Antica fiancheggiato dai pini marittimi e dai cipressi',
    },
    {
      titoloGiorno: 'Giorno 5 — Alta velocità per Firenze',
      tratta: 'Roma → Firenze in alta velocità (1h30)',
      pernottamento: 'Firenze, Oltrarno',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'firenze',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-05-san-miniato.jpg',
      imageAlt: 'Panorama di Firenze dalla terrazza di San Miniato al Monte, con la cupola del Duomo e il campanile di Giotto in mezzo ai tetti della città',
    },
    {
      titoloGiorno: 'Giorno 6 — La cupola e gli Uffizi',
      pernottamento: 'Firenze, Oltrarno',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'cupola con fascia oraria obbligatoria; Uffizi su prenotazione',
      destinazioneSlug: 'firenze',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-06-cupola-uffizi.jpg',
      imageAlt: 'La lanterna della Cupola del Brunelleschi vista da vicino, con i visitatori affacciati sulla balconata sopra il tetto in cotto',
    },
    {
      titoloGiorno: 'Giorno 7 — Il museo che nessuno fa',
      pernottamento: 'Firenze, Oltrarno',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'firenze',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-07-ghiberti.jpg',
      imageAlt: 'La Porta del Paradiso originale di Lorenzo Ghiberti, i pannelli dorati del Battistero conservati al Museo dell\'Opera del Duomo di Firenze',
    },
    {
      titoloGiorno: 'Giorno 8 — Alta velocità per Venezia',
      tratta: 'Firenze → Venezia in alta velocità (2h)',
      pernottamento: 'Venezia, Cannaregio o Castello',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'dormire in centro esenta dal contributo di accesso',
      destinazioneSlug: 'venezia',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-08-santa-lucia.jpg',
      imageAlt: 'Il Canal Grande davanti alla stazione di Venezia Santa Lucia, con la cupola verde della chiesa di San Simeon Piccolo e le barche sull\'acqua',
    },
    {
      titoloGiorno: 'Giorno 9 — Venezia all\'alba e la Scuola di San Rocco',
      pernottamento: 'Venezia, Cannaregio o Castello',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'venezia',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-09-rialto.jpg',
      imageAlt: 'Il loggiato deserto della Pescheria di Rialto a Venezia nella luce del mattino presto, con le colonne in prospettiva e il canale sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 10 — La laguna',
      tratta: 'Giornata in laguna: Torcello, Burano, Murano',
      pernottamento: 'Venezia, Cannaregio o Castello',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'il pass vaporetto a tempo si ripaga in una giornata come questa',
      destinazioneSlug: 'venezia',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-10-burano.jpg',
      imageAlt: 'Un canale di Burano fiancheggiato da case dipinte in colori vivaci, con le barche ormeggiate lungo la riva',
    },
    {
      titoloGiorno: 'Giorno 11 — Alta velocità per Napoli',
      tratta: 'Venezia → Napoli in alta velocità',
      pernottamento: 'Napoli, centro storico o Chiaia',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'napoli',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-11-napoli.jpg',
      imageAlt: 'Panorama di Napoli dal Vomero, con il porto, i palazzi del centro e il Vesuvio che domina sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 12 — Pompei ed Ercolano, e rientro',
      tratta: 'Napoli → Pompei ed Ercolano con la Circumvesuviana',
      intensita: 'intenso',
      costiNoti: 'Pompei con biglietto nominativo e tetto di 20.000 visitatori al giorno',
      destinazioneSlug: 'napoli',
      immagine: '/images/viaggi/grandi-citta-italia/giorno-12-pompei.jpg',
      imageAlt: 'Il muro di cinta degli scavi di Pompei con un pino ad ombrello in primo piano e il Vesuvio sullo sfondo',
    },
  ],
  budget: [
    { etichetta: 'Alta velocità (4 tratte)', valore: 'i prezzi crollano prenotando con settimane di anticipo' },
    { etichetta: 'Ingressi contingentati', valore: 'Colosseo, Uffizi, cupola, Galleria Borghese, Pompei: da prenotare settimane prima' },
    { etichetta: 'Contributo di accesso Venezia', valore: '5€ con almeno quattro giorni di anticipo, 10€ sotto soglia; esente chi pernotta' },
    { etichetta: 'Pass vaporetto a tempo', valore: 'quasi sempre conveniente rispetto ai biglietti singoli' },
    { etichetta: 'Chiese', valore: 'gratuite, e contengono una parte enorme di quello che si viene a vedere' },
    { etichetta: 'Pasti', valore: 'la regola che vale più di ogni altra: mai entro trecento metri da un monumento' },
  ],
}
