import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Indonesia in 35 giorni: da Sumatra a Sulawesi, isola dopo isola".
// Il testo narrativo resta nel markdown (src/content/viaggi/48-indonesia-itinerario.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.
//
// Questo è un itinerario "composito": condensa il meglio di sei viaggi reali in
// Indonesia (sette isole su otto già documentate in src/content/destinazioni/indonesia.ts,
// Raja Ampat esclusa per l'incompatibilità di stagione) in un unico racconto di
// trentacinque giorni. Tutti e trentacinque i giorni hanno una foto sourced da
// Wikimedia Commons (crediti in src/content/viaggi-giorno-foto-crediti.ts).

export const indonesiaItinerarioMeta: TripMeta = {
  tripSlug: 'indonesia-itinerario',
  paeseSlug: 'indonesia',
  ritmo: 'Impegnativo: sette isole in trentacinque giorni, con trekking fisicamente duri (Rinjani, oranghi, Ijen) alternati a giorni di solo trasferimento e a un tratto via terra più lento tra Sumatra, Giava e le tante zone di Bali',
  trasporti: 'Voli interni, traghetti veloci e barche multi-giorno, bus e treni, auto con autista o scooter a noleggio nei tratti via terra di Sumatra, Giava e Bali, jeep 4x4 per il Bromo, cidomo alle Gili dove i motori sono vietati',
  stile: ['natura', 'avventura', 'trekking', 'vulcani', 'isole', 'cultura'],
  adattoA: [
    'chi ha almeno tre settimane, meglio più di un mese, e preferisce un solo grande giro a più viaggi separati',
    'chi cerca trekking impegnativi (Rinjani, oranghi di Sumatra, Kawah Ijen) e non solo mare',
    'chi vuole vedere insieme la parte più conosciuta dell\'Indonesia (Bali, Giava) e quella meno battuta (Flores, Komodo, Sulawesi)',
    'chi è disposto a scegliere, tappa per tappa, tra guidare uno scooter in autonomia e affidarsi a un driver privato',
    'chi preferisce dividere: la Parte 1 (Sumatra-Giava-Bali, 20 giorni) e la Parte 2 (Lombok-Komodo-Flores-Sulawesi, 15 giorni) funzionano anche come due viaggi indipendenti',
  ],
  puntiForti: [
    'L\'incontro con gli oranghi selvatici di Sumatra nella giungla del Gunung Leuser, cercandoli a piedi invece di aspettarli da una piattaforma',
    'Le tante Bali diverse in una sola isola: la calma delle risaie di Sidemen, le cascate di Munduk, il surf e i tramonti di Uluwatu — molto più della cartolina da resort del sud',
    'Il trekking al Rinjani e il risveglio sopra il lago craterico Segara Anak, il più duro e il più pagante di tutto il viaggio',
    'I draghi di Komodo nel loro habitat naturale e l\'alba da Padar Island, con tre baie di sabbie diverse sotto lo stesso sguardo',
    'I tre laghi craterici del Kelimutu a Flores e i villaggi tongkonan di Tana Toraja, le due tappe più lontane dal turismo di massa',
  ],
  criticita: [
    'Raja Ampat è volutamente esclusa: la sua stagione migliore (ottobre-aprile) è opposta a quella del resto dell\'arcipelago percorso qui (aprile-ottobre), e va fatta come viaggio a sé',
    'Il tratto via terra di Sumatra (Bukit Lawang-Berastagi-Lago Toba) si copre in scooter a noleggio o con driver privato: il motorino costa meno ma richiede vera esperienza di guida su strade di montagna spesso dissestate',
    'Il trekking al Rinjani richiede guida obbligatoria per legge, buona forma fisica e notti in quota vicine allo zero: non va sottovalutato',
    'Il trekking agli oranghi di Bukit Lawang va prenotato solo con guide certificate: alcune guide non ufficiali attirano gli animali con il cibo, pratica da rifiutare esplicitamente',
    'Il trasferimento da Probolinggo a Cemoro Lawang per il Bromo è terreno di truffe classiche: tout che dichiarano i minivan pubblici "pieni" o "partiti", jeep condivisi venduti a prezzi doppi o tripli rispetto al riferimento (700.000-900.000 IDR)',
    'A Bali il sud generico attorno a Seminyak è turismo di massa senza molta personalità: le gite da Ubud a Sidemen, Amed, Munduk e Lovina si fanno in scooter (stessa cautela sulla guida) o con un driver privato a giornata, pratica molto diffusa sull\'isola',
    'e-VOA e All Indonesia Arrival Card (obbligatoria dal 2025) vanno compilate prima di ogni ingresso nel paese sui portali ufficiali',
    'L\'itinerario attraversa due fusi orari (WIB e WITA): va tenuto presente incastrando i voli interni, soprattutto nel passaggio da Giava a Bali',
    'Il Kawah Ijen richiede maschera antigas: i fumi di zolfo sono realmente pericolosi, non una formalità',
    'Bancomat rari fuori da Bali e Giava (Lombok, Komodo, Flores, interno di Sulawesi): conviene arrivarci già riforniti di contanti',
    'Se le date coincidono con il Nyepi (capodanno balinese), Bali si ferma per 24 ore e l\'aeroporto chiude',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, mettendo insieme sei viaggi reali fatti nel tempo in un unico racconto',
    cosaCercavo: undefined,
    treEsperienzePiuBelle:
      'L\'incontro con gli oranghi selvatici a Bukit Lawang, l\'alba sopra il lago Segara Anak dopo la salita al Rinjani, Padar Island all\'alba nel Parco di Komodo',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Sumatra', destinazioneSlug: 'sumatra' },
    { nome: 'Giacarta', destinazioneSlug: 'giava' },
    { nome: 'Giava', destinazioneSlug: 'giava' },
    { nome: 'Bali', destinazioneSlug: 'bali' },
    { nome: 'Lombok e Gili', destinazioneSlug: 'lombok-gili' },
    { nome: 'Komodo', destinazioneSlug: 'komodo' },
    { nome: 'Flores', destinazioneSlug: 'flores' },
    { nome: 'Sulawesi', destinazioneSlug: 'sulawesi' },
  ],
  giorni: [
    { titoloGiorno: 'Giorno 1 — Arrivo a Medan e trasferimento a Bukit Lawang', tratta: 'Medan (KNO) → Bukit Lawang in auto/bus, circa 3h', pernottamento: 'Bukit Lawang, lungo il fiume Bohorok', statoPernottamento: 'da-confermare', intensita: 'leggero', destinazioneSlug: 'sumatra', immagine: '/images/viaggi/indonesia-itinerario/giorno-01-bukit-lawang.jpg', imageAlt: 'Il ponte sospeso sul fiume Bohorok a Bukit Lawang, Sumatra, tra le foglie di palma e le case del villaggio' },
    { titoloGiorno: 'Giorno 2 — Trekking tra gli oranghi del Gunung Leuser', pernottamento: 'Bukit Lawang, lungo il fiume Bohorok', statoPernottamento: 'da-confermare', intensita: 'intenso', costiNoti: 'trekking guidato indicativamente 25-40€ per mezza giornata, di più per i multi-giorno', destinazioneSlug: 'sumatra', immagine: '/images/viaggi/indonesia-itinerario/giorno-02-orango-gunung-leuser.jpg', imageAlt: 'Un orango di Sumatra su un ramo nella giungla del Parco Nazionale del Gunung Leuser' },
    { titoloGiorno: 'Giorno 3 — Berastagi, i vulcani Sibayak e Sinabung', tratta: 'Bukit Lawang → Berastagi, scooter o driver privato (5-8h secondo le soste)', pernottamento: 'Berastagi', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'driver privato indicativamente 800.000-900.000 IDR (45-50€) per la tratta', destinazioneSlug: 'sumatra', immagine: '/images/viaggi/indonesia-itinerario/giorno-03-sibayak.jpg', imageAlt: 'Il cratere del vulcano Sibayak fumante, con il cono del Sinabung sullo sfondo, altopiano di Berastagi, Sumatra' },
    { titoloGiorno: 'Giorno 4 — Verso il Lago Toba e l\'isola di Samosir', tratta: 'Berastagi → Parapat, Lago Toba, poi traghetto per Samosir', pernottamento: 'Isola di Samosir, Lago Toba', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'driver privato Berastagi-Parapat indicativamente 700.000-800.000 IDR (40-45€)', destinazioneSlug: 'sumatra', immagine: '/images/viaggi/indonesia-itinerario/giorno-04-lago-toba.jpg', imageAlt: 'Vista panoramica del Lago Toba e della cittadina di Parapat dalle acque del lago, Sumatra' },
    { titoloGiorno: 'Giorno 5 — Samosir e i villaggi Batak', pernottamento: 'Isola di Samosir, Lago Toba', statoPernottamento: 'da-confermare', intensita: 'leggero', destinazioneSlug: 'sumatra', immagine: '/images/viaggi/indonesia-itinerario/giorno-05-rumah-bolon-samosir.jpg', imageAlt: 'Ingresso in pietra del villaggio tradizionale Batak di Huta Siallagan, con le statue antropomorfe scolpite, isola di Samosir' },
    { titoloGiorno: 'Giorno 6 — Giacarta e il volo verso Yogyakarta', tratta: 'Samosir → Medan → volo per Giacarta → volo serale per Yogyakarta', pernottamento: 'Yogyakarta, zona Prawirotaman', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'giava', immagine: '/images/viaggi/indonesia-itinerario/giorno-06-kota-tua-jakarta.jpg', imageAlt: "L'ex Municipio di Batavia (oggi Museo di Storia di Giacarta) affacciato sulla Fatahillah Square, Kota Tua, Giacarta" },
    { titoloGiorno: 'Giorno 7 — Alba a Borobudur, tramonto a Prambanan', pernottamento: 'Yogyakarta, zona Prawirotaman', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'giava', immagine: '/images/viaggi/indonesia-itinerario/giorno-07-borobudur-alba.jpg', imageAlt: "Le stupa del tempio di Borobudur all'alba, con i vulcani sullo sfondo tra le nuvole dorate, Giava centrale" },
    { titoloGiorno: 'Giorno 8 — Yogyakarta: kraton, batik e Malioboro', pernottamento: 'Yogyakarta, zona Prawirotaman', statoPernottamento: 'da-confermare', intensita: 'leggero', destinazioneSlug: 'giava', immagine: '/images/viaggi/indonesia-itinerario/giorno-08-kraton-yogyakarta.jpg', imageAlt: 'Un padiglione decorato del Kraton di Yogyakarta, il palazzo del Sultano, tra gli alberi del cortile interno' },
    { titoloGiorno: 'Giorno 9 — In treno verso Surabaya e trasferimento a Cemoro Lawang', tratta: 'Yogyakarta → Surabaya Gubeng (treno, 4-5h) → Probolinggo (treno, 2h) → Cemoro Lawang', pernottamento: 'Cemoro Lawang', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'treno Yogyakarta-Surabaya 75.000-285.000 IDR; minivan pubblico Probolinggo-Cemoro Lawang circa 35.000 IDR a persona, attenzione ai prezzi gonfiati dai tout in stazione', destinazioneSlug: 'giava', immagine: '/images/viaggi/indonesia-itinerario/giorno-09-cemoro-lawang.jpg', imageAlt: 'Il villaggio di Cemoro Lawang aggrappato al bordo della caldera del Bromo, visto dal Monte Penanjakan' },
    { titoloGiorno: 'Giorno 10 — Alba al Gunung Bromo e la cascata di Madakaripura', tratta: 'Dopo Madakaripura, trasferimento verso Banyuwangi/Licin', pernottamento: 'Banyuwangi o Licin', statoPernottamento: 'da-confermare', intensita: 'intenso', costiNoti: 'jeep condiviso per il Bromo 700.000-900.000 IDR per veicolo, diffidare di chi ne chiede il doppio o il triplo', destinazioneSlug: 'giava', immagine: '/images/viaggi/indonesia-itinerario/giorno-10-bromo-alba.jpg', imageAlt: "Il massiccio del Tengger all'alba, con il cratere fumante del Bromo e il Semeru in eruzione sullo sfondo, sopra un mare di nuvole" },
    { titoloGiorno: 'Giorno 11 — Il fuoco blu del Kawah Ijen', pernottamento: 'Banyuwangi o Licin', statoPernottamento: 'da-confermare', intensita: 'intenso', destinazioneSlug: 'giava', immagine: '/images/viaggi/indonesia-itinerario/giorno-11-kawah-ijen.jpg', imageAlt: 'Le fiamme blu del fuoco di zolfo del Kawah Ijen, fotografate di notte nel buio del cratere' },
    { titoloGiorno: 'Giorno 12 — Il traghetto per Bali e arrivo a Ubud', tratta: 'Banyuwangi/Licin → Ketapang → traghetto per Gilimanuk (30-60 min) → Ubud', pernottamento: 'Ubud', statoPernottamento: 'da-confermare', intensita: 'leggero', costiNoti: 'traghetto Ketapang-Gilimanuk pochi euro a persona, partenze ogni 15 minuti 24 ore su 24', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-12-traghetto-gilimanuk.jpg', imageAlt: 'Il traghetto KMP Gilimanuk attraversa lo stretto di Bali tra Ketapang e Gilimanuk' },
    { titoloGiorno: 'Giorno 13 — Ubud e le risaie di Tegalalang', pernottamento: 'Ubud', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-13-tegalalang.jpg', imageAlt: 'Le risaie a terrazza di Tegalalang che scendono a onde verdi tra le palme, vicino a Ubud, Bali' },
    { titoloGiorno: 'Giorno 14 — Sidemen, la pace delle risaie', tratta: 'Ubud → Sidemen e ritorno, circa 1h15-1h30 di scooter o auto', pernottamento: 'Ubud', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'driver privato andata/ritorno indicativamente 350.000 IDR (20€)', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-14-sidemen.jpg', imageAlt: 'Le risaie della valle di Sidemen ai piedi del Gunung Agung, viste da un canale di irrigazione, Bali orientale' },
    { titoloGiorno: 'Giorno 15 — Amed e il mare a est', tratta: 'Ubud → Amed e ritorno, circa 2h di scooter o auto', pernottamento: 'Ubud', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'driver privato andata/ritorno indicativamente 500.000 IDR (28-30€)', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-15-amed.jpg', imageAlt: 'La spiaggia di sabbia nera vulcanica di Amed, con le barche a bilanciere dei pescatori tirate a riva, Bali orientale' },
    { titoloGiorno: 'Giorno 16 — Munduk e le cascate, verso Lovina', tratta: 'Ubud → Munduk → Lovina', pernottamento: 'Lovina', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'driver privato per l\'intero anello indicativamente 500.000-600.000 IDR (28-35€)', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-16-munduk-cascata.jpg', imageAlt: 'La cascata Belong tra le felci e la vegetazione della foresta pluviale di Munduk, altopiano vulcanico di Bali' },
    { titoloGiorno: 'Giorno 17 — Lovina e i delfini all\'alba', tratta: 'Lovina → Ubud, dopo l\'uscita in barca all\'alba', pernottamento: 'Ubud', statoPernottamento: 'da-confermare', intensita: 'leggero', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-17-lovina-delfini.jpg', imageAlt: 'Un gruppo di delfini che salta tra le onde al largo di Lovina, visto dalla prua di una barca a bilanciere, Bali del nord' },
    { titoloGiorno: 'Giorno 18 — Uluwatu: surf, spiagge e la danza Kecak al tramonto', tratta: 'Ubud → Uluwatu', pernottamento: 'Uluwatu', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-18-uluwatu.jpg', imageAlt: 'Le scogliere a strapiombo di Uluwatu con il tempio Pura Luhur in cima, sopra il mare turchese di Bali' },
    { titoloGiorno: 'Giorno 19 — Canggu e la vita notturna di Bali', tratta: 'Uluwatu → Canggu', pernottamento: 'Canggu', statoPernottamento: 'da-confermare', intensita: 'leggero', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-19-canggu.jpg', imageAlt: 'Tramonto sulla spiaggia di Canggu, Bali' },
    { titoloGiorno: 'Giorno 20 — Giornata a Nusa Penida', tratta: 'Canggu → Sanur (imbarco) → Nusa Penida e ritorno', pernottamento: 'Canggu', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'tour di giornata 30-50€ a persona, snorkeling con le manta come extra', destinazioneSlug: 'bali', immagine: '/images/viaggi/indonesia-itinerario/giorno-20-nusa-penida.jpg', imageAlt: 'Kelingking Beach a forma di T-Rex vista dal punto panoramico in cima alla scogliera, Nusa Penida' },
    { titoloGiorno: 'Giorno 21 — Da Bali a Lombok, verso Senaru', tratta: 'Bali → Lombok in traghetto veloce o volo, poi verso Senaru/Sembalun', pernottamento: 'Senaru o Sembalun, Lombok', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'lombok-gili', immagine: '/images/viaggi/indonesia-itinerario/giorno-21-senaru-sembalun.jpg', imageAlt: 'La savana ai piedi del Gunung Rinjani lungo il sentiero da Sembalun, Lombok' },
    { titoloGiorno: 'Giorno 22 — Inizio del trekking al Gunung Rinjani', pernottamento: 'Campo in quota, Gunung Rinjani', statoPernottamento: 'da-confermare', intensita: 'intenso', costiNoti: 'pacchetto guidato con guida, portatori, campo e pasti da 150-250€ a persona secondo la durata', destinazioneSlug: 'lombok-gili', immagine: '/images/viaggi/indonesia-itinerario/giorno-22-rinjani-trekking.jpg', imageAlt: 'Il cono del Gunung Rinjani visto dal sentiero di savana sulla via Sembalun-Plawangan II' },
    { titoloGiorno: 'Giorno 23 — Il lago Segara Anak e la discesa dal Rinjani', pernottamento: 'Senaru o Sembalun, Lombok', statoPernottamento: 'da-confermare', intensita: 'intenso', destinazioneSlug: 'lombok-gili', immagine: '/images/viaggi/indonesia-itinerario/giorno-23-segara-anak.jpg', imageAlt: "Il lago craterico Segara Anak e il cono del Gunung Baru all'alba, visti dal bordo della caldera del Rinjani sopra un mare di nuvole" },
    { titoloGiorno: 'Giorno 24 — Verso le isole Gili', tratta: 'Lombok → Gili in barca veloce', pernottamento: 'Isole Gili (Trawangan o Air)', statoPernottamento: 'da-confermare', intensita: 'leggero', destinazioneSlug: 'lombok-gili', immagine: '/images/viaggi/indonesia-itinerario/giorno-24-gili-trawangan.jpg', imageAlt: 'La spiaggia di sabbia bianca di Gili Trawangan al crepuscolo, con i warung sulla battigia' },
    { titoloGiorno: 'Giorno 25 — Gili Trawangan e Gili Air, senza motori', pernottamento: 'Isole Gili (Trawangan o Air)', statoPernottamento: 'da-confermare', intensita: 'leggero', destinazioneSlug: 'lombok-gili', immagine: '/images/viaggi/indonesia-itinerario/giorno-25-gili-air.jpg', imageAlt: 'La strada sterrata sul lungomare di Gili Air, senza auto né motorini, con il mare sullo sfondo' },
    { titoloGiorno: 'Giorno 26 — Labuan Bajo e inizio del tour nel Parco di Komodo', tratta: 'Gili/Lombok → Labuan Bajo, Flores', pernottamento: 'A bordo della barca, Parco di Komodo', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'komodo', immagine: '/images/viaggi/indonesia-itinerario/giorno-26-labuan-bajo.jpg', imageAlt: "Barche da pesca e da tour ancorate nella baia di Labuan Bajo con la bassa marea, punto di partenza dei tour nel Parco di Komodo, Flores" },
    { titoloGiorno: 'Giorno 27 — Padar Island all\'alba e Pink Beach', pernottamento: 'A bordo della barca, Parco di Komodo', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'komodo', immagine: '/images/viaggi/indonesia-itinerario/giorno-27-padar-island.jpg', imageAlt: 'Vista dal sentiero panoramico di Padar Island sulle sue baie dalle acque turchesi, Parco Nazionale di Komodo' },
    { titoloGiorno: 'Giorno 28 — I draghi di Komodo e lo snorkeling a Kanawa', tratta: 'Rientro in barca a Labuan Bajo', pernottamento: 'Labuan Bajo', statoPernottamento: 'da-confermare', intensita: 'medio', costiNoti: 'ingresso al parco più ranger, indicativamente 15-25€ a persona', destinazioneSlug: 'komodo', immagine: '/images/viaggi/indonesia-itinerario/giorno-28-komodo-dragon.jpg', imageAlt: "Primo piano della testa di un drago di Komodo con la lingua biforcuta estesa, Rinca, Parco Nazionale di Komodo" },
    { titoloGiorno: 'Giorno 29 — Trans-Flores verso Bajawa e il villaggio di Bena', tratta: 'Labuan Bajo → Bajawa sulla Trans-Flores', pernottamento: 'Bajawa', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'flores', immagine: '/images/viaggi/indonesia-itinerario/giorno-29-bena-village.jpg', imageAlt: 'Le case dal tetto conico di paglia del villaggio tradizionale di Bena disposte in file, ai piedi del vulcano Inerie, Flores' },
    { titoloGiorno: 'Giorno 30 — Da Bajawa a Moni', tratta: 'Bajawa → Moni sulla Trans-Flores', pernottamento: 'Moni', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'flores', immagine: '/images/viaggi/indonesia-itinerario/giorno-30-ruteng-rice-fields.jpg', imageAlt: "Terrazzamenti di riso a ragnatela visti dall'alto, con contadini al lavoro tra i campi, altopiano centrale di Flores" },
    { titoloGiorno: 'Giorno 31 — Alba al Kelimutu', tratta: 'Dopo l\'alba, trasferimento verso Ende o Maumere', pernottamento: 'Ende o Maumere', statoPernottamento: 'da-confermare', intensita: 'intenso', costiNoti: 'biglietto d\'ingresso al parco nazionale, pochi euro', destinazioneSlug: 'flores', immagine: '/images/viaggi/indonesia-itinerario/giorno-31-kelimutu.jpg', imageAlt: "I laghi craterici color turchese del Kelimutu visti dal bordo del cratere all'alba, Flores" },
    { titoloGiorno: 'Giorno 32 — Verso Makassar e Tana Toraja', tratta: 'Ende/Maumere → volo su Makassar → bus/volo interno per Rantepao', pernottamento: 'Rantepao, Tana Toraja', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'sulawesi', immagine: '/images/viaggi/indonesia-itinerario/giorno-32-losari-makassar.jpg', imageAlt: 'Il lungomare di Pantai Losari a Makassar, con le storiche navi ormeggiate e la Moschea Galleggiante sullo sfondo, Sulawesi' },
    { titoloGiorno: 'Giorno 33 — Tana Toraja: villaggi tongkonan e tombe nella roccia', pernottamento: 'Rantepao, Tana Toraja', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'sulawesi', immagine: '/images/viaggi/indonesia-itinerario/giorno-33-kete-kesu-tongkonan.jpg', imageAlt: 'La facciata intagliata e dipinta di una tongkonan a Kete Kesu, decorata con corna di bufalo impilate, Tana Toraja' },
    { titoloGiorno: 'Giorno 34 — Trekking tra i villaggi di montagna di Rantepao', tratta: 'Rientro verso Makassar nel tardo pomeriggio', pernottamento: 'Makassar', statoPernottamento: 'da-confermare', intensita: 'medio', destinazioneSlug: 'sulawesi', immagine: '/images/viaggi/indonesia-itinerario/giorno-34-limbong-toraja.jpg', imageAlt: 'Una casa tongkonan dal tetto a barca affacciata su risaie terrazzate nelle montagne intorno a Rantepao, Tana Toraja' },
    { titoloGiorno: 'Giorno 35 — Makassar e partenza', intensita: 'leggero', destinazioneSlug: 'sulawesi', immagine: '/images/viaggi/indonesia-itinerario/giorno-35-fort-rotterdam.jpg', imageAlt: 'Il cortile interno di Fort Rotterdam, il forte coloniale olandese sul lungomare di Makassar' },
  ],
  budget: [
    { etichetta: 'Voli intercontinentali', valore: undefined },
    { etichetta: 'Voli interni', valore: 'diversi tratti su Garuda, Lion Air, Citilink o Wings Air, più il traghetto Ketapang-Gilimanuk e altri due-tre traghetti veloci' },
    { etichetta: 'Spostamenti via terra (Sumatra, Giava, Bali)', valore: 'scooter a noleggio pochi euro al giorno per chi guida con sicurezza, oppure driver privato indicativamente 350.000-900.000 IDR a tratta secondo la distanza' },
    { etichetta: 'Guide obbligatorie', valore: 'Rinjani 150-250€ a persona secondo la durata; oranghi 25-40€ per mezza giornata; draghi di Komodo 15-25€' },
    { etichetta: 'Tour in barca Parco di Komodo', valore: 'variabile secondo la durata, con pernottamento a bordo' },
    { etichetta: 'Alloggi', valore: 'molto variabile: economico a Sumatra e Flores, medio a Bali, Lombok e Sulawesi' },
    { etichetta: 'Pasti', valore: 'pochi euro a piatto nei warung fuori da Bali; leggermente di più nei ristoranti turistici' },
  ],
}
