import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Egadi, Pantelleria e Lampedusa in 12 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/38-isole-siciliane.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const isoleSicilianeMeta: TripMeta = {
  tripSlug: 'isole-siciliane',
  paeseSlug: 'italia',
  ritmo: 'Tre arcipelaghi separati, con una giornata interamente di transito che è inevitabile e va prevista invece che scoperta',
  trasporti: 'Aliscafi da Trapani per le Egadi, voli in continuità territoriale per Pantelleria e Lampedusa; bici a Favignana, auto o scooter altrove',
  stile: [
    'isole',
    'mare',
    'vulcani',
  ],
  adattoA: [
    'chi vuole attraversare il Canale di Sicilia a tappe e vedere l\'Europa diventare Africa',
    'chi non cerca la spiaggia di sabbia, che qui quasi non esiste',
    'chi tiene margini larghi sugli spostamenti, perché il vento decide',
  ],
  puntiForti: [
    'I giardini ipogei dentro le ex cave di tufo di Favignana',
    'Le viti ad alberello dentro le conche scavate a Pantelleria, patrimonio immateriale UNESCO dal 2014',
    'La Spiaggia dei Conigli a Lampedusa, dentro le regole della riserva che è il motivo per cui è ancora così',
  ],
  criticita: [
    'Pantelleria e Lampedusa non sono collegate tra loro: per passare dall\'una all\'altra si torna in Sicilia',
    'Il vento cancella traghetti e voli: non vanno incastrate coincidenze strette né biglietti non modificabili',
    'Le regole della Riserva dell\'Isola dei Conigli — contingentamenti, orari, chiusure per la nidificazione delle Caretta caretta — cambiano ogni stagione',
    'La Grotta del Genovese si visita solo con accompagnamento e su prenotazione, non presentandosi sul posto',
    'A Pantelleria non ci sono spiagge di sabbia, e i mezzi a noleggio sono pochi e finiscono',
    'Su Pantelleria e Lampedusa l\'acqua viene da dissalatori e cisterne',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, tra voli interni, traghetti, bici e scooter',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'Le incisioni paleolitiche della Grotta del Genovese, la sauna naturale di Benikulà dentro la roccia, la Tabaccara con le barche che sembrano sospese',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Favignana', destinazioneSlug: 'isole-siciliane' },
    { nome: 'Levanzo', destinazioneSlug: 'isole-siciliane' },
    { nome: 'Marettimo', destinazioneSlug: 'isole-siciliane' },
    { nome: 'Pantelleria', destinazioneSlug: 'isole-siciliane' },
    { nome: 'Lampedusa e Linosa', destinazioneSlug: 'isole-siciliane' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Trapani e sbarco a Favignana',
      tratta: 'Trapani e aliscafo per Favignana',
      pernottamento: 'Favignana, in paese',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'aliscafi frequenti da Trapani, venti minuti di traversata',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-01-favignana.jpg',
      imageAlt: 'Vecchie ancore arrugginite sulla banchina del porto di Favignana, con l\'ex stabilimento Florio e il Monte Santa Caterina sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 2 — Favignana in bicicletta',
      tratta: 'Giro dell\'isola in bicicletta e ex stabilimento Florio',
      pernottamento: 'Favignana',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'quasi nessuna cala è di sabbia: servono scarpe di gomma',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-02-cala-rossa.jpg',
      imageAlt: 'Una ciclista sulla scogliera di roccia bianca tagliata di Cala Rossa a Favignana, con il mare turchese e la costa siciliana sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 3 — Levanzo e la Grotta del Genovese',
      tratta: 'Traversata per Levanzo e Grotta del Genovese',
      pernottamento: 'Favignana o Levanzo',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'la grotta si visita solo con accompagnamento, prenotando: via mare o in fuoristrada',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-03-levanzo.jpg',
      imageAlt: 'Il piccolo paese bianco di Levanzo affacciato sulla baia con le barche ormeggiate nell\'acqua turchese',
    },
    {
      titoloGiorno: 'Giorno 4 — Marettimo',
      tratta: 'Marettimo a piedi e giro delle grotte in barca, poi rientro a Trapani',
      intensita: 'intenso',
      costiNoti: 'Marettimo non ha auto e ha pochissimi posti letto',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-04-marettimo.jpg',
      imageAlt: 'Il Castello di Punta Troia in cima al promontorio roccioso di Marettimo, raggiunto da un sentiero a tornanti sopra il mare blu',
    },
    {
      titoloGiorno: 'Giorno 5 — Trasferimento a Pantelleria e primo giro',
      tratta: 'Volo o traghetto notturno per Pantelleria e primo giro dell\'isola',
      pernottamento: 'Pantelleria, in un dammuso',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'voli in continuità territoriale; il traghetto da Trapani viene cancellato spesso con mare mosso',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-05-arco-elefante.jpg',
      imageAlt: 'L\'Arco dell\'Elefante, la formazione di roccia lavica nera a forma di proboscide che entra nel mare blu a Pantelleria',
    },
    {
      titoloGiorno: 'Giorno 6 — Lo Specchio di Venere, Benikulà e la Montagna Grande',
      tratta: 'Specchio di Venere, sauna di Benikulà e salita alla Montagna Grande',
      pernottamento: 'Pantelleria',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'la sauna di Benikulà è libera e gratuita; i fanghi del lago anche',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-06-specchio-venere.jpg',
      imageAlt: 'Vista panoramica del lago Specchio di Venere a Pantelleria, un bacino turchese dentro una caldera circondata da vigneti terrazzati',
    },
    {
      titoloGiorno: 'Giorno 7 — I vigneti, i capperi e il Passito',
      tratta: 'I vigneti ad alberello, i giardini panteschi, i capperi e una cantina di Passito',
      pernottamento: 'Pantelleria',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'cantine su appuntamento: la visita è gran parte del viaggio',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-07-alberello.jpg',
      imageAlt: 'Filari di vite ad alberello pantesco coltivate basse tra muretti di pietra lavica a secco, con una persona al lavoro tra i filari',
    },
    {
      titoloGiorno: 'Giorno 8 — Pantelleria dal mare',
      tratta: 'Giro dell\'isola in barca, oppure i sentieri dell\'interno',
      pernottamento: 'Pantelleria',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'si sceglie la cala in base al vento del giorno, come fanno i panteschi',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-08-dammuso.jpg',
      imageAlt: 'Un dammuso abbandonato in pietra lavica con il tetto a cupola erboso, circondato da fiori selvatici e con il mare sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 9 — Giornata di transito',
      tratta: 'Volo Pantelleria-Palermo o Catania e coincidenza per Lampedusa',
      pernottamento: 'Lampedusa',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'da prevedere con margine: una cancellazione per vento manda a monte la coincidenza',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-09-transito.jpg',
      imageAlt: 'L\'ingresso dell\'Aeroporto di Palermo Falcone Borsellino, tappa di coincidenza tra il volo da Pantelleria e quello per Lampedusa',
    },
    {
      titoloGiorno: 'Giorno 10 — Lampedusa e la Spiaggia dei Conigli',
      tratta: 'Spiaggia dei Conigli, le cale e la Porta d\'Europa',
      pernottamento: 'Lampedusa',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'accesso alla riserva contingentato e regolamentato, con regole che cambiano ogni stagione',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-10-conigli.jpg',
      imageAlt: 'La Spiaggia dei Conigli a Lampedusa, con la sabbia bianca e l\'acqua trasparente dai toni turchesi dentro la baia protetta',
    },
    {
      titoloGiorno: 'Giorno 11 — In barca, o Linosa',
      tratta: 'Giro dell\'isola in barca fino alla Tabaccara, oppure traversata per Linosa',
      pernottamento: 'Lampedusa',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'alla Tabaccara non si sbarca e l\'ancoraggio è regolamentato',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-11-tabaccara.jpg',
      imageAlt: 'Barche che sembrano sospese sull\'acqua trasparente color turchese della Tabaccara a Lampedusa, dentro un\'insenatura di roccia calcarea',
    },
    {
      titoloGiorno: 'Giorno 12 — Partenza',
      tratta: 'Volo di rientro, con margine',
      intensita: 'leggero',
      destinazioneSlug: 'isole-siciliane',
      immagine: '/images/viaggi/isole-siciliane/giorno-12-partenza.jpg',
      imageAlt: 'L\'aeroporto di Lampedusa con la torre di controllo ENAV e un piccolo aereo in decollo nel cielo azzurro',
    },
  ],
  budget: [
    { etichetta: 'Voli interni', valore: 'la voce più alta e la più rigida: Pantelleria e Lampedusa si raggiungono quasi solo in aereo' },
    { etichetta: 'Aliscafi per le Egadi', valore: 'economici e frequenti, l\'arcipelago più facile d\'Italia da raggiungere' },
    { etichetta: 'Mezzi a noleggio', valore: 'bici a Favignana, auto o scooter a Pantelleria e Lampedusa: da prenotare in anticipo' },
    { etichetta: 'Alloggio', valore: 'limitato ovunque, con prezzi che salgono molto in agosto su isole piccole senza grande capacità ricettiva' },
    { etichetta: 'Cibo', valore: 'quasi tutto arriva via mare: conviene mangiare quello che l\'isola produce davvero' },
  ],
}
