import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per il viaggio "Messico Beach Life".
// Il testo narrativo resta nel markdown (src/content/viaggi/13-messico-beach-life.md):
// questo file aggiunge solo i campi che il markdown non modella esplicitamente
// (pernottamento per giorno, intensità, link a destinazioni, budget, mappa).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const messicoBeachLifeMeta: TripMeta = {
  tripSlug: 'messico-beach-life',
  paeseSlug: 'messico',
  ritmo: 'Intenso — pochi giorni di vero riposo, molti transfer e giornate a tappe serrate',
  trasporti: 'Van privato con autista per i trasferimenti principali, bus ADO e traghetto per Holbox',
  stile: ['mare', 'cultura', 'natura', 'nightlife'],
  adattoA: ['gruppi', 'coppie', 'primo viaggio nello Yucatán'],
  puntiForti: [
    'Copre sia il lato Yucatán/entroterra (Chichén Itzá, cenote, Mérida) sia la Riviera Maya costiera in un unico giro',
    'Lo squalo balena a Holbox come chiusura, non come tappa isolata',
    'Due Temazcal in punti diversi del viaggio, non solo uno "da cartolina"',
  ],
  criticita: [
    'Ritmo molto denso su alcune giornate (in particolare Giorno 5 e Giorno 6): poco margine per imprevisti',
    'Bacalar vista solo in giornata: meriterebbe una notte in più',
    'Diversi hotel del secondo tratto del viaggio (Mahahual, Tulum, Playa del Carmen, Holbox) non hanno ancora un nome confermato nella bozza',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: undefined,
    cosaCercavo: undefined,
    treEsperienzePiuBelle: undefined,
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Cancún', destinazioneSlug: 'cancun' },
    { nome: 'Río Lagartos' },
    { nome: 'Valladolid', destinazioneSlug: 'valladolid' },
    { nome: 'Mérida', destinazioneSlug: 'merida' },
    { nome: 'Campeche', destinazioneSlug: 'campeche' },
    { nome: 'Mahahual', destinazioneSlug: 'mahahual' },
    { nome: 'Bacalar', destinazioneSlug: 'bacalar' },
    { nome: 'Tulum', destinazioneSlug: 'tulum' },
    { nome: 'Playa del Carmen', destinazioneSlug: 'playa-del-carmen' },
    { nome: 'Holbox', destinazioneSlug: 'holbox' },
    { nome: 'Cancún', destinazioneSlug: 'cancun' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 0 — Cancún, notte extra pre-tour',
      tratta: 'Arrivo a Cancún',
      pernottamento: 'Hostel Selina Cancún Downtown',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'cancun',
      immagine: '/images/viaggi/messico-beach-life/giorno-0-cancun-zona-hotelera.jpg',
      imageAlt: 'La Zona Hotelera di Cancún vista tra le palme, con la spiaggia e il mare turchese',
    },
    {
      titoloGiorno: 'Giorno 1 — Cancún, giornata di spiaggia',
      tratta: 'Cancún (senza transfer)',
      pernottamento: 'Hostel Selina Cancún Downtown',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'cancun',
      immagine: '/images/viaggi/messico-beach-life/giorno-1-cancun-spiaggia.jpg',
      imageAlt: 'La spiaggia di Cancún con sabbia bianca, mare turchese e lo skyline degli hotel sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 2 — Cancún → Valladolid',
      tratta: 'Cancún → Río Lagartos → Ek Balam → Valladolid',
      pernottamento: 'Hotel Waye',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'valladolid',
      immagine: '/images/viaggi/messico-beach-life/giorno-2-valladolid-cattedrale.jpg',
      imageAlt: "La Chiesa di San Gervasio sulla piazza principale di Valladolid, nello Yucatán",
    },
    {
      titoloGiorno: 'Giorno 3 — Valladolid → Mérida',
      tratta: 'Valladolid → Chichén Itzá → Izamal → cenote Ik Kil → Mérida',
      pernottamento: 'Ontico Urban Design Hotel',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Chichén Itzá 614 MXN/persona · cenote Ik Kil 320 MXN',
      destinazioneSlug: 'merida',
      immagine: '/images/viaggi/messico-beach-life/giorno-3-merida-paseo-montejo.jpg',
      imageAlt: 'Una delle eleganti dimore coloniali sul Paseo de Montejo, il viale monumentale di Mérida',
    },
    {
      titoloGiorno: 'Giorno 4 — Mérida, giornata break: Playa Progreso',
      tratta: 'Mérida (giornata break, gita a Playa Progreso)',
      pernottamento: 'Ontico Urban Design Hotel',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'merida',
      immagine: '/images/viaggi/messico-beach-life/giorno-4-playa-progreso.jpg',
      imageAlt: 'La spiaggia di Playa Progreso con il lunghissimo molo che si allunga nel Golfo del Messico',
    },
    {
      titoloGiorno: 'Giorno 5 — Mérida → Campeche',
      tratta: 'Mérida → Uxmal → Becal → Pomuch → Temazcal Yax Ha → Campeche',
      pernottamento: 'Hotel Francis Drake',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Temazcal Yax Ha 450 MXN · sombrero base a Becal 800 MXN',
      destinazioneSlug: 'campeche',
      immagine: '/images/viaggi/messico-beach-life/giorno-5-campeche-case-colorate.jpg',
      imageAlt: 'Le case colorate del centro storico coloniale di Campeche, patrimonio UNESCO',
    },
    {
      titoloGiorno: 'Giorno 6 — Campeche → Mahahual',
      tratta: 'Campeche → Balam Ku → cenote Miguel Colorado → Mahahual',
      pernottamento: 'nome da confermare',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'mahahual',
      immagine: '/images/viaggi/messico-beach-life/giorno-6-mahahual-costa.jpg',
      imageAlt: 'Il lungomare di Mahahual con palapa, ristoranti e l\'accesso diretto alla spiaggia caraibica',
    },
    {
      titoloGiorno: 'Giorno 7 — Mahahual: Bacalar, snorkeling e Temazcal',
      tratta: 'Mahahual (tour in giornata a Bacalar)',
      pernottamento: 'nome da confermare',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'mahahual',
      immagine: '/images/viaggi/messico-beach-life/giorno-7-bacalar-laguna.jpg',
      imageAlt: 'Vista aerea della Laguna di Bacalar, la "laguna dei sette colori", con un molo di legno e due palapa',
    },
    {
      titoloGiorno: 'Giorno 8 — Tulum: giornata chill',
      tratta: 'Mahahual → Tulum',
      pernottamento: 'nome da confermare',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'Caleta Tankah 300 MXN/persona',
      destinazioneSlug: 'tulum',
      immagine: '/images/viaggi/messico-beach-life/giorno-8-tulum-rovine.jpg',
      imageAlt: 'Le rovine Maya di Tulum su una scogliera a picco sulla spiaggia bianca e il mare turchese',
    },
    {
      titoloGiorno: 'Giorno 9 — Tulum e Playa del Carmen',
      tratta: 'Tulum (mattina) → serata a Playa del Carmen',
      pernottamento: 'nome da confermare — non è chiaro se la notte sia stata a Tulum o Playa del Carmen',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'tulum',
      immagine: '/images/viaggi/messico-beach-life/giorno-9-playa-del-carmen.jpg',
      imageAlt: 'La spiaggia di Playa del Carmen con lettini, ombrelloni e il molo sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 10 — Verso Holbox: 3 Islas e bioluminescenza',
      tratta: 'Tulum/Playa del Carmen → Chiquilà → Holbox',
      pernottamento: 'nome da confermare',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'holbox',
      immagine: '/images/viaggi/messico-beach-life/giorno-10-holbox-acqua-bassa.jpg',
      imageAlt: "L'acqua bassa e turchese di Holbox con la spiaggia bianca, dove ci si sposta anche in bicicletta",
    },
    {
      titoloGiorno: 'Giorno 11 — Holbox: squalo balena',
      tratta: 'Holbox (escursione in giornata)',
      pernottamento: 'nome da confermare',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'holbox',
      immagine: '/images/viaggi/messico-beach-life/giorno-11-holbox-squalo-balena.jpg',
      imageAlt: 'Uno squalo balena affiora in superficie mentre alcuni snorkeler nuotano accanto, con la barca del tour sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 12 — Rientro a Cancún',
      tratta: 'Holbox → Cancún',
      pernottamento: 'da confermare (giorno di rientro)',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'cancun',
      immagine: '/images/viaggi/messico-beach-life/giorno-12-cancun-aeroporto.jpg',
      imageAlt: "L'interno del terminal dell'aeroporto di Cancún, con i viaggiatori in transito verso l'uscita",
    },
  ],
  budget: [
    { etichetta: 'Voli', valore: undefined },
    { etichetta: 'Pernottamenti', valore: undefined },
    { etichetta: 'Trasporti in loco', valore: undefined },
    { etichetta: 'Escursioni e attività', valore: undefined },
    { etichetta: 'Ingressi (siti archeologici, cenote)', valore: undefined },
    { etichetta: 'Cibo', valore: undefined },
    { etichetta: 'Vita notturna', valore: undefined },
    { etichetta: 'Totale', valore: undefined },
  ],
}
