import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Normandia e Bretagna in 12 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/41-normandia-bretagna.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const normandiaBretagnaMeta: TripMeta = {
  tripSlug: 'normandia-bretagna',
  paeseSlug: 'francia',
  ritmo: 'Cinque giorni di Normandia densa e storica, sette di Bretagna lenta e costiera, con il Mont-Saint-Michel come cerniera',
  trasporti: 'Auto a noleggio per quasi tutto il percorso',
  stile: [
    'storia',
    'costa',
    'trekking',
  ],
  adattoA: [
    'chi vuole unire la storia dello sbarco con la costa bretone',
    'chi cammina volentieri e ama i paesaggi marittimi',
    'chi ha tempo per fare bene entrambe le regioni',
  ],
  puntiForti: [
    'Le spiagge dello sbarco, viste dopo un museo che dia il contesto',
    'Il Mont-Saint-Michel dormendo nella baia, visto alla sera e all\'alba',
    'Un tratto del GR34, il sentiero dei doganieri, in qualunque paese bretone',
  ],
  criticita: [
    'Il meteo resta una variabile in ogni mese: si porta sempre l\'antipioggia',
    'La baia del Mont-Saint-Michel non si attraversa da soli per le sabbie mobili',
    'Le distanze in Bretagna sono più lunghe di quanto la mappa suggerisca',
    'Il museo dell\'Arazzo di Bayeux è interessato da un lungo cantiere di ristrutturazione',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con auto a noleggio',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'La Pointe du Hoc con i crateri ancora intatti, il Mont-Saint-Michel all\'alba, gli allineamenti di Carnac',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Rouen', destinazioneSlug: 'normandia' },
    { nome: 'Spiagge dello sbarco', destinazioneSlug: 'normandia' },
    { nome: 'Mont-Saint-Michel', destinazioneSlug: 'normandia' },
    { nome: 'Saint-Malo e Dinan', destinazioneSlug: 'bretagna' },
    { nome: 'Côte de Granit Rose', destinazioneSlug: 'bretagna' },
    { nome: 'Carnac e Morbihan', destinazioneSlug: 'bretagna' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Rouen',
      tratta: 'Rouen: cattedrale, Gros-Horloge',
      pernottamento: 'Rouen',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'normandia',
    },
    {
      titoloGiorno: 'Giorno 2 — Le spiagge dello sbarco (parte 1)',
      tratta: 'Trasferimento a Bayeux, Mémorial de Caen',
      pernottamento: 'Bayeux',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'normandia',
    },
    {
      titoloGiorno: 'Giorno 3 — Le spiagge dello sbarco (parte 2)',
      tratta: 'Spiagge dello sbarco: Omaha, Pointe du Hoc, Arromanches',
      pernottamento: 'Bayeux',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      destinazioneSlug: 'normandia',
    },
    {
      titoloGiorno: 'Giorno 4 — Bayeux e l\'Arazzo',
      tratta: 'Arazzo di Bayeux',
      pernottamento: 'Bayeux',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'verificare stato del cantiere di ristrutturazione',
      destinazioneSlug: 'normandia',
    },
    {
      titoloGiorno: 'Giorno 5 — Étretat e Honfleur',
      tratta: 'Falesie di Étretat, Honfleur',
      pernottamento: 'verso Mont-Saint-Michel',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'normandia',
    },
    {
      titoloGiorno: 'Giorno 6 — Mont-Saint-Michel',
      tratta: 'Arrivo alla baia, abbazia in tarda giornata',
      pernottamento: 'baia del Mont-Saint-Michel',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'normandia',
    },
    {
      titoloGiorno: 'Giorno 7 — Mont-Saint-Michel all\'alba, poi Saint-Malo',
      tratta: 'Mont-Saint-Michel all\'alba, trasferimento a Saint-Malo',
      pernottamento: 'Saint-Malo',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'bretagna',
    },
    {
      titoloGiorno: 'Giorno 8 — Dinan e la Côte de Granit Rose',
      tratta: 'Dinan, prima tappa sulla Côte de Granit Rose',
      pernottamento: 'zona Perros-Guirec',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'bretagna',
    },
    {
      titoloGiorno: 'Giorno 9 — Ploumanac\'h e il GR34',
      tratta: 'Ploumanac\'h, camminata sul GR34',
      pernottamento: 'zona Perros-Guirec',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'bretagna',
    },
    {
      titoloGiorno: 'Giorno 10 — Penisola di Crozon',
      tratta: 'Trasferimento alla penisola di Crozon',
      pernottamento: 'penisola di Crozon',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'bretagna',
    },
    {
      titoloGiorno: 'Giorno 11 — Carnac e il Golfo del Morbihan',
      tratta: 'Allineamenti di Carnac, Golfo del Morbihan',
      pernottamento: 'Carnac o Vannes',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'bretagna',
    },
    {
      titoloGiorno: 'Giorno 12 — Partenza',
      tratta: 'Partenza',
      intensita: 'leggero',
      destinazioneSlug: 'bretagna',
    },
  ],
  budget: [
    { etichetta: 'Auto a noleggio', valore: 'necessaria per quasi tutto il percorso' },
    { etichetta: 'Musei e siti dello sbarco', valore: 'in gran parte gratuiti, con il Mémorial de Caen a biglietto contenuto' },
    { etichetta: 'Mont-Saint-Michel', valore: 'ingresso all\'abbazia a pagamento, parcheggio e navetta una voce a parte' },
    { etichetta: 'Alloggio', valore: 'più economico in Bretagna che a ridosso del Mont in alta stagione' },
    { etichetta: 'GR34', valore: 'gratuito' },
  ],
}
