import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Sardegna, le due anime".
// Il testo narrativo resta nel markdown (src/content/viaggi/37-sardegna-due-anime.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const sardegnaDueAnimeMeta: TripMeta = {
  tripSlug: 'sardegna-due-anime',
  paeseSlug: 'italia',
  ritmo: 'Una diagonale da Olbia a Cagliari che mette in fila la Sardegna che si conosce e quella che comincia venti chilometri più in là',
  trasporti: 'Auto a noleggio in formula one-way, aperto su Olbia e chiuso su Cagliari; barca per l\'arcipelago della Maddalena e il Golfo di Orosei',
  stile: [
    'mare',
    'archeologia',
    'trekking',
  ],
  adattoA: [
    'chi non vuole fermarsi ai quaranta chilometri intorno a Olbia',
    'chi mette insieme mare, canyon, nuraghi e archeologia industriale',
    'chi prenota le spiagge a numero chiuso con mesi di anticipo',
  ],
  puntiForti: [
    'Cala Goloritzé raggiunta a piedi, con l\'Aguglia alta 143 metri e nessun servizio sulla spiaggia',
    'Porto Flavia, la galleria scavata orizzontalmente nella falesia sopra il Pan di Zucchero',
    'I Giganti di Mont\'e Prama, le più antiche statue antropomorfe a tutto tondo del Mediterraneo occidentale',
  ],
  criticita: [
    'Molte spiagge hanno accesso contingentato con prenotazione obbligatoria e tetto giornaliero: le regole cambiano ogni stagione e senza prenotazione non si entra',
    'Prendere sabbia, sassi o conchiglie è vietato per legge e sanzionato, con controlli reali in aeroporto',
    'La Spiaggia Rosa di Budelli è interdetta dal 1994: chi promette di farci sbarcare mente',
    'La percorrenza di Su Gorropu oltre il primo tratto richiede attrezzatura o guida e dipende dal livello dell\'acqua',
    'Le distanze sono più lunghe di quanto la mappa suggerisca e le statali interne sono lente',
    'In agosto i prezzi triplicano, e sul nord-est il moltiplicatore è ancora più alto',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con auto a noleggio one-way',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'La discesa a piedi su Cala Goloritzé, il Pan di Zucchero visto dall\'apertura di Porto Flavia, le dune di Piscinas alte decine di metri con le miniere alle spalle',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Costa Smeralda e Gallura', destinazioneSlug: 'sardegna' },
    { nome: 'Arcipelago della Maddalena', destinazioneSlug: 'sardegna' },
    { nome: 'Golfo di Orosei e Supramonte', destinazioneSlug: 'sardegna' },
    { nome: 'Barbagia', destinazioneSlug: 'sardegna' },
    { nome: 'Sinis, Barumini e i nuraghi', destinazioneSlug: 'sardegna' },
    { nome: 'Sulcis e Costa Verde', destinazioneSlug: 'sardegna' },
    { nome: 'Carloforte e Cagliari', destinazioneSlug: 'sardegna' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Olbia e Costa Smeralda',
      tratta: 'Arrivo a Olbia, ritiro auto e Costa Smeralda',
      pernottamento: 'Cannigione, Palau o San Pantaleo',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'dormire a pochi chilometri dalla Costa Smeralda costa una frazione e la costa è la stessa',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 2 — L\'arcipelago della Maddalena',
      tratta: 'Giornata in barca nel Parco Nazionale dell\'Arcipelago di La Maddalena, con Caprera',
      pernottamento: 'zona Palau o Cannigione',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Cala Coticcio ha accesso contingentato e solo con guide autorizzate; la Spiaggia Rosa si guarda dall\'acqua',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 3 — Capo Testa, la Valle della Luna e la Gallura interna',
      tratta: 'Capo Testa, Valle della Luna e Gallura interna',
      pernottamento: 'Gallura o verso sud',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'cantine di Vermentino di Gallura su appuntamento',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 4 — Verso il Golfo di Orosei',
      tratta: 'Trasferimento lungo la costa orientale fino a Cala Gonone',
      pernottamento: 'Cala Gonone o Dorgali',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Cala Brandinchi e Lu Impostu sono soggette a contingentamento in alta stagione',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 5 — Cala Goloritzé',
      tratta: 'Altopiano del Golgo e discesa a piedi a Cala Goloritzé',
      pernottamento: 'Cala Gonone o Dorgali',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'accesso a numero chiuso con prenotazione e contributo; nessun servizio in spiaggia e ritorno tutto in salita',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 6 — Le cale del golfo in barca',
      tratta: 'Le cale del Golfo di Orosei in barca e la Grotta del Bue Marino',
      pernottamento: 'Cala Gonone o Dorgali',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'le imbarcazioni hanno quote di sbarco assegnate sulle cale contingentate',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 7 — Il Supramonte: Gorropu o Tiscali',
      tratta: 'Gola di Su Gorropu oppure il villaggio nuragico di Tiscali',
      pernottamento: 'zona Dorgali o Barbagia',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'ingresso a pagamento a Gorropu; oltre il primo tratto servono attrezzatura o guida',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 8 — La Barbagia: Orgosolo, Mamoiada, il Cannonau',
      tratta: 'Orgosolo, Mamoiada e le cantine di Cannonau',
      pernottamento: 'agriturismo in Barbagia',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'in Barbagia gli agriturismi hanno prezzi bassissimi rispetto alla costa e la cucina migliore dell\'isola',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 9 — Il Sinis, Tharros e i nuraghi',
      tratta: 'Su Nuraxi di Barumini, Pozzo sacro di Santa Cristina, Tharros e il Sinis',
      pernottamento: 'zona Oristano o Sinis',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Barumini si visita solo con accompagnamento a orari fissi; a Is Arutas la sabbia non si tocca',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 10 — Il Sulcis-Iglesiente e Porto Flavia',
      tratta: 'Sulcis-Iglesiente, Porto Flavia e le miniere',
      pernottamento: 'zona Iglesias o Costa Verde',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Porto Flavia si visita solo con accompagnamento',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 11 — Le dune di Piscinas e la Costa Verde',
      tratta: 'Dune di Piscinas e Costa Verde',
      pernottamento: 'Costa Verde',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'nessun servizio sulle spiagge della Costa Verde: si porta tutto, e la corrente è seria',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 12 — Carloforte e l\'isola di San Pietro',
      tratta: 'Traghetto per l\'isola di San Pietro e giornata a Carloforte',
      pernottamento: 'Carloforte o verso Cagliari',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'il tonno è l\'identità gastronomica dell\'isola',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 13 — Cagliari',
      tratta: 'Cagliari: Castello, Museo Archeologico, Poetto e Molentargius',
      pernottamento: 'Cagliari, in centro',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'al Museo Archeologico ci sono i bronzetti nuragici e i Giganti di Mont\'e Prama',
      destinazioneSlug: 'sardegna',
    },
    {
      titoloGiorno: 'Giorno 14 — Partenza',
      tratta: 'Costa del Sud e Nora sulla via dell\'aeroporto, volo da Cagliari',
      intensita: 'leggero',
      costiNoti: 'Tuerredda è contingentata in stagione',
      destinazioneSlug: 'sardegna',
    },
  ],
  budget: [
    { etichetta: 'Volo e noleggio one-way', valore: 'aperto su Olbia e chiuso su Cagliari; i traghetti convengono solo portandosi l\'auto propria' },
    { etichetta: 'Spiagge a numero chiuso', valore: 'contributi contenuti, ma vanno prenotati con mesi di anticipo in alta stagione' },
    { etichetta: 'Escursioni in barca', valore: 'Maddalena e Golfo di Orosei: le due voci di gita più alte, e le due che valgono di più' },
    { etichetta: 'Alloggio', valore: 'la forbice più ampia d\'Italia: la Costa Smeralda ad agosto e un agriturismo della Barbagia non appartengono alla stessa scala' },
    { etichetta: 'Visite accompagnate', valore: 'Barumini, Porto Flavia e la Grotta del Bue Marino hanno orari fissi e vanno incastrate' },
  ],
}
