import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Sicilia orientale in 10 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/26-sicilia-itinerario.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const siciliaItinerarioMeta: TripMeta = {
  tripSlug: 'sicilia-itinerario',
  paeseSlug: 'italia',
  ritmo: 'Equilibrato: due o tre basi e trasferimenti brevi, evitando il giro completo dell\'isola che trasforma la vacanza in guida',
  trasporti: 'Auto a noleggio indispensabile; sulle statali interne i tempi vanno aumentati di un terzo',
  stile: ['archeologia', 'vulcani', 'gastronomia'],
  adattoA: [
    'chi va in Sicilia per la prima volta e vuole farne bene una metà invece di attraversarla tutta',
    'chi mette archeologia e cucina davanti al mare',
    'chi guida volentieri',
  ],
  puntiForti: [
    'L\'Etna, che non è un panorama ma un vulcano in attività su cui si cammina',
    'Il Duomo di Siracusa, dove si toccano colonne doriche del V secolo a.C. inglobate in una chiesa barocca',
    'Villa Romana del Casale, con i mosaici romani più estesi e meglio conservati al mondo',
  ],
  criticita: [
    'L\'accesso alla zona sommitale dell\'Etna dipende dall\'attività del vulcano e può essere interdetto senza preavviso',
    'La Valle dei Templi d\'estate è senza ombra: si visita in notturna o all\'alba',
    'L\'accesso alla Scala dei Turchi è stato regolamentato e a tratti interdetto per l\'erosione',
    'I tempi di percorrenza sulle statali interne sono più lunghi di quanto le mappe stimino',
    'Luglio e agosto sono il peggior periodo possibile su ogni parametro',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con auto a noleggio',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'I crateri dell\'Etna con il terreno caldo sotto la mano, le colonne greche dentro il Duomo di Siracusa, la Valle dei Templi in notturna',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Catania e l\'Etna', destinazioneSlug: 'sicilia' },
    { nome: 'Taormina', destinazioneSlug: 'sicilia' },
    { nome: 'Siracusa e Ortigia', destinazioneSlug: 'sicilia' },
    { nome: 'Val di Noto', destinazioneSlug: 'sicilia' },
    { nome: 'Piazza Armerina ed Enna', destinazioneSlug: 'sicilia' },
    { nome: 'Agrigento', destinazioneSlug: 'sicilia' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Catania',
      tratta: 'Volo su Catania e ritiro auto',
      pernottamento: 'Catania o versante etneo',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 2 — L\'Etna',
      tratta: 'Salita all\'Etna con funivia e fuoristrada',
      pernottamento: 'Catania o versante etneo',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'guida obbligatoria oltre i 2.900 m circa; accesso interdetto in caso di attività',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 3 — Taormina e i Gole dell\'Alcantara',
      tratta: 'Taormina e Gole dell\'Alcantara',
      pernottamento: 'Catania o versante etneo',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 4 — Siracusa e Ortigia',
      tratta: 'Trasferimento a Siracusa',
      pernottamento: 'Ortigia, Siracusa',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 5 — Noto, Modica, Scicli',
      tratta: 'Giro del barocco: Noto, Modica, Scicli',
      pernottamento: 'Ortigia o Val di Noto',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 6 — Ragusa Ibla e Vendicari',
      tratta: 'Ragusa Ibla e riserva di Vendicari',
      pernottamento: 'Ortigia o Val di Noto',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 7 — Verso l\'interno: Piazza Armerina ed Enna',
      tratta: 'Verso l\'interno: Piazza Armerina ed Enna',
      pernottamento: 'Interno o Agrigento',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Villa Romana del Casale: 3.500 mq di mosaici romani del IV secolo',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 8 — Agrigento',
      tratta: 'Trasferimento ad Agrigento',
      pernottamento: 'Agrigento',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Valle dei Templi: in estate si visita in notturna o al primo mattino',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 9 — Scala dei Turchi e rientro verso Catania',
      tratta: 'Scala dei Turchi e rientro verso Catania',
      pernottamento: 'Catania',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'accesso alla Scala dei Turchi regolamentato e a tratti interdetto: da verificare',
      destinazioneSlug: 'sicilia',
    },
    {
      titoloGiorno: 'Giorno 10 — Ultima mattina e partenza',
      tratta: 'Volo da Catania',
      intensita: 'leggero',
      destinazioneSlug: 'sicilia',
    },
  ],
  budget: [
    { etichetta: 'Volo e auto a noleggio', valore: 'l\'auto è indispensabile e va messa in conto per tutti i dieci giorni' },
    { etichetta: 'Salita all\'Etna', valore: 'funivia più fuoristrada più guida obbligatoria oltre quota: la voce singola più alta' },
    { etichetta: 'Siti archeologici', valore: 'prezzi contenuti, con cumulativi che convengono quasi sempre' },
    { etichetta: 'Alloggi', valore: 'più economici del centro-nord, con l\'eccezione di Taormina' },
    { etichetta: 'Cantine dell\'Etna', valore: 'degustazioni su appuntamento, mai senza' },
  ],
}
