import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per "Sicilia tutta: il giro completo in 17 giorni".
// Il testo narrativo resta nel markdown (src/content/viaggi/36-sicilia-completa.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// del file markdown, altrimenti il merge in DayTimeline non trova la corrispondenza.

export const siciliaCompletaMeta: TripMeta = {
  tripSlug: 'sicilia-completa',
  paeseSlug: 'italia',
  ritmo: 'Un anello antiorario da Palermo a Catania, senza ritorni sui propri passi: diciassette giorni sono il minimo per farla tutta senza passare la vacanza in auto',
  trasporti: 'Auto a noleggio in formula one-way, aperto su Palermo e chiuso su Catania; sulle statali interne i tempi vanno aumentati di un terzo',
  stile: [
    'archeologia',
    'arte',
    'gastronomia',
  ],
  adattoA: [
    'chi ha almeno due settimane e non vuole scegliere tra est e ovest',
    'chi mette archeologia, arte e cucina davanti al mare',
    'chi non salta l\'interno per stare solo sulla costa',
  ],
  puntiForti: [
    'La Cappella Palatina, con un soffitto arabo a muqarnas sopra mosaici bizantini in una chiesa latina, per volontà esplicita di Ruggero II',
    'Le Cave di Cusa, ferme al giorno del 409 a.C. in cui arrivarono i Cartaginesi, con i rocchi di colonna ancora a metà estrazione',
    'Il Duomo di Siracusa, dove si toccano colonne doriche del V secolo a.C. inglobate in una chiesa barocca',
  ],
  criticita: [
    'L\'accesso alla zona sommitale dell\'Etna dipende dall\'attività del vulcano e può essere interdetto senza preavviso',
    'Valle dei Templi, Selinunte e Segesta non hanno ombra: d\'estate si visitano in notturna o all\'alba',
    'L\'accesso alla Scala dei Turchi è stato regolamentato e a tratti interdetto',
    'Gli orari e il percorso della Cappella Palatina cambiano nei giorni di attività dell\'Assemblea Regionale',
    'I tempi di percorrenza sulle statali interne sono più lunghi di quanto le mappe stimino',
    'Sotto i dodici giorni il giro completo non ha senso: si passa la vacanza sulle statali',
  ],
  budgetTotale: undefined,
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'in autonomia, con auto a noleggio one-way',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'Il soffitto a muqarnas della Cappella Palatina, i rocchi abbandonati delle Cave di Cusa, i crateri sommitali dell\'Etna con il terreno caldo sotto la mano',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Palermo e Monreale', destinazioneSlug: 'sicilia-occidentale' },
    { nome: 'Segesta, Erice e Trapani', destinazioneSlug: 'sicilia-occidentale' },
    { nome: 'Le saline, Mozia e Marsala', destinazioneSlug: 'sicilia-occidentale' },
    { nome: 'Selinunte e le Cave di Cusa', destinazioneSlug: 'sicilia-occidentale' },
    { nome: 'Agrigento e la Valle dei Templi', destinazioneSlug: 'sicilia' },
    { nome: 'Piazza Armerina e l\'interno', destinazioneSlug: 'sicilia' },
    { nome: 'Val di Noto', destinazioneSlug: 'sicilia' },
    { nome: 'Siracusa e Ortigia', destinazioneSlug: 'sicilia' },
    { nome: 'Etna e Taormina', destinazioneSlug: 'sicilia' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Arrivo a Palermo',
      tratta: 'Volo su Palermo, ritiro auto, primo giro in centro',
      pernottamento: 'Palermo, in centro',
      statoPernottamento: 'da-confermare',
      intensita: 'leggero',
      costiNoti: 'a Palermo l\'auto resta in garage: la città si gira a piedi',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-1-palermo-quattro-canti.jpg',
      imageAlt: 'I Quattro Canti di Palermo, l\'incrocio barocco tra via Maqueda e il Cassaro con le facciate concave dei quattro palazzi',
    },
    {
      titoloGiorno: 'Giorno 2 — Palermo arabo-normanna',
      tratta: 'Palazzo dei Normanni, Cappella Palatina, Cattedrale, Martorana e gli oratori del Serpotta',
      pernottamento: 'Palermo',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'orari e percorso della Cappella Palatina variano con le attività dell\'Assemblea Regionale',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-2-cappella-palatina.jpg',
      imageAlt: 'I mosaici bizantini dorati e gli archi della Cappella Palatina a Palermo, illuminati dalle candele',
    },
    {
      titoloGiorno: 'Giorno 3 — I mercati, le Catacombe, Palazzo Abatellis',
      tratta: 'Mercati storici, Catacombe dei Cappuccini e Palazzo Abatellis',
      pernottamento: 'Palermo',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'le Catacombe dei Cappuccini non sono un luogo adatto a tutti: è giusto saperlo prima',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-3-mercato-ballaro.jpg',
      imageAlt: 'Il mercato di Ballarò a Palermo, tra bancarelle di frutta e passanti nel vicolo del centro storico',
    },
    {
      titoloGiorno: 'Giorno 4 — Monreale e Cefalù',
      tratta: 'Monreale al mattino, Cefalù nel pomeriggio',
      pernottamento: 'Palermo o verso ovest',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'a Monreale duomo e chiostro sono biglietti distinti e vanno fatti entrambi',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-4-monreale-mosaici.jpg',
      imageAlt: "L'abside dorata del Duomo di Monreale, con il grande mosaico del Cristo Pantocratore sopra l'altare",
    },
    {
      titoloGiorno: 'Giorno 5 — Segesta, Erice e Trapani',
      tratta: 'Segesta, salita a Erice e arrivo a Trapani',
      pernottamento: 'Trapani o dintorni',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'a Erice si sale in auto o in funivia da Trapani',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-5-segesta-tempio.jpg',
      imageAlt: 'Il tempio dorico di Segesta, isolato nella campagna siciliana con le colline sullo sfondo',
    },
    {
      titoloGiorno: 'Giorno 6 — Le saline, Mozia e Marsala',
      tratta: 'Saline di Trapani e Marsala, isola di Mozia, cantine di Marsala',
      pernottamento: 'Trapani o Marsala',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'a Mozia si arriva con un breve tragitto in barca; cantine su appuntamento',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-6-saline-mulino.jpg',
      imageAlt: 'Un mulino a vento tra le saline di Trapani, con le pale controluce sul cielo nuvoloso',
    },
    {
      titoloGiorno: 'Giorno 7 — Lo Zingaro, Scopello e San Vito Lo Capo',
      tratta: 'Riserva dello Zingaro, Scopello e San Vito Lo Capo',
      pernottamento: 'San Vito Lo Capo o Trapani',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'dentro la riserva non si compra niente: acqua al seguito',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-7-scopello-tonnara.jpg',
      imageAlt: 'La tonnara di Scopello con i faraglioni a picco sul mare e la torre di avvistamento sulla scogliera',
    },
    {
      titoloGiorno: 'Giorno 8 — Selinunte e le Cave di Cusa',
      tratta: 'Selinunte al mattino, Cave di Cusa, trasferimento verso Agrigento',
      pernottamento: 'Agrigento o Sciacca',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'Selinunte è il più grande parco archeologico d\'Europa e non ha ombra: si va presto',
      destinazioneSlug: 'sicilia-occidentale',
      immagine: '/images/viaggi/sicilia-completa/giorno-8-selinunte-tempio.jpg',
      imageAlt: 'Le colonne spezzate del Tempio G di Selinunte contro il cielo azzurro',
    },
    {
      titoloGiorno: 'Giorno 9 — Agrigento e la Valle dei Templi',
      tratta: 'Valle dei Templi, Museo Archeologico e Giardino della Kolymbethra',
      pernottamento: 'Agrigento',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'd\'estate la Valle si visita in notturna o al primo mattino; cumulativo con il museo',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-9-agrigento-giunone.jpg',
      imageAlt: 'Il Tempio di Giunone nella Valle dei Templi di Agrigento, con le colonne doriche in luce diurna',
    },
    {
      titoloGiorno: 'Giorno 10 — La Scala dei Turchi e l\'interno',
      tratta: 'Scala dei Turchi, poi Villa Romana del Casale e l\'interno',
      pernottamento: 'Val di Noto o zona Piazza Armerina',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'lo stato di accesso della Scala dei Turchi va verificato: è stato regolamentato e a tratti interdetto',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-10-scala-turchi-alto.jpg',
      imageAlt: 'Vista dall\'alto della Scala dei Turchi, la scogliera bianca a strati che scende verso la spiaggia e il mare',
    },
    {
      titoloGiorno: 'Giorno 11 — Ragusa Ibla e l\'arrivo nel barocco',
      tratta: 'Ragusa Ibla e Ragusa superiore',
      pernottamento: 'Ragusa Ibla, Modica o Noto',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'ZTL attive nei centri storici del Val di Noto',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-11-ragusa-ibla-notte.jpg',
      imageAlt: 'Ragusa Ibla di sera, con le luci accese lungo le strade del centro storico arroccato',
    },
    {
      titoloGiorno: 'Giorno 12 — Modica, Scicli e Noto',
      tratta: 'Modica, Scicli e Noto',
      pernottamento: 'Val di Noto',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'sono tutte a venti chilometri l\'una dall\'altra: la giornata si fa senza fretta',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-12-modica-duomo.jpg',
      imageAlt: 'La scalinata barocca e la facciata del Duomo di San Giorgio a Modica',
    },
    {
      titoloGiorno: 'Giorno 13 — Vendicari e arrivo a Siracusa',
      tratta: 'Riserva di Vendicari al mattino, trasferimento a Siracusa',
      pernottamento: 'Ortigia, Siracusa',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'in primavera e in autunno a Vendicari ci sono i fenicotteri',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-13-vendicari.jpg',
      imageAlt: 'Le lagune e gli acquitrini della Riserva Naturale di Vendicari, habitat degli uccelli migratori',
    },
    {
      titoloGiorno: 'Giorno 14 — Siracusa',
      tratta: 'Parco della Neapolis, Ortigia, Museo Paolo Orsi',
      pernottamento: 'Ortigia',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'cumulativo tra parco archeologico e Museo Paolo Orsi',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-14-siracusa-tempio-apollo.jpg',
      imageAlt: 'Le colonne doriche del Tempio di Apollo a Ortigia, Siracusa, tra i palazzi del centro storico',
    },
    {
      titoloGiorno: 'Giorno 15 — L\'Etna',
      tratta: 'Salita alla zona sommitale dell\'Etna e cantina sul versante etneo',
      pernottamento: 'versante etneo o Catania',
      statoPernottamento: 'da-confermare',
      intensita: 'intenso',
      costiNoti: 'funivia più fuoristrada più guida obbligatoria oltre quota: la voce singola più alta del viaggio',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-15-etna-lava.jpg',
      imageAlt: "Un pendio di roccia lavica e zolfo sui fianchi dell'Etna, tra le nuvole che avvolgono la montagna",
    },
    {
      titoloGiorno: 'Giorno 16 — Taormina e le Gole dell\'Alcantara',
      tratta: 'Taormina al mattino presto, Gole dell\'Alcantara nel pomeriggio',
      pernottamento: 'Catania o versante etneo',
      statoPernottamento: 'da-confermare',
      intensita: 'medio',
      costiNoti: 'Taormina in alta stagione ha prezzi da un\'altra regione: si va prima dei pullman',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-16-alcantara-gole.jpg',
      imageAlt: 'Le colonne basaltiche esagonali scolpite dall\'acqua nelle Gole dell\'Alcantara',
    },
    {
      titoloGiorno: 'Giorno 17 — Catania e partenza',
      tratta: 'Catania, mercato della Pescheria e volo di rientro',
      intensita: 'leggero',
      destinazioneSlug: 'sicilia',
      immagine: '/images/viaggi/sicilia-completa/giorno-17-catania-via-etnea.jpg',
      imageAlt: 'Via Etnea a Catania, la via principale della città con i palazzi barocchi e i passanti',
    },
  ],
  budget: [
    { etichetta: 'Volo e noleggio one-way', valore: 'il supplemento del one-way si ripaga con la giornata di ritorno che non si fa' },
    { etichetta: 'Salita all\'Etna', valore: 'funivia, fuoristrada e guida obbligatoria oltre quota: la voce singola più alta' },
    { etichetta: 'Siti archeologici', valore: 'prezzi contenuti, con cumulativi che convengono quasi sempre' },
    { etichetta: 'Alloggi', valore: 'nettamente più bassi nell\'ovest e nell\'interno che nella Sicilia orientale e sulla costa nord-est' },
    { etichetta: 'Cantine', valore: 'Etna, Marsala e Vittoria: degustazioni su appuntamento, mai senza' },
  ],
}
