import type { TripMeta } from '@/lib/types'

// Overlay di metadati strutturati per il viaggio "Sri Lanka in 12 giorni". Il
// testo narrativo resta nel markdown (src/content/viaggi/04-sri-lanka-2023.md).
// `titoloGiorno` deve combaciare esattamente con le intestazioni "### Giorno N — ..."
// (o il titolo speciale della notte dell'Adam's Peak) del file markdown.

export const sriLanka2023Meta: TripMeta = {
  tripSlug: 'sri-lanka-2023',
  paeseSlug: 'sri-lanka',
  ritmo: 'Molto denso — quasi ogni giorno una tappa diversa, tra templi, trekking, safari e spiagge',
  trasporti: 'Van privato con autista anglofono per tutto il viaggio, più un tratto in treno panoramico da Nuwara Eliya a Ella',
  stile: ['on the road', 'natura', 'cultura'],
  adattoA: ['chi vuole vedere il triangolo culturale, la montagna del tè e le spiagge del sud in un solo viaggio', 'chi cerca una sfida fisica come l\'Adam\'s Peak', 'viaggi organizzati con van privato e DMC locale'],
  puntiForti: [
    'La densità e varietà di paesaggi in soli 12 giorni: templi, safari, montagna del tè, spiagge',
    'La scalata notturna dell\'Adam\'s Peak, vissuta insieme a centinaia di pellegrini locali',
    'Il tramonto da Pidurangala Rock con vista su Sigiriya, meno affollato della Rocca stessa',
  ],
  criticita: [
    'Il ritmo è molto denso, quasi senza giorni di vero riposo fino alle spiagge finali',
    'Gli orari di treni e trasferimenti sono spesso imprevedibili (il treno panoramico Nuwara Eliya-Ella in particolare)',
    'Diversi hotel intermedi (Nallathanniya su tutti) sono punti d\'appoggio funzionali più che strutture da vacanza',
  ],
  budgetTotale: 'circa 250€ a testa di cassa comune di partenza, più altri 200€ a testa durante il viaggio',
  viaggioInBreve: {
    percheHoScelto: undefined,
    conChiSonoPartito: 'van privato con autista per tutto il percorso, con DMC locale (WanderlustAsia) a organizzare hotel e attività',
    cosaCercavo: undefined,
    treEsperienzePiuBelle: 'La scalata notturna dell\'Adam\'s Peak, il tramonto da Pidurangala Rock su Sigiriya, la cerimonia serale al Tempio del Dente di Kandy',
    cosaCambierei: undefined,
    aChiLoConsiglio: undefined,
  },
  tappeMappa: [
    { nome: 'Negombo', destinazioneSlug: 'negombo' },
    { nome: 'Anuradhapura', destinazioneSlug: 'anuradhapura' },
    { nome: 'Dambulla e Sigiriya', destinazioneSlug: 'dambulla-sigiriya' },
    { nome: 'Polonnaruwa', destinazioneSlug: 'polonnaruwa' },
    { nome: 'Kandy', destinazioneSlug: 'kandy' },
    { nome: 'Nallathanniya (Adam\'s Peak)', destinazioneSlug: 'nallathanniya' },
    { nome: 'Nuwara Eliya', destinazioneSlug: 'nuwara-eliya' },
    { nome: 'Ella', destinazioneSlug: 'ella' },
    { nome: 'Hikkaduwa', destinazioneSlug: 'hikkaduwa' },
    { nome: 'Negombo', destinazioneSlug: 'negombo' },
  ],
  giorni: [
    {
      titoloGiorno: 'Giorno 1 — Negombo',
      tratta: 'Arrivo a Colombo → Negombo',
      pernottamento: 'Regal Réseau Hotel & Spa',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'negombo',
    },
    {
      titoloGiorno: 'Giorno 2 — Negombo-Anuradhapura',
      tratta: 'Negombo → Anuradhapura (5h)',
      pernottamento: 'Miridiya Lake Resort',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'anuradhapura',
    },
    {
      titoloGiorno: 'Giorno 3 — Anuradhapura-Dambulla: Mihintale e safari',
      tratta: 'Anuradhapura → Mihintale → safari a Minneriya → Pidurangala Rock → Dambulla',
      pernottamento: 'Tropical Life Resort',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Mihintale 500 LKR + sarong 50 LKR; safari 12.000 LKR a jeep + ingresso; Pidurangala 1.000 LKR',
      destinazioneSlug: 'dambulla-sigiriya',
    },
    {
      titoloGiorno: 'Giorno 4 — Dambulla-Polonnaruwa-Dambulla',
      tratta: 'Dambulla → Sigiriya → Polonnaruwa → Dambulla',
      pernottamento: 'Tropical Life Resort',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Sigiriya 10.000-30 USD a persona; bicicletta a Polonnaruwa 1.000 LKR',
      destinazioneSlug: 'polonnaruwa',
    },
    {
      titoloGiorno: 'Giorno 5 — Dambulla-Kandy',
      tratta: 'Dambulla → Ranweli Spice Garden → Kandy',
      pernottamento: 'Rivendell Hotel',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'kandy',
    },
    {
      titoloGiorno: 'Giorno 6 — Kandy-Nallathanniya: rafting a Kitulgala',
      tratta: 'Kandy → Kitulgala (rafting) → Nallathanniya',
      pernottamento: 'Wathsala Inn',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      destinazioneSlug: 'nallathanniya',
    },
    {
      titoloGiorno: 'Notte Adam\'s Peak — la sfida fisica del viaggio',
      tratta: 'Scalata notturna dell\'Adam\'s Peak (2.243 m)',
      pernottamento: 'Wathsala Inn (rientro dopo la discesa)',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      destinazioneSlug: 'nallathanniya',
    },
    {
      titoloGiorno: 'Giorno 7 — Hatton-Nuwara Eliya: piantagioni di tè',
      tratta: 'Hatton → Pedro Tea Plantation → Nuwara Eliya',
      pernottamento: 'Araliya RED',
      statoPernottamento: 'provato',
      intensita: 'medio',
      costiNoti: 'Attività a Nuwara Eliya 5.000-8.000 LKR',
      destinazioneSlug: 'nuwara-eliya',
    },
    {
      titoloGiorno: 'Giorno 8 — Nuwara Eliya-Ella: il treno panoramico',
      tratta: 'Nuwara Eliya (Nanu Oya) → Ella, in treno',
      pernottamento: '88th Hotel',
      statoPernottamento: 'provato',
      intensita: 'medio',
      destinazioneSlug: 'ella',
    },
    {
      titoloGiorno: 'Giorno 9 — Ella-Yala-Hikkaduwa: safari e prima spiaggia',
      tratta: 'Ella → safari a Yala → Mirissa → Hikkaduwa',
      pernottamento: 'Sapphire Seas Beachfront Hotel',
      statoPernottamento: 'provato',
      intensita: 'intenso',
      costiNoti: 'Safari a Yala 12.000-16.000 LKR a jeep + ingresso (27-30€ a persona) + mancia',
      destinazioneSlug: 'hikkaduwa',
    },
    {
      titoloGiorno: 'Giorno 10 — Hikkaduwa: giornata di mare',
      tratta: 'Giornata libera a Hikkaduwa',
      pernottamento: 'Sapphire Seas Beachfront Hotel',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'hikkaduwa',
    },
    {
      titoloGiorno: 'Giorno 11 — Hikkaduwa-Negombo',
      tratta: 'Hikkaduwa → Sea Turtle Conservation Project di Bentota → Negombo',
      pernottamento: 'Goldi Sands Hotel',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'negombo',
    },
    {
      titoloGiorno: 'Giorno 12 — Negombo-Aeroporto',
      tratta: 'Negombo → Aeroporto di Colombo',
      pernottamento: 'nessun pernottamento (giorno di partenza)',
      statoPernottamento: 'provato',
      intensita: 'leggero',
      destinazioneSlug: 'negombo',
    },
  ],
  budget: [
    { etichetta: 'Voli', valore: undefined },
    { etichetta: 'Cassa comune di partenza', valore: '250€ a testa' },
    { etichetta: 'Spese durante il viaggio (cibo, bevande, souvenir, massaggi)', valore: '200€ a testa' },
    { etichetta: 'Visto ETA', valore: '~70€ a persona' },
    { etichetta: 'Totale', valore: undefined },
  ],
}
